Repository antvis/G2, pull requests merged in 2019-11, with the labels that each got.

#1591 fix: setTheme ts 声明修改
  src/index.d.ts
Labels: PR: unreviewed, bug

#1573 调试 axis component
  package.json
  src/chart/controller/axis.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/dependents.ts
  src/theme/antv.ts
  src/util/axis.ts
  src/util/scale.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-spec.ts
  tests/unit/util/axis-spec.ts
Labels: PR: reviewed-approved

#1602 Interaction 机制
  package.json
  src/chart/interface.ts
  src/chart/view.ts
  src/core.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/path.ts
  src/interaction/base.ts
  src/interaction/index.ts
  src/state/active.ts
  src/state/index.ts
  src/state/manager.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/path-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/interaction/index-spec.ts
  tests/unit/state/index-spec.ts
Labels: PR: reviewed-approved

#1606 联调 Geometry 事件
  src/chart/event.ts
  src/chart/view.ts
  src/util/event.ts
  tests/unit/chart/event/event-spec.ts
  tests/unit/interaction/index-spec.ts
  tests/unit/util/event-spec.ts
Labels: PR: reviewed-approved

#1608 Test use github action
  .github/workflows/ci.yml
  .travis.yml
  package.json
Labels: PR: reviewed-approved

#1609 Shape 添加 getMarker() 方法
  package.json
  src/dependents.ts
  src/geometry/base.ts
  src/geometry/shape/area.ts
  src/geometry/shape/base.ts
  src/geometry/shape/index.ts
  src/geometry/shape/interval.ts
  src/geometry/shape/line.ts
  src/geometry/shape/point.ts
  src/geometry/shape/polygon.ts
  src/geometry/shape/util/path.ts
  src/interface.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/shape/area-spec.ts
  tests/unit/geometry/shape/base-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/line-spec.ts
  tests/unit/geometry/shape/point-spec.ts
  tests/unit/geometry/shape/util/path-spec.ts
Labels: PR: reviewed-approved

#1612 fix: reset <li> style
  src/theme/default.js
  test/bugs/issue-472-spec.js
Labels: PR: reviewed-changes-requested, bug

#1616 Feat gatsby antv theme
  .gitignore
  demos/index.html
  examples/gallery/basic/demo/funnel.js
  examples/gallery/basic/demo/interval.js
  examples/gallery/basic/demo/line.js
  examples/gallery/basic/demo/meta.json
  examples/gallery/basic/demo/pie.js
  examples/gallery/basic/index.en.md
  examples/gallery/basic/index.zh.md
  gatsby-browser.js
  gatsby-config.js
  package.json
  site/images/gatsby-astronaut.png
  site/locale.json
  site/pages/index.en.tsx
  site/pages/index.zh.tsx
  src/chart/chart.ts
  src/interaction/active.ts
Labels: PR: reviewed-approved

#1601 调试 category legend component
  src/chart/controller/legend.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/dependents.ts
  src/theme/antv.ts
  src/util/attr.ts
  src/util/legend.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-spec.ts
  tests/unit/component/category-legend-spec.ts
  tests/unit/util/attr-spec.ts
  tests/unit/util/padding-spec.ts
Labels: PR: reviewed-approved

#1614 circle axis component and layout
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/dependents.ts
  src/theme/antv.ts
  src/util/axis.ts
  src/util/bbox.ts
  tests/unit/chart/event/event-spec.ts
  tests/unit/component/axis-circle-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/util/axis-spec.ts
  tests/unit/util/bbox-spec.ts
Labels: PR: reviewed-approved

#1621 fix(component): update component import, update test cases
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/dependents.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-line-spec.ts
Labels: PR: reviewed-approved, bug

#1623 fix(axis): fix axis factor error
  src/theme/antv.ts
Labels: PR: reviewed-changes-requested, bug

#1615 Tooltip 组件接入以及对应的交互行为
  src/chart/chart.ts
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/controller/tooltip.ts
  src/chart/interface.ts
  src/chart/view.ts
  src/constant.ts
  src/dependents.ts
  src/geometry/base.ts
  src/interaction/base.ts
  src/interaction/index.ts
  src/interaction/tooltip.ts
  src/interface.ts
  src/theme/antv.ts
  src/util/dom.ts
  src/util/scale.ts
  src/util/tooltip.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/interaction/index-spec.ts
  tests/unit/util/tooltip-spec.ts
Labels: PR: unreviewed

#1626 Refactor class controller
  src/chart/__components__/index.ts
  src/chart/__components__/mock-component.ts
  src/chart/__components__/text.ts
  src/chart/controller/axis.ts
  src/chart/controller/base.ts
  src/chart/controller/legend.ts
  src/chart/interface.ts
  src/chart/view.ts
  src/component/index.ts
  src/component/text.ts
  src/constant.ts
  src/dependents.ts
  src/facet/interface.ts
  src/facet/rect.ts
  tests/unit/component/axis-circle-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/component/legend-category-spec.ts
Labels: PR: unreviewed

#1628 Fix tooltip
  src/chart/controller/tooltip.ts
  src/theme/antv.ts
Labels: PR: unreviewed

#1627 Feat axis grid
  src/chart/controller/axis.ts
  src/chart/controller/tooltip.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/constant.ts
  src/dependents.ts
  src/theme/antv.ts
  src/util/grid.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/util/grid-spec.ts
Labels: PR: reviewed-approved

#1631 Fix controller container
  src/chart/controller/base.ts
  src/chart/controller/legend.ts
  tests/unit/chart/chart-spec.ts
Labels: PR: reviewed-approved

#1633 补充 polygon shape 以及添加相应的测试用例
  src/geometry/shape/polygon.ts
  src/theme/antv.ts
  tests/unit/geometry/polygon-spec.ts
  tests/unit/geometry/shape/polygon-spec.ts
Labels: PR: reviewed-approved

#1634 fix(ci): ci fail because component version
  package.json
  src/dependents.ts
Labels: PR: reviewed-changes-requested, bug

#1640 chore: remove unnecessary insert-css
  gatsby-browser.js
  package.json
Labels: PR: reviewed-changes-requested, chore

#1641 修复 Cannot assign to read only property 'constructor' of object '#<t>' 报错问题
  site/locale.json
  site/pages/index.zh.tsx
  src/component/plot.js
  src/geom/label/geom-labels.js
  src/geom/label/interval-labels.js
  src/geom/label/pie-labels.js
  src/geom/label/polar-labels.js
  src/interaction/component/range.js
Labels: PR: reviewed-changes-requested

#1638 fix: fix where the execution of the animation caused the originalStyl…
  examples/gallery/basic/demo/interval.js
  examples/gallery/basic/demo/tooltip.ts
  src/geometry/element/index.ts
  src/interaction/active.ts
Labels: PR: unreviewed, bug

#1642 View module augment
  src/chart/view.ts
  src/geometry/line.ts
  src/geometry/path.ts
  src/index.ts
Labels: PR: reviewed-approved

#1644 fix: rect crosshair should be under the shapes
  packages/component/package.json
  packages/component/src/tooltip/crosshair.ts
Labels: PR: reviewed-changes-requested, bug

#1645 Site review
  .npmignore
  README.md
  README.zh-CN.md
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested

#1649 Fix add tooltip css reset
  packages/g2/src/theme/default.ts
Labels: PR: reviewed-changes-requested

#1650 chore(site): update homepage icon
  site/pages/index.zh.tsx
Labels: PR: unreviewed, chore

#1643 Fix view basic event & plot event
  package.json
  src/chart/view.ts
  tests/unit/chart/event/event-spec.ts
Labels: PR: reviewed-approved

#1652 chore: remove comment
  src/geometry/element/index.ts
  src/interaction/active-region.ts
  src/interaction/active.ts
  src/interaction/tooltip.ts
Labels: PR: reviewed-changes-requested, chore

#1654 fix(tooltip-style): replace visibility: hidden with display: node, av…
  packages/component/__tests__/unit/tooltip/html-spec.js
  packages/component/package.json
  packages/component/src/annotation/html.ts
  packages/component/src/tooltip/html.ts
  packages/component/src/tooltip/theme.ts
  packages/g2/package.json
  packages/g2/src/global.ts
  packages/g2/src/theme/default.ts
Labels: PR: reviewed-changes-requested, bug

#1632 continuous legend component
  src/chart/controller/legend.ts
  src/chart/layout/index.ts
  src/dependents.ts
  src/theme/antv.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/legend-continuous-spec.ts
  tests/unit/interaction/index-spec.ts
Labels: PR: unreviewed, refactor

#1659 fix: fix homepage link 404
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#1656 chore: add comments
  src/geometry/animate/action.ts
  src/geometry/animate/util.ts
  src/geometry/area.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/interface.ts
  src/geometry/shape/base.ts
  src/interface.ts
Labels: PR: reviewed-changes-requested, chore

#1658 Adjust theme
  src/geometry/base.ts
  src/geometry/path.ts
  src/theme/antv.ts
  tests/unit/geometry/shape/area-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/line-spec.ts
  tests/unit/geometry/shape/point-spec.ts
  tests/unit/geometry/shape/polygon-spec.ts
Labels: PR: reviewed-approved

#1660 fix: add international prefix
  site/pages/index.zh.tsx
Labels: PR: unreviewed, bug

#1651 feat(pie-label): 修改饼图label连接线样式
  packages/g2/src/element/controller/label/components/pie.ts
Labels: PR: reviewed-changes-requested, enhancement

#1603 fix: brush startPonit; forcefie 新选区; 鼠标移出再回来;
  src/interaction/brush.js
  test/bugs/issue-1405-spec.js
Labels: PR: reviewed-approved, bug

#1648 fix: fix rounded-stacked demo
  examples/column/stack/demo/rounded-stacked.js
Labels: PR: reviewed-changes-requested, bug

#1661 漏网之鱼...
  tests/unit/geometry/base-spec.ts
Labels: PR: reviewed-approved

#1662 chore(site): update screenshot
  examples/column/stack/demo/meta.json
Labels: PR: unreviewed, chore

#1571 fix: 多y轴无法隐藏指定legend
  src/chart/controller/legend.js
Labels: PR: unreviewed, bug

#1664 fix: gridLines should be under axisLines
  packages/component/src/axis/base.ts
Labels: PR: reviewed-approved, bug

#1666 docs: update api docs. Closed #978
  docs/api/chart.en.md
  docs/api/chart.zh.md
Labels: PR: unreviewed, documentation

#1667 chore(site): fix mask format. Closed #1597
  examples/other/other/demo/line-realtime.js
Labels: PR: reviewed-changes-requested, chore

#1668 fix: 修复下legend position的类型定义
  src/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#1665 release 3.5.10
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-approved

#1676 Add comments
  src/chart/chart.ts
  src/chart/controller/axis.ts
  src/chart/controller/base.ts
  src/chart/controller/coordinate.ts
  src/chart/controller/legend.ts
  src/chart/event.ts
  src/chart/view.ts
  tests/unit/chart/view/index-spec.ts
Labels: PR: unreviewed

#1677 chore: update .npmignore
  .npmignore
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-approved, chore

#1678 Fix homepage
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed

#1679 chore(site): update homepage
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, chore

#1680 Release 4.0 alpha
  CHANGELOG.md
  README.md
  package.json
  src/core.ts
  tests/unit/index-spec.ts
  tsconfig.json
Labels: PR: reviewed-approved

#1683 🚀 g2.antv.vision
  CHANGELOG.md
  README.md
  README.zh-CN.md
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, rocket

#1684 refactor: rename geometry's getLegendAttributes() as getGroupAttribut…
  src/chart/controller/legend.ts
  src/chart/view.ts
  src/geometry/base.ts
Labels: PR: reviewed-changes-requested, refactor

#1686 chore(site): adjust homepage thumbnail style
  site/pages/index.less
  site/pages/index.zh.tsx
Labels: PR: unreviewed, chore

#1687 fix(site): correct api path
  docs/api/chart.en.md
  docs/api/chart.zh.md
  docs/api/data-set.en.md
  docs/api/data-set.zh.md
  docs/api/g2.en.md
  docs/api/g2.zh.md
  docs/api/geometry.en.md
  docs/api/geometry.zh.md
  docs/api/options.en.md
  docs/api/options.zh.md
  docs/api/slider.en.md
  docs/api/slider.zh.md
  docs/api/tooltip.en.md
  docs/api/tooltip.zh.md
  docs/api/view.en.md
  docs/api/view.zh.md
  docs/manual/tutorial/animate.en.md
  docs/manual/tutorial/animate.zh.md
  docs/manual/tutorial/attribute.en.md
  docs/manual/tutorial/attribute.zh.md
  docs/manual/tutorial/axis.en.md
  docs/manual/tutorial/axis.zh.md
  docs/manual/tutorial/creating-chart.en.md
  docs/manual/tutorial/creating-chart.zh.md
  docs/manual/tutorial/data-set.en.md
  docs/manual/tutorial/data-set.zh.md
  docs/manual/tutorial/event.en.md
  docs/manual/tutorial/event.zh.md
  docs/manual/tutorial/facet.en.md
  docs/manual/tutorial/facet.zh.md
  docs/manual/tutorial/g2-v3-changes.en.md
  docs/manual/tutorial/g2-v3-changes.zh.md
  docs/manual/tutorial/geometry.en.md
  docs/manual/tutorial/geometry.zh.md
  docs/manual/tutorial/guide.en.md
  docs/manual/tutorial/guide.zh.md
  docs/manual/tutorial/label.en.md
  docs/manual/tutorial/label.zh.md
  docs/manual/tutorial/shape.en.md
  docs/manual/tutorial/shape.zh.md
  docs/manual/tutorial/slider.en.md
  docs/manual/tutorial/slider.zh.md
  docs/manual/tutorial/tooltip.en.md
  docs/manual/tutorial/tooltip.zh.md
  docs/manual/tutorial/update-data.en.md
  docs/manual/tutorial/update-data.zh.md
  docs/manual/tutorial/view.en.md
  docs/manual/tutorial/view.zh.md
Labels: PR: unreviewed, bug

#1689 chore(site): update title
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, chore

#1688 fix: corejs 2 and corejs 3 build conflict
  .babelrc
  .babelrc.js
  package.json
Labels: PR: reviewed-changes-requested, bug

#1690 docs: Remove wrong title and description
  package.json
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: unreviewed, documentation

#1669 feat: add Schema geometry and shapes
  src/geometry/schema.ts
  src/geometry/shape/schema.ts
  src/index.ts
  src/interface.ts
  src/theme/antv.ts
  src/util/helper.ts
  tests/unit/geometry/schema-spec.ts
  tests/unit/geometry/shape/polygon-spec.ts
  tests/unit/geometry/shape/schema-spec.ts
  tests/unit/util/helper-spec.ts
Labels: PR: reviewed-approved, enhancement

#1682 优化 Geometry 中数据相关的类型定义
  src/chart/controller/tooltip.ts
  src/geometry/animate/index.ts
  src/geometry/base.ts
  src/geometry/interval.ts
  src/geometry/path.ts
  src/geometry/point.ts
  src/geometry/polygon.ts
  src/interface.ts
  src/util/tooltip.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/util/tooltip-spec.ts
Labels: PR: reviewed-approved

#1694 fix: fix index.d.ts legend layout definition
  src/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#1696 chore: upgrade gatsby-theme-antv version
  package.json
Labels: PR: unreviewed, chore

#1697 fix: 同步开源3.5版本上的PR#54到3.6分支，修复Tooltip在边缘位置错误
  packages/component/__tests__/unit/tooltip/html-spec.js
  packages/component/src/tooltip/html.ts
Labels: PR: reviewed-approved, bug

#1701 3.6.x: 组件绘制层级错误
  packages/component/src/tooltip/crosshair.ts
  packages/component/src/tooltip/html.ts
Labels: PR: reviewed-changes-requested, x

#1655 add annotation component
  src/chart/controller/annotation.ts
  src/chart/controller/axis.ts
  src/chart/controller/base.ts
  src/chart/controller/legend.ts
  src/chart/controller/tooltip.ts
  src/chart/view.ts
  src/constant.ts
  src/dependents.ts
  src/theme/antv.ts
  tests/unit/chart/controller/tooltip-spec.ts
  tests/unit/component/annotation-spec.ts
Labels: PR: unreviewed

#1705 chore: 3.6分支3.6.0-beta.6版本
  packages/component/package.json
  packages/g2/package.json
  packages/g2/src/global.ts
Labels: PR: reviewed-changes-requested, chore

#1707 chore: remove ts-ignore
  src/index.ts
  tests/unit/chart/chart-auto-fit-spec.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/controller/tooltip-spec.ts
  tests/unit/chart/event/event-spec.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-circle-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/component/legend-continuous-spec.ts
  tests/unit/facet/rect-spec.ts
  tests/unit/interaction/index-spec.ts
Labels: PR: reviewed-approved, chore

#1706 chore: add setSelected and clearSelected
  src/index.d.ts
Labels: PR: reviewed-changes-requested, chore

#1713 chore: site homepage
  site/locale.json
  site/pages/index.less
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved, chore

#1714 docs: demo line & bugfix
  examples/line/double/demo/curved.js
  examples/line/double/demo/dash.js
  examples/line/double/demo/meta.json
  examples/line/double/demo/rain-and-flow.js
  examples/line/double/demo/series.js
  examples/line/multiple/demo/kernel-smooth-regression-1.js
  examples/line/multiple/demo/kernel-smooth-regression-2.js
  examples/line/step/demo/step-series.js
  examples/line/step/demo/step.js
  gatsby-browser.js
  package.json
  src/chart/chart.ts
  src/chart/controller/legend.ts
  src/chart/view.ts
  src/theme/antv.ts
  src/util/dom.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/util/theme-spec.ts
Labels: PR: reviewed-approved, documentation

#1717 feat(changelog): add commit-msg and changelog generator
  .commitlintrc.js
  package.json
Labels: PR: reviewed-changes-requested, enhancement
