Repository antvis/G2, pull requests merged in 2019-09, with the labels that each got.

#1406 fix(tooltip): add missing rect type crosshairs
  packages/component/src/tooltip/crosshair.ts
  packages/g2/src/plot/controller/tooltip.ts
  packages/g2/src/theme/default.ts
Labels: PR: unreviewed, bug

#1407 fix(filter): keep getFilteredValues same with getFilteredOutValues
  src/chart/view.js
  test/bugs/issue-1264-spec.js
Labels: PR: unreviewed, bug

#1410 test(torch): use torch as unit test framework
  .torch.compile.opts.js
  __tests__/index.spec.ts
  __tests__/unit/index-spec.ts
  __tests__/unit/template-spec.ts
  package.json
Labels: PR: reviewed-changes-requested, test

#1416 fix(legend): add getFlippedBBox to support auto padding for flipped l…
  packages/component/src/legend/category/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#1419 fix: 补充没有save到package.json 中包
  packages/g2/package.json
Labels: PR: unreviewed, bug

#1420 fix(legend): add getBBox public method to legend
  packages/component/src/legend/base.ts
  packages/component/src/legend/category/canvas.ts
  packages/component/src/legend/category/html.ts
Labels: PR: unreviewed, bug

#1423 fix(tooltip): fix tooltip position when panelGroup has clip attr
  packages/component/__tests__/unit/tooltip/base-spec.js
  packages/component/__tests__/unit/tooltip/canvas-spec.js
  packages/component/__tests__/unit/tooltip/html-spec.js
  packages/component/src/tooltip/canvas.ts
  packages/component/src/tooltip/html.ts
  packages/g2/src/plot/controller/tooltip.ts
Labels: PR: reviewed-changes-requested, bug

#1425 fix(legend): canvas legend getHeight
  packages/component/src/legend/category/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#1451 legend在panelGroup有clip属性的时候的高宽限制
  packages/g2/src/plot/controller/legend.ts
Labels: PR: reviewed-changes-requested

#1452 View 实现
  __tests__/unit/chart/chart-spec.ts
  __tests__/unit/chart/view-spec.ts
  __tests__/unit/util/bbox-spec.ts
  __tests__/unit/util/direction-spec.ts
  __tests__/unit/util/padding-spec.ts
  __tests__/util/dom.ts
  src/chart/__components__/index.ts
  src/chart/__components__/mock-component.ts
  src/chart/constant.ts
  src/chart/controller/axis.ts
  src/chart/controller/coordinate.ts
  src/chart/controller/legend.ts
  src/chart/index.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/component/index.ts
  src/core.ts
  src/dependents.ts
  src/geometry/geometry.ts
  src/geometry/interval/index.ts
  src/index.ts
  src/interface.ts
  src/util/bbox.ts
  src/util/direction.ts
  src/util/index.ts
Labels: PR: unreviewed

#1465 chore: rename `setCoord` to `setCoordinate`, `getCoord` to `getCoordi…
  __tests__/unit/geometry/shape-spec.ts
  src/geometry/geometry.ts
  src/geometry/interface.ts
  src/geometry/shape.ts
Labels: PR: reviewed-changes-requested, chore

#1466 View geometry 基本联调
  __tests__/unit/chart/view-spec.ts
  __tests__/util/dom.ts
  src/chart/controller/coordinate.ts
  src/chart/controller/legend.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/geometry/geometry.ts
  src/index.ts
Labels: PR: unreviewed

#1470 feat: use coordinate.update(cfg) to update instance
  src/chart/view.ts
  src/dependents.ts
  src/geometry/geometry.ts
  src/geometry/interface.ts
  src/geometry/shape.ts
  src/geometry/util/path.ts
  tsconfig.json
Labels: PR: reviewed-changes-requested, enhancement

#1474 feat(tooltip): add lock tooltip
  package.json
  src/chart/chart.js
  src/chart/controller/tooltip.js
  src/global.js
  test/bugs/issue-tooltip-lock-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#1475 fix: Element updates when data changed.
  __tests__/unit/geometry/geometry-spec.ts
  package.json
  src/geometry/geometry.ts
Labels: PR: reviewed-changes-requested, bug

#1483 feat(bug): fixed bug #476
  src/geom/base.js
  src/geom/label/geom-labels.js
  test/bugs/issue-476-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#1486 chore: update issue and pull request template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/----please-use-antv-issue-helper---.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed, chore

#1408 fix(auto-padding): fixed #1249, when y axis alias length <= 2
  src/chart/util/bbox-of-back-plot.js
  test/bugs/issue-1249-spec.js
Labels: PR: reviewed-changes-requested, bug

#1485 feat(bug): fixed bug of #600
  src/geom/schema.js
  test/bugs/issue-600-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#1409 fix(tooltip position):position will be wrong when tooltip init
  src/component/tooltip/index.js
Labels: PR: reviewed-changes-requested

#1487 fix(ts): legend
  src/index.d.ts
Labels: PR: reviewed-changes-requested, bug

#1493 fix: when color field === x field, tooltip crosshair'bug
  src/chart/controller/tooltip.js
  test/bugs/issue-1248-spec.js
Labels: PR: unreviewed, bug

#1473 chore: remove repeated color.
  packages/g2/src/theme/default.ts
Labels: PR: reviewed-changes-requested, chore

#1492 fix(ts): fix #1489
  src/index.d.ts
Labels: PR: reviewed-approved, bug

#1482 feat(theme): getTheme, registerTheme, and use theme in view
  __tests__/unit/chart/view-spec.ts
  __tests__/unit/geometry/geometry-spec.ts
  __tests__/unit/theme/index-spec.ts
  __tests__/unit/util/theme-spec.ts
  src/chart/view.ts
  src/core.ts
  src/theme/default.ts
  src/theme/index.ts
  src/util/theme.ts
Labels: PR: reviewed-approved, enhancement

#1494 fix(label): fix label dom leak, fixed #1213
  src/chart/controller/axis.js
  test/bugs/issue-1213-spec.js
Labels: PR: reviewed-approved, bug

#1496 fix: fix error of intervalSymmetric when data is empty, fix #1082
  src/geom/base.js
  test/unit/geom/geom-spec.js
Labels: PR: reviewed-approved, bug

#1500 chore: update version
  packages/component/package.json
  packages/g2/package.json
Labels: PR: unreviewed, chore

#1501 fix: modify the coordinate property call method.
  packages/g2/__tests__/unit/element/util/path-spec.js
  packages/g2/src/animate/animate.ts
  packages/g2/src/animate/util.ts
  packages/g2/src/element/controller/size.ts
  packages/g2/src/element/util/path.ts
Labels: PR: reviewed-changes-requested, bug

#1505 fix: update coord getWidth/getHeight
  packages/component/src/annotation/base.ts
Labels: PR: reviewed-changes-requested, bug

#1499 Daily 0926 2
  src/geom/mixin/active.js
  src/geom/mixin/select.js
  src/geom/mixin/zindex-util.js
  test/bugs/issue-792-spec.js
  test/bugs/issue-813-spec.js
  test/bugs/issue-999-spec.js
  test/unit/chart/controller/guide-spec.js
  test/unit/component/guide/region-filter-spec.js
Labels: PR: reviewed-changes-requested

#1481 feat(view): view.changeData API, update the geometries
  __tests__/unit/chart/multi-view-spec.ts
  __tests__/unit/chart/view/index-spec.ts
  __tests__/util/delay.ts
  src/chart/chart.ts
  src/chart/view.ts
  src/index.ts
  src/interface.ts
Labels: PR: reviewed-approved, enhancement

#1507 fix: remove __tests__, fix coordinate.type
  src/chart/controller/coordinate.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/util/delay.ts
Labels: PR: reviewed-approved, bug

#1504 fix: when data has some categorys not in category scale, stack will c…
  src/geom/base.js
  test/unit/geom/geom-spec.js
Labels: PR: reviewed-changes-requested, bug

#1399 fix(brush): fix onEnd function parameter data missing problem. Closed…
  src/interaction/brush.js
Labels: PR: reviewed-approved

#1174 fix(brush): brush filter wrong data when coord transpose
  src/interaction/brush.js
Labels: PR: reviewed-approved

#1509 feat(version): update to 3.5.8
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, enhancement

#1510 entry
  src/chart/state-manager.ts
  src/core.ts
  src/index.ts
Labels: PR: reviewed-changes-requested

#1517 Tooltip fix
  src/chart/controller/tooltip.js
  src/theme/default.js
  test/bugs/default-tooltip-marker-spec.js
  test/bugs/tooltip-unfollow-spec.js
Labels: PR: reviewed-changes-requested

#1512 修复重复调用 chart.render() 绘制出错的问题
  src/geometry/geometry.ts
  tests/unit/geometry/geometry-spec.ts
Labels: PR: reviewed-approved, bug

#1520 test: migrate torchjs to jest-electron
  .torch.compile.opts.js
  package.json
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/geometry/element-spec.ts
  tests/unit/geometry/geometry-spec.ts
  tests/unit/geometry/interval/index-spec.ts
  tests/unit/geometry/interval/shape-spec.ts
  tests/unit/geometry/polygon/index-spec.ts
  tests/unit/geometry/polygon/shape-spec.ts
  tests/unit/geometry/shape-spec.ts
  tests/unit/index-spec.ts
  tests/unit/template-spec.ts
  tests/unit/theme/index-spec.ts
  tests/unit/util/bbox-spec.ts
  tests/unit/util/coordinate-spec.ts
  tests/unit/util/direction-spec.ts
  tests/unit/util/padding-spec.ts
  tests/unit/util/scale-spec.ts
  tests/unit/util/theme-spec.ts
  tsconfig.json
Labels: PR: reviewed-approved, test

#1521 fix code review
  .travis.yml
  package.json
  src/chart/chart.ts
  src/chart/controller/axis.ts
  src/chart/controller/event.ts
  src/chart/controller/legend.ts
  src/chart/index.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/component/index.ts
  src/constant.ts
  src/core.ts
  src/interface.ts
  src/util/bbox.ts
  src/util/direction.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/util/bbox-spec.ts
  tests/unit/util/direction-spec.ts
Labels: PR: reviewed-approved
