Repository antvis/G2, pull requests merged in 2019-12, with the labels that each got.

#1731 docs: 纠正 API 文档
  docs/api/chart.en.md
  docs/api/chart.zh.md
Labels: PR: unreviewed, documentation

#1722 feat: multi engine supported
  package.json
  src/chart/chart.ts
  src/chart/view.ts
  src/core.ts
  src/dependents.ts
  src/engine/index.ts
  src/geometry/animate/util.ts
  src/index.ts
  src/util/graphics.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/engine/engine-render-spec.ts
  tests/unit/engine/index-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/shape/base-spec.ts
  tests/unit/interaction/index-spec.ts
  tests/util/dom.ts
Labels: PR: reviewed-approved, enhancement

#1738 refactor: view 的三层 group 不从父 view 的 middleGroup 中创建，而是从父 view 对应的层级中创建
  src/chart/view.ts
Labels: PR: reviewed-changes-requested, refactor

#1729 chore: bar demo & bugfix
  examples/bar/basic/demo/basic.js
  examples/bar/basic/demo/radial-bar.js
  examples/bar/basic/demo/radial-line.js
  examples/bar/basic/demo/ranged.js
  examples/bar/basic/demo/time-bar.js
  src/chart/controller/annotation.ts
  src/chart/controller/axis.ts
  src/chart/layout/index.ts
  src/util/axis.ts
  src/util/direction.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/util/axis-spec.ts
  tests/unit/util/direction-spec.ts
Labels: PR: reviewed-approved, chore

#1741 Fix #1739
  docs/support/upgrade.zh.md
  examples/pie/nested/demo/multi-level.js
  examples/pie/rose/demo/donut-rose.js
  package.json
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/shape/area.ts
  src/geometry/shape/interval.ts
  src/geometry/shape/line.ts
  src/geometry/shape/point.ts
  src/geometry/shape/polygon.ts
  src/geometry/shape/schema.ts
  src/geometry/shape/util/get-style.ts
  src/interface.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/shape/area-spec.ts
  tests/unit/geometry/shape/base-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/line-spec.ts
  tests/unit/geometry/shape/point-spec.ts
  tests/unit/geometry/shape/polygon-spec.ts
  tests/unit/geometry/shape/schema-spec.ts
  tests/unit/geometry/shape/util/get-style-spec.ts
Labels: PR: reviewed-approved

#1745 chore: 按需引用 @antv/util, closed #1740
  src/chart/chart.ts
  src/chart/controller/annotation.ts
  src/chart/controller/axis.ts
  src/chart/controller/base.ts
  src/chart/controller/coordinate.ts
  src/chart/controller/legend.ts
  src/chart/controller/tooltip.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/facet/facet.ts
  src/facet/index.ts
  src/facet/rect.ts
  src/geometry/animate/index.ts
  src/geometry/area.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/interval.ts
  src/geometry/path.ts
  src/geometry/point.ts
  src/geometry/polygon.ts
  src/geometry/schema.ts
  src/geometry/shape/area.ts
  src/geometry/shape/base.ts
  src/geometry/shape/interval.ts
  src/geometry/shape/line.ts
  src/geometry/shape/point.ts
  src/geometry/shape/polygon.ts
  src/geometry/shape/schema.ts
  src/geometry/shape/util/get-path-points.ts
  src/geometry/shape/util/get-style.ts
  src/geometry/shape/util/path.ts
  src/geometry/shape/util/split-points.ts
  src/geometry/util/is-model-change.ts
  src/geometry/util/parse-fields.ts
  src/geometry/util/shape-size.ts
  src/interaction/active-region.ts
  src/interaction/index.ts
  src/interaction/tooltip.ts
  src/state/index.ts
  src/state/manager.ts
  src/theme/antv.ts
  src/theme/index.ts
  src/util/axis.ts
  src/util/bbox.ts
  src/util/graphics.ts
  src/util/grid.ts
  src/util/helper.ts
  src/util/legend.ts
  src/util/padding.ts
  src/util/scale.ts
  src/util/theme.ts
  src/util/tooltip.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/util/theme-spec.ts
Labels: PR: reviewed-approved, chore

#1742 column demos & bugfix
  examples/column/basic/demo/helix-coordinate.js
  examples/column/basic/demo/image-top.js
  examples/column/basic/demo/marked.js
  examples/column/basic/demo/waterfall.js
  examples/column/dodge/demo/circular-stacked.js
  examples/column/dodge/demo/column-clustered-stacked.js
  examples/column/dodge/demo/column12.js
  examples/column/histogram/demo/histogram-binwidth.js
  examples/column/histogram/demo/histogram-stacked.js
  examples/column/histogram/demo/histogram.js
  examples/column/stack/demo/polar-stack.js
  examples/column/stack/demo/rounded-stacked.js
  examples/column/stack/demo/rounded.js
  examples/column/stack/demo/stacked-percentage.js
  examples/column/stack/demo/wind-rose.js
  examples/pie/basic/demo/pie-size.js
  src/chart/controller/annotation.ts
  src/chart/controller/legend.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/geometry/element/index.ts
  src/util/grid.ts
Labels: PR: reviewed-approved

#1758 fix(register-shape): fix demo usage of registerShape API
  examples/column/basic/demo/marked.js
  examples/column/basic/demo/waterfall.js
  examples/column/stack/demo/rounded-stacked.js
  examples/column/stack/demo/rounded.js
Labels: PR: reviewed-changes-requested, bug

#1759 chore: remove unused info
  README.md
  README.zh-CN.md
Labels: PR: reviewed-approved, chore

#1765 fix(legend): fix legend layout
  src/util/legend.ts
  tests/unit/util/legend-spec.ts
Labels: PR: reviewed-approved, bug

#1755 feat(plugin): add registerComponent for componentPlugin
  src/chart/component/annotation.ts
  src/chart/component/axis.ts
  src/chart/component/base.ts
  src/chart/component/index.ts
  src/chart/component/legend.ts
  src/chart/component/tooltip.ts
  src/chart/controller/coordinate.ts
  src/chart/index.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/component/text.ts
  src/core.ts
  src/index.ts
  src/util/coordinate.ts
  tests/unit/chart/component/custom-title-spec.ts
  tests/unit/chart/component/index-spec.ts
  tests/unit/chart/component/title.ts
  tests/unit/chart/component/tooltip-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/component/axis-circle-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/component/legend-continuous-spec.ts
  tests/unit/util/coordinate-spec.ts
Labels: PR: reviewed-approved, enhancement

#1766 fix(coordinate): shapeFactory cache cause coordinate update is invalid
  src/geometry/base.ts
  tests/bugs/1746-spec.ts
Labels: PR: reviewed-approved, bug

#1768 fix(layout): add layout for legend 12 directions
  src/util/bbox.ts
  src/util/legend.ts
  tests/unit/util/bbox-spec.ts
  tests/unit/util/legend-spec.ts
Labels: PR: reviewed-approved, bug

#1769 fix(coordinate): fix coordinate is undefined after layout
  src/util/bbox.ts
Labels: PR: reviewed-changes-requested, bug

#1772 docs: 🔍 Add algolia docsearchOptions
  gatsby-config.js
  package.json
Labels: PR: reviewed-approved, documentation

#1771 feat: element 添加 getBBox() 方法，返回整体的包围盒
  src/geometry/element/index.ts
  tests/unit/geometry/element/index-spec.ts
Labels: PR: reviewed-approved, enhancement

#1770 为元素添加 show()、hide() 以及 visible 属性
  src/base.ts
  src/chart/chart.ts
  src/chart/component/base.ts
  src/chart/component/tooltip.ts
  src/chart/interface.ts
  src/chart/view.ts
  src/dependents.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/component/custom-title-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
Labels: PR: reviewed-approved

#1777 fix: 极坐标下值坐标轴文本应该朝左放置
  src/chart/component/axis.ts
  tests/unit/component/axis-circle-spec.ts
Labels: PR: reviewed-approved, bug

#1779 fix(legend): 同样画布下 legend 在上和在下表现不一致
  packages/component/docs/zh-cn/legend.md
  packages/component/src/legend/category/base.ts
  packages/g2/src/theme/default.ts
Labels: PR: reviewed-approved, bug

#1781 移除 StateAction，保留 StateManager
  src/chart/view.ts
  src/core.ts
  src/interaction/action/active-region.ts
  src/interaction/action/tooltip.ts
  src/interaction/index.ts
  src/state/active.ts
  src/state/index.ts
  src/state/manager.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/state/index-spec.ts
Labels: PR: reviewed-approved

#1787 feat: publish-3.6.0-beta.7
  packages/g2/package.json
  packages/g2/src/global.ts
Labels: PR: reviewed-changes-requested, enhancement

#1790 fix(event-rect): not remove event rect after clear
  src/chart/view.ts
  tests/unit/chart/chart-spec.ts
Labels: PR: reviewed-approved, bug

#1808 修复 show() hide() 不生效的问题
  src/chart/view.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
Labels: PR: reviewed-changes-requested

#1807 fix(label): move label to foregroundGroup
  packages/g2/__tests__/unit/element/base-spec.js
  packages/g2/__tests__/unit/element/controller/state-spec.js
  packages/g2/src/element/controller/label/index.ts
  packages/g2/src/plot/view.ts
Labels: PR: reviewed-approved, bug

#1809 [3.6.x]fix: auto rotate修复
  packages/component/src/axis/base.ts
  packages/component/src/axis/line.ts
Labels: PR: reviewed-approved, bug

#1810 build: upgrade version
  packages/g2/package.json
Labels: PR: reviewed-approved, build

#1812 fix: add offset when auto rotate label
  packages/component/src/axis/line.ts
Labels: PR: reviewed-approved, bug

#1813 buid(version): update version
  packages/component/package.json
  packages/g2/package.json
Labels: PR: reviewed-approved, buid

#1816 [3.6.x]feat: support axis formatter
  packages/component/package.json
  packages/component/src/axis/base.ts
  packages/component/src/axis/line.ts
  packages/g2/package.json
Labels: PR: reviewed-changes-requested, enhancement

#1831 [3.6.x]feat: 支持自定义多角度的axis label autoRotate
  packages/component/package.json
  packages/component/src/axis/line.ts
  packages/g2/package.json
Labels: PR: reviewed-changes-requested, enhancement

#1837 fix: auto rotate get labels fix
  packages/component/package.json
  packages/component/src/axis/line.ts
  packages/g2/package.json
Labels: PR: reviewed-changes-requested, bug

#1839 chore: 网站 demo 支持 html 代码片段
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, chore

#1840 fix: Reducers may not dispatch actions
  gatsby-config.js
Labels: PR: reviewed-changes-requested, bug

#1842 chore: fix html code snippt unwork
  gatsby-config.js
Labels: PR: reviewed-changes-requested, chore

#1843 fix: TypeScript issue
  examples/column/histogram/demo/histogram.ts
  tsconfig.json
  typings.d.ts
Labels: PR: reviewed-changes-requested, bug

#1851 docs: fix gallery page
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  examples/gallery/line/index.en.md
  examples/gallery/line/index.zh.md
  gatsby-config.js
  package.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-changes-requested, documentation

#1852 docs: fix gallery
  examples/candlestick/candlestick/demo/basic.js
  examples/candlestick/candlestick/demo/k-and-area.js
  examples/candlestick/candlestick/demo/meta.json
  examples/candlestick/candlestick/index.en.md
  examples/candlestick/candlestick/index.zh.md
Labels: PR: reviewed-approved, documentation

#1855 fix(#1848): add name property for every animate function, to avoid to…
  packages/g2/package.json
  packages/g2/src/animate/action.ts
  packages/g2/src/animate/index.ts
Labels: PR: reviewed-changes-requested, bug

#1856 docs: fix examples url 404
  examples/gallery/index.en.md
  examples/gallery/index.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, documentation

#1860 Feat plot event
  src/chart/view.ts
  src/constant.ts
  tests/unit/chart/event/event-spec.ts
Labels: PR: reviewed-approved

#1868 fix(axis-title): fix axis title is undefined when option with no title
  src/chart/controller/axis.ts
  tests/unit/chart/controller/axis-update-spec.ts
Labels: PR: reviewed-approved, bug

#1869 fix(circle-grid): fix circle grid style is wrong
  src/chart/controller/axis.ts
Labels: PR: reviewed-changes-requested, bug

#1871 fix: 用户为定义 text 时，传 null
  src/chart/controller/annotation.ts
Labels: PR: reviewed-changes-requested, bug

#1880 fix(layout): legend 布局上，需要和 coordinateBBox 对齐
  src/chart/controller/legend.ts
  src/chart/layout/index.ts
Labels: PR: reviewed-changes-requested, bug
