Repository antvis/G2, pull requests merged in 2019-10, with the labels that each got.

#1524 部分 Coordinate 接口为修改
  packages/g2/__tests__/unit/element/shape/base-spec.js
  packages/g2/__tests__/unit/plot/controller/annotation-spec.js
Labels: PR: reviewed-changes-requested

#1527 fix: when mouse enter tooltip and leave, the tooltip should hide.
  src/chart/controller/tooltip.js
Labels: PR: reviewed-changes-requested, bug

#1534 添加 Geometry 模块的测试用例以及一些 BUGFIX
  package.json
  src/geometry/geometry.ts
  src/geometry/interval/index.ts
  src/geometry/util/path.ts
  src/util/scale.ts
  tests/unit/geometry/interval/index-spec.ts
  tests/unit/geometry/util/path-spec.ts
  tests/unit/geometry/util/shape-size-spec.ts
  tests/util/dom.ts
  tests/util/theme.ts
Labels: PR: reviewed-approved

#1536 使用 @antv/g-canvas
  package.json
  src/chart/__components__/mock-component.ts
  src/chart/chart.ts
  src/chart/controller/coordinate.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/component/index.ts
  src/dependents.ts
  src/geometry/element.ts
  src/geometry/geometry.ts
  src/geometry/interface.ts
  src/util/bbox.ts
  src/util/direction.ts
  src/util/transform.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/geometry/element-spec.ts
  tests/unit/geometry/geometry-spec.ts
  tests/unit/geometry/interval/index-spec.ts
  tests/unit/geometry/shape-spec.ts
  tests/unit/geometry/util/shape-size-spec.ts
  tests/unit/util/bbox-spec.ts
  tests/unit/util/direction-spec.ts
  tests/util/dom.ts
Labels: PR: reviewed-approved

#1508 feat(event): add view events recursively
  package.json
  src/chart/view.ts
  src/dependents.ts
Labels: PR: reviewed-approved, enhancement

#1541 Upgrade g version
  package.json
  src/chart/chart.ts
  src/dependents.ts
  src/geometry/geometry.ts
  src/geometry/util/split-data.ts
  src/util/transform.ts
  tests/unit/geometry/shape-spec.ts
  tests/unit/geometry/util/split-data-spec.ts
Labels: PR: unreviewed

#1544 geometry 相关模块文件结构调整
  src/chart/view.ts
  src/core.ts
  src/element.ts
  src/geometry/base.ts
  src/geometry/interface.ts
  src/geometry/interval.ts
  src/geometry/polygon.ts
  src/interface.ts
  src/shape/base.ts
  src/shape/index.ts
  src/shape/interval.ts
  src/shape/polygon.ts
  src/shape/util/path.ts
  tests/unit/element-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/polygon/index-spec.ts
  tests/unit/geometry/polygon/shape-spec.ts
  tests/unit/shape/base-spec.ts
  tests/unit/shape/interval-spec.ts
  tests/unit/shape/util/path-spec.ts
Labels: PR: reviewed-approved

#1519 publish 3.5.9-beta.1
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested

#1531 修复legend左侧不显示
  src/chart/controller/legend.js
  test/bugs/issue-472-spec.js
  test/unit/chart/controller/legend-spec.js
Labels: PR: reviewed-changes-requested

#1547 fix(testcases): Skip failed testcases
  packages/component/__tests__/unit/axis/line-spec.js
  packages/component/__tests__/unit/legend/category/html-spec.js
  packages/component/__tests__/unit/tooltip/html-spec.js
  packages/g2/__tests__/unit/element/edge-spec.js
  packages/g2/__tests__/unit/plot/controller/legend-spec.js
  packages/g2/src/global.ts
Labels: PR: unreviewed, bug

#1543 feat(typings): add generic params typings for components
  packages/component/src/annotation/base.ts
  packages/component/src/axis/base.ts
  packages/component/src/base.ts
  packages/component/src/interface.ts
  packages/component/src/label/base.ts
  packages/component/src/legend/base.ts
  packages/component/src/tooltip/base.ts
  packages/component/src/tooltip/canvas.ts
  packages/component/src/tooltip/crosshair.ts
  packages/component/src/tooltip/html.ts
  packages/component/src/tooltip/interface.ts
  packages/g2/src/plot/controller/tooltip.ts
Labels: PR: unreviewed, enhancement

#1546 Feat path
  src/chart/controller/legend.ts
  src/element.ts
  src/geometry/base.ts
  src/geometry/interval.ts
  src/geometry/line.ts
  src/geometry/path.ts
  src/geometry/polygon.ts
  src/index.ts
  src/interface.ts
  src/shape/interval.ts
  src/shape/line.ts
  src/shape/util/path.ts
  src/shape/util/split-points.ts
  src/theme/antv.ts
  src/util/transform.ts
  tests/unit/element-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/line-spec.ts
  tests/unit/geometry/path-spec.ts
  tests/util/dom.ts
  tests/util/theme.ts
Labels: PR: reviewed-approved

#1550 重新调整 geometry 的目录结构~~~
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/interval.ts
  src/geometry/line.ts
  src/geometry/path.ts
  src/geometry/polygon.ts
  src/geometry/shape/base.ts
  src/geometry/shape/index.ts
  src/geometry/shape/interval.ts
  src/geometry/shape/line.ts
  src/geometry/shape/polygon.ts
  src/geometry/shape/util/path.ts
  src/geometry/shape/util/split-points.ts
  src/interface.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/shape/base-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/util/path-spec.ts
Labels: PR: reviewed-changes-requested

#1551 fix: hide axis tick line when hide axis label
  packages/component/src/axis/base.ts
  packages/component/src/axis/line.ts
  tslint.json
Labels: PR: reviewed-changes-requested, bug

#1552 feat(update): update verson
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, enhancement

#1561 feat(view): enhance axis, legend API, fixed #1554
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/interface.ts
  src/chart/view.ts
  tests/unit/chart/view/index-spec.ts
Labels: PR: reviewed-approved, enhancement

#1563 remove baseUrl of tsconfig
  src/chart/__components__/mock-component.ts
  src/chart/view.ts
  src/geometry/interval.ts
  tsconfig.json
Labels: PR: reviewed-changes-requested

#1564 always set id for shape draw cfg
  packages/component/src/axis/line.ts
  packages/g2/src/element/base.ts
Labels: PR: reviewed-changes-requested

#1553 为 Geometry 添加动画
  src/chart/interface.ts
  src/chart/view.ts
  src/geometry/animate/action.ts
  src/geometry/animate/index.ts
  src/geometry/animate/util.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/path.ts
  src/geometry/shape/base.ts
  src/geometry/shape/interval.ts
  src/geometry/shape/line.ts
  src/geometry/shape/util/split-points.ts
  src/interface.ts
  src/theme/antv.ts
  src/util/bbox.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/line-spec.ts
  tests/unit/geometry/path-spec.ts
  tests/unit/geometry/shape/base-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/util/split-points-spec.ts
  tests/unit/geometry/util/shape-size-spec.ts
  tests/util/theme.ts
Labels: PR: reviewed-approved, WIP

#1568 添加 line shape 的测试用例及一系列 BUGFIX
  src/geometry/animate/action.ts
  src/geometry/animate/util.ts
  src/geometry/path.ts
  src/geometry/shape/interval.ts
  src/geometry/shape/line.ts
  src/geometry/shape/util/get-path-points.ts
  src/geometry/shape/util/split-points.ts
  src/interface.ts
  tests/unit/geometry/path-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/line-spec.ts
  tests/unit/geometry/shape/util/get-path-points-spec.ts
Labels: PR: reviewed-approved

#1569 使用 typedoc 生成 api 文档
  docs/README.md
  package.json
  tsconfig.json
Labels: PR: reviewed-approved, WIP

#1570 添加 docs 目录
  docs/README.md
  docs/tutorial/README.md
Labels: PR: reviewed-approved

#1572 shape 打标，支持 name: eventName 事件
  src/geometry/element/index.ts
  tests/unit/geometry/element/index-spec.ts
Labels: PR: reviewed-approved, name

#1576 fix(view): view.getData return filtererData
  src/chart/view.ts
  src/facet/facet.ts
  tests/unit/facet/rect-spec.ts
Labels: PR: reviewed-approved, bug

#1577 为现有 Geometry 添加默认动画配置
  package.json
  src/geometry/animate/action.ts
  src/geometry/animate/index.ts
  src/geometry/shape/base.ts
Labels: PR: unreviewed

#1582 remove bbox
  src/chart/controller/coordinate.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/component/index.ts
  src/dependents.ts
  src/facet/rect.ts
  src/util/bbox.ts
  src/util/direction.ts
  tests/unit/util/bbox-spec.ts
  tests/unit/util/direction-spec.ts
Labels: PR: reviewed-approved

#1584 统一使用 init 作为初始化含义
  src/chart/__components__/mock-component.ts
  src/chart/__components__/text.ts
  src/chart/view.ts
  src/component/index.ts
  src/facet/facet.ts
  src/geometry/base.ts
  src/geometry/interval.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/line-spec.ts
  tests/unit/geometry/path-spec.ts
  tests/unit/geometry/util/shape-size-spec.ts
Labels: PR: reviewed-approved

#1583 添加 Point
  src/geometry/animate/action.ts
  src/geometry/animate/index.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/path.ts
  src/geometry/point.ts
  src/geometry/shape/point.ts
  src/index.ts
  src/interface.ts
  src/theme/antv.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/point-spec.ts
  tests/unit/geometry/shape/line-spec.ts
  tests/unit/geometry/shape/point-spec.ts
Labels: PR: reviewed-approved

#1581 Feat plot events
  src/chart/chart.ts
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/event.ts
  src/chart/index.ts
  src/chart/interface.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/constant.ts
  src/core.ts
  src/dependents.ts
  src/util/coordinate.ts
  src/util/helper.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/event/event-class-spec.ts
  tests/unit/chart/event/event-spec.ts
  tests/util/simulate.ts
Labels: PR: reviewed-approved

#1586 process chart autoFit props.
  src/chart/chart.ts
  src/chart/interface.ts
  src/constant.ts
  src/interface.ts
  src/util/dom.ts
  tests/unit/chart/chart-auto-fit-spec.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/event/event-spec.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/facet/rect-spec.ts
  tests/unit/util/dom-spec.ts
  tsconfig.json
Labels: PR: reviewed-approved

#1589 添加 Area
  src/geometry/animate/action.ts
  src/geometry/animate/index.ts
  src/geometry/area.ts
  src/geometry/path.ts
  src/geometry/shape/area.ts
  src/geometry/shape/util/get-path-points.ts
  src/geometry/util/split-data.ts
  src/index.ts
  src/interface.ts
  src/theme/antv.ts
  tests/unit/geometry/area-spec.ts
  tests/unit/geometry/shape/area-spec.ts
  tests/unit/geometry/shape/point-spec.ts
  tests/unit/geometry/shape/util/get-path-points-spec.ts
  tests/unit/geometry/util/split-data-spec.ts
Labels: PR: unreviewed, WIP

#1593 添加 Tooltip 相关的工具函数
  src/chart/view.ts
  src/geometry/base.ts
  src/util/scale.ts
  src/util/tooltip.ts
  tests/unit/util/scale-spec.ts
  tests/unit/util/tooltip-spec.ts
Labels: PR: reviewed-approved

#1595 Fix: 修复 label typings定义问题
  packages/component/docs/zh-cn/label.md
  packages/component/src/interface.ts
  packages/component/src/label/base.ts
  packages/g2/__tests__/unit/element/controller/state-spec.js
Labels: PR: reviewed-changes-requested

#1599 feat: support element event
  src/geometry/element/index.ts
  tests/unit/geometry/element/index-spec.ts
Labels: PR: reviewed-approved
