Repository antvis/G2, pull requests merged in 2020-11, with the labels that each got.

#2973 fix(label): fix label position for zero data
  src/geometry/label/interval.ts
  tests/data/positive-negative.ts
  tests/unit/geometry/label/interval-spec.ts
Labels: PR: partially-approved

#2972 fix(interaction): fix link-by-color path for transposed coord
  src/interaction/action/element/link-by-color.ts
  tests/unit/interaction/action/link-by-color-spec.ts
Labels: PR: partially-approved

#2970 fix(tooltip): 先对 Geometry 数据判空再进行查找
  package.json
  src/chart/controller/tooltip.ts
  src/core.ts
Labels: PR: reviewed-approved

#2974 fix: delete fill attr in interval-line
  src/geometry/shape/interval/line.ts
  tests/unit/geometry/shape/interval-spec.ts
Labels: PR: reviewed-approved

#2975 chore: 4.1.0-beta.16
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#2979 fix: ci hang
  .github/workflows/ci.yml
Labels: PR: partially-approved

#2984 fix: the event variable is misspelled
  docs/manual/tutorial/event.zh.md
Labels: PR: reviewed-approved

#2981 refactor: walkthrough label
  docs/api-zh/legend.md
  examples/gallery/area/demo/area4.ts
  examples/pie/basic/demo/innerlabel.ts
  examples/pie/basic/demo/pie-size.ts
  src/component/labels.ts
  src/component/update-label.ts
  src/geometry/label/base.ts
  src/geometry/label/interface.ts
  src/geometry/label/interval.ts
  src/geometry/label/layout/pie/distribute.ts
  src/geometry/label/pie/index.ts
  src/geometry/label/polar.ts
  src/interface.ts
  src/util/theme.ts
  tests/unit/geometry/label/default-cfg-spec.ts
  tests/unit/geometry/label/label-offset-spec.ts
Labels: PR: partially-approved

#2987 fix(annotation): :smile: 修复 html-annotation 没有 clear
  src/chart/controller/annotation.ts
  tests/unit/chart/controller/annotation-update-spec.ts
Labels: PR: reviewed-approved

#2992 chore: release 4.1.0-beta.17
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#2995 feat(view): add syncViewPadding support callback
  package.json
  src/chart/layout/padding-cal.ts
  src/chart/util/sync-view-padding.ts
  src/chart/view.ts
  src/core.ts
  src/interface.ts
  tests/bugs/2849-spec.ts
  tests/unit/chart/layout/padding-cal-spec.ts
Labels: PR: partially-approved

#2881 feat: pixel interval padding and dodge padding
  src/geometry/base.ts
  src/geometry/util/shape-size.ts
  src/util/theme.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/util/shape-size-spec.ts
Labels: PR: unreviewed, enhancement

#2998 fix: #2996
  src/chart/util/scale-pool.ts
  src/chart/view.ts
  src/util/scale.ts
  tests/bugs/2996-spec.ts
  tests/unit/theme/multiple-pie-width-ratio-spec.ts
Labels: PR: partially-approved

#3002 docs: add G2Plot in readme
  README.md
  README.zh-CN.md
Labels: PR: partially-approved

#3005 docs: fix the parameter description of TooltipCrosshairsTextCallback …
  docs/api/general/tooltip.zh.md
  src/interface.ts
Labels: PR: reviewed-approved

#3010 fix: tooltip clear
  src/chart/controller/tooltip.ts
  tests/bugs/1962-spec.ts
  tests/unit/chart/controller/tooltip-spec.ts
  tests/unit/component/tooltip-crosshairs-spec.ts
Labels: PR: reviewed-approved

#3011 chore: update preview.yml
  .github/workflows/preview.yml
Labels: PR: reviewed-approved

#3014 chore: only sync gh-pages to Gitee Mirror
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved

#3015 chore: upgrade site theme
  gatsby-config.js
  package.json
Labels: PR: partially-approved

#3013 fix(slider): slider, scrollbar filter data
  src/chart/controller/scrollbar.ts
  src/chart/controller/slider.ts
  tests/bugs/g2plot-1899-spec.ts
Labels: PR: partially-approved

#3016 fix: adjust color 支持超出图形的数据标签
  src/geometry/label/layout/adjust-color.ts
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/util/color.ts
  src/util/theme.ts
  tests/unit/geometry/label/layout/adjust-color-spec.ts
  tests/unit/util/color-spec.ts
Labels: PR: partially-approved

#3018 refactor(theme): 主题重构，暴露 createTheme 方法
  docs/api/advanced/registertheme.en.md
  docs/api/advanced/registertheme.zh.md
  src/chart/view.ts
  src/geometry/label/interface.ts
  src/index.ts
  src/interface.ts
  src/theme/index.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/theme/util/create-by-style-sheet.ts
  src/theme/util/create-theme.ts
  src/theme/util/index.ts
  tests/bugs/2377-spec.ts
  tests/unit/theme/create-theme-spec.ts
  tests/unit/theme/dark-spec.ts
  tests/unit/theme/index-spec.ts
  tests/unit/util/theme-spec.ts
  tests/unit/util/theme/index-spec.ts
Labels: PR: partially-approved

#3021 chore: release 4.1.0-beta.19
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: partially-approved

#3023 fix(san-key): 贝塞尔曲线的方向不对
  src/geometry/shape/edge/util.ts
  tests/unit/geometry/shape/util/c-path-spec.ts
Labels: PR: partially-approved

#3027 docs(sankey): add indicator sankey demo
  examples/case/sankey/demo/meta.json
  examples/case/sankey/demo/sankey-card.ts
  examples/case/sankey/index.en.md
  examples/case/sankey/index.zh.md
Labels: PR: partially-approved

#3028 fix: change the triggering condition
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved

#3030 docs: add guide for sankey
  examples/case/sankey/demo/sankey-card.ts
  examples/case/sankey/design.en.md
  examples/case/sankey/design.zh.md
  package.json
Labels: PR: partially-approved

#3029 docs(magi): add monitor line chart demo
  static/magi/monitor-line-chart/index.html
Labels: PR: reviewed-approved

#3032 docs(magi): adjust pin position of monitor line chart
  static/magi/monitor-line-chart/index.html
Labels: PR: unreviewed

#3031 chore: version 4.1.0-beta.20
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3035 docs(magi): adjust styles of monitor line chart
  static/magi/monitor-line-chart/index.html
Labels: PR: reviewed-approved

#3043 fix: limitInPlot 更新后需要清除 clip
  src/chart/view.ts
  tests/unit/chart/chart-clip-spec.ts
Labels: PR: partially-approved

#3044 chore: release 4.1.0-beta.21
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3040 docs: 补充丢失的分面&交互的英文文档
  docs/api/general/facet.en.md
  docs/api/general/interaction.en.md
Labels: PR: reviewed-changes-requested

#3047 fix: return early from sectorPathUpdate if path is invalid
  src/animate/animation/sector-path-update.ts
Labels: PR: reviewed-approved

#3036 feat: interval support lineCap round
  src/geometry/shape/interval/index.ts
  src/geometry/shape/interval/util.ts
  src/geometry/shape/util/path.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/util/path-spec.ts
Labels: PR: partially-approved

#3054 chore: v4.1.0
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3057 fix(pie-label): 修复饼图 label 溢出
  src/geometry/label/layout/pie/outer.ts
  src/geometry/label/layout/pie/util.ts
  src/geometry/label/polar.ts
  tests/bugs/3056-spec.ts
Labels: PR: partially-approved

#3055 feat: support tooltip reversed cfg
  src/chart/controller/tooltip.ts
  src/interface.ts
  tests/unit/chart/controller/tooltip-spec.ts
Labels: PR: reviewed-approved
