Repository antvis/G2, pull requests merged in 2020-05, with the labels that each got.

#2387 docs(label): 修复文档中Layout Function参数的错误
  docs/manual/developer/registerlabel.en.md
  docs/manual/developer/registerlabel.zh.md
Labels: PR: partially-approved, documentation

#2382 修改了教程中 axis.md中小错误
  docs/manual/tutorial/axis.en.md
  docs/manual/tutorial/axis.zh.md
Labels: PR: unreviewed

#2403 docs(upgrade): 完善升级文档
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: reviewed-approved, documentation

#2416 fix(2377): registerTheme 时，需要和基础主题进行合并
  src/theme/index.ts
  tests/bugs/2377-spec.ts
  tests/unit/theme/index-spec.ts
Labels: PR: partially-approved, bug

#2417 fix(2412): 修复 axis title offset 设置不生效的问题，默认自动计算
  src/util/theme.ts
  tests/bugs/2412-spec.ts
Labels: PR: reviewed-approved, bug

#2422 fix(2371): 修复未判断 labels 为空导致的饼图图例过滤错误
  src/component/labels.ts
  tests/bugs/2371-spec.ts
Labels: PR: reviewed-approved, bug

#2424 fix(2365): 修复极坐标系圆弧坐标轴文本不响应坐标系 rotate 的问题
  src/util/axis.ts
  tests/bugs/2365-spec.ts
Labels: PR: reviewed-approved, bug

#2438 chore(deps): 升级 matrix-util
  package.json
  src/animate/animation/scale-in.ts
  src/animate/animation/util.ts
  src/animate/animation/zoom.ts
  src/geometry/shape/util/path.ts
  src/interaction/action/view/button.ts
  src/interaction/action/view/move.ts
  src/util/theme.ts
  src/util/transform.ts
Labels: PR: reviewed-changes-requested, dependencies

#2428 Fix 2356
  src/chart/layout/auto.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/geometry/base.ts
  src/geometry/path.ts
  tests/bugs/2356-spec.ts
  tests/unit/component/legend-category-spec.ts
Labels: PR: reviewed-approved

#2445 chore(deps): 升级 @antv/coord 依赖
  package.json
  src/util/axis.ts
Labels: PR: partially-approved, dependencies

#2447 3.5.x 版本升级 g
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested

#2446 fix: fix some ts error to pass build
  src/index.ts
  src/util/axis.ts
  src/util/transform.ts
Labels: PR: reviewed-approved, bug

#2442 fix: fix min/max value map to color
  src/chart/controller/legend.ts
  tests/bugs/2442-spec.ts
Labels: PR: partially-approved, bug

#2465 chore: release v4.0.8
  CHANGELOG.md
Labels: PR: unreviewed, chore

#2460 fix: tooltip 调整
  src/chart/controller/tooltip.ts
  src/index.ts
  src/interaction/action/component/tooltip.ts
  tests/unit/interaction/action/tooltip-spec.ts
Labels: PR: partially-approved, bug

#2469 fix typo
  docs/manual/tutorial/animate.en.md
  docs/manual/tutorial/animate.zh.md
Labels: PR: reviewed-approved

#2473 fix(typo): fix typo
  docs/manual/tutorial/scale.zh.md
Labels: PR: reviewed-approved, bug

#2488 fix: 图例应于坐标轴对齐
  src/chart/controller/legend.ts
  tests/unit/chart/controller/legend-spec.ts
Labels: PR: partially-approved, bug

#2496 fix(#2495): fix layout error after render twice
  src/chart/layout/index.ts
  tests/bugs/2495-spec.ts
Labels: PR: partially-approved, bug

#2497 feat: support legend layout margin
  src/chart/controller/legend.ts
  src/util/theme.ts
  tests/unit/chart/controller/legend-spec.ts
Labels: PR: partially-approved, enhancement

#2504 chore: release v4.0.9
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2502 feat: 增加 appendPadding 调节padding
  docs/manual/concepts/visual-channel.en.md
  docs/manual/developer/registerlabel.en.md
  docs/manual/developer/registerlabel.zh.md
  src/chart/chart.ts
  src/chart/layout/index.ts
  src/chart/layout/padding-cal.ts
  src/chart/view.ts
  src/interface.ts
  src/util/bbox.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/layout/padding-cal-spec.ts
Labels: PR: reviewed-approved, enhancement

#2512 fix(2505): 修复图表暗黑主题无背景色的问题
  src/chart/chart.ts
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/util/theme.ts
  tests/bugs/2505-spec.ts
Labels: PR: partially-approved, bug
