Repository antvis/G2, pull requests merged in 2020-12, with the labels that each got.

#3062 feat(label): add limitInPlot label layout
  src/geometry/label/layout/limit-in-plot.ts
  src/index.ts
  src/util/coordinate.ts
  tests/unit/geometry/label/layout/limit-in-plot-spec.ts
  tests/unit/util/coordinate-spec.ts
Labels: PR: partially-approved

#3066 feat(label-layout): 标签布局 limit-in-plot 支持 ellipsis 展示
  src/geometry/label/layout/limit-in-plot.ts
  src/util/text.ts
  tests/bugs/3065-spec.ts
  tests/unit/util/text-spec.ts
Labels: PR: reviewed-approved

#3059 fix: 更改默认 scale type 设置：time -> timeCat
  src/util/scale.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/util/scale-spec.ts
Labels: PR: partially-approved

#3069 chore: update changelog
  CHANGELOG.md
Labels: PR: reviewed-approved

#3074 fix(issue-3073): 修复数据存在null值，在pie-outer 标签布局下报错
  src/geometry/label/layout/pie/outer.ts
  tests/bugs/3073-spec.ts
Labels: PR: partially-approved

#3075 chore: release 4.1.1
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3067 chore: try to fix preview action vulnerability
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/preview.yml
Labels: PR: reviewed-approved

#3078 chore: fix preview build workflow
  .github/workflows/preview-build.yml
Labels: PR: reviewed-approved

#3080 chore: update ci worfklow
  .github/workflows/ci.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-upload.yml
Labels: PR: reviewed-approved

#3081 fix: fix early create canvas context cause build error in server side
  src/util/context.ts
  src/util/text.ts
Labels: PR: reviewed-approved

#3099 chore: add src to files for sourceMap
  package.json
Labels: PR: reviewed-approved

#3104 fix auto hide legend padding
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/theme/util/create-by-style-sheet.ts
  tests/unit/chart/controller/axis-spec.ts
  tests/unit/chart/controller/legend-padding-spec.ts
  tests/unit/chart/controller/legend-spec.ts
  tests/unit/interaction/action/ellipsis-text-spec.ts
  tests/unit/theme/create-theme-spec.ts
Labels: PR: reviewed-approved

#3106 chore: 4.1.2
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3112 fix: fix empty div container for annotation
  src/chart/controller/annotation.ts
  tests/bugs/3108-spec.ts
Labels: PR: reviewed-approved

#3091 fix: width和height传null或不传时，不要覆盖原有数据
  src/chart/chart.ts
Labels: PR: reviewed-approved

#3118 docs: 增加 element, view.en, dataset 等若干文档
  docs/manual/concepts/adjust.en.md
  docs/manual/concepts/adjust.zh.md
  docs/manual/concepts/coordinate.en.md
  docs/manual/concepts/coordinate.zh.md
  docs/manual/concepts/element.en.md
  docs/manual/concepts/element.zh.md
  docs/manual/concepts/interaction.en.md
  docs/manual/concepts/interaction.zh.md
  docs/manual/concepts/view.en.md
  docs/manual/concepts/view.zh.md
  docs/manual/dataset/connector.en.md
  docs/manual/dataset/connector.zh.md
  docs/manual/dataset/dataset.en.md
  docs/manual/dataset/dataset.zh.md
  docs/manual/dataset/overview.en.md
  docs/manual/dataset/overview.zh.md
  docs/manual/dataset/transform.en.md
  docs/manual/dataset/transform.zh.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested

#3113 feat(testcases): 增加单测，g 层修复 animate shape 在 changesize 的时候报错
  tests/bugs/3111-spec.ts
Labels: PR: partially-approved

#3119 docs: 增加 faq,升级指南等文档
  docs/api/general/annotation.en.md
  docs/api/general/annotation.zh.md
  docs/api/general/label.en.md
  docs/api/general/style.en.md
  docs/api/general/style.zh.md
  docs/manual/concepts/element.en.md
  docs/manual/concepts/element.zh.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/dataset/connector.en.md
  docs/manual/dataset/dataset.en.md
  docs/manual/dataset/overview.en.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: partially-approved

#3116 docs: fix legend filter bug on case line demo
  examples/case/line/demo/line8.ts
Labels: PR: partially-approved

#3132 feat: change log
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3110 fix: 修复element shape进行syncShapeStyle时，可能存在空对象的情况
  src/geometry/element/index.ts
Labels: PR: unreviewed

#3135 docs: 调整文档导航顺序
  docs/manual/concepts/element.en.md
  docs/manual/concepts/element.zh.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved

#3141 fix(esm): remove all lib import
  package.json
  src/animate/animation/sector-path-update.ts
  src/core.ts
  src/dependents.ts
  src/geometry/element/index.ts
  src/interaction/action/component/list-highlight-util.ts
  src/interaction/action/util.ts
  src/interaction/action/view/button.ts
  src/theme/util/create-by-style-sheet.ts
  tests/bugs/2173-spec.ts
  tests/unit/component/axis-circle-spec.ts
Labels: PR: partially-approved

#3142 fix(export): add some export method
  src/core.ts
  src/index.ts
Labels: PR: partially-approved

#3144 fix: 3134
  src/theme/util/create-by-style-sheet.ts
  tests/bugs/3143-spec.ts
Labels: PR: reviewed-approved

#3145 legend marker
  docs/common/marker-cfg.md
  docs/manual/faq.zh.md
  docs/manual/tutorial/legend.zh.md
  docs/manual/upgrade.zh.md
  package.json
  src/util/legend.ts
  tests/bugs/2474-spec.ts
Labels: PR: partially-approved

#3147 feat: 增强饼图标签跟随切片颜色
  src/component/labels.ts
  src/geometry/label/pie.ts
  tests/bugs/3146-spec.ts
Labels: PR: partially-approved

#3148 fix: 修复路径错误
  src/geometry/label/interval.ts
Labels: PR: reviewed-approved

#3149 chore 4.1.5
  CHANGELOG.md
  docs/api/general/event.zh.md
  docs/manual/concepts/component/overview.en.md
  docs/manual/concepts/component/overview.zh.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3150 docs: remove notifications
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved

#3156 fix: correct label position for histogram
  src/geometry/label/base.ts
  tests/bugs/g2plot-2081-spec.ts
Labels: PR: partially-approved

#3165 docs: 404
  docs/api/advanced/register-animation.en.md
  docs/api/advanced/register-animation.zh.md
  docs/api/advanced/register-facet.en.md
  docs/api/advanced/register-facet.zh.md
  docs/api/advanced/register-interaction.en.md
  docs/api/advanced/register-interaction.zh.md
  docs/api/advanced/register-label.en.md
  docs/api/advanced/register-label.zh.md
  docs/api/advanced/register-shape.en.md
  docs/api/advanced/register-shape.zh.md
  docs/api/advanced/register-theme.en.md
  docs/api/advanced/register-theme.zh.md
  docs/api/general/axis.zh.md
  docs/api/general/facet.en.md
  docs/api/general/interaction.en.md
  docs/api/general/legend.zh.md
  docs/common/annotation-base-option.md
  docs/manual/concepts/component/annotation.en.md
  docs/manual/concepts/component/annotation.zh.md
  docs/manual/concepts/component/axis.en.md
  docs/manual/concepts/component/axis.zh.md
  docs/manual/concepts/component/label.en.md
  docs/manual/concepts/component/label.zh.md
  docs/manual/concepts/component/legend.en.md
  docs/manual/concepts/component/legend.zh.md
  docs/manual/faq.zh.md
  docs/manual/upgrade.zh.md
  src/interface.ts
Labels: PR: reviewed-approved
