Repository antvis/G2, pull requests merged in 2020-06, with the labels that each got.

#2519 fix(line 40): replace '!=' with '!=='
  examples/interaction/brush/demo/brush-filter-shape.ts
Labels: PR: reviewed-changes-requested, bug

#2531 fix(annotation): fix regionFilter not work on sub view
  src/chart/controller/annotation.ts
  tests/bugs/sub-view-region-filter-spec.ts
Labels: PR: reviewed-approved, bug

#2530 chore: release v3.5.17
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#2539 Update overview.zh.md
  docs/manual/tutorial/overview.zh.md
Labels: PR: unreviewed

#2560 chore: release v4.0.10
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2547 fix: error if chart destroyed during resize
  src/chart/chart.ts
  tests/unit/chart/chart-spec.ts
Labels: PR: reviewed-approved, bug

#2572 docs(site): update size nav
  README.md
  README.zh-CN.md
  gatsby-config.js
Labels: PR: reviewed-approved, documentation

#2577 fix(2570): 修复 appendPadding 设置后，图表更新不断缩小的问题
  src/chart/layout/auto.ts
  tests/bugs/2570-spec.ts
  tests/unit/chart/chart-spec.ts
Labels: PR: reviewed-approved, bug

#2578 fix(lint): 手工 prettier
  src/chart/chart.ts
Labels: PR: reviewed-changes-requested, bug

#2580 docs: fix indentation
  docs/manual/concepts/data-and-scales.en.md
  docs/manual/concepts/data-and-scales.zh.md
Labels: PR: reviewed-approved, documentation

#2587 fix(legend): 修改 legend 布局的宽高限制
  src/chart/controller/legend.ts
  src/interface.ts
  tests/unit/chart/controller/legend-spec.ts
Labels: PR: reviewed-approved, bug

#2588 chore: release 4.0.11
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2599 Better highlight
  package.json
  src/constant.ts
  src/interaction/action/element/highlight-by-x.ts
  src/interaction/action/element/highlight.ts
  tests/unit/interaction/action/highlight-spec.ts
Labels: PR: partially-approved

#2600 chore: 添加 lint-staged 配置
  package.json
Labels: PR: reviewed-approved, chore

#2601 chore: release v4.0.12
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, chore

#2607 refactor: 删除不必要的代码
  src/base.ts
Labels: PR: reviewed-changes-requested, refactor

#2615 fix: 修复#2279 canvas resize 之后tooltip越界的问题
  src/chart/controller/tooltip.ts
Labels: PR: reviewed-changes-requested, bug
