Repository antvis/G2, pull requests merged in 2020-09, with the labels that each got.

#2783 Fix slider cfg and options
  src/chart/controller/legend.ts
  src/chart/view.ts
  src/interface.ts
  tests/unit/options/annotation-spec.ts
Labels: PR: reviewed-approved

#2785 Feat legend padding
  src/chart/controller/legend.ts
  src/chart/layout/auto.ts
  src/chart/view.ts
  src/interface.ts
  src/theme/style-sheet/light.ts
  src/util/theme.ts
  tests/bugs/2173-spec.ts
  tests/unit/chart/controller/legend-padding-spec.ts
  tests/unit/chart/controller/legend-spec.ts
Labels: PR: partially-approved

#2787 chore: 4.1.0-beta.1
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, chore

#2791 fix(issue-2778): 修复 label 点击的时候，没有获取到数据
  src/component/labels.ts
  tests/bugs/2778-spec.ts
Labels: PR: reviewed-approved, bug

#2789 fix: add dom-util dependence
  package.json
Labels: PR: reviewed-approved, bug

#2788 Options facets
  src/chart/view.ts
  src/interface.ts
  tests/unit/options/facet-spec.ts
Labels: PR: reviewed-approved

#2793 fix(#2433): fix slider collide legend
  src/util/bbox.ts
  tests/bugs/2433-spec.ts
  tests/unit/util/bbox-spec.ts
Labels: PR: partially-approved, bug

#2795 fix(offscreen): sync clip style in offscreen group
  src/geometry/element/index.ts
  tests/bugs/2798-spec.ts
Labels: PR: reviewed-approved, bug

#2802 fix(#2763): 修复 legend-filter 在view中行为错误
  src/util/legend.ts
  tests/bugs/2763-spec.ts
Labels: PR: partially-approved, bug

#2801 Walk through
  src/chart/controller/base.ts
  src/interface.ts
Labels: PR: reviewed-approved

#2803 test(padding): add a test case
  src/chart/layout/auto.ts
  tests/bugs/padding-update-spec.ts
Labels: PR: partially-approved, test

#2800 fix(clear): chart.clear then render, memory leak
  src/chart/view.ts
  tests/bugs/2799-spec.ts
  tests/unit/chart/chart-spec.ts
Labels: PR: reviewed-approved, bug

#2811 fix(typos): correct spelling
  src/index.ts
  src/interaction/grammar-interaction.ts
Labels: PR: reviewed-approved, bug

#2813 feat: support scrollbar component
  src/chart/chart.ts
  src/chart/controller/scrollbar.ts
  src/chart/layout/auto.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/constant.ts
  src/dependents.ts
  src/index.ts
  src/interface.ts
  src/util/theme.ts
  tests/data/sales.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/controller/index-spec.ts
  tests/unit/chart/controller/scrollbar-spec.ts
  tests/unit/chart/controller/tooltip-spec.ts
Labels: PR: partially-approved, enhancement

#2826 docs: walkthrough api link in manual
  docs/manual/developer/registeranimation.en.md
  docs/manual/developer/registeranimation.zh.md
  docs/manual/developer/registerfacet.en.md
  docs/manual/developer/registerfacet.zh.md
  docs/manual/developer/registerlabel.en.md
  docs/manual/developer/registerlabel.zh.md
  docs/manual/developer/registershape.en.md
  docs/manual/developer/registershape.zh.md
  docs/manual/developer/registertheme.en.md
  docs/manual/developer/registertheme.zh.md
  docs/manual/tutorial/axis.en.md
  docs/manual/tutorial/axis.zh.md
  docs/manual/tutorial/coordinate.en.md
  docs/manual/tutorial/coordinate.zh.md
  docs/manual/tutorial/legend.en.md
  docs/manual/tutorial/legend.zh.md
Labels: PR: reviewed-approved, documentation

#2829 feat: 添加 supportCSSTransform 属性, 使图表在 css transform 下事件和交互都生效
  src/chart/chart.ts
  src/interface.ts
Labels: PR: reviewed-approved, enhancement

#2828 fix: slider bugfix
  src/chart/controller/scrollbar.ts
  src/chart/controller/slider.ts
  src/util/types.ts
  tests/bugs/2295-spec.ts
  tests/bugs/2433-spec.ts
  tests/unit/chart/controller/slider-spec.ts
Labels: PR: partially-approved, bug

#2832 chore: upgrade version
  package.json
  src/core.ts
Labels: PR: partially-approved, chore

#2833 fix: build before deploy to get latest type definition
  package.json
Labels: PR: reviewed-approved, bug

#2823 配置项及更新问题
  src/chart/view.ts
  src/geometry/element/index.ts
  src/interface.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/options/views-spec.ts
Labels: PR: reviewed-approved

#2831 feat(geometry): add geometry.custom API for registerShape
  src/geometry/base.ts
  src/interface.ts
  tests/unit/geometry/base-spec.ts
Labels: PR: partially-approved, enhancement

#2834 feat: tooltip custom content 内置 class: "g2-tooltip"
  src/chart/controller/tooltip.ts
  src/interface.ts
  tests/unit/component/tooltip-custom-content-spec.ts
Labels: PR: partially-approved, enhancement

#2840 fix: fix slider changeSize bug and scrollbar overlap with legend
  src/chart/controller/scrollbar.ts
  src/chart/controller/slider.ts
  tests/unit/chart/controller/scrollbar-spec.ts
  tests/unit/chart/controller/slider-spec.ts
Labels: PR: partially-approved, bug

#2838 fix(demo): 修复环图自定义 label 的 demo, 获取 labelItems 为空
  src/geometry/label/polar.ts
Labels: PR: reviewed-approved, bug

#2848 fix(axis): 回调带上默认主题
  src/chart/controller/axis.ts
Labels: PR: reviewed-approved, bug

#2843 feat: view padding sync
  examples/gallery/line/demo/line1.ts
  src/chart/chart.ts
  src/chart/controller/axis.ts
  src/chart/layout/auto.ts
  src/chart/layout/index.ts
  src/chart/view.ts
  src/interface.ts
  tests/bugs/2356-spec.ts
  tests/bugs/2570-spec.ts
  tests/bugs/2658-spec.ts
  tests/bugs/2841-spec.ts
  tests/bugs/2849-spec.ts
  tests/unit/chart/controller/legend-spec.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/options/options-spec.ts
Labels: PR: partially-approved, enhancement

#2850 chore: 4.1.0-beta.8 release
  package.json
  src/core.ts
Labels: PR: reviewed-approved, chore

#2855 fix: 修复数据为空时 slider 报错的问题
  src/chart/controller/slider.ts
  tests/bugs/slider-spec.ts
Labels: PR: reviewed-approved, bug

#2869 feat: improve interval label position
  src/geometry/label/base.ts
  src/geometry/label/interval.ts
  tests/data/positive-negative.ts
  tests/unit/geometry/label/interval-spec.ts
Labels: PR: partially-approved, enhancement

#2866 docs(about): update about-g2 in manual
  docs/api-zh/chart.md
  docs/api-zh/data.md
  docs/manual/about-g2.zh.md
Labels: PR: unreviewed, documentation

#2872 Fix typos
  src/chart/view.ts
  src/geometry/label/layout/pie/outer.ts
  src/interaction/index.ts
  src/interaction/interaction.ts
Labels: PR: reviewed-approved

#2874 docs: move common to docs folder
  docs-cache/api-zh/chart-func.md
  docs-cache/api-zh/geometry-func.md
  docs-cache/api-zh/geometry-get-func.md
  docs-cache/api-zh/register.md
  docs-cache/api-zh/utils.md
  docs-cache/api-zh/view.md
  docs/api/general/annotation.zh.md
  docs/api/general/facet.zh.md
  docs/api/general/geometry.zh.md
  docs/api/general/legend.zh.md
  docs/api/general/tooltip.zh.md
  docs/common/Region.md
  docs/common/annotation-base-option.md
  docs/common/annotation-position.md
  docs/common/attribute-option.md
  docs/common/component-animate-option.md
  docs/common/enhanced-text-cfg.md
  docs/common/facet-cfg.md
  docs/common/facet-title.md
  docs/common/geom-base-cfg.md
  docs/common/marker-cfg.md
  docs/common/region-position-base-option.md
  docs/common/style.md
  docs/common/tooltip-dom.md
Labels: PR: reviewed-approved, documentation

#2876 chore: release 4.1.0-beta.10
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved, chore

#2882 chore: run PR preview on pull_request
  .github/workflows/preview.yml
Labels: PR: unreviewed, chore

#2879 feat(region-filter): add geometry life circle, after draw animate
  src/chart/controller/annotation.ts
  src/constant.ts
  src/geometry/element/index.ts
  tests/bugs/2851-spec.ts
  tests/bugs/sub-view-region-filter-spec.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/util/omit.ts
Labels: PR: partially-approved, enhancement
