Repository antvis/G2, pull requests merged in 2020-08, with the labels that each got.

#2723 fix: bugs in wordcloud demo
  examples/other/other/demo/word-cloud.ts
Labels: PR: reviewed-changes-requested, bug

#2725 feat: add api-extractor for extract typescript declare file
  api-extractor.json
  src/api.ts
  src/geometry/base.ts
Labels: PR: reviewed-changes-requested, enhancement

#2726 feat(pie-label): add pie-outer label layout
  docs/api/geometry/geometry.en.md
  docs/api/geometry/geometry.zh.md
  src/geometry/label/layout/pie/distribute.ts
  src/geometry/label/layout/pie/outer.ts
  src/index.ts
  tests/data/country-economy.ts
  tests/unit/geometry/label/layout/pie-outer-spec.ts
Labels: PR: reviewed-approved, enhancement

#2733 fix: resolve tooltip debounce
  src/util/theme.ts
Labels: PR: reviewed-approved, bug

#2732 添加组件的 tooltip 交互，用于展示缩略文本的完整信息
  CHANGELOG.md
  src/chart/chart.ts
  src/index.ts
  src/interaction/action/component/tooltip/ellipsis-text.ts
  src/interaction/action/component/tooltip/geometry.ts
  src/interaction/action/component/tooltip/sibling.ts
  tests/unit/interaction/action/ellipsis-text-spec.ts
  tests/unit/interaction/action/tooltip-spec.ts
Labels: PR: partially-approved

#2734 fix(change-size): when size is equal, not render
  src/chart/chart.ts
  tests/unit/chart/chart-auto-fit-spec.ts
Labels: PR: reviewed-approved, bug

#2741 refactor(axis): axis update 包含有 create 逻辑,删除容易的 create 逻辑,简化代码
  src/chart/controller/axis.ts
Labels: PR: reviewed-approved, refactor

#2739 feat: Tooltip supported customContent
  src/interface.ts
  tests/unit/component/tooltip-custom-content-spec.ts
Labels: PR: partially-approved, enhancement

#2735 feat(annotation): text annotation content 提供回调，将图表filteredData作为回调参数
  src/chart/controller/annotation.ts
  src/interface.ts
  tests/unit/component/annotation-spec.ts
Labels: PR: partially-approved, enhancement

#2746 chore: upgrade version
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: partially-approved, chore

#2748 fix(background): backgroup shape should set capture = false
  src/chart/view.ts
  tests/bugs/2505-spec.ts
  tests/unit/theme/background-spec.ts
Labels: PR: partially-approved, bug

#2750 fix: the doc example error
  docs/manual/developer/registerinteraction.zh.md
Labels: PR: reviewed-approved, bug

#2751 Adjust layout
  package.json
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/layout/auto.ts
  src/chart/layout/padding-cal.ts
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/util/theme.ts
  tests/bugs/1265-spec.ts
  tests/bugs/1744-spec.ts
  tests/bugs/2045-spec.ts
  tests/bugs/2173-spec.ts
  tests/bugs/2261-spec.ts
  tests/bugs/2307-spec.ts
  tests/bugs/2665-spec.ts
  tests/bugs/active-region-spec.ts
  tests/unit/chart/controller/axis-spec.ts
  tests/unit/chart/controller/legend-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/axis-circle-spec.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/theme/geometry-theme-spec.ts
Labels: PR: reviewed-approved

#2747 feat: label 增强
  examples/pie/basic/demo/pie-size.ts
  src/component/labels.ts
  src/geometry/label/interface.ts
  src/geometry/label/layout/hide-overlap.ts
  src/geometry/label/layout/pie/outer.ts
  src/geometry/label/pie/index.ts
  src/geometry/label/util/index.ts
  src/index.ts
  src/util/collision-detect.ts
  src/util/graphics.ts
  src/util/transform.ts
  tests/bugs/2347-spec.ts
  tests/bugs/2629-spec.ts
  tests/performance/geometry/label/layout/hide-overlap-spec.ts
  tests/unit/geometry/label/layout/hide-overlap-spec.ts
  tests/unit/geometry/label/layout/overlap-spec.ts
  tests/unit/util/collision-detect-spec.ts
  tests/unit/util/transform-spec.ts
Labels: PR: partially-approved, WIP, enhancement

#2759 fix: 移除 0.5px 的边框以及文本的描边
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  tests/bugs/1744-spec.ts
  tests/bugs/1823-spec.ts
  tests/bugs/active-region-spec.ts
  tests/bugs/crosshairs-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/theme/geometry-theme-spec.ts
Labels: PR: reviewed-approved, bug

#2742 fix: gitee mirror action don't work when push gh-pages only
  package.json
Labels: PR: unreviewed, bug

#2760 fix(background): 背景色 shape z-index 顺序不对
  src/chart/view.ts
  tests/unit/theme/background-spec.ts
Labels: PR: partially-approved, bug

#2762 fix(tooltip): make tooltip enterable
  src/chart/controller/tooltip.ts
  src/interaction/action/component/tooltip/geometry.ts
  src/interface.ts
  src/util/bbox.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/interaction/action/tooltip-spec.ts
  tests/unit/util/bbox-spec.ts
Labels: PR: reviewed-approved, bug

#2766 chore(slider): export typedefine
  src/chart/controller/slider.ts
  src/interface.ts
  tests/unit/chart/controller/slider-spec.ts
Labels: PR: reviewed-approved, chore

#2768 chore(view-recursive): add warning message before refactor
  src/chart/view.ts
Labels: PR: reviewed-approved, chore

#2761 docs(manual): update english documentation
  README.md
  docs/manual/about-g2.en.md
  docs/manual/concepts-overview.en.md
  docs/manual/contact.en.md
  docs/manual/faq.en.md
  docs/manual/getting-started.en.md
  docs/manual/shape-attrs.en.md
  docs/manual/upgrade.en.md
Labels: PR: reviewed-approved, documentation

#2753 feat(label): add adjust-color label layout
  src/geometry/label/layout/adjust-color.ts
  src/geometry/label/layout/interval/adjust-position.ts
  src/geometry/label/layout/point/adjust-position.ts
  src/geometry/label/util/index.ts
  src/index.ts
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/util/bbox.ts
  src/util/color.ts
  src/util/theme.ts
  tests/data/city-temperature.ts
  tests/data/sales.ts
  tests/unit/geometry/label/layout/adjust-color-spec.ts
  tests/unit/geometry/label/layout/interval/adjust-position-spec.ts
  tests/unit/geometry/label/layout/point/adjust-position-spec.ts
  tests/util/math.ts
Labels: PR: partially-approved, enhancement

#2771 Options 配置项优化系列
  src/chart/view.ts
  src/geometry/base.ts
  src/interface.ts
  tests/unit/options/events-spec.ts
  tests/unit/options/label-spec.ts
  tests/unit/options/options-spec.ts
  tests/unit/options/slider-spec.ts
Labels: PR: reviewed-approved, WIP

#2776 fix(slider): slider + layout, add slider padding
  src/chart/controller/slider.ts
  src/chart/layout/auto.ts
  src/constant.ts
  src/interface.ts
  src/util/bbox.ts
  src/util/theme.ts
  tests/bugs/2212-spec.ts
  tests/unit/chart/controller/slider-spec.ts
  tests/unit/util/bbox-spec.ts
Labels: PR: reviewed-approved, bug

#2782 Fix tooltip events
  docs/manual/tutorial/tooltip.en.md
  docs/manual/tutorial/tooltip.zh.md
  src/chart/controller/tooltip.ts
  src/chart/event.ts
  tests/unit/chart/controller/tooltip-spec.ts
  tests/unit/chart/view/index-spec.ts
Labels: PR: reviewed-approved
