Repository antvis/G2, pull requests merged in 2020-01, with the labels that each got.

#1889 feat(interaction): add view interaction
  examples/interaction/interaction/demo/drag-move.ts
  examples/interaction/interaction/demo/meta.json
  examples/interaction/interaction/demo/zoom.ts
  package.json
  src/interaction/action/base.ts
  src/interaction/action/data/range-filter.ts
  src/interaction/action/index.ts
  src/interaction/action/register.ts
  src/interaction/action/view/drag.ts
  src/interaction/action/view/move.ts
  src/interaction/action/view/scale-transform.ts
  src/interaction/action/view/scale-translate.ts
  src/interaction/action/view/scale-zoom.ts
  src/interaction/action/view/selection.ts
  src/interface.ts
  tests/unit/interaction/action/view-scale-spec.ts
  tests/unit/interaction/action/view-spec.ts
  tests/unit/interaction/element-spec.ts
Labels: PR: reviewed-approved, enhancement

#1893 Release 4.0 beta
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested

#1898 fix: 修复坐标轴网格线 grid 动画未生效的问题
  src/theme/antv.ts
  tests/unit/chart/controller/axis-spec.ts
Labels: PR: reviewed-approved, bug

#1902 chore: 修复错误的代码标识
  docs/api/shape.en.md
  docs/api/shape.zh.md
  docs/api/slider.en.md
  docs/api/slider.zh.md
  docs/manual/tutorial/legend.en.md
  docs/manual/tutorial/legend.zh.md
Labels: PR: unreviewed, chore

#1900 feat(action): add interaction
  examples/interaction/interaction/demo/drag-move.ts
  src/chart/event.ts
  src/interaction/action/index.ts
  src/interaction/action/view/button.ts
  src/interaction/context.ts
  src/interaction/index.ts
  src/interface.ts
  tests/unit/interaction/action/button-spec.ts
  tests/unit/interaction/element-spec.ts
  tests/unit/interaction/interaction-spec.ts
Labels: PR: reviewed-approved, enhancement

#1913 feat(padding): sub view padding extends parent view padding
  examples/gallery/area/demo/area7.ts
  src/chart/view.ts
  tests/unit/chart/multi-view-spec.ts
Labels: PR: reviewed-approved, enhancement

#1916 feat: area Geometry 支持 startOnZero 属性
  src/geometry/area.ts
  src/geometry/base.ts
  src/index.ts
  tests/unit/geometry/area-spec.ts
  tests/unit/geometry/line-spec.ts
Labels: PR: reviewed-approved, enhancement

#1915 feat: 当用户通过 scale 定义 values 后，geometry 也需要按照 values 对数据进行分组
  src/geometry/base.ts
  src/geometry/util/group-data.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/util/group-data-spec.ts
Labels: PR: reviewed-approved, enhancement

#1920 [3.6.x]fix: 使用color-util代替attr/color-util
  packages/component/package.json
  packages/component/src/legend/continuous/color.ts
  packages/g2/package.json
  packages/g2/src/dependents.ts
Labels: PR: reviewed-changes-requested, bug

#1928 Upgrade scale
  examples/area/basic/demo/area-large.ts
  examples/area/range/demo/range.ts
  examples/bar/dodge/demo/bar4.ts
  examples/bar/dodge/demo/bar5.ts
  examples/candlestick/candlestick/demo/basic.ts
  examples/candlestick/candlestick/demo/k-and-area.ts
  examples/column/basic/demo/helix-coordinate.ts
  examples/column/histogram/demo/histogram.ts
  examples/component/component/demo/label-treemap.ts
  examples/funnel/funnel/demo/basic.ts
  examples/gallery/area/demo/area5.ts
  examples/gallery/area/demo/area7.ts
  examples/gallery/bar/demo/bar1.ts
  examples/gallery/bar/demo/bar2.ts
  examples/gallery/bar/demo/bar3.ts
  examples/gallery/column/demo/column3.ts
  examples/gallery/pie/demo/pie2.ts
  examples/gauge/gauge/demo/basic.ts
  examples/gauge/gauge/demo/color.ts
  examples/gauge/gauge/demo/text.ts
  examples/map/map/demo/bubble-map.ts
  examples/map/map/demo/hex-choropleth-map.ts
  examples/map/map/demo/us-states-hex.ts
  examples/map/map/demo/with-heatmap.ts
  examples/point/scatter/demo/bubble-text.ts
  examples/point/scatter/demo/time-bubble.ts
  examples/relation/relation/demo/polar-treemap.ts
  examples/relation/relation/demo/treemap-children.ts
  examples/relation/relation/demo/treemap.ts
  package.json
  src/dependents.ts
  src/util/scale.ts
  tests/unit/chart/controller/axis-spec.ts
  tests/unit/chart/view/scale-sync/multi-view-sync-scale-spec.ts
  tests/unit/chart/view/scale-sync/simple-sync-scale-spec.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/component/legend-continuous-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/line-spec.ts
  tests/unit/interaction/action/data-fitler-spec.ts
  tests/unit/interaction/action/range-filter-spec.ts
  tests/unit/util/scale-spec.ts
  tests/unit/util/tooltip-spec.ts
Labels: PR: reviewed-approved

#1936 fix(circle-grid): fix circle grid center is not valid
  src/chart/controller/axis.ts
  tests/unit/component/axis-circle-spec.ts
Labels: PR: reviewed-approved, bug

#1940 fix: 修复 geometry 上设置 theme 不生效的问题
  src/chart/view.ts
  tests/unit/theme/geometry-theme-spec.ts
Labels: PR: reviewed-approved, bug

#1944 feat(axis): axis support position config
  src/chart/controller/axis.ts
  src/chart/interface.ts
  src/util/axis.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/util/axis-spec.ts
Labels: PR: reviewed-approved, enhancement

#1952 feat: chart.annotation().text() 支持 rotate 属性
  src/chart/controller/annotation.ts
  tests/unit/component/annotation-spec.ts
Labels: PR: reviewed-approved, enhancement
