Repository antvis/G2, pull requests merged in 2020-07, with the labels that each got.

#2638 优化坐标轴超常文本展现策略
  package.json
  src/chart/chart.ts
  src/chart/controller/axis.ts
  src/constant.ts
  src/interface.ts
  src/util/theme.ts
  tests/unit/chart/controller/axis-auto-overlap.ts
Labels: PR: partially-approved

#2593 fix: 拆分字段有空数值时不使用tooltip title来显示
  src/util/tooltip.ts
  tests/unit/util/tooltip-spec.ts
Labels: PR: partially-approved, bug

#2579 改正示例“大规模区域图”中的时间格式
  examples/area/basic/demo/area-large.ts
Labels: PR: reviewed-changes-requested

#2643 fix: issues of pie demo 2
  examples/gallery/pie/demo/pie3.ts
Labels: PR: reviewed-changes-requested, bug

#2644 docs(event.en.md): fix typo
  docs/manual/tutorial/event.en.md
Labels: PR: reviewed-approved, documentation

#2648 fix(pie-label): 饼图 label 若干修复
  src/component/labels.ts
  src/geometry/label/layout/distribute.ts
  tests/bugs/2347-spec.ts
  tests/bugs/2629-spec.ts
Labels: PR: reviewed-approved, bug

#2645 fix: 修复 interval 下 shape='line' 设置 lineCap 失效的问题
  src/geometry/shape/interval/line.ts
  src/geometry/shape/interval/util.ts
  tests/unit/geometry/shape/interval-spec.ts
Labels: PR: reviewed-approved, bug

#2604 fix: tooltip controller isVisible not update
  src/chart/controller/slider.ts
  src/chart/controller/tooltip.ts
  tests/bugs/2295-spec.ts
  tests/bugs/2603-spec.ts
Labels: PR: reviewed-approved, bug

#2652 Docs/navs
  gatsby-config.js
Labels: PR: reviewed-changes-requested

#2655 docs: modified scale.md document error
  docs/manual/tutorial/scale.en.md
  docs/manual/tutorial/scale.zh.md
Labels: PR: reviewed-approved, documentation

#2659 fix: #2658
  src/chart/view.ts
  tests/bugs/2658-spec.ts
Labels: PR: reviewed-approved, bug

#2666 feat: path line area 三类 Geometry 支持 showSinglePoint 属性，用于支持单点孤立数据点的绘制
  src/geometry/area.ts
  src/geometry/path.ts
  src/geometry/shape/area/util.ts
  src/geometry/shape/line/index.ts
  src/geometry/shape/line/step.ts
  src/geometry/shape/util/get-path-points.ts
  src/interface.ts
  tests/bugs/2665-spec.ts
  tests/unit/geometry/shape/util/get-path-points-spec.ts
Labels: PR: reviewed-approved, enhancement

#2669 fix(label): 修复 labelItem 不存在时，coordinate 为空，获取cetner中心坐标点出错
  src/component/labels.ts
  tests/bugs/component-label-spec.ts
Labels: PR: reviewed-approved, bug

#2667 chore: v4.0.13
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved, chore

#2677 fix: path err in dynamic demos
  examples/gallery/dynamic/demo/dynamic-bar.ts
  examples/gallery/dynamic/demo/dynamic-bubble.ts
Labels: PR: reviewed-changes-requested, bug

#2688 fix: error in bubbleplot demo
  examples/point/bubble/demo/bubble-text.ts
Labels: PR: reviewed-approved, bug

#2694 chore: use new-issue.antv.vision for bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: PR: partially-approved, chore

#2687 组件文本的自适应
  src/chart/controller/annotation.ts
  src/chart/controller/legend.ts
  src/dependents.ts
  src/interface.ts
  src/util/theme.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/component/legend-category-spec.ts
Labels: PR: reviewed-approved

#2692 fix: 坐标轴 verticalLimitLength 的参照物是画布
  src/chart/controller/axis.ts
  src/facet/circle.ts
  src/facet/list.ts
  src/facet/matrix.ts
  src/facet/mirror.ts
  src/facet/rect.ts
  src/facet/tree.ts
  src/geometry/shape/polygon/square.ts
  src/index.ts
  src/interface.ts
  tests/unit/facet/circle/index-spec.ts
Labels: PR: reviewed-approved, bug

#2700 chore: release 4.0.14
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2710 fix: #2706
  examples/other/other/demo/word-cloud.ts
Labels: PR: reviewed-changes-requested, bug

#2718 docs: add part API documents
  .gitignore
  docs/api/chart.en.md
  docs/api/chart.zh.md
  docs/api/element.en.md
  docs/api/element.zh.md
  docs/api/geometry/area.en.md
  docs/api/geometry/area.zh.md
  docs/api/geometry/edge.en.md
  docs/api/geometry/edge.zh.md
  docs/api/geometry/geometry.en.md
  docs/api/geometry/geometry.zh.md
  docs/api/geometry/heatmap.en.md
  docs/api/geometry/heatmap.zh.md
  docs/api/geometry/interval.en.md
  docs/api/geometry/interval.zh.md
  docs/api/geometry/line.en.md
  docs/api/geometry/line.zh.md
  docs/api/geometry/path.en.md
  docs/api/geometry/path.zh.md
  docs/api/geometry/point.en.md
  docs/api/geometry/point.zh.md
  docs/api/geometry/schema.en.md
  docs/api/geometry/schema.zh.md
  docs/api/interaction.en.md
  docs/api/interaction.zh.md
  docs/api/scale.en.md
  docs/api/scale.zh.md
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, documentation

#2722 chore: gatsby version update
  package.json
Labels: PR: reviewed-approved, chore
