Repository antvis/G2, pull requests merged in 2020-10, with the labels that each got.

#2890 refactor(legend): legend update and render with same logic
  src/chart/controller/legend.ts
Labels: PR: unreviewed, refactor

#2892 fix(types): add legend option
  src/interface.ts
Labels: PR: reviewed-approved, bug

#2885 docs: update chart, data, get-started. add demo playground
  docs/api/general/chart.zh.md
  docs/api/general/data.zh.md
  docs/common/style.md
  docs/manual/getting-started.zh.md
  examples/column/basic/demo/basic.ts
  package.json
  site/pages/docs.less
  site/pages/index.less
Labels: PR: reviewed-approved, documentation

#2894 feat(lint): add lint-md for docs lint
  .lintmdrc
  package.json
Labels: PR: unreviewed, enhancement

#2897 fix(pie-demo): typo, fixed #2884
  examples/pie/nested/demo/multi-level.ts
Labels: PR: unreviewed, bug

#2889 feat(legend): set default maxItemWidth = 200
  src/util/theme.ts
  tests/unit/component/legend-category-spec.ts
Labels: PR: partially-approved, enhancement

#2898 chore: v4.1.0-beta.11
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, chore

#2896 docs(view): add docs for view
  docs/manual/concepts/view.zh.md
  examples/map/map/demo/choropleth-map.ts
Labels: PR: partially-approved, documentation

#2901 docs(facet): improve facet docs
  docs/api/general/facet.zh.md
  docs/common/facet-cfg.md
  docs/common/facet-title.md
  docs/common/region.md
Labels: PR: unreviewed, documentation

#2895 docs(interaction): add docs for grammar of interaction
  docs/manual/concepts/interaction.zh.md
Labels: PR: unreviewed, documentation

#2909 fix: 漏斗图 label position 可生效
  src/geometry/label/interval.ts
  tests/unit/geometry/label/interval-spec.ts
Labels: PR: reviewed-approved, bug

#2911 docs: marker单词拼写错误修正
  docs/api-zh/legend.md
  docs/manual/tutorial/event.en.md
  docs/manual/tutorial/event.zh.md
Labels: PR: reviewed-approved, documentation

#2871 fix(issue-2541): state 状态依然存在时，但由于changeSize, changeData 等重绘后丢失
  src/geometry/element/index.ts
  tests/bugs/2541-spec.ts
  tests/unit/chart/controller/scrollbar-spec.ts
Labels: PR: partially-approved, WIP, bug

#2917 docs: modify some descriptions
  docs/api-zh/legend.md
  docs/manual/dataset/transform.en.md
  docs/manual/dataset/transform.zh.md
Labels: PR: partially-approved, documentation

#2906 fix(issue-2905): 自定义 shape 的默认样式设置
  src/geometry/base.ts
  src/geometry/shape/base.ts
  src/interface.ts
  tests/bugs/2905-spec.ts
Labels: PR: reviewed-approved, bug

#2922 feat(annotation): add support for mean / median
  src/chart/controller/annotation.ts
  src/util/annotation.ts
  src/util/stat.ts
  tests/unit/util/annotation-spec.ts
  tests/unit/util/stat-spec.ts
Labels: PR: partially-approved, enhancement

#2919 fix: 修复 adjust-color label layout 对一些颜色不生效的问题
  src/util/color.ts
  tests/unit/util/color-spec.ts
Labels: PR: partially-approved, bug

#2925 fix: median typo
  src/util/annotation.ts
  tests/unit/util/annotation-spec.ts
Labels: PR: partially-approved, bug

#2916 fix(annotation): text annotation re-render will be hidden
  src/chart/controller/annotation.ts
  tests/bugs/2851-spec.ts
Labels: PR: reviewed-approved, bug

#2926 chore: v4.1.0-beta.13
  package.json
  src/core.ts
Labels: PR: unreviewed, chore

#2927 docs: add theme doc
  docs/api/general/theme.zh.md
Labels: PR: reviewed-approved, documentation

#2931 feat(docs): add event document
  docs/api/general/event.zh.md
Labels: PR: reviewed-changes-requested

#2932 文档: 图形语法
  docs/manual/about-g2.zh.md
  docs/manual/concepts/grammar-of-graphic.zh.md
  docs/manual/concepts/graph-grammar.zh.md
Labels: PR: reviewed-changes-requested

#2934 feat: G2 层支持 custom annotation html annotation
  package.json
  src/chart/controller/annotation.ts
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/controller/slider.ts
  src/interface.ts
  tests/unit/component/annotation-spec.ts
Labels: PR: partially-approved

#2936 New docs adjust
  docs/api/general/adjust.zh.md
  docs/api/general/animate.zh.md
  docs/api/general/annotation.zh.md
  docs/api/general/axis.zh.md
  docs/api/general/event.zh.md
  docs/api/general/facet.zh.md
  docs/api/general/geometry.zh.md
  docs/api/general/interaction.zh.md
  docs/api/general/label.zh.md
  docs/api/general/legend.zh.md
  docs/api/general/scrollbar.zh.md
  docs/api/general/slider.zh.md
  docs/api/general/theme.zh.md
  docs/api/general/tooltip.zh.md
  docs/manual/concepts/adjust.zh.md
Labels: PR: reviewed-changes-requested

#2935 docs: add shape attrs
  docs/api/shape/shape-attrs.zh.md
Labels: PR: reviewed-changes-requested

#2938 docs(component): add docs for components
  docs/manual/concepts/composition.zh.md
Labels: PR: reviewed-changes-requested

#2942 docs: coordinate
  docs/manual/concepts/coordinate.zh.md
Labels: PR: reviewed-changes-requested

#2937 docs: geometry
  docs/manual/concepts/composition.zh.md
  docs/manual/concepts/geometry.zh.md
  docs/manual/concepts/geometry/area.en.md
  docs/manual/concepts/geometry/area.zh.md
  docs/manual/concepts/geometry/interval.en.md
  docs/manual/concepts/geometry/interval.zh.md
  docs/manual/concepts/geometry/overview.en.md
  docs/manual/concepts/geometry/overview.zh.md
  docs/manual/concepts/geometry/path-and-line.en.md
  docs/manual/concepts/geometry/path-and-line.zh.md
  docs/manual/concepts/geometry/point.en.md
  docs/manual/concepts/geometry/point.zh.md
  docs/manual/concepts/geometry/polygon.en.md
  docs/manual/concepts/geometry/polygon.zh.md
  docs/manual/concepts/geometry/schema.en.md
  docs/manual/concepts/geometry/schema.zh.md
  docs/manual/concepts/grammar-of-graphic.zh.md
  docs/manual/concepts/interaction.zh.md
  gatsby-config.js
Labels: PR: unreviewed

#2945 fix(#2905): 无需传入 color,color 必须来源于字段映射
  src/geometry/base.ts
  tests/bugs/2905-spec.ts
Labels: PR: reviewed-approved

#2947 chore: 4.1.0-beta.14
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: partially-approved

#2949 docs: 文档补充
  docs/api/general/animate.zh.md
  docs/manual/articles.zh.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/tutorial/data-flow.en.md
  docs/manual/tutorial/data-flow.zh.md
  docs/manual/tutorial/legend.en.md
  docs/manual/tutorial/legend.zh.md
  docs/manual/tutorial/renderers.en.md
  docs/manual/tutorial/renderers.zh.md
  docs/manual/tutorial/tooltip.en.md
  docs/manual/tutorial/tooltip.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved

#2951 docs: unified types hightlight to sign code
  docs/api/general/adjust.zh.md
  docs/api/general/axis.zh.md
  docs/api/general/coordinate.zh.md
  docs/api/general/interaction.zh.md
  docs/api/general/label.zh.md
  docs/api/general/legend.zh.md
  docs/api/general/scale.zh.md
  docs/common/annotation-position.md
Labels: PR: reviewed-approved

#2953 feat(line-style): default use round style
  src/util/theme.ts
Labels: PR: partially-approved

#2955 docs: add docs for slider/scrollbar/annotation
  docs/api/general/annotation.zh.md
  docs/api/general/scrollbar.zh.md
  docs/api/general/slider.zh.md
  docs/common/scrollbar-options.md
  docs/common/slider-options.md
  docs/manual/concepts/composition.zh.md
Labels: PR: partially-approved

#2957 docs: event & interaction API
  docs/api/general/coordinate.zh.md
  docs/api/general/event.zh.md
  docs/api/general/interaction.zh.md
Labels: PR: unreviewed

#2958 fix: catalogue of docs
  gatsby-config.js
Labels: PR: partially-approved

#2960 chore: upgrade gatsby theme preview
  gatsby-config.js
  package.json
  site/pages/docs.less
  site/pages/index.less
Labels: PR: reviewed-approved

#2962 docs(component): migrate components manaul and add scrollbar manual
  docs/manual/concepts/component/annotation.en.md
  docs/manual/concepts/component/annotation.zh.md
  docs/manual/concepts/component/axis.en.md
  docs/manual/concepts/component/axis.zh.md
  docs/manual/concepts/component/legend.en.md
  docs/manual/concepts/component/legend.zh.md
  docs/manual/concepts/component/overview.en.md
  docs/manual/concepts/component/overview.zh.md
  docs/manual/concepts/component/scrollbar.en.md
  docs/manual/concepts/component/scrollbar.zh.md
  docs/manual/concepts/component/slider.en.md
  docs/manual/concepts/component/slider.zh.md
  docs/manual/concepts/component/tooltip.en.md
  docs/manual/concepts/component/tooltip.zh.md
  examples/column/basic/demo/meta.json
  examples/column/basic/demo/scrollbar.ts
  gatsby-config.js
Labels: PR: partially-approved

#2964 New docs merge master
  CHANGELOG.md
  docs-cache/manual/dataset/transform.en.md
  docs-cache/manual/dataset/transform.zh.md
  docs-cache/manual/tutorial/event.en.md
  docs-cache/manual/tutorial/event.zh.md
  docs/api/general/legend.zh.md
  examples/pie/nested/demo/multi-level.ts
  package.json
  src/chart/controller/annotation.ts
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/chart/controller/slider.ts
  src/chart/view.ts
  src/constant.ts
  src/core.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/label/base.ts
  src/geometry/label/interval.ts
  src/geometry/label/layout/pie/outer.ts
  src/geometry/shape/base.ts
  src/interaction/index.ts
  src/interaction/interaction.ts
  src/interface.ts
  src/util/annotation.ts
  src/util/color.ts
  src/util/stat.ts
  src/util/theme.ts
  tests/bugs/2541-spec.ts
  tests/bugs/2851-spec.ts
  tests/bugs/2905-spec.ts
  tests/bugs/slider-spec.ts
  tests/bugs/sub-view-region-filter-spec.ts
  tests/data/positive-negative.ts
  tests/unit/chart/controller/scrollbar-spec.ts
  tests/unit/component/annotation-spec.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/label/interval-spec.ts
  tests/unit/util/annotation-spec.ts
  tests/unit/util/color-spec.ts
  tests/unit/util/stat-spec.ts
  tests/util/omit.ts
Labels: PR: partially-approved

#2963 feat(theme): 更新主题色,更新三个色值
  src/theme/style-sheet/light.ts
  tests/bugs/2258-spec.ts
  tests/unit/component/legend-continuous-spec.ts
Labels: PR: reviewed-approved

#2965 docs: advances
  docs/api/advanced/dive-into-theme.en.md
  docs/api/advanced/dive-into-theme.zh.md
  docs/api/advanced/gesture.zh.md
  docs/api/advanced/register-animate.zh.md
  docs/api/advanced/register-facet.zh.md
  docs/api/advanced/register-geometry.zh.md
  docs/api/advanced/register-interaction.zh.md
  docs/api/advanced/register-label-layout.zh.md
  docs/api/advanced/register-shape.zh.md
  docs/api/advanced/register-theme.zh.md
  docs/api/advanced/registeranimation.en.md
  docs/api/advanced/registeranimation.zh.md
  docs/api/advanced/registerfacet.en.md
  docs/api/advanced/registerfacet.zh.md
  docs/api/advanced/registerinteraction.en.md
  docs/api/advanced/registerinteraction.zh.md
  docs/api/advanced/registerlabel.en.md
  docs/api/advanced/registerlabel.zh.md
  docs/api/advanced/registershape.en.md
  docs/api/advanced/registershape.zh.md
  docs/api/advanced/registertheme.en.md
  docs/api/advanced/registertheme.zh.md
  docs/api/advanced/require.en.md
  docs/api/advanced/require.zh.md
Labels: PR: reviewed-changes-requested

#2966 docs: scale docs
  docs/manual/tutorial/scale.en.md
  docs/manual/tutorial/scale.zh.md
Labels: PR: reviewed-changes-requested

#2967 docs: label
  docs/manual/concepts/component/annotation.en.md
  docs/manual/concepts/component/annotation.zh.md
  docs/manual/concepts/component/label.en.md
  docs/manual/concepts/component/label.zh.md
  docs/manual/concepts/component/scrollbar.en.md
  docs/manual/concepts/component/scrollbar.zh.md
  docs/manual/concepts/component/slider.en.md
  docs/manual/concepts/component/slider.zh.md
Labels: PR: partially-approved
