Repository antvis/G2, pull requests merged in 2020-04, with the labels that each got.

#2246 feat(interaction): avoid event error
  src/index.ts
  src/interaction/action/element/range-state.ts
  src/interaction/grammar-interaction.ts
  tests/unit/interaction/action/highlight-spec.ts
Labels: PR: reviewed-approved, enhancement

#2257 fix(#2173): fix legend overlap when in same direction
  src/chart/controller/legend.ts
  tests/bugs/2173-spec.ts
Labels: PR: reviewed-approved, bug

#2270 chore: release v4.0.4
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved, chore

#2276 feat: add sankey sort
  docs/manual/dataset/transform.en.md
  docs/manual/dataset/transform.zh.md
  examples/relation/relation/demo/sankey.ts
  package.json
Labels: PR: reviewed-changes-requested, enhancement

#2277 fix: fix scatter crosshairs style
  src/chart/controller/tooltip.js
Labels: PR: reviewed-changes-requested, bug

#2287 Release v4.0.5
  CHANGELOG.md
  docs/manual/concepts/visual-channel.en.md
  docs/manual/concepts/visual-channel.zh.md
  docs/manual/tutorial/interaction.en.md
  docs/manual/tutorial/interaction.zh.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested

#2283 chore: release v3.5.15
  CHANGELOG.md
  package.json
  src/global.js
Labels: PR: reviewed-changes-requested, chore

#2280 fix(#2272): 当映射数据中不存在 x 和 y 时，不绘制 label
  src/geometry/label/base.ts
  tests/bugs/2272-spec.ts
Labels: PR: partially-approved, bug

#2296 chore: release v4.0.6
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2315 Fix 2272
  packages/g2/__tests__/bug/2272-spec.js
  packages/g2/package.json
  packages/g2/src/element/controller/label/components/base.ts
Labels: PR: reviewed-changes-requested

#2308 Fix state style
  src/geometry/element/index.ts
  tests/bugs/state-style-spec.ts
  tests/unit/chart/controller/gesture-spec.ts
Labels: PR: partially-approved

#2316 chore: 补充外联 interface 的注释
  src/interface.ts
Labels: PR: reviewed-approved, chore

#2319 fix(delegation): mouse leave failed
  package.json
  src/chart/view.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  tests/bugs/2307-spec.ts
  tests/unit/chart/controller/gesture-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/label/layout/limit-in-canvas-spec.ts
Labels: PR: reviewed-approved, bug

#2328 changlog 以及文档自动生成命令优化
  bin/doc.sh
  bin/typedoc-theme/theme.js
  package.json
Labels: PR: partially-approved, chore

#2329 chore: release v4.0.7
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2330 fix: site build
  package.json
Labels: PR: reviewed-approved, bug

#2336 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved, chore

#2340 chore: remove sensitive data
  tests/bugs/2197-spec.ts
  tests/bugs/2212-spec.ts
  tests/bugs/2261-spec.ts
  tests/bugs/views-legend-spec.ts
Labels: PR: reviewed-approved, chore

#2341 chore: remove unnecessary file
  examples/area/basic/demo/area-null.ts
  examples/area/basic/demo/meta.json
  examples/data/time-scatter.json
  examples/point/bubble/demo/time-bubble.ts
Labels: PR: reviewed-changes-requested, chore

#2348 chore: add sourcesContent to sourcemap close #2338
  tsconfig.json
Labels: PR: partially-approved, chore

#2360 chore: 去掉外部钉钉群二维码
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
Labels: PR: unreviewed, chore

#2359 refactor: 增加所有接口的导出
  src/index.ts
Labels: PR: reviewed-approved, refactor

#2363 fix(interaction): delegate object error
  src/interaction/action/element/state.ts
  tests/unit/geometry/label/label-update-spec.ts
Labels: PR: reviewed-approved, bug

#2364 docs(view): component docs
  src/chart/view.ts
Labels: PR: reviewed-changes-requested, documentation

#2369 fix: gesture controller off event when destroy
  src/chart/controller/gesture.ts
  tests/unit/chart/controller/gesture-spec.ts
Labels: PR: partially-approved, bug

#2368 fix(types): remove syntax export * as
  package.json
  src/core.ts
  src/index.ts
Labels: PR: reviewed-changes-requested, bug
