Repository antvis/G2, pull requests merged in 2020-02, with the labels that each got.

#1957 chore: 同步双轴数值范围
  examples/column/stack/demo/rounded.js
Labels: PR: reviewed-changes-requested, chore

#1975 feat(interaction): chart support defaultInteractions
  src/chart/chart.ts
  src/chart/controller/tooltip.ts
  src/chart/interface.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/interaction/action/tooltip-spec.ts
  tests/unit/theme/geometry-theme-spec.ts
Labels: PR: reviewed-approved, enhancement

#1981 fix: update data region options
  examples/gallery/line/demo/line3.ts
  src/chart/controller/annotation.ts
  tests/unit/component/annotation-spec.ts
Labels: PR: reviewed-approved, bug

#1982 fix: 修复重复调用 chart.render() 绘图异常问题
  src/animate/index.ts
  tests/bugs/1980-spec.ts
Labels: PR: reviewed-approved, bug

#1985 fix: 修复 tooltip crosshairs 失效的问题。Closed #1984
  src/chart/controller/tooltip.ts
Labels: PR: reviewed-changes-requested, bug

#1983 Feat category legend unchecked
  src/chart/view.ts
  src/util/legend.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/component/legend-unchecked-spec.ts
Labels: PR: reviewed-approved

#1986 feat(selected): pie selected animate
  src/interaction/action/element/pie-selected.ts
  src/interaction/action/element/single-state.ts
  tests/bugs/pie-unselected-spec.ts
Labels: PR: reviewed-approved, enhancement

#1998 Issue 1993
  examples/gallery/line/demo/line8.ts
  examples/interaction/interaction/demo/pie-selected.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/interface.ts
  src/geometry/path.ts
  src/geometry/shape/base.ts
  src/index.ts
  src/interaction/action/element/pie-selected.ts
  src/theme/antv.ts
  tests/bugs/pie-unselected-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/element/index-spec.ts
  tests/unit/geometry/shape/area-spec.ts
  tests/unit/geometry/shape/base-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/line-spec.ts
  tests/unit/geometry/shape/point-spec.ts
  tests/unit/geometry/shape/polygon-spec.ts
  tests/unit/geometry/shape/schema-spec.ts
  tests/unit/geometry/state-spec.ts
  tests/unit/interaction/action/selected-spec.ts
Labels: PR: reviewed-approved

#2015 feat: geometry 添加 getShapes() 接口已获取所有的 shapes 图形
  src/geometry/base.ts
  tests/unit/geometry/base-spec.ts
Labels: PR: reviewed-approved, enhancement

#2012 fix(axis): update axis component when coordinate changed
  src/chart/controller/axis.ts
  tests/bugs/1935-spec.ts
Labels: PR: reviewed-approved, bug

#2011 feat(interaction): drag mask
  examples/interaction/interaction/demo/range-highlight.ts
  src/index.ts
  src/interaction/action/element/filter.ts
  src/interaction/action/element/range-state.ts
  src/interaction/action/mask/base.ts
  src/interaction/action/mask/circle.ts
  src/interaction/action/mask/path.ts
  src/interaction/action/mask/rect.ts
  src/interaction/action/util.ts
  tests/unit/interaction/action/mask-filter-spec.ts
  tests/unit/interaction/action/mask-range-state-spec.ts
  tests/unit/interaction/action/mask-spec.ts
  tests/unit/interaction/element-spec.ts
Labels: PR: reviewed-approved, enhancement

#2017 feat: 细微得调节下主题内容
  src/theme/antv.ts
Labels: PR: reviewed-changes-requested, enhancement

#2008 [3.6.x] update scale to 0.3 stable version
  packages/component/package.json
  packages/g2/package.json
Labels: PR: reviewed-approved

#2036 fix: 修复多 view 共享一个 shapeFactory 实例，导致 Coordinate 混用
  src/geometry/base.ts
  tests/bugs/2032-spec.ts
Labels: bug

#2057 【G2 3.6.x】fix: 修复 legend 翻页判断问题
  packages/component/src/legend/category/canvas.ts
Labels: bug

#2062 fix: 修复 package.json 中 main、module、types 的引用地址问题
  tsconfig.json
Labels: bug

#2063 feat: 添加 view.getSnapRecords() 接口
  src/chart/view.ts
  src/util/tooltip.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
  tests/unit/util/tooltip-spec.ts
Labels: enhancement

#2066 fix(coordinate): redo matrix actions when adjust coordinate start end
  src/chart/controller/coordinate.ts
  tests/bugs/2044-spec.ts
  tests/bugs/active-region-spec.ts
Labels: bug

#2065 feat(interaction): add actions of higlight
  src/chart/chart.ts
  src/index.ts
  src/interaction/action/element/highlight-by-color.ts
  src/interaction/action/element/highlight-by-x.ts
  src/interaction/action/element/highlight.ts
  src/interaction/action/element/state.ts
  tests/unit/interaction/action/highlight-spec.ts
Labels: enhancement

#2067 Legend unchecked
  src/chart/controller/legend.ts
  src/chart/util/scale-pool.ts
  tests/bugs/legend-check-spec.ts
Labels: PR: reviewed-approved

#2064 fix(legend): 分页图例设置 maxWidth、maxHeight 导致位置不正确
  src/chart/controller/legend.ts
  tests/unit/component/legend-category-spec.ts
Labels: bug

#2081 chore: 注释补充必要的链接
  src/chart/controller/coordinate.ts
  src/chart/view.ts
  src/interaction/context.ts
  src/interaction/grammar-interaction.ts
  src/interaction/interaction.ts
  src/interface.ts
Labels: chore

#2084 fix: 堆叠下scale的min/max设置修复
  packages/g2/package.json
  packages/g2/src/element/base.ts
Labels: bug

#2086 feat(action): when iten has unchecked, no highlight
  src/interaction/action/component/list-highlight.ts
  src/interaction/action/component/list-state.ts
  src/interaction/action/element/state.ts
  tests/unit/interaction/action/highlight-spec.ts
  tests/unit/interaction/action/list-active-spec.ts
  tests/unit/interaction/action/list-highlight-spec.ts
Labels: enhancement

#2090 feat(axis): axis support set title.text property
  src/chart/controller/axis.ts
  src/util/axis.ts
  tests/unit/util/axis-spec.ts
Labels: enhancement

#2094 feat(label): add label event
  src/chart/view.ts
  src/geometry/base.ts
  tests/unit/interaction/action/active-spec.ts
Labels: enhancement

#2095 feat(highlight): stop shine of highlight
  src/interaction/action/element/single-state.ts
  src/interaction/action/element/state.ts
  src/interaction/action/util.ts
  tests/unit/interaction/action/highlight-spec.ts
Labels: enhancement

#2097 fix: 更新 dark 主题部分颜色
  src/theme/style-sheet/dark.ts
Labels: bug

#2102 [3.6.x] fix: 修复legend 无法翻页的问题
  packages/component/src/legend/category/canvas.ts
Labels: bug
