Repository antvis/G2, pull requests merged in 2020-03, with the labels that each got.

#2109 【3.6.x】feat: update g version
  packages/g2/package.json
Labels: enhancement

#2127 fix: 时间正则错误，20200229
  src/chart/controller/scale.js
Labels: PR: reviewed-changes-requested, bug

#2133 docs(interaction): update interaction docs
  docs/manual/developer/registerinteraction.en.md
  docs/manual/developer/registerinteraction.zh.md
  docs/manual/tutorial/interaction.en.md
  docs/manual/tutorial/interaction.zh.md
  examples/interaction/element/demo/meta.json
Labels: PR: reviewed-approved, documentation

#2132 chore: 更新网站 H5 模板
  gatsby-config.js
Labels: PR: reviewed-changes-requested, chore

#2123 chore: update g2 version to publish
  packages/g2/package.json
Labels: PR: reviewed-approved, chore

#2136 chore: 发布 v4.0.1
  CHANGELOG.md
  package.json
  src/core.ts
  src/index.ts
Labels: PR: reviewed-changes-requested, chore

#2131 feat: 添加图片下载相关的工具方法. Closed #2122
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
Labels: PR: unreviewed, enhancement

#2152 Fix 2138
  docs/manual/tutorial/shape-attrs.zh.md
  package.json
  tests/bugs/2138-spec.ts
Labels: PR: reviewed-approved

#2137 fix(scale): 修复日期正则表达式将 '20200229' 判断为 time 类型的问题, related #2115
  src/util/scale.ts
  tests/unit/util/scale-spec.ts
Labels: PR: reviewed-approved, bug

#2151 修复 chart.annotation() 接口 animateOption 属性不生效的问题
  src/chart/controller/annotation.ts
  src/chart/controller/axis.ts
  src/interface.ts
  tests/bugs/2146-spec.ts
Labels: PR: reviewed-approved

#2150 [3.6.x] 升级scale & 发布新版本
  packages/component/package.json
  packages/g2/package.json
Labels: PR: reviewed-approved

#2156 docs: interaction page element single selected spelling mistakes
  docs/manual/tutorial/interaction.en.md
  docs/manual/tutorial/interaction.zh.md
Labels: documentation

#2161 fix(slider): when changeData, slider min max text should be update
  src/chart/controller/slider.ts
  tests/unit/chart/controller/slider-spec.ts
Labels: bug

#2169 release v4.0.2
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested

#2170 chore(interaction): add action to docs
  docs/manual/tutorial/interaction.en.md
  docs/manual/tutorial/interaction.zh.md
Labels: PR: reviewed-approved, chore

#2182 chore: 更新文档和 demo
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  docs/manual/shape-attrs.en.md
  docs/manual/shape-attrs.zh.md
  docs/manual/upgrade.en.md
  docs/manual/upgrade.zh.md
  examples/interaction/others/demo/meta.json
  examples/interaction/others/demo/pie-legend.ts
  gatsby-config.js
Labels: PR: reviewed-changes-requested, chore

#2184 Fix tooltip
  src/chart/controller/tooltip.ts
  src/chart/view.ts
  tests/bugs/2174-spec.ts
  tests/bugs/tooltip-spec.ts
Labels: PR: reviewed-approved

#2188 fix: 修复体验不太好的 demo
  examples/gallery/facet/demo/facet3.ts
  examples/gallery/facet/demo/multi-gauge.ts
  examples/gallery/line/demo/line6.ts
  examples/gauge/gauge/demo/color.ts
  examples/other/other/demo/bullet-graph.ts
  examples/other/other/demo/double-axes.ts
Labels: PR: reviewed-approved, bug

#2190 fix(data): 修复使用数据引用造成数据未更新的问题
  src/chart/view.ts
  src/geometry/base.ts
  tests/bugs/2186-spec.ts
  tests/bugs/candle-legend-spec.ts
  tests/unit/geometry/label/labels-spec.ts
Labels: PR: reviewed-approved, bug

#2192 fix(geometry): 修复 element 打标策略导致的数据未被全部绘制的问题。Closed #2141
  src/geometry/base.ts
  src/geometry/heatmap.ts
  src/geometry/path.ts
  tests/bugs/2016-spec.ts
  tests/bugs/2141-spec.ts
Labels: PR: reviewed-approved, bug

#2194 feat: 支持用户指定确定数据 id 的字段
  src/geometry/base.ts
  src/interface.ts
  tests/unit/chart/chart-spec.ts
Labels: PR: reviewed-approved, enhancement

#2200 fix(options): 修复 chart.updateOptions() 更新失败的问题
  docs/manual/tutorial/schema.en.md
  docs/manual/tutorial/schema.zh.md
  src/chart/view.ts
  src/interface.ts
  tests/bugs/2157-spec.ts
Labels: PR: reviewed-changes-requested, bug

#2196 Issue 2181
  docs/manual/tutorial/event.en.md
  docs/manual/tutorial/event.zh.md
  examples/interaction/others/demo/pie-legend.ts
  src/chart/view.ts
  src/geometry/element/index.ts
  tests/unit/chart/event/multiple-view-spec.ts
  tests/unit/chart/event/statechange-spec.ts
Labels: PR: reviewed-approved

#2143 优化 label 类以及修复相关 BUG
  examples/pie/basic/demo/pie-texture.ts
  src/chart/controller/annotation.ts
  src/chart/controller/tooltip.ts
  src/component/labels.ts
  src/geometry/base.ts
  src/geometry/label/base.ts
  src/geometry/label/index.ts
  src/geometry/label/interface.ts
  src/geometry/label/interval.ts
  src/geometry/label/layout/distribute.ts
  src/geometry/label/layout/limit-in-canvas.ts
  src/geometry/label/layout/limit-in-shape.ts
  src/geometry/label/layout/overlap.ts
  src/geometry/label/pie.ts
  src/geometry/label/polar.ts
  src/index.ts
  src/interaction/action/element/state.ts
  src/interface.ts
  src/theme/default.ts
  src/util/coordinate.ts
  tests/unit/geometry/label/base-spec.ts
  tests/unit/geometry/label/chart/funnel-spec.ts
  tests/unit/geometry/label/chart/polar-interval-spec.ts
  tests/unit/geometry/label/chart/polygon-spec.ts
  tests/unit/geometry/label/interval-spec.ts
  tests/unit/geometry/label/labels-spec.ts
  tests/unit/geometry/label/layout/limit-in-canvas-spec.ts
  tests/unit/geometry/label/layout/limit-in-shape-spec.ts
  tests/unit/geometry/label/layout/overlap-spec.ts
  tests/unit/geometry/label/pie-spec.ts
  tests/unit/util/coordinate-spec.ts
Labels: PR: reviewed-approved

#2203 修复 active-reigon 计算错误的问题
  src/chart/controller/tooltip.ts
  src/interaction/action/active-region.ts
  tests/bugs/1265-spec.ts
  tests/bugs/2174-spec.ts
Labels: PR: reviewed-approved

#2208 chore: 添加动态气泡图 demo
  examples/gallery/bar/demo/dynamic-bar.ts
  examples/gallery/bar/demo/meta.json
  examples/gallery/dynamic/demo/dynamic-bar.ts
  examples/gallery/dynamic/demo/dynamic-bubble.ts
  examples/gallery/dynamic/demo/meta.json
  examples/gallery/dynamic/index.en.md
  examples/gallery/dynamic/index.zh.md
Labels: PR: reviewed-approved, chore

#2209 feat(tooltip): 通过 pointer-events 属性来达到 tooltip 躲避鼠标的交互效果
  examples/gallery/dynamic/demo/dynamic-bar.ts
  examples/gallery/dynamic/demo/dynamic-bubble.ts
  src/chart/controller/tooltip.ts
  src/chart/view.ts
  tests/bugs/tooltip-spec.ts
  tests/unit/chart/view/index-spec.ts
Labels: PR: reviewed-approved, enhancement

#2211 chore: release v4.0.3
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-changes-requested, chore

#2214 refactor: use unpkg other than browser field in package.json
  package.json
Labels: PR: reviewed-approved, refactor

#2217 Facet 问题修复
  src/chart/view.ts
Labels: PR: reviewed-changes-requested

#2226 feat(force-fit): add forceFit api for chart
  src/chart/chart.ts
  tests/bugs/2197-spec.ts
Labels: PR: reviewed-approved, enhancement

#2228 fix(#2212): fix when slider option has no start or end
  src/chart/controller/slider.ts
  src/chart/view.ts
  tests/bugs/2212-spec.ts
Labels: PR: reviewed-approved, bug

#2239 feat: 添加一些方法的别名，以兼容 3.x，但是这些方法将会在 4.1 版本中移除
  src/chart/view.ts
  tests/unit/chart/multi-view-spec.ts
  tests/unit/chart/view/index-spec.ts
Labels: PR: partially-approved, enhancement

#2240 Fix failed test
  package.json
  src/global.js
  test/bugs/issue-439-spec.js
  test/unit/chart/view-spec.js
Labels: PR: reviewed-changes-requested
