Repository antvis/G2, pull requests merged in 2021-06, with the labels that each got.

#3462 fix: remove speical data
  examples/other/other/demo/word-cloud.ts
Labels: PR: reviewed-approved

#3465 chore: 4.1.18
  .github/workflows/ci.yml
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3460 refactor: refactor shape attribute
  __tests__/unit/visual/attribute/shape-spec.ts
  src/visual/attribute/attribute.ts
  src/visual/attribute/shape.ts
Labels: PR: reviewed-approved

#3451 feat: add shape factory & shape
  .eslintrc.js
  package.json
  src/geometry/element.ts
  src/geometry/factory.ts
  src/types/common.ts
  src/types/coordinate.ts
  src/types/factory.ts
  src/types/g.ts
  src/types/geometry.ts
  src/util/coordinate.ts
  src/util/geometry.ts
  src/util/path.ts
  src/visual/coordinate/index.ts
Labels: PR: unreviewed

#3410 fix:fix trendCfg type definition of SliderCfg
  src/interface.ts
Labels: PR: reviewed-approved

#3482 fix(types): 修复类型定义，设置为可选项
  src/interface.ts
  tests/bugs/1744-spec.ts
Labels: PR: unreviewed

#3483 feat(interaction/link-by-color): element-link 交互反馈增加参数配置
  src/interaction/action/element/link-by-color.ts
  tests/unit/interaction/action/link-by-color-spec.ts
  tests/unit/interaction/element-link-spec.ts
Labels: PR: reviewed-approved

#3488 docs(readme): change Typescript to TypeScript
  README.md
Labels: PR: partially-approved

#3485 feat(events): 暴露 brush 交互的生命周期，便于在 G2Plot 层可以监听
  src/chart/event.ts
  src/chart/view.ts
  src/index.ts
  src/interaction/action/data/range-filter.ts
  src/interface.ts
  tests/unit/interaction/action/range-filter-spec.ts
Labels: PR: unreviewed

#3484 fix: active-region 若干问题
  src/chart/controller/tooltip.ts
  src/interaction/action/active-region.ts
  src/util/tooltip.ts
  tests/unit/interaction/active-region-spec.ts
Labels: PR: unreviewed

#3487 Test/scale
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  __tests__/unit/visual/scale/band-spec.ts
  __tests__/unit/visual/scale/cat-spec.ts
  __tests__/unit/visual/scale/constant-spec.ts
  __tests__/unit/visual/scale/identity-spec.ts
  __tests__/unit/visual/scale/index-spec.ts
  __tests__/unit/visual/scale/linear-spec.ts
  __tests__/unit/visual/scale/log-spec.ts
  __tests__/unit/visual/scale/ordinal-spec.ts
  __tests__/unit/visual/scale/point-spec.ts
  __tests__/unit/visual/scale/pow-spec.ts
  __tests__/unit/visual/scale/quantile-spec.ts
  __tests__/unit/visual/scale/quantize-spec.ts
  __tests__/unit/visual/scale/sqrt-spec.ts
  __tests__/unit/visual/scale/time-cat-spec.ts
  __tests__/unit/visual/scale/time-spec.ts
  package.json
  src/types/scale.ts
  src/util/scale.ts
  src/visual/scale/index.ts
  src/visual/scale/pool.ts
Labels: PR: unreviewed

#3489 chore: 4.1.19
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: partially-approved

#3486 Feat line geometry
  __tests__/unit/geometry/geometry-spec.ts
  __tests__/unit/geometry/interval/interval-spec.ts
  __tests__/unit/util/diff-spec.ts
  __tests__/unit/visual/scale/pool-spec.ts
  __tests__/unit/visual/scale/time-cat-spec.ts
  package.json
  src/chart/view.ts
  src/core/visibility.ts
  src/geometry/element.ts
  src/geometry/factory.ts
  src/geometry/geometry.ts
  src/geometry/interval/index.ts
  src/geometry/interval/shapes.ts
  src/types/coordinate.ts
  src/types/element.ts
  src/types/factory.ts
  src/types/geometry.ts
  src/types/view.ts
  src/util/attribute.ts
  src/util/diff.ts
  src/util/path.ts
  src/util/scale.ts
  src/visual/attribute/index.ts
  src/visual/coordinate/index.ts
  src/visual/scale/pool.ts
Labels: PR: unreviewed

#3491 docs: 修改 AxisOption.title 文档
  docs/api/general/axis.zh.md
Labels: PR: reviewed-approved

#3490 docs: faq 文档更新
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
Labels: PR: reviewed-approved

#3493 feat: draw interval geometry
  .eslintrc.js
  __tests__/unit/geometry/interval/interval-spec.ts
  __tests__/unit/util/coordinate-spec.ts
  __tests__/unit/util/element-spec.ts
  __tests__/unit/util/graphics-spec.ts
  __tests__/unit/visual/scale/index-spec.ts
  jest.setup.js
  package.json
  src/constant.ts
  src/geometry/factory.ts
  src/geometry/geometry.ts
  src/geometry/interval/index.ts
  src/geometry/interval/shapes.ts
  src/geometry/interval/shapes/index.ts
  src/geometry/interval/util.ts
  src/types/factory.ts
  src/types/geometry.ts
  src/util/coordinate.ts
  src/util/element.ts
  src/util/graphics.ts
  webpack.config.js
Labels: PR: unreviewed
