Repository antvis/G2, pull requests merged in 2021-04, with the labels that each got.

#3355 chore: 添加 release create to trigger publish site
  .github/workflows/release.yml
  package.json
Labels: PR: unreviewed

#3356 Update about-g2.zh.md
  docs/manual/about-g2.zh.md
Labels: PR: unreviewed

#3357 ci: remove surge preview
  .github/workflows/preview-build.yml
  .github/workflows/preview-upload.yml
Labels: PR: unreviewed

#3358 fix: 修复主题相关的错误拼写
  src/theme/style-sheet/dark.ts
  src/theme/util/create-by-style-sheet.ts
Labels: PR: unreviewed

#3360 chore: 解决本地开发控制台warning & babel 解析 tsx、jsx 语法
  .babelrc
  api-extractor.json
  webpack.config.js
Labels: PR: unreviewed

#3362 refactor theme
  src/chart/controller/axis.ts
  src/chart/controller/legend.ts
  src/theme/util/create-by-style-sheet.ts
  src/util/axis.ts
  src/util/grid.ts
  src/util/legend.ts
  tests/unit/component/axis-line-spec.ts
  tests/unit/theme/create-theme-spec.ts
  tests/unit/theme/util/index-spec.ts
Labels: PR: partially-approved

#3366 fix(issue-3160): 修复饼图使用连续型图例，标签无法展示
  src/geometry/base.ts
  src/geometry/label/layout/pie/spider.ts
  tests/bugs/3160-spec.ts
  tests/unit/geometry/label/layout/pie-spider-spec.ts
Labels: PR: reviewed-approved

#3370 chore: change log
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3371 fix: 修复 babel 配置
  webpack.config.js
Labels: PR: reviewed-approved

#3377 chore(api): add API for chart, view, geometry
  .eslintrc
  package.json
  src/chart/chart.ts
  src/chart/index.ts
  src/chart/view.ts
  src/core.ts
  src/geometry/element.ts
  src/geometry/geometry.ts
  src/geometry/index.ts
  src/types.ts
Labels: PR: unreviewed

#3378 fix: 修复数据为 0 时动画更新出错
  src/animate/animation/sector-path-update.ts
  tests/bugs/charts-574-spec.ts
Labels: PR: partially-approved

#3361 feat(theme): 主题 Token
  docs/api/advanced/register-theme.en.md
  docs/api/advanced/register-theme.zh.md
  examples/bar/basic/demo/radial-bar-with-background.ts
  package.json
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/theme/util/create-by-style-sheet.ts
  tests/unit/theme/create-theme-spec.ts
Labels: PR: partially-approved

#3376 feat: 主题中增加图例样式的配置，便于用户了解怎么修改
  src/theme/util/create-by-style-sheet.ts
Labels: PR: partially-approved

#3383 feat(geometry): add data process
  .prettierrc
  src/chart/view.ts
  src/constant.ts
  src/geometry/adjust/adjust.ts
  src/geometry/adjust/index.ts
  src/geometry/adjust/stack.ts
  src/geometry/attribute/README.md
  src/geometry/attribute/attribute.ts
  src/geometry/attribute/color.ts
  src/geometry/attribute/indentity.ts
  src/geometry/attribute/index.ts
  src/geometry/attribute/position.ts
  src/geometry/attribute/shape.ts
  src/geometry/attribute/size.ts
  src/geometry/geometry.ts
  src/geometry/geometry/area/index.ts
  src/geometry/geometry/edge/index.ts
  src/geometry/geometry/geometry.ts
  src/geometry/geometry/index.ts
  src/geometry/geometry/interval/index.ts
  src/geometry/geometry/line/index.ts
  src/geometry/geometry/point/index.ts
  src/geometry/geometry/polygon/index.ts
  src/types.ts
  src/types/adjust.ts
  src/types/animate.ts
  src/types/chart.ts
  src/types/common.ts
  src/types/component.ts
  src/types/facet.ts
  src/types/geometry.ts
  src/types/index.ts
  src/types/interaction.ts
  src/types/scale.ts
  src/util/adjust.ts
  src/util/attribute.ts
  src/util/data.ts
  src/util/scale.ts
Labels: PR: unreviewed

#3385 修改饼图图例联动示例交互异常问题
  examples/interaction/others/demo/pie-legend.ts
Labels: PR: reviewed-approved

#3393 chore 4.1.15
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3391 feat(attr): add attribute class
  __tests__/unit/visual/attribute/color-spec.ts
  __tests__/unit/visual/attribute/index-spec.ts
  __tests__/unit/visual/attribute/position-spec.ts
  __tests__/unit/visual/attribute/shape-spec.ts
  __tests__/unit/visual/attribute/size-spec.ts
  src/geometry/attribute/attribute.ts
  src/geometry/attribute/color.ts
  src/geometry/attribute/indentity.ts
  src/geometry/attribute/index.ts
  src/geometry/attribute/position.ts
  src/geometry/attribute/shape.ts
  src/geometry/attribute/size.ts
  src/geometry/geometry/geometry.ts
  src/util/attribute.ts
  src/visual/adjust/adjust.ts
  src/visual/adjust/index.ts
  src/visual/adjust/stack.ts
  src/visual/attribute/README.md
  src/visual/attribute/attribute.ts
  src/visual/attribute/color.ts
  src/visual/attribute/indentity.ts
  src/visual/attribute/index.ts
  src/visual/attribute/position.ts
  src/visual/attribute/shape.ts
  src/visual/attribute/size.ts
  src/visual/scale/index.ts
  typings.d.ts
Labels: PR: unreviewed

#3396 feat: scrollbar theme
  docs/api/general/element.en.md
  docs/api/general/element.zh.md
  docs/manual/concepts/grammar-of-graphics.zh.md
  package.json
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/theme/util/create-by-style-sheet.ts
Labels: PR: unreviewed

#3397 chore: 4.1.16
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3395 feat(scale): add G2 scale base on antv/scale
  __tests__/unit/visual/scale/index-spec.ts
  package.json
  src/visual/attribute/index.ts
  src/visual/scale/index.ts
Labels: PR: unreviewed

#3399 feat(adjust): add module
  src/visual/adjust/adjust.ts
  src/visual/adjust/index.ts
  src/visual/adjust/stack.ts
Labels: PR: unreviewed
