Repository antvis/G2, pull requests merged in 2021-12, with the labels that each got.

#3745 fix(bar): 修复条形图在 reflect y 时，绘制圆角错误
  .github/workflows/auto-release.yml
  package.json
  src/geometry/shape/interval/util.ts
  tests/bugs/3743-spec.ts
  tests/unit/geometry/shape/interval-util-spec.ts
Labels: PR: reviewed-approved

#3744 fix: demo 中自定义shape会有误导
  examples/column/basic/demo/custom-shape.ts
Labels: PR: unreviewed

#3746 chore: v4.1.35 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3750 Update auto-inspection.yml
  .github/workflows/auto-inspection.yml
Labels: PR: unreviewed

#3756 feat(legend): 添加图例的正反选功能
  docs/api/general/legend.zh.md
  src/index.ts
  src/interaction/action/component/list-focus.ts
  src/interaction/action/component/list-radio.ts
  src/interface.ts
  tests/unit/component/legend-category-radio-spec.ts
Labels: PR: partially-approved

#3747 fix(scrollbar): Scale option tickMethod doesn't work with scrollbar
  src/chart/controller/scrollbar.ts
Labels: PR: reviewed-approved

#3758 perf: 优化性能，由于set-zindex每次都会调用 sort，导致耗时为指数级别的
  src/geometry/base.ts
  src/geometry/element/index.ts
  tests/bugs/pie-update-spec.ts
  tests/performance/geometry/point/index-spec.ts
  tests/unit/animate/index-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/state-spec.ts
Labels: PR: unreviewed

#3759 chore: v4.1.36 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed
