Repository antvis/G2, pull requests merged in 2021-05, with the labels that each got.

#3405 docs: 更新文档内容
  README.md
  docs/api/advanced/register-theme.zh.md
  docs/api/general/theme.zh.md
  gatsby-config.js
Labels: PR: reviewed-approved

#3403 refactor: wrapping for @antv/scale
  .eslintrc
  .eslintrc.js
  __tests__/unit/visual/scale/index-spec.ts
  package.json
  src/types/common.ts
  src/types/scale.ts
  src/util/scale.ts
  src/visual/scale/index.ts
Labels: PR: partially-approved

#3407 Feat constraint
  __tests__/unit/visual/scale/index-spec.ts
  src/chart/constraint/index.ts
  src/chart/constraint/solver.ts
  src/chart/controller/index.ts
  src/chart/layout/index.ts
  src/types/common.ts
  src/types/scale.ts
  src/util/bbox.ts
  src/util/scale.ts
Labels: PR: unreviewed

#3411 feat: update scale-def domain type
  __tests__/unit/visual/scale/index-spec.ts
  src/types/scale.ts
  src/visual/scale/index.ts
Labels: PR: reviewed-approved

#3412 feat: chart view api
  .eslintrc.js
  src/chart/chart.ts
  src/chart/view.ts
  src/facet/facet.ts
  src/facet/index.ts
  src/interaction/index.ts
  src/interaction/interaction.ts
  src/theme/index.ts
  src/types/chart.ts
  src/types/common.ts
  src/types/index.ts
  src/types/view.ts
  src/util/facet.ts
  src/util/interaction.ts
  src/visual/scale/pool.ts
Labels: PR: reviewed-changes-requested

#3414 test: add test case for view api
  .eslintrc.js
  __tests__/unit/chart/view/view-setter-api-spec.ts
  __tests__/unit/visual/attribute/color-spec.ts
  __tests__/unit/visual/attribute/index-spec.ts
  __tests__/unit/visual/attribute/position-spec.ts
  __tests__/unit/visual/attribute/shape-spec.ts
  __tests__/unit/visual/attribute/size-spec.ts
  __tests__/unit/visual/scale/index-spec.ts
  package.json
  src/chart/view.ts
  src/facet/index.ts
  src/facet/rect.ts
  src/types/view.ts
  src/util/facet.ts
  src/util/interaction.ts
  tsconfig.json
Labels: PR: unreviewed

#3417 feat: view controllers
  __tests__/unit/visual/adjust/index-spec.ts
  src/chart/controller/README.md
  src/chart/controller/component/annotation.ts
  src/chart/controller/component/axis.ts
  src/chart/controller/component/conponent.ts
  src/chart/controller/component/index.ts
  src/chart/controller/component/legend.ts
  src/chart/controller/component/scrollbar.ts
  src/chart/controller/component/slider.ts
  src/chart/controller/component/timeline.ts
  src/chart/controller/component/tooltip.ts
  src/chart/controller/coordinate/index.ts
  src/chart/controller/event/event.ts
  src/chart/controller/event/gesture.ts
  src/chart/controller/event/index.ts
  src/chart/controller/event/plot.ts
  src/chart/controller/index.ts
Labels: PR: unreviewed

#3419 ci(cache): add cache support for github action
  .github/workflows/build.yml
  package.json
Labels: PR: reviewed-approved

#3402 refactor(attr): refactor position attribute
  .eslintrc.js
  __tests__/bugs/1-spec.ts
  __tests__/unit/index-spec.ts
  __tests__/unit/visual/attribute/color-spec.ts
  __tests__/unit/visual/attribute/index-spec.ts
  __tests__/unit/visual/attribute/position-spec.ts
  __tests__/unit/visual/attribute/shape-spec.ts
  __tests__/unit/visual/attribute/size-spec.ts
  package.json
  src/geometry/geometry/geometry.ts
  src/util/attribute.ts
  src/visual/attribute/README.md
  src/visual/attribute/attribute.ts
  src/visual/attribute/color.ts
  src/visual/attribute/indentity.ts
  src/visual/attribute/index.ts
  src/visual/attribute/position.ts
  src/visual/attribute/shape.ts
  src/visual/attribute/size.ts
  src/visual/scale/pool.ts
Labels: PR: reviewed-approved

#3420 chore: gatsby 加上 ts 依赖，以使 codesandbox 可以打开
  gatsby-config.js
Labels: PR: reviewed-approved

#3424 refactor: refactor base attribute class
  __tests__/unit/visual/attribute/base-spec.ts
  __tests__/unit/visual/attribute/index-spec.ts
  src/types/common.ts
  src/util/facet.ts
  src/visual/attribute/attribute.ts
Labels: PR: partially-approved

#3421 chore: add test case from scale v0.3
  __tests__/unit/chart/view/view-setter-api-spec.ts
  __tests__/unit/visual/adjust/index-spec.ts
  __tests__/unit/visual/attribute/base-spec.ts
  __tests__/unit/visual/attribute/index-spec.ts
  __tests__/unit/visual/attribute/position-spec.ts
  __tests__/unit/visual/scale/cat-spec.ts
  __tests__/unit/visual/scale/index-spec.ts
  __tests__/unit/visual/scale/linear-spec.ts
  __tests__/unit/visual/scale/log-spec.ts
  __tests__/unit/visual/scale/pow-spec.ts
  __tests__/unit/visual/scale/quantile-spec.ts
  __tests__/unit/visual/scale/quantize-spec.ts
  __tests__/unit/visual/scale/time-cat-spec.ts
  __tests__/unit/visual/scale/time-spec.ts
  package.json
  src/types/scale.ts
  src/util/facet.ts
  src/visual/attribute/attribute.ts
  src/visual/scale/index.ts
  tsconfig.json
Labels: PR: unreviewed

#3426 feat(violin): 完善小提琴图
  examples/other/other/demo/violin.ts
  src/geometry/shape/violin/index.ts
  src/index.ts
  tests/unit/geometry/shape/violin-hollow-spec.ts
  tests/unit/geometry/shape/violin-smooth-spec.ts
  tests/unit/geometry/shape/violin-spec.ts
Labels: PR: unreviewed

#3429 docs(voilin): 添加小提琴文档
  docs/api/advanced/dive-into-theme.zh.md
  docs/api/advanced/register-shape.en.md
  docs/api/advanced/register-shape.zh.md
  docs/api/general/event.zh.md
  docs/api/general/geometry.zh.md
Labels: PR: reviewed-changes-requested

#3431 refactor(attr): refactor color attribute
  __tests__/unit/visual/attribute/color-spec.ts
  src/types/scale.ts
  src/util/scale.ts
  src/visual/attribute/attribute.ts
  src/visual/attribute/color.ts
  src/visual/scale/index.ts
Labels: PR: partially-approved

#3416 feat(violin): 增加小提琴图
  docs/api/advanced/dive-into-theme.zh.md
  docs/api/advanced/register-shape.en.md
  docs/api/advanced/register-shape.zh.md
  docs/api/general/event.zh.md
  docs/api/general/geometry.zh.md
  examples/other/other/demo/meta.json
  examples/other/other/demo/violin.ts
  src/geometry/base.ts
  src/geometry/shape/util/get-path-points.ts
  src/geometry/shape/violin/hollow.ts
  src/geometry/shape/violin/index.ts
  src/geometry/shape/violin/smooth.ts
  src/geometry/violin.ts
  src/index.ts
  src/interface.ts
  src/theme/util/create-by-style-sheet.ts
  tests/bugs/1744-spec.ts
  tests/data/violin.ts
  tests/unit/geometry/shape/util/get-path-points-spec.ts
  tests/unit/geometry/shape/violin-hollow-spec.ts
  tests/unit/geometry/shape/violin-smooth-spec.ts
  tests/unit/geometry/shape/violin-spec.ts
  tests/unit/geometry/violin-spec.ts
Labels: PR: reviewed-approved

#3439 ci: changelog&inspect
  .github/workflows/auto-inspection.yml
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3430 feat: add scale pool
  __tests__/unit/visual/scale/index-spec.ts
  __tests__/unit/visual/scale/pool-spec.ts
  package.json
  src/types/scale.ts
  src/types/view.ts
  src/util/scale.ts
  src/visual/scale/index.ts
  src/visual/scale/pool.ts
Labels: PR: unreviewed

#3445 refactor: refactor size attribute
  .eslintrc.js
  __tests__/unit/visual/attribute/color-spec.ts
  __tests__/unit/visual/attribute/index-spec.ts
  __tests__/unit/visual/attribute/position-spec.ts
  __tests__/unit/visual/attribute/size-spec.ts
  src/visual/attribute/attribute.ts
  src/visual/attribute/size.ts
  src/visual/scale/pool.ts
Labels: PR: reviewed-approved

#3448 feat(legend): 图例支持回调设置 marker
  docs/api/general/legend.zh.md
  examples/component/legend/API.en.md
  examples/component/legend/API.zh.md
  examples/component/legend/demo/custom-items.ts
  examples/component/legend/demo/marker-callback.ts
  examples/component/legend/demo/meta.json
  examples/component/legend/index.en.md
  examples/component/legend/index.zh.md
  src/interface.ts
  src/util/legend.ts
  tests/unit/component/legend-category-spec.ts
Labels: PR: partially-approved

#3438 fix: 修复 view.changeData 在重新渲染的时候 报 toFront 为 underfind 的错误
  src/geometry/element/index.ts
Labels: PR: reviewed-approved

#3444 Feat geometry render
  .eslintrc.js
  __tests__/unit/core/visibility-spec.ts
  __tests__/unit/geometry/geometry-spec.ts
  src/core.ts
  src/core/index.ts
  src/core/visibility.ts
  src/geometry/area/index.ts
  src/geometry/edge/index.ts
  src/geometry/geometry.ts
  src/geometry/geometry/index.ts
  src/geometry/interval/index.ts
  src/geometry/line/index.ts
  src/geometry/point/index.ts
  src/geometry/polygon/index.ts
  src/index.ts
  src/types/geometry.ts
  src/types/scale.ts
  src/util/scale.ts
  src/visual/coordinate/index.ts
  src/visual/index.ts
  src/visual/scale/index.ts
Labels: PR: unreviewed

#3450 fix: 修复 view 上没有正确的 scale 时，绘制 annotation 出错
  .github/workflows/auto-inspection.yml
  src/util/annotation.ts
  tests/bugs/annotation-spec.ts
Labels: PR: reviewed-approved
