Repository antvis/G2, pull requests merged in 2021-02, with the labels that each got.

#3249 docs: 补充 geometry 和 element 的 api 文档
  docs/api/general/adjust.en.md
  docs/api/general/adjust.zh.md
  docs/api/general/animate.zh.md
  docs/api/general/coordinate.en.md
  docs/api/general/coordinate.zh.md
  docs/api/general/data.zh.md
  docs/api/general/element.en.md
  docs/api/general/element.zh.md
  docs/api/general/geometry.en.md
  docs/api/general/geometry.zh.md
  docs/api/general/scale.en.md
  docs/api/general/scale.zh.md
Labels: PR: partially-approved

#3256 typings: 增加 getAction 的返回参数类型定义
  src/interaction/action/register.ts
Labels: PR: reviewed-approved

#3259 fix: 提示增强
  src/index.ts
Labels: PR: reviewed-approved

#3250 fix: 修复实心的 shape 设置空心的 marker，会导致marker.style设置不生效
  docs/common/marker-cfg.md
  src/interface.ts
  src/util/legend.ts
  tests/unit/util/legend-spec.ts
Labels: PR: reviewed-approved

#3262 docs(labels.ts): 修改注释错别字
  src/component/labels.ts
Labels: PR: reviewed-approved

#3261 feat(tooltip): tooltip.showContent support function
  src/chart/controller/tooltip.ts
  src/interface.ts
  tests/bugs/g2plot-2223-spec.ts
  tests/unit/chart/controller/tooltip-spec.ts
Labels: PR: partially-approved

#3258 fix: 判断提前
  src/chart/controller/slider.ts
Labels: PR: reviewed-approved

#3265 chore: 4.1.10
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3267 Fix docs
  docs/manual/concepts/view.zh.md
Labels: PR: reviewed-approved

#3273 fix(rose): 修复 TooltipItem data 类型
  src/interface.ts
Labels: PR: reviewed-approved

#3277 docs: 日常文档走查, 层级处理
  docs/api/general/geometry.zh.md
  docs/common/api.zh.md
  docs/manual/concepts/interaction.zh.md
  package.json
Labels: PR: reviewed-approved

#3271 fix: 修复饼图在动画更新过程中如果宽度变为 0 导致的问题
  src/animate/animation/sector-path-update.ts
  tests/bugs/pie-update-spec.ts
Labels: PR: reviewed-approved

#3248 fix(pie): 饼图数据 NaN 导致页面崩溃数据边界处理(#2930)
  src/geometry/interval.ts
  src/util/scale.ts
  tests/bugs/2930-spec.ts
  tests/unit/util/scale-spec.ts
Labels: PR: reviewed-approved

#3281 feat: export constants like: view-life-circle
  src/index.ts
Labels: PR: reviewed-approved

#3280 feat: register interaction with action execute args
  src/interaction/grammar-interaction.ts
  tests/unit/interaction/passing-arg-spec.ts
Labels: PR: reviewed-approved

#3282 fix(event): 修复相同 type 时间触发两次
  src/chart/view.ts
  tests/unit/chart/event/event-spec.ts
Labels: PR: reviewed-approved

#3283 test: 补充 action 单测
  src/interaction/grammar-interaction.ts
  tests/unit/interaction/grammar-interaction-spec.ts
Labels: PR: reviewed-approved

#3286 feat(scrollbar): 滚动条增加主题样式设置，允许设置滑道、滑块颜色
  src/chart/controller/scrollbar.ts
  src/interface.ts
  src/theme/util/create-by-style-sheet.ts
  tests/unit/chart/controller/scrollbar-spec.ts
Labels: PR: partially-approved

#3284 feat(active-region): 支持配置底色样式，全局统一注册一个 配置样式
  src/chart/view.ts
  src/interaction/action/active-region.ts
  tests/unit/interaction/action/active-region-spec.ts
Labels: PR: partially-approved

#3287 chore: 4.1.11
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3288 feat(life-circle): view 生命周期事件触发，携带事件内容
  src/chart/view.ts
Labels: PR: reviewed-approved

#3290 feat(animation): 动画添加重复执行参数
  src/animate/index.ts
  src/interface.ts
  tests/unit/animate/index-spec.ts
Labels: PR: reviewed-approved

#3289 feat: legend 增加 checked 单选交互
  examples/interaction/component/demo/legend-focus.ts
  examples/interaction/component/demo/meta.json
  src/index.ts
  src/interaction/action/component/list-checked.ts
  tests/unit/component/legend-checked-spec.ts
  tests/unit/interaction/action/list-check-spec.ts
Labels: PR: partially-approved

#3291 feat(scrollbar): 滚动条增加一个滚道激活样式配置
  docs/common/scrollbar-options.md
  src/chart/controller/scrollbar.ts
  src/interface.ts
  tests/unit/chart/controller/scrollbar-spec.ts
Labels: PR: reviewed-approved

#3292 feat(typings): 增强类型声明
  CHANGELOG.md
  package.json
  src/chart/view.ts
  src/core.ts
  src/interaction/action/component/tooltip/geometry.ts
Labels: PR: partially-approved

#3294 feat(axis): axisCfg.top option
  src/chart/controller/axis.ts
  src/interface.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/chart/controller/axis-top-spec.ts
  tests/unit/chart/controller/tooltip-spec.ts
Labels: PR: reviewed-approved

#3295 perf: performance optimized
  package.json
  src/chart/controller/tooltip.ts
  src/geometry/base.ts
  src/geometry/label/base.ts
  src/geometry/path.ts
  src/geometry/util/group-data.ts
  tests/bugs/2141-spec.ts
  tests/performance/component/tooltip/pick-spec.ts
  tests/performance/render/line-spec.ts
  tests/performance/render/scatter-spec.ts
  tests/unit/chart/chart-spec.ts
  tests/unit/geometry/base-spec.ts
  tests/unit/geometry/line-spec.ts
Labels: PR: reviewed-approved

#3298 feat: umd 新增浏览器兼容配置
  .babelrc
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  package.json
  webpack.config.js
Labels: PR: reviewed-changes-requested
