Repository antvis/G2, pull requests merged in 2021-09, with the labels that each got.

#3570 fix(scrollbar): 修复了由于getYScales方法中去重方法错误导致的 scrollbar会在特定情况下失效(#3569）
  src/chart/view.ts
Labels: PR: reviewed-approved

#3600 feat(api): add new api for view
  examples/customize/component/API.en.md
  examples/customize/component/API.zh.md
  examples/customize/component/demo/bar-annotation.ts
  examples/customize/component/demo/line-tooltip.ts
  examples/customize/component/demo/meta.json
  examples/customize/component/demo/pie-legend.ts
  examples/customize/component/index.en.md
  examples/customize/component/index.zh.md
  gatsby-config.js
  src/chart/view.ts
  src/geometry/base.ts
  src/geometry/heatmap.ts
  tests/api/geometry-spec.ts
  tests/api/view-spec.ts
Labels: PR: unreviewed

#3609 docs: set default lang = zh
  README.en-US.md
  README.md
Labels: PR: reviewed-changes-requested

#3611 refactor(funnel): annotation 位置添加center，支持在漏斗图中正常显示
  examples/funnel/funnel/demo/basic.ts
  src/util/annotation.ts
  tests/unit/util/annotation-spec.ts
Labels: PR: reviewed-approved

#3614 refactor(facet): 添加了spacing属性，支持配置分面图之间的间距
  docs/common/facet-cfg.md
  examples/case/column/demo/column11.ts
  src/facet/facet.ts
  src/interface.ts
  tests/unit/facet/list/index-spec.ts
  tests/unit/facet/mirror/index-spec.ts
Labels: PR: reviewed-approved

#3591 fix: legend 自定义items 添加marker回调
  src/interface.ts
  src/util/legend.ts
  tests/unit/chart/controller/legend-spec.ts
Labels: PR: reviewed-approved

#3619 docs(facet): 修改了镜像分面的案例，使得轴标签居中显示
  examples/facet/facet/demo/mirror-transpose.ts
  examples/facet/facet/demo/mirror.ts
Labels: PR: unreviewed

#3615 refactor(annotation): annotation position 支持百分比混用
  docs/common/annotation-position.md
  src/chart/controller/annotation.ts
  tests/unit/chart/controller/annotation-position-spec.ts
Labels: PR: reviewed-approved

#3623 chore/dep
  .eslintrc
  .eslintrc.js
  .husky/commit-msg
  .husky/pre-commit
  package.json
  tslint.json
  webpack.config.js
Labels: PR: reviewed-approved

#3625 fix(tests): eslint error
  .eslintrc.js
  package.json
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  tests/unit/component/legend-category-spec.ts
  tests/unit/geometry/label/layout/pie-outer-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/interaction/active-region-spec.ts
  tests/unit/theme/create-theme-spec.ts
  tests/unit/util/legend-spec.ts
Labels: PR: reviewed-approved

#3613 docs(get-start): add docs when disposing the node
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
Labels: PR: reviewed-approved

#3627 fix(uniq): when uniq element is not string
  src/chart/view.ts
  src/geometry/base.ts
  src/util/helper.ts
  tests/unit/util/helper-spec.ts
Labels: PR: reviewed-approved

#3624 chore: v4.1.26 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3629 chore(package.json): downgrade ts-loader to 8.x and upgrade typescrip…
  package.json
Labels: PR: reviewed-approved

#3632 fix(annotation): 修复了parsePosition的解析逻辑
  docs/common/annotation-position.md
  package.json
  src/chart/controller/annotation.ts
Labels: PR: reviewed-approved

#3633 chore: update version to 4.1.27
  CHANGELOG.md
  src/core.ts
Labels: PR: reviewed-approved

#3622 feat: constraint layout solver
  package.json
  src/chart/layout/constraint/bounds.ts
  src/chart/layout/constraint/constraint.ts
  src/chart/layout/constraint/gauss.ts
  src/chart/layout/constraint/index.ts
  src/chart/layout/constraint/solver.ts
  src/chart/layout/constraint/types.ts
  src/chart/layout/constraint/variable.ts
  tests/unit/chart/layout/constraint/bounds-spec.ts
  tests/unit/chart/layout/constraint/constraint-spec.ts
  tests/unit/chart/layout/constraint/gauss-spec.ts
  tests/unit/chart/layout/constraint/index-spec.ts
  tests/unit/chart/layout/constraint/solver-spec.ts
  tests/unit/chart/layout/constraint/variable-spec.ts
Labels: PR: unreviewed

#3626 feat(geometry): refactor and rename createElements
  .eslintrc.js
  .github/workflows/auto-inspection.yml
  .husky/pre-commit
  src/geometry/base.ts
  src/geometry/heatmap.ts
  src/geometry/path.ts
  src/geometry/util/diff.ts
  tests/bugs/tooltip-dom-spec.ts
  tests/unit/geometry/util/diff-spec.ts
  tests/util/delay.ts
Labels: PR: unreviewed

#3637 revert: annotation position 相关的
  CHANGELOG.md
  docs/common/annotation-position.md
  package.json
  src/chart/controller/annotation.ts
  src/core.ts
  tests/unit/chart/controller/annotation-position-spec.ts
Labels: PR: reviewed-approved

#3640 fix: crash on safari 15 when fillText with unicode
  package.json
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
Labels: PR: unreviewed

#3642 chore: update changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3644 fix(custom-content): 修复custom-content的undefined无法变回tooltip模版的问题
  src/chart/controller/tooltip.ts
  tests/bugs/tooltip-custom-content-spec.ts
Labels: PR: unreviewed

#3645 chore: update changelog
  CHANGELOG.md
  package.json
  src/core.ts
  tests/unit/geometry/base-spec.ts
Labels: PR: reviewed-approved

#3648 chore: v4.1.30 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3649 chore: add release-notify
  .github/workflows/release-notify.yml
Labels: PR: reviewed-approved

#3650 chore: add release-notify
  .github/workflows/release-notify.yml
Labels: PR: unreviewed
