Repository antvis/G2, pull requests merged in 2021-11, with the labels that each got.

#3701 chore: 添加 auto-release actions
  .github/workflows/auto-release.yml
  .github/workflows/release-notify.yml
  package.json
Labels: PR: reviewed-changes-requested

#3703 chore(release): v4.1.34 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3711 错别字：天平 -> 天秤
  examples/case/pie/demo/pie6.ts
Labels: PR: reviewed-approved
