Repository antvis/G2, pull requests merged in 2021-08, with the labels that each got.

#3546 Fix/smooth line
  src/geometry/shape/util/path.ts
  tests/bugs/2425-spec.ts
  tests/unit/geometry/shape/line-spec.ts
Labels: PR: partially-approved

#3542 style(geometry): removed double slash in path
  src/geometry/label/layout/limit-in-plot.ts
Labels: PR: reviewed-approved

#3549 docs(tooltip): remove useless code
  docs/manual/concepts/component/tooltip.en.md
  docs/manual/concepts/component/tooltip.zh.md
Labels: PR: reviewed-approved

#3552 docs: fix typos in 'docs/manual/concepts'
  docs/manual/concepts/geometry/overview.en.md
  docs/manual/concepts/geometry/overview.zh.md
  docs/manual/concepts/geometry/path-and-line.en.md
  docs/manual/concepts/geometry/path-and-line.zh.md
  docs/manual/concepts/geometry/schema.en.md
  docs/manual/concepts/geometry/schema.zh.md
  docs/manual/concepts/interaction.zh.md
Labels: PR: reviewed-changes-requested

#3557 docs: Fix a few typos
  CONTRIBUTING.md
Labels: PR: unreviewed

#3553 docs(AxisTitleCfg): added optional configuration
  docs/api/general/axis.zh.md
Labels: PR: reviewed-approved

#3558 chore: v4.1.23 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3554 fix(types): fix type change in g-canvas@1.0.0-alpha.3
  __tests__/unit/chart/view/view-init-spec.ts
  __tests__/unit/chart/view/view-render-spec.ts
  __tests__/unit/chart/view/view-setter-api-spec.ts
  __tests__/unit/geometry/interval/interval-spec.ts
  __tests__/unit/geometry/interval/shape/funnel-spec.ts
  __tests__/unit/geometry/interval/shape/hollow-rect-spec.ts
  __tests__/unit/geometry/interval/shape/line-spec.ts
  __tests__/unit/geometry/interval/shape/pyramid-spec.ts
  __tests__/unit/geometry/interval/shape/rect-spec.ts
  __tests__/unit/geometry/interval/shape/tick-spec.ts
  __tests__/unit/geometry/line/line-spec.ts
  __tests__/unit/geometry/line/shape/line-spec.ts
  __tests__/unit/geometry/line/shape/step-spec.ts
  __tests__/unit/geometry/path/path-spec.ts
  __tests__/unit/geometry/path/shape/line-spec.ts
  src/chart/view.ts
  src/geometry/element.ts
  src/geometry/line/shapes/step.ts
Labels: PR: unreviewed

#3548 feat(view): layout with constraint
  src/chart/layout/index.ts
  src/chart/view.ts
  src/geometry/geometry.ts
  src/types/layout.ts
Labels: PR: unreviewed

#3560 docs: fix 404 links for interaction
  docs/api/advanced/register-interaction.en.md
  docs/api/advanced/register-interaction.zh.md
  docs/api/general/interaction.zh.md
Labels: PR: reviewed-approved

#3559 docs(style): fix style issues in docs
  site/pages/index.less
Labels: PR: reviewed-approved

#3572 typo: fix appendPading to appendPadding
  docs/api/general/chart.zh.md
  src/interface.ts
Labels: PR: reviewed-approved

#3571 feat: 导出 utils，供 G2Plot 使用
  src/core.ts
Labels: PR: unreviewed

#3581 docs(get-start): add docs when use with script
  docs/manual/getting-started.en.md
  docs/manual/getting-started.zh.md
Labels: PR: unreviewed

#3585 fix(funnel): pyramid shape 最下面一层的 label 绘制不对齐
  package.json
  src/geometry/shape/interval/pyramid.ts
  src/geometry/shape/interval/util.ts
  tests/bugs/funnel-pyramid-spec.ts
  tests/unit/geometry/label/chart/funnel-spec.ts
  tests/unit/geometry/shape/interval-spec.ts
Labels: PR: partially-approved

#3590 chore: update chore.ts and changelog for v4.1.25
  CHANGELOG.md
  src/core.ts
Labels: PR: reviewed-approved

#3601 fix(annotation): 修复annotation添加id失败
  src/chart/controller/annotation.ts
Labels: PR: reviewed-approved
