Repository antvis/G2, pull requests merged in 2021-03, with the labels that each got.

#3308 docs(typo): dblclick, not dbclick
  docs/api/general/event.zh.md
Labels: PR: reviewed-approved

#3320 docs: update old code in api/advanced/require
  docs/api/advanced/require.en.md
  docs/api/advanced/require.zh.md
Labels: PR: reviewed-approved

#3300 fix: getArcStartPoint function support path C (#3213)
  src/animate/animation/sector-path-update.ts
Labels: PR: reviewed-approved

#3324 feat(legend): 图例支持配置分页器的主题样式
  docs/api/advanced/dive-into-theme.en.md
  docs/api/advanced/dive-into-theme.zh.md
  docs/api/general/interaction.en.md
  docs/api/general/legend.zh.md
  src/chart/controller/legend.ts
  src/dependents.ts
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/theme/util/create-by-style-sheet.ts
  tests/unit/component/legend-category-spec.ts
Labels: PR: partially-approved

#3327 feat: 单 view 支持默认图例选中
  src/chart/view.ts
  src/interface.ts
  tests/unit/util/legend-spec.ts
Labels: PR: reviewed-approved

#3330 Chore new version
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3341 update type-only import
  src/core.ts
Labels: PR: reviewed-approved

#3346 feat: 补充兼容性文档&修改webpack配置
  .babelrc
  docs/manual/faq.en.md
  docs/manual/faq.zh.md
  package.json
  webpack.config.js
Labels: PR: reviewed-changes-requested

#3350 chore: 修复 import type 导致网站无法启动，更新为 export type
  src/core.ts
Labels: PR: reviewed-approved

#3351 docs(legend): 图例完善默认不选中以及点击选中交互的文档 & 增加 demo
  docs/api/general/interaction.en.md
  docs/api/general/interaction.zh.md
  docs/api/general/legend.zh.md
  examples/interaction/component/demo/legend-focus.ts
  examples/interaction/component/demo/legend-unselected.ts
  examples/interaction/component/demo/meta.json
Labels: PR: reviewed-approved
