Repository antvis/G2, pull requests merged in 2021-01, with the labels that each got.

#3172 docs: 添加 chart 和 view 对象的 api 文档 & 修复 shapeAttrs 链接文档 404
  docs/api/general/annotation.zh.md
  docs/api/general/axis.zh.md
  docs/api/general/chart.en.md
  docs/api/general/chart.zh.md
  docs/api/general/legend.zh.md
  docs/api/general/tooltip.zh.md
  docs/common/api.en.md
  docs/common/api.zh.md
  docs/common/enhanced-text-cfg.md
  docs/common/marker-cfg.md
  docs/common/new-chart.md
  site/pages/index.less
Labels: PR: reviewed-approved

#3174 fix(geometry): geometry.update should update scale when data is changed
  src/geometry/base.ts
  tests/bugs/g2plot-2165-spec.ts
Labels: PR: reviewed-approved

#3176 docs: add mask documents
  docs/api/general/scale.zh.md
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved

#3173 feat: 支持对 geometry 下的 elements zIndex 进行降序
  src/geometry/base.ts
  tests/unit/geometry/base-spec.ts
Labels: PR: partially-approved

#3177 fix(tooltip-tip): label tip max width 50%, and break word
  src/interaction/action/component/tooltip/ellipsis-text.ts
  tests/bugs/tooltip-tip-max-width-spec.ts
Labels: PR: unreviewed

#3175 feat: interval shape 支持 background
  examples/bar/basic/demo/meta.json
  examples/bar/basic/demo/radial-bar-with-background.ts
  examples/case/column/demo/column5.ts
  src/geometry/element/index.ts
  src/geometry/interval.ts
  src/geometry/shape/constant.ts
  src/geometry/shape/interval/hollow-rect.ts
  src/geometry/shape/interval/index.ts
  src/geometry/shape/interval/util.ts
  src/geometry/shape/util/get-style.ts
  src/interface.ts
  tests/bugs/tooltip-tip-max-width-spec.ts
  tests/unit/geometry/interval-spec.ts
  tests/unit/geometry/shape/interval-util-spec.ts
  tests/unit/geometry/shape/util/get-style-spec.ts
  tests/unit/geometry/state-spec.ts
Labels: PR: reviewed-approved

#3181 chore: v4.1.5
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3188 fix: performance improvement by disable default sort for line/area
  CHANGELOG.md
  package.json
  src/core.ts
  src/geometry/area.ts
  src/geometry/line.ts
  tests/unit/geometry/area-spec.ts
  tests/unit/geometry/line-spec.ts
Labels: PR: unreviewed

#3196 test: 修复 tooltip ci 报错问题
  tests/bugs/tooltip-tip-max-width-spec.ts
Labels: PR: reviewed-approved

#3170 feat: interval support cornerRadius(方案梳理中)
  examples/column/basic/demo/corner-radius.ts
  examples/column/basic/demo/meta.json
  src/geometry/shape/interval/index.ts
  src/geometry/shape/interval/util.ts
  tests/unit/geometry/shape/interval-spec.ts
  tests/unit/geometry/shape/interval-util-spec.ts
Labels: PR: partially-approved

#3199 docs: 添加钉钉联系方式
  README.md
  README.zh-CN.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
Labels: PR: reviewed-approved

#3200 chore: 4.1.7 & add changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved

#3202 docs: 移除legend useHtml api
  docs/manual/concepts/component/legend.en.md
  docs/manual/concepts/component/legend.zh.md
  docs/manual/faq.zh.md
  docs/manual/tutorial/legend.en.md
  docs/manual/tutorial/legend.zh.md
  docs/manual/upgrade.zh.md
Labels: PR: reviewed-approved

#3216 feat(tooltip): add tooltip.showNil
  src/chart/controller/tooltip.ts
  src/interface.ts
  src/util/tooltip.ts
  tests/bugs/1518-spec.ts
Labels: PR: reviewed-approved

#3221 docs: 走查，文档优化
  docs/api/general/adjust.zh.md
Labels: PR: reviewed-approved

#3224 docs: 删除多余文字
  docs/manual/concepts/component/legend.zh.md
Labels: PR: reviewed-approved

#3227 docs: 文档修改,移除图例废弃的 api & tooltipStyles 类型定义修整
  docs/api/general/tooltip.zh.md
  docs/manual/tutorial/legend.en.md
  docs/manual/tutorial/legend.zh.md
Labels: PR: partially-approved

#3230 perf(smooth): smooth line do not capture event
  package.json
  src/geometry/shape/line/index.ts
  tests/performance/component/tooltip/pick-spec.ts
Labels: PR: reviewed-approved

#3234 docs: 交互的英文文档
  docs/api/general/interaction.en.md
Labels: PR: reviewed-approved

#3236 docs(scrollbar): 修改文档错误
  docs/common/scrollbar-options.md
Labels: PR: partially-approved

#3240 feat: 暴露获取扇形 path 的方法
  src/core.ts
Labels: PR: partially-approved

#3239 feat(tooltip): add tooltip.customItems config
  docs/api/general/tooltip.zh.md
  src/chart/controller/tooltip.ts
  src/interface.ts
  tests/bugs/g2plot-2223-spec.ts
Labels: PR: partially-approved

#3242 feat: add 4.1.8 changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: partially-approved

#3246 chore: 更新版本号
  package.json
  src/core.ts
  src/geometry/label/util/index.ts
Labels: PR: reviewed-approved
