Repository antvis/G2, pull requests merged in 2022-09, with the labels that each got.

#4114 feat(api): support register, update data and return context
  .genjirc
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/library.spec.ts
  __tests__/unit/runtime/animation.spec.ts
  __tests__/unit/runtime/annotationConnector.spec.ts
  __tests__/unit/runtime/annotationRange.spec.ts
  __tests__/unit/runtime/facet.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/runtime/label.spec.ts
  __tests__/unit/runtime/line.spec.ts
  docs/basic.md
  docs/register.md
  package.json
  src/api/chart.ts
  src/api/index.ts
  src/api/library.ts
  src/index.ts
  src/runtime/render.ts
Labels: PR: unreviewed

#4116 fix: test failed because of error usage of `done`
  __tests__/unit/runtime/label.spec.ts
Labels: PR: unreviewed

#4126 docs: 移除地图 demo
  examples/map/map/API.en.md
  examples/map/map/API.zh.md
  examples/map/map/demo/bubble-map.ts
  examples/map/map/demo/choropleth-map.ts
  examples/map/map/demo/hex-choropleth-map.ts
  examples/map/map/demo/legend-size.ts
  examples/map/map/demo/meta.json
  examples/map/map/demo/us-states-hex.ts
  examples/map/map/demo/with-heatmap.ts
  examples/map/map/index.en.md
  examples/map/map/index.zh.md
Labels: Documentation, PR: unreviewed

#4127 chore: remove map demo
  examples/component/label/demo/label-map.ts
  examples/component/label/demo/meta.json
Labels: PR: partially-approved, ignore-for-release

#4128 Chore update mirror action
  .github/workflows/mirror.yml
Labels: PR: unreviewed

#4131 chore: remove map demo
  examples/component/component/demo/label-map.js
  examples/component/component/demo/meta.json
  examples/map/map/demo/bubble-map.js
  examples/map/map/demo/choropleth-map.js
  examples/map/map/demo/hex-choropleth-map.js
  examples/map/map/demo/meta.json
  examples/map/map/demo/us-states-hex.js
  examples/map/map/demo/with-connection.js
  examples/map/map/demo/with-heatmap.js
  examples/map/map/index.en.md
  examples/map/map/index.zh.md
  gatsby-config.js
  package.json
Labels: PR: unreviewed

#4130 docs: add vector mark
  docs/mark-vector.md
Labels: PR: reviewed-approved

#4113 feat: support custom renderer and plugins
  __tests__/unit/renderer/index.spec.ts
  package.json
  rollup.config.js
  src/api/chart.ts
  src/renderer/canvas.ts
Labels: PR: unreviewed

#4132 feat: use vite to preview charts in integration tests
  __tests__/integration/charts/index.html
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/main.ts
  __tests__/integration/charts/sales-basic-rose.ts
  __tests__/integration/index.spec.ts
  __tests__/integration/snapshots/salesBasicInterval.svg
  __tests__/integration/snapshots/salesBasicRose.png
  __tests__/integration/snapshots/salesBasicRose.svg
  __tests__/integration/svg.ts
  __tests__/unit/data/arc/index.spec.ts
  __tests__/unit/data/cluster.spec.ts
  __tests__/unit/data/d3-sankey/constant.spec.ts
  __tests__/unit/data/sankey.spec.ts
  __tests__/unit/data/tree.spec.ts
  __tests__/unit/data/voronoi.spec.ts
  __tests__/unit/data/wordCloud.spec.ts
  package.json
  src/adjust/index.ts
  src/animation/index.ts
  src/component/index.ts
  src/composition/index.ts
  src/coordinate/index.ts
  src/data/arc.ts
  src/data/cluster.ts
  src/data/index.ts
  src/data/sankey.ts
  src/data/tree.ts
  src/data/utils/arc/index.ts
  src/data/voronoi.ts
  src/data/wordCloud.ts
  src/encode/index.ts
  src/interaction/action/index.ts
  src/interaction/index.ts
  src/interaction/interactor/index.ts
  src/interaction/types.ts
  src/mark/annotation/index.ts
  src/mark/geometry/index.ts
  src/palette/index.ts
  src/renderer/index.ts
  src/scale/index.ts
  src/shape/index.ts
  src/transform/index.ts
  tsconfig.json
  vite.config.js
Labels: PR: partially-approved

#4117 fix(api): do not clone the value of node when mapping
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/node.spec.ts
  src/api/chart.ts
  src/api/node.ts
Labels: PR: partially-approved

#4133 feat(runtime): remove renderer component
  __tests__/unit/animation/helper.ts
  __tests__/unit/interaction/helper.ts
  __tests__/unit/renderer/index.spec.ts
  __tests__/unit/shape/helper.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/utils/selection.spec.ts
  __tests__/utils/canvas.ts
  src/api/chart.ts
  src/renderer/canvas.ts
  src/renderer/index.ts
  src/runtime/render.ts
  src/runtime/types/component.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4139 feat: render alphabet-bar-chart
  .genjirc
  __tests__/integration/charts/alphabet-bar-chart.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/sales-basic-interval.ts
  __tests__/integration/charts/sales-basic-rose.ts
  __tests__/integration/data/alphabet.csv
  __tests__/integration/data/sales.js
  __tests__/integration/fetch.ts
  __tests__/integration/index.html
  __tests__/integration/index.spec.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshots/alphabetBarChart.png
  __tests__/integration/snapshots/alphabetBarChart.svg
  __tests__/integration/snapshots/salesBasicInterval.png
  __tests__/integration/snapshots/salesBasicInterval.svg
  __tests__/integration/snapshots/salesBasicRose.png
  __tests__/integration/snapshots/salesBasicRose.svg
  __tests__/unit/stdlib/index.spec.ts
  docs/scale-overview.md
  docs/transform-sortx.md
  package.json
  src/component/axis.ts
  src/runtime/component.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/sortX.ts
  vite.config.js
Labels: PR: reviewed-approved

#4138 docs: add box docs and rename schema to box
  .genjirc
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/interaction/builtin/tooltip.spec.ts
  __tests__/unit/mark/geometry/box.spec.ts
  __tests__/unit/runtime/box.spec.ts
  __tests__/unit/runtime/transform.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/examples.md
  docs/mark-box.md
  docs/mark-schema.md
  docs/mark-vector.md
  docs/transform-dodge.md
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/mark/geometry/box.ts
  src/mark/geometry/index.ts
  src/shape/box/box.ts
  src/shape/index.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4142 docs: add Image docs
  docs/mark-image.md
  src/mark/geometry/image.ts
  src/mark/geometry/line.ts
  src/mark/geometry/point.ts
Labels: PR: partially-approved

#4143 feat: alphabet-bar-chart-horizontal
  .genjirc
  __tests__/integration/charts/alphabet-bar-chart-horizontal.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/alphabetBarChartHorizontal.png
  __tests__/integration/snapshots/alphabetBarChartHorizontal.svg
  __tests__/unit/animation/helper.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/api/props.spec.ts
  __tests__/unit/shape/annotation/badge.spec.ts
  __tests__/unit/shape/annotation/text.spec.ts
  __tests__/unit/shape/helper.ts
  docs/mark-overview.md
  docs/scale-overview.md
  docs/transform-sortx.md
  src/animation/morphing.ts
  src/api/chart.ts
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/api/props.ts
  src/runtime/plot.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/shape/annotation/text.ts
  src/shape/label/label.ts
  src/spec/geometry.ts
  src/utils/coordinate.ts
Labels: PR: partially-approved

#4144 refactor: remove node/edge mark and shapes
  .genjirc
  __tests__/unit/mark/geometry/edge.spec.ts
  __tests__/unit/mark/geometry/link.spec.ts
  __tests__/unit/mark/geometry/node.spec.ts
  __tests__/unit/mark/geometry/polygon.spec.ts
  __tests__/unit/runtime/edge.spec.ts
  __tests__/unit/runtime/graph.spec.ts
  __tests__/unit/runtime/link.spec.ts
  __tests__/unit/runtime/node.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/mark-graph.md
  docs/node-edge.md
  src/data/arc.ts
  src/data/cluster.ts
  src/data/index.ts
  src/data/sankey.ts
  src/data/tree.ts
  src/mark/geometry/edge.ts
  src/mark/geometry/index.ts
  src/mark/geometry/link.ts
  src/mark/geometry/node.ts
  src/mark/geometry/polygon.ts
  src/shape/edge/edge.ts
  src/shape/index.ts
  src/shape/link/arc.ts
  src/shape/link/smoothEdge.ts
  src/shape/link/vhv.ts
  src/shape/node/point.ts
  src/shape/node/polygon.ts
  src/shape/polygon/ribbon.ts
  src/spec/data.ts
  src/spec/transform.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4149 fix(#4141): avoid cost O(n^2) to getComponents
  src/chart/view.ts
  tests/bugs/4141-spec.ts
Labels: PR: unreviewed, bugfix

#4151 chore: v4.2.8 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved, ignore-for-release

#4140 feat: update some data transform
  __tests__/unit/data/custom.spec.ts
  __tests__/unit/data/fetch.spec.ts
  __tests__/unit/data/filterBy.spec.ts
  __tests__/unit/data/map.spec.ts
  __tests__/unit/data/sortBy.spec.ts
  __tests__/unit/runtime/line.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/data-custom.md
  docs/data-fetch.md
  docs/data-filterBy.md
  docs/data-fold.md
  docs/data-map.md
  docs/data-pick.md
  docs/data-sortBy.md
  docs/data.md
  docs/mark-link.md
  docs/mark-point.md
  docs/mark-polygon.md
  src/composition/rect.ts
  src/data/connector.ts
  src/data/custom.ts
  src/data/fetch.ts
  src/data/filterBy.ts
  src/data/index.ts
  src/data/map.ts
  src/data/sortBy.ts
  src/data/utils/fields.ts
  src/spec/data.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4154 docs: add coordinate docs
  docs/coordinate-fisheye.md
  docs/coordinate-helix.md
  docs/coordinate-parallel.md
  docs/coordinate-polar.md
  docs/coordinate-theta.md
  docs/coordinate-transpose.md
Labels: PR: reviewed-approved

#4153 feat: add more palettes
  __tests__/unit/palette/index.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/palette/divergingGreenRed.ts
  src/palette/divergingGreenYellow.ts
  src/palette/divergingRedBlue.ts
  src/palette/divergingRedPurple.ts
  src/palette/index.ts
  src/palette/sequentialBlue.ts
  src/palette/sequentialDarkBlue.ts
  src/palette/sequentialDarkGreen.ts
  src/palette/sequentialGreen.ts
  src/palette/sequentialGreenBlue.ts
  src/palette/sequentialGrey.ts
  src/palette/sequentialOrange.ts
  src/palette/sequentialPink.ts
  src/palette/sequentialPinkPurple.ts
  src/palette/sequentialPurple.ts
  src/palette/sequentialRed.ts
  src/palette/sequentialYellow.ts
  src/palette/sequentialYellowGreen.ts
  src/palette/sequentialYellowOrange.ts
  src/spec/palette.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4163 feat(interval): support size channel and radius
  __tests__/integration/charts/commit-interval-fixed-corner.ts
  __tests__/integration/charts/gdp-interval-var-size.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/commit.js
  __tests__/integration/snapshots/alphabetInterval.svg
  __tests__/integration/snapshots/alphabetIntervalTransposed.svg
  __tests__/integration/snapshots/commitIntervalFixedCorner.png
  __tests__/integration/snapshots/commitIntervalFixedCorner.svg
  __tests__/integration/snapshots/gdpIntervalFlex.svg
  __tests__/integration/snapshots/gdpIntervalVarSize.png
  __tests__/integration/snapshots/gdpIntervalVarSize.svg
  __tests__/integration/snapshots/marketIntervalMarimekko.svg
  __tests__/integration/snapshots/populationIntervalDiverging.svg
  __tests__/integration/snapshots/populationIntervalLayered.svg
  __tests__/integration/snapshots/populationIntervalNormalizedStacked.svg
  __tests__/integration/snapshots/productIntervalStackedGrouped.svg
  __tests__/integration/snapshots/profitIntervalRange.svg
  __tests__/integration/snapshots/questionsIntervalDivergingStacked.svg
  __tests__/integration/snapshots/seattleWeatherIntervalAggregated.svg
  __tests__/integration/snapshots/stateAgesIntervalGrouped.svg
  __tests__/integration/snapshots/stateAgesIntervalStacked.svg
  __tests__/unit/mark/interval.spec.ts
  __tests__/unit/shape/interval/rect.spec.ts
  docs/mark-interval.md
  src/mark/interval.ts
  src/runtime/plot.ts
  src/shape/interval/color.ts
  src/shape/utils.ts
Labels: PR: reviewed-approved

#4168 docs: 增加自定义图例筛选交互案例
  examples/customize/component/demo/meta.json
  examples/customize/component/demo/pie-legend.ts
Labels: Documentation, PR: unreviewed, PR: reviewed-approved

#4173 feat(interval): plots related to radial interval
  .genjirc
  __tests__/integration/charts/ages-interval-radial-stacked-sorted.ts
  __tests__/integration/charts/ages-interval-radial-stacked.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/population-interval-rose.ts
  __tests__/integration/charts/population2015-interval-donut.ts
  __tests__/integration/charts/population2015-interval-pie.ts
  __tests__/integration/charts/question8-interval-radial-gradient-color.ts
  __tests__/integration/data/ages.csv
  __tests__/integration/data/population2015.csv
  __tests__/integration/data/question8.js
  __tests__/integration/snapshots/agesIntervalRadialStacked.png
  __tests__/integration/snapshots/agesIntervalRadialStacked.svg
  __tests__/integration/snapshots/agesIntervalRadialStackedSorted.png
  __tests__/integration/snapshots/agesIntervalRadialStackedSorted.svg
  __tests__/integration/snapshots/gdpIntervalFlex.svg
  __tests__/integration/snapshots/gdpIntervalVarSize.svg
  __tests__/integration/snapshots/population2015IntervalDonut.png
  __tests__/integration/snapshots/population2015IntervalDonut.svg
  __tests__/integration/snapshots/population2015IntervalPie.png
  __tests__/integration/snapshots/population2015IntervalPie.svg
  __tests__/integration/snapshots/populationIntervalRose.png
  __tests__/integration/snapshots/populationIntervalRose.svg
  __tests__/integration/snapshots/question8IntervalRadialGradientColor.png
  __tests__/integration/snapshots/question8IntervalRadialGradientColor.svg
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/scale/index.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/coordinate-polar.md
  docs/coordinate-radial.md
  docs/coordinate-theta.md
  docs/mark-interval.md
  docs/scale-overview.md
  package.json
  src/component/axis.ts
  src/component/legendCategory.ts
  src/coordinate/index.ts
  src/coordinate/radial.ts
  src/runtime/component.ts
  src/runtime/coordinate.ts
  src/runtime/layout.ts
  src/runtime/plot.ts
  src/runtime/scale.ts
  src/runtime/types/common.ts
  src/scale/index.ts
  src/scale/sqrt.ts
  src/shape/interval/color.ts
  src/shape/label/label.ts
  src/spec/coordinate.ts
  src/spec/scale.ts
  src/stdlib/index.ts
  src/utils/coordinate.ts
Labels: PR: partially-approved

#4178 docs: add document for mark `Text`
  __tests__/unit/data/wordCloud.spec.ts
  __tests__/unit/shape/text/badge.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/mark-text.md
  src/data/index.ts
  src/data/wordCloud.ts
  src/shape/text/badge.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4180 feat: rename composition rect to square
  .genjirc
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/composition/square.spec.ts
  __tests__/unit/runtime/facet.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/composition-square.md
  src/api/composition/index.ts
  src/api/composition/rect.ts
  src/api/composition/square.ts
  src/composition/circle.ts
  src/composition/index.ts
  src/composition/matrix.ts
  src/composition/square.ts
  src/spec/composition.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4166 feat: arc wave-in animation
  __tests__/unit/animation/waveIn.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/animation.md
  docs/coordinate.md
  src/animation/index.ts
  src/animation/morphing.ts
  src/animation/utils.ts
  src/animation/waveIn.ts
  src/spec/animate.ts
  src/stdlib/index.ts
  src/utils/selection.ts
Labels: PR: reviewed-approved

#4185 feat(line): support render missing data
  __tests__/integration/charts/aapl-line-missing-connect.ts
  __tests__/integration/charts/aapl-line-missing-styled.ts
  __tests__/integration/charts/aapl-line-missing.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/aaplLineMissing.png
  __tests__/integration/snapshots/aaplLineMissingConnect.png
  __tests__/integration/snapshots/aaplLineMissingStyled.png
  __tests__/unit/shape/line/line.spec.ts
  docs/mark-line.md
  src/runtime/plot.ts
  src/shape/createElement.ts
  src/shape/line/curve.ts
  src/shape/utils.ts
  src/utils/selection.ts
Labels: PR: reviewed-approved

#4182 docs: area mark and docuement
  __tests__/integration/charts/aapl-area-missing-data.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/paragraph-text-vis.ts
  __tests__/integration/charts/population-by-state-area-normalize-stacked.ts
  __tests__/integration/charts/temperature-compare-area-difference.ts
  __tests__/integration/charts/unemployment-area-normalize-stacked.ts
  __tests__/integration/charts/unemployment-area-stacked.ts
  __tests__/integration/charts/unemployment-area-streamgraph.ts
  __tests__/integration/data/aapl.csv
  __tests__/integration/data/population-by-state.csv
  __tests__/integration/data/temperature-compare.csv
  __tests__/integration/data/unemployment-by-industry.csv
  __tests__/integration/data/unemployment.csv
  __tests__/integration/snapshots/aaplAreaMissingData.png
  __tests__/integration/snapshots/paragraphTextVis.png
  __tests__/integration/snapshots/populationByStateAreaNormalizeStacked.png
  __tests__/integration/snapshots/temperatureCompareAreaDifference.png
  __tests__/integration/snapshots/unemploymentAreaNormalizedStacked.png
  __tests__/integration/snapshots/unemploymentAreaStacked.png
  __tests__/integration/snapshots/unemploymentAreaStreamgraph.png
  __tests__/unit/stdlib/index.spec.ts
  src/shape/area/step.ts
  src/shape/index.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/diffY.ts
  src/transform/index.ts
Labels: PR: unreviewed
