Repository antvis/G2, pull requests merged in 2022-05, with the labels that each got.

#3894 feat(runtime): support facet and unit visualization
  .genjirc
  __tests__/unit/adjust/pack.spec.ts
  __tests__/unit/composition/flex.spec.ts
  __tests__/unit/composition/layer.spec.ts
  __tests__/unit/composition/rect.spec.ts
  __tests__/unit/composition/view.spec.ts
  __tests__/unit/runtime/facet.spec.ts
  __tests__/unit/runtime/unit.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/facet.md
  docs/unit.md
  package.json
  src/action/transformer/tooltip.ts
  src/adjust/pack.ts
  src/component/axis.ts
  src/component/legendCategory.ts
  src/composition/flex.ts
  src/composition/index.ts
  src/composition/layer.ts
  src/composition/mark.ts
  src/composition/rect.ts
  src/composition/utils.ts
  src/composition/view.ts
  src/runtime/layout.ts
  src/runtime/mark.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/scale.ts
  src/runtime/types/common.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/utils/helper.ts
Labels: PR: unreviewed

#3900 feat(axis): update @antv/gui, limit axis-title in bounds
  jest.config.js
  package.json
  src/component/axis.ts
  src/component/legendCategory.ts
Labels: PR: unreviewed

#3903 fix: some bugs showing in examples
  __tests__/unit/runtime/unit.spec.ts
  __tests__/unit/shape/text/text.spec.ts
  docs/unit.md
  src/composition/rect.ts
  src/shape/text/text.ts
Labels: PR: partially-approved

#3907 chore: set coverage = false by default
  .gitignore
  jest.config.js
  package.json
Labels: PR: partially-approved

#3909 fix/add window detect
  CHANGELOG.md
  package.json
  src/core.ts
  src/geometry/label/util/createWorker.ts
Labels: PR: unreviewed

#3906 feat(legend): update @antv/gui, simplify legend marker config
  src/component/legendCategory.ts
Labels: PR: reviewed-approved

#3910 feat: add area geometry and related area, smoothArea shape
  __tests__/data/sales.ts
  __tests__/unit/geometry/area.spec.ts
  __tests__/unit/runtime/area.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/statistic/stackY.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/geometry/area.ts
  src/geometry/index.ts
  src/infer/maybeStackY.ts
  src/shape/area/area.ts
  src/shape/area/curveArea.ts
  src/shape/area/smoothArea.ts
  src/shape/index.ts
  src/spec/geometry.ts
  src/spec/statistic.ts
  src/statistic/stackY.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#3916 chore: add bundle analysis visualizer
  .gitignore
  package.json
  rollup.config.js
Labels: PR: partially-approved

#3915 feat: add edge geometry and shapes
  __tests__/unit/geometry/edge.spec.ts
  __tests__/unit/runtime/edge.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/geometry/area.ts
  src/geometry/edge.ts
  src/geometry/index.ts
  src/shape/edge/arc.ts
  src/shape/edge/edge.ts
  src/shape/index.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#3919 feat: add image geometry and shape
  __tests__/unit/geometry/image.spec.ts
  __tests__/unit/runtime/image.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/mark/geometry/image.ts
  src/mark/geometry/index.ts
  src/shape/image/image.ts
  src/shape/index.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3920 feat(annotation): support lineX, lineY annotation
  __tests__/unit/mark/annotation/lineX.spec.ts
  __tests__/unit/mark/annotation/lineY.spec.ts
  __tests__/unit/runtime/annotationLine.spec.ts
  __tests__/unit/shape/annotation/line.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/component/axis.ts
  src/mark/annotation/index.ts
  src/mark/annotation/lineX.ts
  src/mark/annotation/lineY.ts
  src/shape/annotation/line.ts
  src/shape/index.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#3922 feat(encode): support array field
  __tests__/unit/runtime/interval.spec.ts
  src/runtime/mark.ts
Labels: PR: reviewed-approved

#3924 feat(axis): support arc axis in polar coordinate
  __tests__/data/sales.ts
  __tests__/unit/runtime/area.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  src/component/axis.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/runtime/component.ts
  src/runtime/layout.ts
  src/runtime/types/common.ts
Labels: PR: partially-approved

#3926 fix: ts errors in ci
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/shape/annotation/connector.spec.ts
  __tests__/unit/shape/interval/rect.spec.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/shape/annotation/connector.ts
  src/shape/annotation/text.ts
Labels: PR: reviewed-approved

#3923 feat: add polygon geometry and shape
  __tests__/unit/geometry/polygon.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/runtime/polygon.spec.ts
  __tests__/unit/shape/annotation/connector.spec.ts
  __tests__/unit/shape/interval/rect.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/transform/voronoi.spec.ts
  package.json
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/mark/geometry/index.ts
  src/mark/geometry/polygon.ts
  src/shape/annotation/connector.ts
  src/shape/annotation/text.ts
  src/shape/index.ts
  src/shape/polygon/polygon.ts
  src/spec/geometry.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/voronoi.ts
Labels: PR: unreviewed

#3928 feat: add vh, hv, hvh shape for line geometry
  __tests__/unit/runtime/line.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/shape/index.ts
  src/shape/line/hv.ts
  src/shape/line/hvh.ts
  src/shape/line/vh.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#3929 feat(axis): 更新 axis-description-tooltip 样式, 添加自定义 style 配置
  src/interaction/action/component/axis/axis-description.ts
Labels: feature, PR: unreviewed, PR: reviewed-approved

#3931 chore: v4.2.2 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#3933 feat: add schema geometry and box shape
  __tests__/unit/geometry/schema.spec.ts
  __tests__/unit/runtime/schema.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/mark/geometry/index.ts
  src/mark/geometry/schema.ts
  src/shape/index.ts
  src/shape/schema/box.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3935 fix: close path in area shapes
  __tests__/unit/runtime/area.spec.ts
  src/mark/geometry/area.ts
  src/shape/area/area.ts
  src/shape/area/curveArea.ts
  src/shape/area/smoothArea.ts
Labels: PR: partially-approved

#3934 docs: annotation
  .genjirc
  docs/annotation.md
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
Labels: PR: partially-approved

#3940 fix(test): text annotation rotate transform is apply to group
  __tests__/unit/shape/annotation/text.spec.ts
  __tests__/unit/shape/text/text.spec.ts
  src/shape/annotation/text.ts
Labels: PR: reviewed-approved

#3943 Update README.md
  README.md
Labels: PR: unreviewed

#3944 feat: add normalize transform
  .genjirc
  __tests__/unit/mark/geometry/interval.spec.ts
  __tests__/unit/runtime/statistic.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/normalize.md
  docs/overview.md
  src/mark/geometry/interval.ts
  src/runtime/scale.ts
  src/spec/statistic.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/statistic/normalizeY.ts
  src/transform/statistic/stackY.ts
Labels: PR: unreviewed

#3945 feat: update stack transform, support orderBy option to sort stacks
  .genjirc
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/runtime/statistic.spec.ts
  docs/normalize.md
  docs/overview.md
  docs/stack.md
  package.json
  src/spec/statistic.ts
  src/transform/connector/fetch.ts
  src/transform/inference/maybeStackY.ts
  src/transform/statistic/normalizeY.ts
  src/transform/statistic/stackY.ts
  src/transform/statistic/utils.ts
  src/transform/utils/helper.ts
Labels: PR: unreviewed

#3946 docs(annotation): add annotation demo
  __tests__/unit/runtime/annotationText.spec.ts
  docs/annotation.md
  docs/overview.md
Labels: PR: reviewed-approved

#3947 feat: draw point shapes with Path
  .eslintrc
  __tests__/unit/runtime/point.spec.ts
  __tests__/unit/shape/point/hollowPoint.spec.ts
  __tests__/unit/shape/point/point.spec.ts
  src/shape/point/colorPoint.ts
  src/shape/point/hollowPoint.ts
  src/shape/point/point.ts
  src/shape/point/symbol.ts
Labels: PR: unreviewed

#3949 feat: add jitter and jitterY transform
  .genjirc
  __tests__/unit/mark/geometry/point.spec.ts
  __tests__/unit/runtime/statistic.spec.ts
  __tests__/unit/shape/point/point.spec.ts
  __tests__/unit/shape/text/text.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/jitter.md
  docs/overview.md
  src/mark/geometry/point.ts
  src/runtime/mark.ts
  src/runtime/types/transform.ts
  src/shape/point/colorPoint.ts
  src/spec/statistic.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/statistic/Jitter.ts
  src/transform/statistic/JitterY.ts
  src/transform/statistic/stackY.ts
  src/utils/coordinate.ts
  src/utils/helper.ts
Labels: PR: partially-approved

#3952 feat: add symmetry
  .genjirc
  __tests__/unit/runtime/statistic.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/overview.md
  docs/symmetry.md
  package.json
  src/spec/statistic.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/statistic/normalizeY.ts
  src/transform/statistic/symmetryY.ts
Labels: PR: unreviewed

#3932 Update axis.zh.md
  docs/api/general/axis.zh.md
Labels: PR: reviewed-approved
