Repository antvis/G2, pull requests merged in 2022-03, with the labels that each got.

#3822 chore: update to version 4.1.47
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#3816 docs: 更新文档，将chart.source 改为 chart.data
  docs/api/general/animate.zh.md
  docs/manual/tutorial/data-flow.en.md
  docs/manual/tutorial/data-flow.zh.md
  docs/manual/tutorial/legend.en.md
  docs/manual/tutorial/legend.zh.md
  docs/manual/tutorial/renderers.en.md
  docs/manual/tutorial/renderers.zh.md
  docs/manual/tutorial/tooltip.en.md
  docs/manual/tutorial/tooltip.zh.md
Labels: Documentation, PR: unreviewed

#3826 fix(interval): 修复转置后的圆角条形图渲染多出一部分
  src/geometry/shape/interval/util.ts
  tests/unit/geometry/shape/interval-util-spec.ts
Labels: PR: reviewed-approved, bugfix

#3833 feat(theme): 主题支持完整样式表的自定义
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  tests/unit/theme/create-theme-spec.ts
Labels: feature, PR: unreviewed

#3834 chore: v4.1.48 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#3838 feat(animation): apply data-driven enter animation for marks
  __tests__/unit/animation/fadeIn.spec.ts
  __tests__/unit/animation/helper.ts
  __tests__/unit/animation/scaleInY.spec.ts
  __tests__/unit/geometry/interval.spec.ts
  __tests__/unit/runtime/animation.spec.ts
  __tests__/unit/runtime/basic.spec.ts
  __tests__/unit/runtime/render.spec.ts
  __tests__/unit/scale/index.spec.ts
  __tests__/unit/statistic/stackEnter.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/theme/light.spec.ts
  package.json
  src/animation/fadeIn.ts
  src/animation/index.ts
  src/animation/scaleInY.ts
  src/animation/utils.ts
  src/component/axis.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/geometry/interval.ts
  src/runtime/mark.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/scale.ts
  src/runtime/types/common.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/shape/interval/colorRect.ts
  src/shape/interval/hollowRect.ts
  src/shape/interval/rect.ts
  src/spec/animate.ts
  src/spec/geometry.ts
  src/spec/index.ts
  src/spec/scale.ts
  src/spec/statistic.ts
  src/statistic/index.ts
  src/statistic/stackEnter.ts
  src/statistic/stackY.ts
  src/stdlib/index.ts
  src/theme/light.ts
  src/utils/coordinate.ts
Labels: PR: partially-approved

#3840 fix: 修复判空问题
  src/geometry/label/layout/pie/spider.ts
Labels: PR: unreviewed, bugfix

#3841 chore: v4.1.49 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed

#3844 feat(transform): add pick
  __tests__/unit/transform/pick.spec.ts
  src/spec/transform.ts
  src/transform/index.ts
  src/transform/pick.ts
Labels: PR: unreviewed

#3839 chore: update readme and package.json
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.en-US.md
  CONTRIBUTING.md
  README.en-US.md
  README.md
  package.json
Labels: PR: unreviewed

#3846 feat: rename subset pick
  __tests__/unit/transform/pick.spec.ts
  __tests__/unit/transform/rename.spec.ts
  __tests__/unit/transform/subset.spec.ts
  src/spec/transform.ts
  src/transform/index.ts
  src/transform/pick.ts
  src/transform/rename.ts
  src/transform/subset.ts
Labels: PR: unreviewed
