Repository antvis/G2, pull requests merged in 2022-12, with the labels that each got.

#4384 refactor: optimize area examples
  site/examples/annotation/annotation/demo/point-point.ts
  site/examples/general/area/demo/area-difference.ts
  site/examples/general/area/demo/area-gradient.ts
  site/examples/general/area/demo/area.ts
  site/examples/general/area/demo/label.ts
  site/examples/general/area/demo/missing-data-area.ts
  site/examples/general/area/demo/percentage-area.ts
  site/examples/general/area/demo/range-spline-area.ts
  site/examples/general/area/demo/stacked-area.ts
  site/examples/general/area/demo/streamgraph.ts
Labels: PR: partially-approved

#4399 feat(theme): update dark theme
  __tests__/integration/snapshots/alphabetIntervalSpaceLayer.png
  __tests__/integration/snapshots/flareTreemapDefault.png
  __tests__/integration/snapshots/philosophyWordCloudCustom.png
  __tests__/integration/snapshots/population2015IntervalPieLabel.png
  __tests__/integration/snapshots/population2015IntervalSpiderLabel.png
  __tests__/integration/snapshots/populationIntervalRoseLabel.png
  __tests__/integration/snapshots/populationIntervalRoseSurroundLabel.png
  __tests__/integration/snapshots/question8IntervalRadialGradientColor.png
  __tests__/integration/snapshots/unemploymentAreaNormalizedStacked.png
  __tests__/integration/snapshots/unemploymentAreaStacked.png
  __tests__/integration/snapshots/unemploymentAreaStackedDataDrivenStyled.png
  __tests__/integration/snapshots/unemploymentAreaStreamgraph.png
  src/shape/area/curve.ts
  src/shape/line/curve.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: partially-approved

#4401 docs: several typo fix
  site/docs/api/mark/cell.zh.md
  site/docs/api/mark/rect.zh.md
  site/docs/api/overview.zh.md
  site/docs/api/scale/band.zh.md
  site/docs/api/scale/point.zh.md
  site/docs/api/scale/time.zh.md
  site/docs/api/transform/bin.zh.md
  site/docs/api/transform/group.zh.md
  site/docs/api/transform/groupColor.zh.md
  site/docs/api/transform/groupX.zh.md
  site/docs/api/transform/groupY.zh.md
  site/docs/manual/getting-started.zh.md
  site/docs/manual/introduction.zh.md
  site/docs/manual/single-view/coordinate.zh.md
  site/examples/annotation/annotation/demo/interval-threshold.ts
  site/examples/general/text/demo/paragraph.ts
Labels: PR: unreviewed

#4400 feat: add transform.sample
  __tests__/integration/charts/aapl-line-basic-sample.ts
  __tests__/integration/charts/house-price-point-sample.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/unemployment-area-stacked-sample.ts
  __tests__/integration/data/house-price-area.json
  __tests__/integration/snapshots/aaplLineBasicSample.png
  __tests__/integration/snapshots/housePricePointSample.png
  __tests__/integration/snapshots/unemploymentAreaStackedSample.png
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/overview.zh.md
  site/docs/api/transform/sample.en.md
  site/docs/api/transform/sample.zh.md
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/groupN.ts
  src/transform/index.ts
  src/transform/sample.ts
Labels: PR: unreviewed

#4395 fix: sort transform should sort the I array
  __tests__/integration/charts/gamma-random-line-sortx-quantitative.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/gamma-random.json
  __tests__/integration/snapshots/gammaRandomLineSortXQuantitative.png
  site/docs/api/transform/sortX.zh.md
  src/spec/transform.ts
  src/transform/sort.ts
Labels: PR: partially-approved

#4402 docs: add usage demo for framework (close: #4370)
  site/.dumirc.ts
  site/docs/manual/more/use-in-framework.en.md
  site/docs/manual/more/use-in-framework.zh.md
Labels: PR: reviewed-approved

#4404 chore: increase maxError to fix ci
  __tests__/integration/charts/unemployment-area-stacked-sample.ts
Labels: PR: reviewed-approved

#4405 chore: update to 5.0.0-beta.2
  package.json
Labels: PR: unreviewed

#4406 fix(select): lowercase Select to select
  src/transform/sample.ts
  src/transform/selectX.ts
  src/transform/selectY.ts
Labels: PR: reviewed-approved, PR: partially-approved

#4407 chore: fix demo bug
  examples/column/basic/demo/custom-shape.ts
  gatsby-config.js
  package.json
Labels: PR: reviewed-approved, ignore-for-release

#4410 chore: update version to 5.0.0-beta.3
  package.json
  site/package.json
Labels: PR: partially-approved

#4408 fix: 修复极坐标下,圆弧坐标轴文本收尾重叠的问题
  .github/workflows/auto-inspection.yml
  docs/api/general/chart.zh.md
  src/chart/controller/axis.ts
  tests/unit/component/axis-circle-spec.ts
Labels: PR: unreviewed, bugfix

#4415 feat: add legendFilter
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/profit-interval-legend-filter-ordinal.ts
  __tests__/integration/interactions/temperatures-line-legend-filter-ordinal.ts
  __tests__/integration/interactions/utils.ts
  __tests__/integration/snapshot-interaction.spec.ts
  __tests__/integration/snapshots/profit-interval-legend-filter-ordinal/step0.png
  __tests__/integration/snapshots/profit-interval-legend-filter-ordinal/step1.png
  __tests__/integration/snapshots/profit-interval-legend-filter-ordinal/step2.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step0.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step1.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step2.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step3.png
  __tests__/unit/stdlib/index.spec.ts
  src/component/legendCategory.ts
  src/data/filter.ts
  src/data/index.ts
  src/interaction/index.ts
  src/interaction/native/legendFilter.ts
  src/spec/data.ts
  src/spec/interaction.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/filter.ts
  src/transform/index.ts
Labels: PR: unreviewed

#4413 feat(component): support slider without interaction
  __tests__/integration/charts/aapl-line-slider-transposed.ts
  __tests__/integration/charts/aapl-line-slider.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/aaplLineSlider.png
  __tests__/integration/snapshots/aaplLineSliderTransponsed.png
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/chart.zh.md
  site/docs/api/component/axis.zh.md
  site/docs/api/component/legend.zh.md
  site/docs/api/component/slider.en.md
  site/docs/api/component/slider.zh.md
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/component/index.ts
  src/component/slider.ts
  src/component/sliderX.ts
  src/component/sliderY.ts
  src/runtime/component.ts
  src/runtime/plot.ts
  src/runtime/types/options.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/theme/light.ts
Labels: PR: unreviewed

#4419 docs: replace site-data-pre.alipay.com
  site/examples/analysis/bin/demo/binx.ts
  site/examples/analysis/regression/demo/exponential-regression.ts
  site/examples/analysis/regression/demo/linear-regression.ts
  site/examples/analysis/regression/demo/logarithmic-regression.ts
Labels: PR: reviewed-approved

#4422 docs: change chart to container in getting-started
  site/docs/manual/getting-started.zh.md
Labels: PR: reviewed-approved

#4416 feat(interaction): add facet tooltip
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/indices-line-chart-facet-tooltip.ts
  __tests__/integration/interactions/temperatures-line-tooltip-discrete.ts
  src/composition/facetRect.ts
  src/composition/mark.ts
  src/composition/repeatMatrix.ts
  src/interaction/native/tooltip.ts
  src/mark/area.ts
  src/mark/line.ts
  src/runtime/types/mark.ts
  src/spec/interaction.ts
Labels: PR: partially-approved

#4424 fix: chart size function
  src/utils/size.ts
Labels: PR: reviewed-approved

#4426 fix(interaction): legend fitler transform should in first
  src/interaction/native/legendFilter.ts
Labels: PR: partially-approved

#4429 feat: add data.transform.sort
  __tests__/integration/charts/alphabet-interval-data-sort.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/alphabetIntervalDataSort.png
  __tests__/unit/data/sort.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/data/index.ts
  src/data/sort.ts
  src/spec/data.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4439 docs: add boxplot、shape document
  site/.dumi/global.ts
  site/docs/api/mark/box.zh.md
  site/docs/api/mark/boxplot.en.md
  site/docs/api/mark/boxplot.zh.md
  site/docs/api/mark/shape.en.md
  site/docs/api/mark/shape.zh.md
  site/docs/api/overview.zh.md
  site/examples/annotation/annotation/demo/meta.json
  site/examples/annotation/annotation/demo/watermark.ts
  site/package.json
Labels: PR: partially-approved

#4442 feat(interaction): legend filter support custom legend
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/profit-interval-custom-legend-filter.ts
  __tests__/integration/main.ts
  src/interaction/native/legendFilter.ts
  src/interaction/native/utils.ts
  src/spec/interaction.ts
Labels: PR: partially-approved

#4430 docs: add slider docs, split legend, unify docs format
  site/docs/api/common/componentTitle.zh.md
  site/docs/api/common/navigator.zh.md
  site/docs/api/common/sparkline.en.md
  site/docs/api/common/sparkline.zh.md
  site/docs/api/common/style.zh.md
  site/docs/api/component/axis.zh.md
  site/docs/api/component/category.en.md
  site/docs/api/component/category.zh.md
  site/docs/api/component/continuous.en.md
  site/docs/api/component/continuous.zh.md
  site/docs/api/component/legend.en.md
  site/docs/api/component/legend.zh.md
  site/docs/api/component/slider.zh.md
  site/docs/api/label/overview.zh.md
  site/docs/api/mark/area.zh.md
  site/docs/api/mark/box.zh.md
  site/docs/api/mark/cell.zh.md
  site/docs/api/mark/image.zh.md
  site/docs/api/mark/interval.zh.md
  site/docs/api/mark/line.zh.md
  site/docs/api/mark/lineX.zh.md
  site/docs/api/mark/lineY.zh.md
  site/docs/api/mark/link.zh.md
  site/docs/api/mark/point.zh.md
  site/docs/api/mark/polygon.zh.md
  site/docs/api/mark/range.zh.md
  site/docs/api/mark/rangeX.zh.md
  site/docs/api/mark/rangeY.zh.md
  site/docs/api/mark/rect.zh.md
  site/docs/api/mark/text.zh.md
  site/docs/api/mark/vector.zh.md
Labels: PR: partially-approved

#4443 feat(component): support axis${position} theme token
  site/docs/api/theme/theme.zh.md
  src/component/axis.ts
  src/runtime/types/theme.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4446 docs: update animation API
  site/.dumirc.ts
  site/docs/api/animation/overview.zh.md
  site/docs/api/chart.zh.md
Labels: PR: partially-approved

#4451 chore: v5.0.0-beta.4
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4456 fix: fix site direct and auto-deploy when push to v5
  .github/workflows/deploy.yml
  site/.dumi/global.ts
Labels: PR: partially-approved

#4457 feat: add clip attributes to clip overflowed plot
  __tests__/integration/charts/aapl-line-clip.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/aaplLineClip.png
  src/composition/mark.ts
  src/runtime/plot.ts
  src/runtime/types/common.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
Labels: PR: partially-approved

#4453 feat: add 4 label.transform
  __tests__/integration/charts/aapl-line-basic-label-overlap-hide.ts
  __tests__/integration/charts/alphabet-interval-label-contrast-reverse.ts
  __tests__/integration/charts/alphabet-interval-label-overflow-hide.ts
  __tests__/integration/charts/gain-lost-interval-cornered.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/population-by-state-area-normalize-stacked.ts
  __tests__/integration/charts/population-interval-rose-surround-label.ts
  __tests__/integration/charts/population2015-interval-donut-label.ts
  __tests__/integration/charts/population2015-interval-pie-label.ts
  __tests__/integration/charts/population2015-interval-spider-label.ts
  __tests__/integration/charts/receipts-line-slope.ts
  __tests__/integration/charts/stocks-line-aggregate-label.ts
  __tests__/integration/snapshots/aaplLineBasicLabelOverlapHide.png
  __tests__/integration/snapshots/alphabetIntervalLabelContrastReverse.png
  __tests__/integration/snapshots/alphabetIntervalLabelOverflowHide.png
  __tests__/integration/snapshots/populationIntervalRoseSurroundLabel.png
  __tests__/unit/runtime/label.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/utils/bounds.spec.ts
  package.json
  site/docs/api/label/overview.zh.md
  site/examples/general/area/demo/label.ts
  site/examples/general/interval/demo/bar-stacked-diverging-rounded.ts
  site/examples/general/line/demo/line-aggregated-label.ts
  site/examples/general/line/demo/line-slope.ts
  site/examples/general/radial/demo/rose-label.ts
  site/examples/general/radial/demo/spider-label.ts
  site/examples/plugin/rough/demo/line.ts
  site/examples/theme/theme/demo/dark.ts
  src/label-transform/contrastReverse.ts
  src/label-transform/hideOverlap.ts
  src/label-transform/index.ts
  src/label-transform/overflowHide.ts
  src/label-transform/overlapDodgeY.ts
  src/label-transform/overlapHide.ts
  src/label-transform/spider.ts
  src/label-transform/surround.ts
  src/runtime/plot.ts
  src/shape/label/label.ts
  src/shape/label/position/area.ts
  src/shape/label/position/bottom.ts
  src/shape/label/position/bottomLeft.ts
  src/shape/label/position/bottomRight.ts
  src/shape/label/position/default.ts
  src/shape/label/position/index.ts
  src/shape/label/position/inside.ts
  src/shape/label/position/left.ts
  src/shape/label/position/outside.ts
  src/shape/label/position/right.ts
  src/shape/label/position/spider.ts
  src/shape/label/position/surround.ts
  src/shape/label/position/top.ts
  src/shape/label/position/topLeft.ts
  src/shape/label/position/topRight.ts
  src/spec/labelTransform.ts
  src/stdlib/index.ts
  src/utils/bounds.ts
  src/utils/color.ts
  src/utils/coordinate.ts
Labels: PR: partially-approved

#4482 feat(interaction): add brush, brushX and brushY for highlight
  __tests__/integration/canvas.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/indices-line-brush-series.ts
  __tests__/integration/interactions/indices-line-chart-facet-brush-shared.ts
  __tests__/integration/interactions/penguins-point-brush-reverse.ts
  __tests__/integration/interactions/penguins-point-brush-x.ts
  __tests__/integration/interactions/penguins-point-brush-y.ts
  __tests__/integration/interactions/penguins-point-brush.ts
  __tests__/integration/interactions/utils.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshots/indices-line-brush-series/step0.png
  __tests__/integration/snapshots/indices-line-chart-facet-brush-shared/step0.png
  __tests__/integration/snapshots/penguins-point-brush-reverse/step0.png
  __tests__/integration/snapshots/penguins-point-brush-reverse/step1.png
  __tests__/integration/snapshots/penguins-point-brush-x/step0.png
  __tests__/integration/snapshots/penguins-point-brush-y/step0.png
  __tests__/integration/snapshots/penguins-point-brush/step0.png
  __tests__/integration/snapshots/penguins-point-brush/step1.png
  __tests__/integration/snapshots/penguins-point-brush/step2.png
  __tests__/integration/snapshots/penguins-point-brush/step3.png
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/index.ts
  src/interaction/native/brushHighlight.ts
  src/interaction/native/brushXHighlight.ts
  src/interaction/native/brushYHighlight.ts
  src/interaction/native/legendFilter.ts
  src/interaction/native/tooltip.ts
  src/interaction/native/utils.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4481 docs: remove g from dependencies in site & use document creating elem…
  site/.dumi/global.ts
  site/docs/api/mark/shape.zh.md
  site/examples/annotation/annotation/demo/watermark.ts
  site/package.json
Labels: PR: reviewed-approved

#4487 fix(runtime): missing field (close: #4437)
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/orders-line-missing-field.ts
  __tests__/integration/data/orders.js
  __tests__/integration/snapshot.spec.ts
  __tests__/integration/snapshots/ordersLineMissingField.png
  src/runtime/transform.ts
Labels: PR: partially-approved

#4488 fix(api): remove interaction and coordinate for mark (close: #4438)
  __tests__/unit/api/mark.spec.ts
  site/docs/api/chart.zh.md
  src/api/mark/mark.ts
  src/api/mark/types.ts
Labels: PR: partially-approved

#4489 refactor: move theme dir to .dumi/theme
  site/.dumi/pages/theme.en.tsx
  site/.dumi/pages/theme.zh.tsx
  site/.dumi/theme/components/ConfigPanel.less
  site/.dumi/theme/components/ConfigPanel.tsx
  site/.dumi/theme/components/DemosView.less
  site/.dumi/theme/components/DemosView.tsx
  site/.dumi/theme/examples/bar-aggregated.ts
  site/.dumi/theme/examples/bar-dodged.ts
  site/.dumi/theme/examples/bar-range.ts
  site/.dumi/theme/examples/grouped-box.ts
  site/.dumi/theme/examples/index.ts
  site/.dumi/theme/examples/line-bar.ts
  site/.dumi/theme/examples/line-connect-nulls.ts
  site/.dumi/theme/examples/line-normalized.ts
  site/.dumi/theme/examples/missing-data-area.ts
  site/.dumi/theme/examples/point-log.ts
  site/.dumi/theme/examples/rose-label.ts
  site/.dumi/theme/examples/sankey.ts
  site/.dumi/theme/examples/spider-label.ts
  site/.dumi/theme/examples/stacked-area.ts
  site/.dumi/theme/examples/treemap.ts
  site/.dumi/theme/index.less
  site/.dumi/theme/index.tsx
  site/.dumi/theme/utils/copyToBoard.ts
  site/.dumi/theme/utils/exportDataToLocal.ts
Labels: PR: reviewed-approved

#4497 chore: 5.0.0-beta.5
  package.json
  site/package.json
Labels: PR: unreviewed

#4500 feat(gui): update gui
  __tests__/integration/charts/gdp-interval-flex.ts
  __tests__/integration/charts/metros-link-trending.ts
  __tests__/integration/charts/stateages-interval-stacked.ts
  __tests__/integration/charts/train-line-multi-axes.ts
  __tests__/integration/snapshots/aaplLineMissingConnect.png
  __tests__/integration/snapshots/alphabetIntervalLabelContrastReverse.png
  __tests__/integration/snapshots/alphabetIntervalSpaceLayer.png
  __tests__/integration/snapshots/events-interval-encode/interval0-0.png
  __tests__/integration/snapshots/events-interval-encode/interval0-1.png
  __tests__/integration/snapshots/events-interval-encode/interval0-2.png
  __tests__/integration/snapshots/flareTreemapDefault.png
  __tests__/integration/snapshots/haleChoroplethWorld.png
  __tests__/integration/snapshots/indices-line-brush-series/step0.png
  __tests__/integration/snapshots/monthIntervalFacetRect.png
  __tests__/integration/snapshots/os-area-stack-enter/interval0-0.png
  __tests__/integration/snapshots/os-area-stack-enter/interval0-1.png
  __tests__/integration/snapshots/os-area-stack-enter/interval0-2.png
  __tests__/integration/snapshots/philosophyWordCloudCustom.png
  __tests__/integration/snapshots/scoreByItemAreaRadar.png
  __tests__/integration/snapshots/scoreByItemAreaRadarCustom.png
  __tests__/integration/snapshots/scoreByItemAreaSmoothRadar.png
  __tests__/integration/snapshots/sepalBoxPolarBox.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval2-1.png
  __tests__/integration/snapshots/sold-interval-pie-keyframe/interval2-0.png
  __tests__/integration/snapshots/sold-interval-pie-keyframe/interval2-1.png
  __tests__/integration/snapshots/sold-interval-pie-keyframe/interval3-0.png
  __tests__/integration/snapshots/sold-interval-pie-keyframe/interval3-1.png
  __tests__/integration/snapshots/sold-interval-pie-keyframe/interval3-2.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step0.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step1.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step2.png
  __tests__/integration/snapshots/temperatures-line-legend-filter-ordinal/step3.png
  __tests__/integration/snapshots/unemploymentAreaNormalizedStacked.png
  __tests__/integration/snapshots/unemploymentAreaStacked.png
  __tests__/integration/snapshots/unemploymentAreaStackedDataDrivenStyled.png
  __tests__/integration/snapshots/unemploymentAreaStackedSample.png
  __tests__/integration/snapshots/unemploymentAreaStreamgraph.png
  src/component/slider.ts
  src/interaction/native/legendFilter.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4501 fix(test): write diff png when mismatch greater than maxError
  __tests__/integration/canvas.ts
  __tests__/integration/snapshot-animation.spec.ts
  __tests__/integration/snapshot-interaction.spec.ts
  __tests__/integration/snapshot.spec.ts
Labels: PR: unreviewed

#4499 test(interaction): add tests for tooltip
  .prettierignore
  __tests__/integration/animations/sex-interval-keyframe.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/indices-line-brush-series.ts
  __tests__/integration/interactions/indices-line-chart-facet-brush-shared.ts
  __tests__/integration/interactions/indices-line-chart-index-series.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshot-animation.spec.ts
  __tests__/integration/snapshot-interaction.spec.ts
  __tests__/integration/snapshot-tooltip.spec.ts
  __tests__/integration/snapshot.spec.ts
  __tests__/integration/snapshots/indices-line-chart-index-series/step0.png
  __tests__/integration/snapshots/tooltip-aaplLine/step0.html
  __tests__/integration/snapshots/tooltip-alphabetInterval1d/step0.html
  __tests__/integration/snapshots/tooltip-alphabetIntervalMulti/step0.html
  __tests__/integration/snapshots/tooltip-alphabetIntervalObject/step0.html
  __tests__/integration/snapshots/tooltip-alphabetIntervalTitle/step0.html
  __tests__/integration/snapshots/tooltip-bodyPoint2d/step0.html
  __tests__/integration/snapshots/tooltip-cars3LineXd/step0.html
  __tests__/integration/snapshots/tooltip-indicesLine/step0.html
  __tests__/integration/snapshots/tooltip-indicesLineChartFacet/step0.html
  __tests__/integration/snapshots/tooltip-indicesLineChartFacet/step1.html
  __tests__/integration/snapshots/tooltip-indicesLinePointReverse/step0.html
  __tests__/integration/snapshots/tooltip-indicesLinePointReverse/step1.html
  __tests__/integration/snapshots/tooltip-indicesLineReverse/step0.html
  __tests__/integration/snapshots/tooltip-indicesLineReverse/step1.html
  __tests__/integration/snapshots/tooltip-morleyBox/step0.html
  __tests__/integration/snapshots/tooltip-stateAgesIntervalShared/step0.html
  __tests__/integration/snapshots/tooltip-temperaturesLineDiscrete/step0.html
  __tests__/integration/snapshots/tooltip-temperaturesLinePointDiscrete/step0.html
  __tests__/integration/snapshots/tooltip-weatherLineInterval/step0.html
  __tests__/integration/svg.ts
  __tests__/integration/tooltips/aapl-line.ts
  __tests__/integration/tooltips/alphabet-interval-1d.ts
  __tests__/integration/tooltips/alphabet-interval-multi.ts
  __tests__/integration/tooltips/alphabet-interval-object.ts
  __tests__/integration/tooltips/alphabet-interval-title.ts
  __tests__/integration/tooltips/body-point-2d.ts
  __tests__/integration/tooltips/cars3-line-xd.ts
  __tests__/integration/tooltips/index.ts
  __tests__/integration/tooltips/indices-line-chart-facet.ts
  __tests__/integration/tooltips/indices-line-point-reverse.ts
  __tests__/integration/tooltips/indices-line-reverse.ts
  __tests__/integration/tooltips/indices-line.ts
  __tests__/integration/tooltips/morley-box.ts
  __tests__/integration/tooltips/stateages-interval-shared.ts
  __tests__/integration/tooltips/temperatures-line-discrete.ts
  __tests__/integration/tooltips/temperatures-line-point-discrete.ts
  __tests__/integration/tooltips/utils.ts
  __tests__/integration/tooltips/weather-line-interval.ts
  src/interaction/native/tooltip.ts
Labels: PR: unreviewed

#4502 docs: adjust site demos and arcY axis defaultStyle
  __tests__/integration/snapshots/agesIntervalRadialStacked.png
  __tests__/integration/snapshots/seasonalWeatherAreaRadial.png
  site/examples/general/interval/demo/bar-flex.ts
  site/examples/general/interval/demo/bar-stacked.ts
  site/examples/general/link/demo/link.ts
  site/examples/general/radial/demo/apple-activity.ts
  site/examples/plugin/rough/demo/interval.ts
  site/examples/plugin/rough/demo/line.ts
  site/examples/plugin/rough/demo/point.ts
  src/component/axis.ts
Labels: PR: reviewed-approved

#4507 fix(boxplot): pass scale, axis and legend (close: #4355)
  __tests__/integration/charts/gdp2-boxplot-log.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/gdp2BoxplotLog.png
  src/mark/boxplot.ts
Labels: PR: partially-approved

#4503 feat(interaction): add brush axis
  .eslintrc
  __tests__/integration/interactions/cars3-line-brush-axis.ts
  __tests__/integration/interactions/cars3-line-vertical-brush-axis.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/penguins-point-brush-axis.ts
  __tests__/integration/snapshots/cars3-line-brush-axis/step0.png
  __tests__/integration/snapshots/cars3-line-brush-axis/step1.png
  __tests__/integration/snapshots/cars3-line-vertical-brush-axis/step0.png
  __tests__/integration/snapshots/cars3-line-vertical-brush-axis/step1.png
  __tests__/integration/snapshots/penguins-point-brush-axis/step0.png
  __tests__/integration/snapshots/penguins-point-brush-axis/step1.png
  __tests__/unit/stdlib/index.spec.ts
  src/component/axis.ts
  src/interaction/index.ts
  src/interaction/native/brushAxisHighlight.ts
  src/interaction/native/brushHighlight.ts
  src/interaction/native/brushXHighlight.ts
  src/interaction/native/brushYHighlight.ts
  src/runtime/component.ts
  src/runtime/layout.ts
  src/runtime/types/common.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4509 fix(types): type errors
  src/interaction/index.ts
  src/spec/action.ts
  src/spec/interaction.ts
Labels: PR: partially-approved

#4521 fix(connect): do not apply default color to connectStyle
  __tests__/integration/snapshots/aaplLineMissingConnect.png
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: partially-approved

#4526 refactor: getShapeTheme do not merge fill & stroke
  __tests__/integration/charts/house-price-point-shapes.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/housePricePointShapes.png
  src/shape/area/curve.ts
  src/shape/box/box.ts
  src/shape/connector/connector.ts
  src/shape/image/image.ts
  src/shape/interval/color.ts
  src/shape/line/curve.ts
  src/shape/lineXY/line.ts
  src/shape/link/arc.ts
  src/shape/link/link.ts
  src/shape/link/smooth.ts
  src/shape/link/vhv.ts
  src/shape/point/color.ts
  src/shape/polygon/polygon.ts
  src/shape/polygon/ribbon.ts
  src/shape/text/badge.ts
  src/shape/text/text.ts
  src/shape/utils.ts
  src/shape/vector/vector.ts
  src/theme/academy.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4522 feat: adjust spider label
  __tests__/integration/snapshots/population2015IntervalSpiderLabel.png
  __tests__/integration/snapshots/populationIntervalRoseSurroundLabel.png
  site/docs/api/transform/groupX.zh.md
  site/docs/api/transform/groupY.zh.md
  src/shape/label/position/default.ts
  src/shape/label/position/outside.ts
  src/shape/label/position/spider.ts
  src/shape/label/position/surround.ts
  src/shape/text/advance.ts
  src/theme/academy.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: unreviewed

#4512 feat: add data.slice, remove data.subset
  __tests__/unit/data/slice.spec.ts
  __tests__/unit/data/subset.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/data/overview.zh.md
  site/docs/api/data/slice.en.md
  site/docs/api/data/slice.zh.md
  site/docs/api/data/subset.en.md
  site/docs/api/data/subset.zh.md
  site/docs/api/overview.zh.md
  src/data/index.ts
  src/data/pick.ts
  src/data/slice.ts
  src/data/subset.ts
  src/spec/data.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4527 refactor: fold config as -> key, value
  __tests__/integration/charts/ages-interval-radial-stacked-sorted.ts
  __tests__/integration/charts/ages-interval-radial-stacked.ts
  __tests__/integration/charts/blockchain-line-annotation.ts
  __tests__/integration/charts/blockchain-line-badge-annotation.ts
  __tests__/integration/charts/gain-lost-interval-cornered.ts
  __tests__/integration/charts/population-by-state-area-normalize-stacked.ts
  __tests__/integration/charts/temperature-compare-area-difference.ts
  __tests__/unit/data/fold.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/data/fold.zh.md
  site/docs/api/transform/diffY.zh.md
  site/examples/annotation/annotation/demo/line-badge.ts
  site/examples/annotation/annotation/demo/line-text.ts
  site/examples/annotation/annotation/demo/point-range.ts
  site/examples/annotation/annotation/demo/quadrant-scatter.ts
  site/examples/general/area/demo/area-difference.ts
  site/examples/general/area/demo/label.ts
  site/examples/general/interval/demo/bar-stacked-diverging-rounded.ts
  site/examples/general/radial/demo/bar-stacked-radial.ts
  site/examples/plugin/search/demo/meta.json
  src/data/fold.ts
  src/spec/data.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4532 feat(component): support scrollbar without interactions
  __tests__/integration/charts/aapl-line-scrollbar.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/aaplLineScrollbar.png
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/component/scrollbar.en.md
  site/docs/api/component/scrollbar.zh.md
  site/docs/api/component/slider.zh.md
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/component/index.ts
  src/component/scrollbar.ts
  src/component/scrollbarX.ts
  src/component/scrollbarY.ts
  src/runtime/component.ts
  src/runtime/types/options.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4511 feat(interaction): add brush filter
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/penguins-point-brush-axis.ts
  __tests__/integration/interactions/penguins-point-brush-filter.ts
  __tests__/integration/interactions/penguins-point-brush-x-filter.ts
  __tests__/integration/interactions/penguins-point-brush-y-filter.ts
  __tests__/integration/interactions/penguins-point-brush.ts
  __tests__/integration/interactions/profit-interval-brush-filter.ts
  __tests__/integration/interactions/seattle-weather-cell-brush-filter.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshots/penguins-point-brush-filter/step0.png
  __tests__/integration/snapshots/penguins-point-brush-filter/step1.png
  __tests__/integration/snapshots/penguins-point-brush-filter/step2.png
  __tests__/integration/snapshots/penguins-point-brush-reverse/step0.png
  __tests__/integration/snapshots/penguins-point-brush-reverse/step1.png
  __tests__/integration/snapshots/penguins-point-brush-x-filter/step0.png
  __tests__/integration/snapshots/penguins-point-brush-x/step0.png
  __tests__/integration/snapshots/penguins-point-brush-y-filter/step0.png
  __tests__/integration/snapshots/penguins-point-brush-y/step0.png
  __tests__/integration/snapshots/penguins-point-brush/step0.png
  __tests__/integration/snapshots/penguins-point-brush/step1.png
  __tests__/integration/snapshots/profit-interval-brush-filter/step0.png
  __tests__/integration/snapshots/profit-interval-brush-filter/step2.png
  __tests__/integration/snapshots/settle-weather-cell-brush-filter/step0.png
  __tests__/integration/snapshots/settle-weather-cell-brush-filter/step1.png
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/index.ts
  src/interaction/native/brushAxisHighlight.ts
  src/interaction/native/brushFilter.ts
  src/interaction/native/brushHighlight.ts
  src/interaction/native/brushXFilter.ts
  src/interaction/native/brushYFilter.ts
  src/interaction/native/utils.ts
  src/runtime/plot.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4529 docs: add documents for title component
  __tests__/integration/charts/alphabet-interval-title.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/alphabetIntervalTitle.png
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/render/renderToMountedElement.spec.ts
  site/docs/api/component/title.en.md
  site/docs/api/component/title.zh.md
  site/docs/api/overview.zh.md
  src/api/chart.ts
  src/component/title.ts
  src/data/fold.ts
  src/data/slice.ts
  src/runtime/component.ts
  src/runtime/types/common.ts
  src/runtime/types/options.ts
  src/runtime/types/theme.ts
  src/theme/academy.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4537 feat(brush): support brush matrix
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/penguins-point-brush-matrix.ts
  __tests__/integration/snapshots/penguins-point-brush-matrix/step0.png
  __tests__/integration/snapshots/penguins-point-brush-matrix/step1.png
  src/interaction/native/brushHighlight.ts
  src/interaction/native/utils.ts
  src/spec/interaction.ts
Labels: PR: partially-approved
