Repository antvis/G2, pull requests merged in 2022-07, with the labels that each got.

#4004 docs(example): brush selection add the modification button example
  examples/interaction/brush/demo/brush-rename-button.ts
  examples/interaction/brush/demo/meta.json
Labels: Documentation, PR: unreviewed, PR: reviewed-approved

#4016 feat: bind series value to series mark
  .genjirc
  __tests__/unit/mark/geometry/area.spec.ts
  __tests__/unit/mark/geometry/line.spec.ts
  __tests__/unit/mark/helper.ts
  __tests__/unit/runtime/area.spec.ts
  __tests__/unit/runtime/line.spec.ts
  docs/area.md
  docs/line.md
  src/component/legendContinuous.ts
  src/mark/geometry/area.ts
  src/mark/geometry/line.ts
  src/runtime/plot.ts
  src/runtime/types/component.ts
  src/runtime/types/mark.ts
  src/runtime/types/transform.ts
  src/shape/area/curveArea.ts
  src/shape/line/curveLine.ts
  src/shape/utils.ts
Labels: PR: partially-approved

#4017 fix(area-shape): fix marker fillOpacity
  src/geometry/shape/area/index.ts
  src/geometry/shape/area/smooth.ts
  tests/unit/geometry/shape/area-spec.ts
Labels: PR: reviewed-approved, bugfix

#4008 fix(crosshairs): crosshairs 删除在坐标轴外不能显示的配置
  src/chart/controller/tooltip.ts
  src/util/coordinate.ts
  tests/bugs/crosshairs-spec.ts
Labels: PR: unreviewed, bugfix

#4021 feat(keyframe): support transition among facet and unit visualization
  __tests__/unit/runtime/keyframe.spec.ts
  docs/keyframe.md
  src/animation/morphing.ts
  src/composition/keyframe.ts
  src/composition/rect.ts
  src/runtime/plot.ts
  src/runtime/types/options.ts
  src/spec/animate.ts
  src/spec/composition.ts
  src/spec/geometry.ts
  src/utils/helper.ts
  src/utils/selection.ts
Labels: PR: unreviewed

#4024 feat(interaction): support tooltip
  .genjirc
  __tests__/unit/interaction/index.spec.ts
  __tests__/unit/interaction/tooltip.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  docs/line.md
  docs/more-interaction.md
  docs/tooltip-interaction.md
  src/interaction/action/service/surfacePointSelection.ts
  src/interaction/action/transformer/tooltip.ts
  src/interaction/builtin/tooltip.ts
  src/runtime/plot.ts
  src/spec/action.ts
  src/spec/interaction.ts
Labels: PR: partially-approved

#4030 chore: v4.2.5 & changelog
  .eslintrc.js
  CHANGELOG.md
  package.json
  src/chart/controller/annotation.ts
  src/core.ts
  tests/unit/theme/create-theme-spec.ts
Labels: PR: unreviewed, ignore-for-release

#4032 feat(interaction): refactor action of element and support elementSelected interaction
  .genjirc
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/interaction-element.md
  docs/interaction-more.md
  docs/interaction-tooltip.md
  src/interaction/action/index.ts
  src/interaction/action/service/elementSelection.ts
  src/interaction/action/transformer/activeElement.ts
  src/interaction/builtin/elementHighlight.ts
  src/interaction/builtin/elementSelected.ts
  src/interaction/index.ts
  src/interaction/stdlib.ts
  src/spec/action.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4033 feat(interaction): support brush interaction
  __tests__/unit/interaction/brush.spec.ts
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/interaction-more.md
  src/component/title.ts
  src/component/utils.ts
  src/interaction/action/index.ts
  src/interaction/action/service/elementSelection.ts
  src/interaction/action/service/recordPoint.ts
  src/interaction/action/service/recordRegion.ts
  src/interaction/action/service/recordState.ts
  src/interaction/action/transformer/button.ts
  src/interaction/action/transformer/cursor.ts
  src/interaction/action/transformer/filter.ts
  src/interaction/action/transformer/filterElement.ts
  src/interaction/action/transformer/highlightElement.ts
  src/interaction/action/transformer/mask.ts
  src/interaction/builtin/brush.ts
  src/interaction/builtin/brushHighlight.ts
  src/interaction/builtin/brushVisible.ts
  src/interaction/create.ts
  src/interaction/index.ts
  src/interaction/stdlib.ts
  src/interaction/types.ts
  src/spec/action.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4039 fix(tooltipMarker): 增加 tooltip marker 回调，以和 point 的不同形状保持一致
  src/chart/controller/tooltip.ts
  tests/unit/chart/controller/tooltip-spec.ts
Labels: PR: reviewed-approved, bugfix

#4040 fix(active-region): Fix type error when importing on demand
  src/interaction/action/active-region.ts
Labels: PR: reviewed-approved, bugfix

#4037 feat(interaction): implement draggable and resizable mask
  __tests__/unit/interaction/index.spec.ts
  __tests__/unit/interaction/stdlib.spec.ts
  package.json
  src/interaction/action/index.ts
  src/interaction/action/service/elementSelection.ts
  src/interaction/action/service/recordCurrentPoint.ts
  src/interaction/action/transformer/cursor.ts
  src/interaction/action/transformer/mask.ts
  src/interaction/action/transformer/move.ts
  src/interaction/builtin/brush.ts
  src/interaction/builtin/brushHighlight.ts
  src/interaction/builtin/brushVisible.ts
  src/interaction/builtin/elementActive.ts
  src/interaction/stdlib.ts
  src/renderer/canvas.ts
  src/runtime/types/component.ts
  src/spec/action.ts
Labels: PR: partially-approved

#4043 feat(component): display axis in polar or transpose coordinate by default
  __tests__/unit/runtime/line.spec.ts
  docs/interval.md
  docs/line.md
  src/component/axis.ts
  src/runtime/component.ts
Labels: PR: partially-approved

#3976 feat: add zoom-in zoom-out cursor
  docs/api/advanced/register-interaction.en.md
  docs/api/advanced/register-interaction.zh.md
  docs/api/general/interaction.zh.md
  src/interaction/action/cursor.ts
  tests/unit/interaction/action/cursor-spec.ts
Labels: feature, PR: unreviewed, PR: reviewed-changes-requested

#4045 feat(component): support axis grid
  docs/interval.md
  docs/spatial.md
  docs/view.md
  src/component/axis.ts
  src/composition/matrix.ts
  src/composition/rect.ts
Labels: PR: partially-approved

#4048 feat(md): 更新钉钉群号
  README.en-US.md
  README.md
  docs/manual/contact.en.md
  docs/manual/contact.zh.md
Labels: feature, PR: unreviewed

#4052 feat(interaction): implement activeRegion interaction and add docs
  .genjirc
  __tests__/unit/interaction/action/transformer/button.spec.ts
  __tests__/unit/interaction/action/transformer/mask.spec.ts
  __tests__/unit/interaction/builtin/brush.spec.ts
  __tests__/unit/interaction/builtin/elementHightlight.spec.ts
  __tests__/unit/interaction/builtin/legend.spec.ts
  __tests__/unit/interaction/builtin/tooltip.spec.ts
  __tests__/unit/interaction/helper.ts
  __tests__/unit/interaction/index.spec.ts
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/annotation.md
  docs/interaction-component.md
  docs/interaction-element.md
  docs/normalize.md
  src/component/legendCategory.ts
  src/interaction/action/index.ts
  src/interaction/action/transformer/activeRegion.ts
  src/interaction/action/transformer/button.ts
  src/interaction/builtin/activeRegion.ts
  src/interaction/create.ts
  src/interaction/index.ts
  src/interaction/stdlib.ts
  src/spec/action.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: partially-approved
