Repository antvis/G2, pull requests merged in 2022-02, with the labels that each got.

#3797 fix(charts): 修复 annotations 创建失败
  .github/release.yml
  .github/workflows/conventional-labels.yml
  CHANGELOG.md
  package.json
  src/chart/controller/annotation.ts
  src/core.ts
Labels: PR: unreviewed, bugfix

#3798 chore: github actions 整理
  .github/workflows/ci.yml
  .github/workflows/npm-publish.yml
  .github/workflows/release.yml
Labels: PR: unreviewed, ignore-for-release

#3799 chore: 修改 npm publish 脚本命令
  .github/workflows/npm-publish.yml
  package.json
Labels: PR: unreviewed, ignore-for-release

#3800 Revert "chore: 修改 npm publish 脚本命令"
  .github/workflows/npm-publish.yml
  package.json
Labels: PR: unreviewed

#3801 chore: 修改 npm publish 脚本命令
  .github/workflows/npm-publish.yml
  package.json
Labels: PR: unreviewed, ignore-for-release

#3802 Revert "chore: 修改 npm publish 脚本命令"
  .github/workflows/npm-publish.yml
  package.json
Labels: PR: unreviewed

#3805 fix(interval): tooltip name when interval config `color` without mapping `field`
  CHANGELOG.md
  package.json
  src/core.ts
  src/util/scale.ts
  tests/bugs/interval-tooltip-spec.ts
Labels: PR: unreviewed, bugfix

#3774 fix: update actions/checkout version to avoid vulnerability
  .github/workflows/ci.yml
Labels: PR: reviewed-approved

#3806 fix: 修复 timeCat scale 没有当作 groupScale，导致对应场景的折线图绘制无法正常分组
  CHANGELOG.md
  package.json
  src/core.ts
  src/util/scale.ts
  tests/bugs/timeCat-spec.ts
Labels: PR: reviewed-approved, bugfix

#3809 chore: init dev env
  .github/workflows/build.yml
  .husky/commit-msg
  .husky/pre-commit
  __tests__/index.spec.ts
  __tests__/unit/drawRedRect.spec.ts
  jest.config.js
  package.json
  src/drawRedRect.ts
  src/index.ts
Labels: PR: partially-approved

#3817 feat: 基于新版本注释规范调整 interface 文件代码注释
  src/animate/interface.ts
  src/geometry/label/interface.ts
  src/interface.ts
Labels: feature, PR: unreviewed
