Repository antvis/G2, pull requests merged in 2022-10, with the labels that each got.

#4186 feat: add rect mark
  .genjirc
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/mark/rect.spec.ts
  __tests__/unit/runtime/rect.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/mark-rect.md
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/mark/index.ts
  src/mark/rect.ts
  src/runtime/types/theme.ts
  src/shape/interval/color.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4188 fix: use custom transition instead of morphing in wavein animation
  __tests__/integration/charts/population2015-interval-pie.ts
  src/animation/waveIn.ts
Labels: PR: reviewed-approved

#4192 fix(line): consistent path generator for defined and undefined points
  __tests__/integration/charts/aapl-line-missing-styled.ts
  __tests__/integration/snapshots/aaplLineMissingStyled.png
  src/shape/line/curve.ts
Labels: PR: unreviewed

#4189 fix(node): node.attr method support to assign undefined
  __tests__/unit/api/node.spec.ts
  __tests__/unit/api/props.spec.ts
  src/api/node.ts
  src/api/props.ts
Labels: PR: unreviewed

#4193 feat: add connectNulls and style for area mark
  __tests__/integration/charts/aapl-area-missing-data.ts
  __tests__/integration/charts/aapl-line-missing-connect.ts
  __tests__/integration/charts/aapl-line-missing-styled.ts
  __tests__/integration/snapshots/aaplAreaMissingData.png
  docs/mark-line.md
  src/shape/area/curve.ts
  src/shape/line/curve.ts
  src/shape/utils.ts
Labels: PR: reviewed-approved

#4196 refactor(grid): rename to cell
  .genjirc
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/composition/square.spec.ts
  __tests__/unit/mark/grid.spec.ts
  __tests__/unit/runtime/cell.spec.ts
  __tests__/unit/runtime/label.spec.ts
  __tests__/unit/runtime/theme.spec.ts
  __tests__/unit/runtime/view.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/theme/light.spec.ts
  docs/data-fetch.md
  docs/data.md
  docs/examples.md
  docs/mark-cell.md
  docs/mark-mix.md
  docs/scale.md
  jest.config.js
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/composition/circle.ts
  src/composition/matrix.ts
  src/composition/square.ts
  src/mark/cell.ts
  src/mark/index.ts
  src/runtime/types/theme.ts
  src/shape/interval/color.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4195 feat(line): add plots related to line mark
  __tests__/integration/charts/aapl2-candlestick-chart.ts
  __tests__/integration/charts/cars3-line-parallel-horizontal.ts
  __tests__/integration/charts/cars3-line-parallel-vertical.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/seasonal-weather-area-radial.ts
  __tests__/integration/charts/stocks-area-gradient.ts
  __tests__/integration/charts/temperature1-line-var-color.ts
  __tests__/integration/charts/temperature2-line-gradient-color.ts
  __tests__/integration/charts/temperature2-line-threshold.ts
  __tests__/integration/charts/temperatures3-area-band-gradient.ts
  __tests__/integration/charts/train-line-multi-axes.ts
  __tests__/integration/charts/world-history-interval-multi-tick-count.ts
  __tests__/integration/data/aapl2.csv
  __tests__/integration/data/cars3.csv
  __tests__/integration/data/seasonal-weather.csv
  __tests__/integration/data/temperatures1.csv
  __tests__/integration/data/temperatures2.csv
  __tests__/integration/data/temperatures3.csv
  __tests__/integration/data/train.csv
  __tests__/integration/data/world-history.csv
  __tests__/integration/snapshots/aapl2CandlestickChart.png
  __tests__/integration/snapshots/cars3LineParallelHorizontal.png
  __tests__/integration/snapshots/cars3LineParallelVertical.png
  __tests__/integration/snapshots/seasonalWeatherAreaRadial.png
  __tests__/integration/snapshots/stocksAreaGradient.png
  __tests__/integration/snapshots/temperature1LineVarColor.png
  __tests__/integration/snapshots/temperature2LineGradientColor.png
  __tests__/integration/snapshots/temperature2LineThreshold.png
  __tests__/integration/snapshots/temperatures3AreaBandGradient.png
  __tests__/integration/snapshots/tranLineMultiAxes.png
  __tests__/integration/snapshots/worldHistoryIntervalMultiTickCount.png
  package.json
  src/component/axis.ts
  src/composition/view.ts
  src/runtime/component.ts
  src/runtime/layout.ts
  src/runtime/scale.ts
  src/runtime/transform.ts
  src/runtime/types/common.ts
  src/shape/area/curve.ts
  src/shape/line/curve.ts
  src/shape/utils.ts
  src/spec/geometry.ts
  src/utils/helper.ts
Labels: PR: reviewed-changes-requested

#4198 feat: add area label postion to show label in StackedArea
  __tests__/integration/charts/population-by-state-area-normalize-stacked.ts
  __tests__/integration/snapshots/populationByStateAreaNormalizeStacked.png
  src/composition/circle.ts
  src/interaction/action/service/triggerInfoSelection.ts
  src/shape/area/curve.ts
  src/shape/box/box.ts
  src/shape/label/label.ts
  src/shape/label/position.ts
  src/shape/utils.ts
  src/utils/string.ts
  src/utils/vector.ts
Labels: PR: unreviewed

#4204 perf: init test env
  __tests__/unit/stdlib/index.spec.ts
  scripts/bench/README.md
  scripts/bench/benchmarks/index.ts
  scripts/bench/benchmarks/point-temperatures/d3-g-canvas.ts
  scripts/bench/benchmarks/point-temperatures/d3-g-svg.ts
  scripts/bench/benchmarks/point-temperatures/d3-svg.ts
  scripts/bench/benchmarks/point-temperatures/echarts-canvas.ts
  scripts/bench/benchmarks/point-temperatures/g2-v4-canvas.ts
  scripts/bench/benchmarks/point-temperatures/g2-v5-canvas-api.ts
  scripts/bench/benchmarks/point-temperatures/g2-v5-canvas-spec.ts
  scripts/bench/benchmarks/point-temperatures/index.ts
  scripts/bench/benchmarks/point-temperatures/plot.ts
  scripts/bench/benchmarks/point-temperatures/vega-lite-svg.ts
  scripts/bench/data/temperatures.csv
  scripts/bench/index.html
  scripts/bench/main.ts
  scripts/bench/package.json
  scripts/bench/tsconfig.json
  scripts/bench/vite.config.js
  src/label-transform/dodgeY.ts
  src/label-transform/hideOverlap.ts
  src/label-transform/index.ts
  src/stdlib/index.ts
  vite.config.js
Labels: PR: partially-approved

#4201 docs: add area mark documents
  docs/mark-area.md
Labels: PR: unreviewed

#4207 fix(docs): typos
  docs/manual/concepts/grammar-of-graphics.zh.md
Labels: PR: reviewed-approved, bugfix

#4206 feat(animation): add zoomIn & zoomOut animation
  __tests__/unit/stdlib/index.spec.ts
  docs/animation.md
  docs/mark-connector.md
  src/animation/index.ts
  src/animation/zoomIn.ts
  src/animation/zoomOut.ts
  src/stdlib/index.ts
Labels: PR: reviewed-changes-requested

#4209 feat/plots-composition
  __tests__/integration/charts/anscombe-point-square-row.ts
  __tests__/integration/charts/barley-point-square-col.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/month-interval-circle.ts
  __tests__/integration/charts/month-interval-radial-square.ts
  __tests__/integration/charts/month-interval-square.ts
  __tests__/integration/charts/movies-interval-multiple-measure.ts
  __tests__/integration/charts/penguins-point-matrix.ts
  __tests__/integration/charts/penguins-point-square.ts
  __tests__/integration/charts/seattle-weather-cell-flex.ts
  __tests__/integration/charts/titanic-point-pack-nested.ts
  __tests__/integration/charts/titanic-point-pack-shared-data.ts
  __tests__/integration/charts/titanic-point-pack-shared-size.ts
  __tests__/integration/charts/titanic-point-pack.ts
  __tests__/integration/charts/titanic2-point-pack.ts
  __tests__/integration/charts/weather-line-area-dual-axis.ts
  __tests__/integration/charts/weather-line-matrix-col.ts
  __tests__/integration/data/anscombe.csv
  __tests__/integration/data/barley.csv
  __tests__/integration/data/movies.csv
  __tests__/integration/data/titanic.csv
  __tests__/integration/data/titanic2.csv
  __tests__/integration/data/weather.csv
  __tests__/integration/snapshots/anscombePointSquareRow.png
  __tests__/integration/snapshots/barleyPointSquareCol.png
  __tests__/integration/snapshots/monthIntervalCircle.png
  __tests__/integration/snapshots/monthIntervalRadialSquare.png
  __tests__/integration/snapshots/monthIntervalSquare.png
  __tests__/integration/snapshots/moviesIntervalMultipleMeasure.png
  __tests__/integration/snapshots/penguinsPointMatrix.png
  __tests__/integration/snapshots/penguinsPointSquare.png
  __tests__/integration/snapshots/seattleWeatherCellFlex.png
  __tests__/integration/snapshots/titanic2PointPack.png
  __tests__/integration/snapshots/titanicPointPack.png
  __tests__/integration/snapshots/titanicPointPackNested.png
  __tests__/integration/snapshots/titanicPointPackSharedData.png
  __tests__/integration/snapshots/titanicPointPackSharedSize.png
  __tests__/integration/snapshots/weatherLineAreaDualAxis.png
  __tests__/integration/snapshots/weatherLineMatrixCol.png
  __tests__/unit/adjust/pack.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/theme/light.spec.ts
  jest.config.js
  src/adjust/index.ts
  src/adjust/pack.ts
  src/component/axis.ts
  src/composition/matrix.ts
  src/composition/square.ts
  src/runtime/plot.ts
  src/runtime/scale.ts
  src/runtime/types/options.ts
  src/shape/interval/color.ts
  src/shape/point/color.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/theme/light.ts
  src/transform/index.ts
  src/transform/pack.ts
  src/transform/sort.ts
Labels: PR: unreviewed

#4212 feat(interaction): add elementActive
  __tests__/integration/interactions/alphabet-interval-active.spec.ts
  __tests__/integration/interactions/alphabet-interval-active.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/utils.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshot.spec.ts
  __tests__/unit/api/constant.spec.ts
  package.json
  src/interaction/index.ts
  src/interaction/native/elementActive.ts
  src/runtime/index.ts
  src/runtime/plot.ts
  src/spec/interaction.ts
Labels: PR: reviewed-approved

#4210 feat: chart API
  .eslintrc
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/node.spec.ts
  src/api/chart.ts
  src/api/node.ts
  src/api/props.ts
  src/api/types.ts
  src/runtime/index.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/utils/event.ts
  src/utils/size.ts
Labels: PR: unreviewed

#4216 refactor: rename composition
  __tests__/integration/charts/anscombe-point-facet-rect-row.ts
  __tests__/integration/charts/barley-point-facet-rect-col.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/month-interval-facet-circle.ts
  __tests__/integration/charts/month-interval-facet-rect.ts
  __tests__/integration/charts/month-interval-radial-facet-rect.ts
  __tests__/integration/charts/penguins-point-facet-rect.ts
  __tests__/integration/charts/penguins-point-repeat-matrix.ts
  __tests__/integration/charts/seattle-weather-cell-space-flex.ts
  __tests__/integration/charts/titanic-point-pack-nested.ts
  __tests__/integration/charts/titanic-point-pack-shared-data.ts
  __tests__/integration/charts/titanic-point-pack-shared-size.ts
  __tests__/integration/charts/titanic-point-pack.ts
  __tests__/integration/charts/titanic2-point-pack.ts
  __tests__/integration/charts/weather-line-repeat-matrix-col.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/snapshots/anscombePointFacetRectRow.png
  __tests__/integration/snapshots/barleyPointFacetRectCol.png
  __tests__/integration/snapshots/monthIntervalFacetCircle.png
  __tests__/integration/snapshots/monthIntervalFacetRect.png
  __tests__/integration/snapshots/monthIntervalRadialFacetRect.png
  __tests__/integration/snapshots/penguinsPointFacetRect.png
  __tests__/integration/snapshots/penguinsPointRepeatMatrix.png
  __tests__/integration/snapshots/seattleWeatherCellSpaceFlex.png
  __tests__/integration/snapshots/weatherLineRepeatMatrixCol.png
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/api/composition/circle.ts
  src/api/composition/facetCircle.ts
  src/api/composition/facetRect.ts
  src/api/composition/flex.ts
  src/api/composition/index.ts
  src/api/composition/keyframe.ts
  src/api/composition/layer.ts
  src/api/composition/matrix.ts
  src/api/composition/repeatMatrix.ts
  src/api/composition/spaceFlex.ts
  src/api/composition/spaceLayer.ts
  src/api/composition/square.ts
  src/api/composition/timingKeyframe.ts
  src/composition/facetCircle.ts
  src/composition/facetRect.ts
  src/composition/index.ts
  src/composition/repeatMatrix.ts
  src/composition/spaceFlex.ts
  src/composition/spaceLayer.ts
  src/composition/timingKeyframe.ts
  src/interaction/native/utils.ts
  src/spec/composition.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4214 更新 BizCharts 地址，Viser 已经没人维护了，去掉
  docs/manual/getting-started.zh.md
Labels: PR: reviewed-approved

#4217 feat(layout): add margin
  __tests__/integration/charts/commits-point-grouped-layout.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshots/commitsPointGroupedLayout.png
  src/composition/mark.ts
  src/runtime/constant.ts
  src/runtime/coordinate.ts
  src/runtime/layout.ts
  src/runtime/plot.ts
  src/runtime/types/common.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/spec/geometry.ts
  src/utils/helper.ts
Labels: PR: reviewed-approved

#4218 feat(runtime): style supports callback
  __tests__/integration/charts/alphabet-interval-data-driven-styled.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/unemployment-area-stacked-data-driven-styled.ts
  __tests__/integration/snapshots/alphabetIntervalDataDrivenStyled.png
  __tests__/integration/snapshots/unemploymentAreaStackedDataDrivenStyled.png
  src/animation/zoomIn.ts
  src/animation/zoomOut.ts
  src/runtime/plot.ts
Labels: PR: partially-approved

#4226 feat(interaction): add fisheye and chartIndex
  __tests__/integration/data/gdp2.csv
  __tests__/integration/data/indices.csv
  __tests__/integration/interactions/alphabet-interval-active-inactive.ts
  __tests__/integration/interactions/gdp2-point-chart-fisheye.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/indices-line-chart-index-series.ts
  __tests__/integration/interactions/utils.ts
  __tests__/integration/snapshots/alphabetIntervalTransposed.png
  __tests__/integration/snapshots/gdp2-point-fisheye/step0.png
  __tests__/integration/snapshots/indices-line-chart-index-series/step0.png
  __tests__/integration/snapshots/marketIntervalMarimekko.png
  __tests__/integration/snapshots/populationByStateAreaNormalizeStacked.png
  __tests__/integration/snapshots/stocksLineAggregateLabel.png
  __tests__/unit/stdlib/index.spec.ts
  src/component/axis.ts
  src/interaction/index.ts
  src/interaction/native/chartIndex.ts
  src/interaction/native/fisheye.ts
  src/interaction/native/utils.ts
  src/runtime/plot.ts
  src/runtime/types/common.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
  src/transform/normalizeY.ts
Labels: PR: partially-approved

#4229 feat(runtime): add renderToMountedElement to render the chart into the g element
  __tests__/unit/renderToMountedElement.spec.ts
  package.json
  src/runtime/index.ts
  src/runtime/render.ts
  src/runtime/types/options.ts
Labels: PR: unreviewed
