Repository antvis/G2, pull requests merged in 2022-11, with the labels that each got.

#4231 chore(runtime): remove useless export
  src/runtime/render.ts
Labels: PR: reviewed-approved

#4236 feat: add area demos
  site/examples/single-view/area/demo/area-difference.ts
  site/examples/single-view/area/demo/area.ts
  site/examples/single-view/area/demo/cascade-area.ts
  site/examples/single-view/area/demo/label.ts
  site/examples/single-view/area/demo/meta.json
  site/examples/single-view/area/demo/missing-data-area.ts
  site/examples/single-view/area/demo/orderly-area.ts
  site/examples/single-view/area/demo/percentage-area.ts
  site/examples/single-view/area/demo/stacked-area.ts
  site/examples/single-view/area/demo/step-area.ts
  site/examples/single-view/area/demo/streamgraph.ts
Labels: PR: partially-approved

#4238 feat: add text demo
  site/examples/single-view/text/demo/meta.json
  site/examples/single-view/text/demo/paragraph.ts
  site/examples/single-view/text/demo/poetry.ts
  site/examples/single-view/text/demo/train.ts
Labels: PR: partially-approved

#4234 feat(mark): add sankey
  .gitignore
  __tests__/integration/charts/energy-sankey-custom.ts
  __tests__/integration/charts/energy-sankey-defaults.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/energy.csv
  __tests__/integration/snapshots/energySankeyCustom.png
  __tests__/integration/snapshots/energySankeyDefaults.png
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/mark/helper.ts
  __tests__/unit/mark/text.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/api/mark/mark.ts
  src/mark/index.ts
  src/mark/sankey.ts
  src/mark/text.ts
  src/runtime/plot.ts
  src/runtime/transform.ts
  src/runtime/types/mark.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/maybeTuple.ts
Labels: PR: partially-approved

#4240 docs: add boxplot demo
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/sepal-box-grouped-box.ts
  __tests__/integration/charts/sepal-box-polar-box.ts
  __tests__/integration/charts/sepal-box-simple-box.ts
  __tests__/integration/data/sepal.js
  __tests__/integration/snapshots/sepalBoxGroupedBox.png
  __tests__/integration/snapshots/sepalBoxPolarBox.png
  __tests__/integration/snapshots/sepalBoxSimpleBox.png
  site/examples/single-view/box/demo/box.ts
  site/examples/single-view/box/demo/grouped-box.ts
  site/examples/single-view/box/demo/meta.json
  site/examples/single-view/box/demo/polar-box.ts
Labels: PR: unreviewed

#4241 feat(mark): add path, geoView, choropleth
  __tests__/integration/charts/airports-point-choropleth.ts
  __tests__/integration/charts/hale-choropleth-world.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/population2015-interval-pie.ts
  __tests__/integration/charts/unemployment-choropleth.ts
  __tests__/integration/data/airports.csv
  __tests__/integration/data/countries-50m.json
  __tests__/integration/data/hale.csv
  __tests__/integration/data/unemployment.tsv
  __tests__/integration/data/us-10m.json
  __tests__/integration/snapshots/airportsPointChoropleth.png
  __tests__/integration/snapshots/haleChoroplethWorld.png
  __tests__/integration/snapshots/unemploymentChoropleth.png
  __tests__/unit/stdlib/index.spec.ts
  package.json
  src/geo/choropleth.ts
  src/geo/d3-projection.ts
  src/geo/geoView.ts
  src/geo/index.ts
  src/mark/index.ts
  src/mark/path.ts
  src/shape/index.ts
  src/shape/path/path.ts
  src/spec/composition.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/utils/selection.ts
Labels: PR: unreviewed

#4239 refactor(text): simplify logic of text shape
  __tests__/integration/charts/blockchain-line-annotation.ts
  __tests__/integration/charts/blockchain-line-badge-annotation.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/paragraph-text-vis.ts
  __tests__/integration/data/blockchain.json
  __tests__/integration/snapshots/blockChainLineAnnotation.png
  __tests__/integration/snapshots/blockChainLineBadgeAnnotation.png
  __tests__/unit/runtime/text.spec.ts
  __tests__/unit/shape/text/badge.spec.ts
  __tests__/unit/shape/text/text.spec.ts
  docs/mark-text.md
  site/examples/single-view/text/demo/paragraph.ts
  src/runtime/types/common.ts
  src/runtime/types/theme.ts
  src/shape/text/badge.ts
  src/shape/text/text.ts
  src/theme/dark.ts
  src/theme/light.ts
  src/transform/maybeTuple.ts
  src/transform/maybeTupleX.ts
  src/transform/maybeTupleY.ts
  src/transform/utils/helper.ts
Labels: PR: partially-approved

#4244 docs: mark vector & image
  __tests__/integration/charts/browser-image-trending.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/wind-vector-wind.ts
  __tests__/integration/data/browser.js
  __tests__/integration/data/wind.csv
  __tests__/integration/snapshots/browserImageTrending.png
  __tests__/integration/snapshots/windVectorWind.png
  docs/mark-vector.md
  site/examples/single-view/box/index.en.md
  site/examples/single-view/box/index.zh.md
  site/examples/single-view/hierarchy/index.en.md
  site/examples/single-view/hierarchy/index.zh.md
  site/examples/single-view/image/demo/contributor.ts
  site/examples/single-view/image/demo/icon.ts
  site/examples/single-view/image/demo/logo.ts
  site/examples/single-view/image/demo/meta.json
  site/examples/single-view/image/index.en.md
  site/examples/single-view/image/index.zh.md
  site/examples/single-view/link/index.en.md
  site/examples/single-view/link/index.zh.md
  site/examples/single-view/map/index.en.md
  site/examples/single-view/map/index.zh.md
  site/examples/single-view/network/index.en.md
  site/examples/single-view/network/index.zh.md
  site/examples/single-view/radial/index.en.md
  site/examples/single-view/radial/index.zh.md
  site/examples/single-view/vector/demo/meta.json
  site/examples/single-view/vector/demo/poisson.ts
  site/examples/single-view/vector/demo/wind.ts
  site/examples/single-view/vector/index.en.md
  site/examples/single-view/vector/index.zh.md
  src/shape/utils.ts
  src/shape/vector/vector.ts
Labels: PR: reviewed-approved

#4246 docs: add polygon demo, treemap and voronoi
  site/.dumi/global.ts
  site/examples/single-view/polygon/demo/meta.json
  site/examples/single-view/polygon/demo/treemap.ts
  site/examples/single-view/polygon/demo/voronoi.ts
  site/package.json
Labels: PR: reviewed-approved

#4251 docs(demos): add interval
  site/examples/single-view/interval/demo/bar-aggregated-normalized-stacked.ts
  site/examples/single-view/interval/demo/bar-aggregated-stacked.ts
  site/examples/single-view/interval/demo/bar-aggregated.ts
  site/examples/single-view/interval/demo/bar-diverging.ts
  site/examples/single-view/interval/demo/bar-dodged.ts
  site/examples/single-view/interval/demo/bar-dual-axes.ts
  site/examples/single-view/interval/demo/bar-fixed-cornered.ts
  site/examples/single-view/interval/demo/bar-flex.ts
  site/examples/single-view/interval/demo/bar-layered.ts
  site/examples/single-view/interval/demo/bar-marimekko.ts
  site/examples/single-view/interval/demo/bar-normalized-stacked.ts
  site/examples/single-view/interval/demo/bar-range.ts
  site/examples/single-view/interval/demo/bar-stacked-diverging.ts
  site/examples/single-view/interval/demo/bar-stacked-horizontal.ts
  site/examples/single-view/interval/demo/bar-stacked.ts
  site/examples/single-view/interval/demo/bar-var-width.ts
  site/examples/single-view/interval/demo/bar.ts
  site/examples/single-view/interval/demo/basic.ts
  site/examples/single-view/interval/demo/column.ts
  site/examples/single-view/interval/demo/meta.json
  site/examples/single-view/radial/demo/bar-radial.ts
  site/examples/single-view/radial/demo/bar-stacked-radial.ts
  site/examples/single-view/radial/demo/donut.ts
  site/examples/single-view/radial/demo/meta.json
  site/examples/single-view/radial/demo/pie.ts
  site/examples/single-view/radial/demo/rose.ts
  src/api/types.ts
Labels: PR: reviewed-approved

#4242 feat(mark): add treemap mark
  __tests__/integration/charts/flare-treemap-custom.ts
  __tests__/integration/charts/flare-treemap-default.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/flare.csv
  __tests__/integration/data/philosophy.js
  __tests__/integration/snapshots/agesIntervalRadialStacked.png
  __tests__/integration/snapshots/agesIntervalRadialStackedSorted.png
  __tests__/integration/snapshots/airportsPointChoropleth.png
  __tests__/integration/snapshots/countries50mProjectionComparison.png
  __tests__/integration/snapshots/countries50mWorldMap.png
  __tests__/integration/snapshots/flarePointCirclePack.png
  __tests__/integration/snapshots/flareTreemapCustom.png
  __tests__/integration/snapshots/flareTreemapDefault.png
  __tests__/integration/snapshots/gdpIntervalFlex.png
  __tests__/integration/snapshots/gdpIntervalVarSize.png
  __tests__/integration/snapshots/haleChoroplethWorld.png
  __tests__/integration/snapshots/penguinsPointLink.png
  __tests__/integration/snapshots/populationIntervalRose.png
  __tests__/integration/snapshots/question8IntervalRadialGradientColor.png
  __tests__/integration/snapshots/seattleWeatherPoint1d.png
  __tests__/integration/snapshots/unemploymentChoropleth.png
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/api/mark/mark.ts
  src/mark/index.ts
  src/mark/sankey.ts
  src/mark/treemap.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/utils/size.ts
Labels: PR: unreviewed

#4252 docs(demo): add line and point
  __tests__/unit/api/mark.spec.ts
  site/.dumi/global.ts
  site/examples/scenario/annotation/demo/meta.json
  site/examples/scenario/annotation/demo/point-line.ts
  site/examples/scenario/annotation/demo/point-point.ts
  site/examples/single-view/area/demo/area-band.ts
  site/examples/single-view/area/demo/area-gradient.ts
  site/examples/single-view/area/demo/meta.json
  site/examples/single-view/box/demo/meta.json
  site/examples/single-view/line/demo/line-aggregated-label.ts
  site/examples/single-view/line/demo/line-basic.ts
  site/examples/single-view/line/demo/line-candle-stick.ts
  site/examples/single-view/line/demo/line-connect-nulls.ts
  site/examples/single-view/line/demo/line-dual-axes.ts
  site/examples/single-view/line/demo/line-gradient-encoding.ts
  site/examples/single-view/line/demo/line-normalized.ts
  site/examples/single-view/line/demo/line-parallel-horizontal.ts
  site/examples/single-view/line/demo/line-parallel-vertical.ts
  site/examples/single-view/line/demo/line-series.ts
  site/examples/single-view/line/demo/line-slope.ts
  site/examples/single-view/line/demo/line-threshold.ts
  site/examples/single-view/line/demo/line-variable-color.ts
  site/examples/single-view/line/demo/meta.json
  site/examples/single-view/point/demo/meta.json
  site/examples/single-view/point/demo/point-aggregated.ts
  site/examples/single-view/point/demo/point-basic.ts
  site/examples/single-view/point/demo/point-bubble.ts
  site/examples/single-view/point/demo/point-dot.ts
  site/examples/single-view/point/demo/point-jitter.ts
  site/examples/single-view/point/demo/point-label.ts
  site/examples/single-view/point/demo/point-log.ts
  site/examples/single-view/point/demo/point-one-dimension.ts
  site/examples/single-view/point/demo/point-sequential.ts
  site/examples/single-view/point/demo/point-shape.ts
  site/examples/single-view/point/demo/point-stacked.ts
  site/examples/single-view/point/demo/point-strip.ts
  site/examples/single-view/radial/demo/area-radial.ts
  site/examples/single-view/radial/demo/meta.json
  site/examples/single-view/radial/demo/point-jitter-radial.ts
  site/examples/single-view/radial/demo/polar-box.ts
  site/package.json
  src/api/chart.ts
  src/api/composition/view.ts
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/shape/label/label.ts
  src/spec/composition.ts
  src/spec/geometry.ts
Labels: PR: reviewed-approved

#4253 docs(demo): add cell
  site/examples/single-view/box/index.en.md
  site/examples/single-view/box/index.zh.md
  site/examples/single-view/cell/demo/cell-aggregated.ts
  site/examples/single-view/cell/demo/cell-basic.ts
  site/examples/single-view/cell/demo/cell-heatmap.ts
  site/examples/single-view/cell/demo/cell-quantile.ts
  site/examples/single-view/cell/demo/cell-quantize.ts
  site/examples/single-view/cell/demo/cell-threshold.ts
  site/examples/single-view/cell/demo/meta.json
  site/examples/single-view/cell/index.en.md
  site/examples/single-view/cell/index.zh.md
  site/examples/single-view/hierarchy/index.en.md
  site/examples/single-view/hierarchy/index.zh.md
  site/examples/single-view/image/index.en.md
  site/examples/single-view/image/index.zh.md
  site/examples/single-view/link/index.en.md
  site/examples/single-view/link/index.zh.md
  site/examples/single-view/map/index.en.md
  site/examples/single-view/map/index.zh.md
  site/examples/single-view/network/index.en.md
  site/examples/single-view/network/index.zh.md
  site/examples/single-view/radial/index.en.md
  site/examples/single-view/radial/index.zh.md
  site/examples/single-view/text/index.en.md
  site/examples/single-view/text/index.zh.md
  site/examples/single-view/vector/index.en.md
  site/examples/single-view/vector/index.zh.md
  src/runtime/scale.ts
Labels: PR: reviewed-approved

#4249 feat(mark): add circle pack
  __tests__/integration/charts/flare-point-circle-pack-custom.ts
  __tests__/integration/charts/flare-point-circle-pack-default.ts
  __tests__/integration/charts/flare-point-circle-pack.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/flarePointCirclePack.png
  __tests__/integration/snapshots/flarePointCirclePackCustom.png
  __tests__/integration/snapshots/flarePointCirclePackDefault.png
  __tests__/unit/stdlib/index.spec.ts
  src/mark/index.ts
  src/mark/pack.ts
  src/mark/treemap.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/utils/size.ts
Labels: PR: reviewed-approved

#4255 docs: add Link demos
  __tests__/integration/charts/income-link-annotation.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/metros-link-trending.ts
  __tests__/integration/data/income.js
  __tests__/integration/data/metros.json
  __tests__/integration/snapshots/incomeLinkAnnotation.png
  __tests__/integration/snapshots/metrosLinkTrending.png
  site/.dumirc.ts
  site/examples/single-view/link/demo/link-annotation.ts
  site/examples/single-view/link/demo/link.ts
  site/examples/single-view/link/demo/meta.json
  src/shape/link/link.ts
Labels: PR: reviewed-approved

#4256 docs(animation): add simple demo of animation effects
  site/examples/others/animation/demo/fade.ts
  site/examples/others/animation/demo/meta.json
  site/examples/others/animation/demo/scaleX.ts
  site/examples/others/animation/demo/scaleY.ts
  site/examples/others/animation/demo/waveIn.ts
  site/examples/others/animation/demo/zoomIn.ts
  site/examples/single-view/radial/demo/bar-cornered-radial.ts
  site/examples/single-view/radial/demo/meta.json
  src/spec/animate.ts
Labels: PR: partially-approved

#4257 docs(demo): add composition
  __tests__/integration/charts/alphabet-interval-space-layer.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/alphabetIntervalSpaceLayer.png
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  package.json
  site/examples/multi-view/.gitkeep
  site/examples/multi-view/facet/demo/circle.ts
  site/examples/multi-view/facet/demo/meta.json
  site/examples/multi-view/facet/demo/rect-bar.ts
  site/examples/multi-view/facet/demo/rect-col.ts
  site/examples/multi-view/facet/demo/rect-pie.ts
  site/examples/multi-view/facet/demo/rect-row.ts
  site/examples/multi-view/facet/demo/rect.ts
  site/examples/multi-view/facet/index.en.md
  site/examples/multi-view/facet/index.zh.md
  site/examples/multi-view/repeat/demo/matrix-col.ts
  site/examples/multi-view/repeat/demo/matrix.ts
  site/examples/multi-view/repeat/demo/meta.json
  site/examples/multi-view/repeat/index.en.md
  site/examples/multi-view/repeat/index.zh.md
  site/examples/multi-view/space/demo/meta.json
  site/examples/multi-view/space/demo/space-flex.ts
  site/examples/multi-view/space/demo/space-layer.ts
  site/examples/multi-view/space/index.en.md
  site/examples/multi-view/space/index.zh.md
  site/examples/scenario/unit/demo/2d.ts
  site/examples/scenario/unit/demo/basic.ts
  site/examples/scenario/unit/demo/meta.json
  site/examples/scenario/unit/demo/nested.ts
  site/examples/scenario/unit/demo/share-data.ts
  site/examples/scenario/unit/demo/share-size.ts
  site/examples/single-view/dual/demo/dual-aggregated-line-area.ts
  site/examples/single-view/dual/demo/meta.json
  site/examples/single-view/dual/index.en.md
  site/examples/single-view/dual/index.zh.md
  site/examples/single-view/interval/demo/bar-multi-measure.ts
  site/examples/single-view/interval/demo/bar-stacked-normalized-1d.ts
  site/examples/single-view/interval/demo/meta.json
  src/api/chart.ts
  src/api/composition/facetRect.ts
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/runtime/scale.ts
  src/spec/composition.ts
Labels: PR: reviewed-approved

#4260 feat(transform): add bin, binX
  __tests__/integration/charts/athletes-rect-bin.ts
  __tests__/integration/charts/athletes-rect-binx.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/movies-point-bin.ts
  __tests__/integration/charts/movies-rect-bin.ts
  __tests__/integration/charts/people-point-stacked.ts
  __tests__/integration/charts/unemployment2-rect-binx.ts
  __tests__/integration/data/athletes.csv
  __tests__/integration/data/unemployment2.csv
  __tests__/integration/snapshots/athletesRectBin.png
  __tests__/integration/snapshots/athletesRectBinX.png
  __tests__/integration/snapshots/moviesPointBin.png
  __tests__/integration/snapshots/moviesRectBin.png
  __tests__/integration/snapshots/unemployment2RectBinX.png
  __tests__/unit/mark/area.spec.ts
  __tests__/unit/mark/box.spec.ts
  __tests__/unit/mark/cell.spec.ts
  __tests__/unit/mark/connector.spec.ts
  __tests__/unit/mark/image.spec.ts
  __tests__/unit/mark/interval.spec.ts
  __tests__/unit/mark/line.spec.ts
  __tests__/unit/mark/lineX.spec.ts
  __tests__/unit/mark/lineY.spec.ts
  __tests__/unit/mark/link.spec.ts
  __tests__/unit/mark/point.spec.ts
  __tests__/unit/mark/polygon.spec.ts
  __tests__/unit/mark/range.spec.ts
  __tests__/unit/mark/rangeX.spec.ts
  __tests__/unit/mark/rangeY.spec.ts
  __tests__/unit/mark/rect.spec.ts
  __tests__/unit/mark/text.spec.ts
  __tests__/unit/mark/vector.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/examples/single-view/point/demo/point-stacked.ts
  src/mark/point.ts
  src/mark/utils.ts
  src/runtime/scale.ts
  src/shape/interval/color.ts
  src/shape/point/color.ts
  src/shape/utils.ts
  src/spec/geometry.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/bin.ts
  src/transform/binX.ts
  src/transform/group.ts
  src/transform/groupColor.ts
  src/transform/groupN.ts
  src/transform/groupX.ts
  src/transform/groupY.ts
  src/transform/index.ts
  src/transform/stackY.ts
  src/transform/utils/order.ts
Labels: PR: reviewed-approved

#4261 feat: refactor connector shape & add customize waterfall
  __tests__/integration/charts/acme-crop-income-interval-connector.ts
  __tests__/integration/charts/income-statement-by-region-interval-custom.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/acmeCropIncome.js
  __tests__/integration/data/incomeStatementByRegion.js
  __tests__/integration/snapshots/acmeCropIncomeIntervalConnector.png
  __tests__/integration/snapshots/incomeStatementByRegionIntervalCustom.png
  __tests__/unit/shape/connector/connector.spec.ts
  site/examples/single-view/interval/demo/acme-crop-income-statement.ts
  site/examples/single-view/interval/demo/meta.json
  site/examples/single-view/interval/demo/revenue-flow-waterfall.ts
  src/shape/connector/connector.ts
  src/theme/light.ts
Labels: PR: reviewed-changes-requested

#4264 feat(mark): add box plot
  __tests__/integration/charts/flare-point-circle-pack-custom.ts
  __tests__/integration/charts/flare-point-circle-pack-default.ts
  __tests__/integration/charts/flare-treemap-custom.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/morley-box-1d.ts
  __tests__/integration/charts/morley-box-extend.ts
  __tests__/integration/charts/morley-box.ts
  __tests__/integration/charts/penguins-boxplot-grouped-extent.ts
  __tests__/integration/charts/penguins-boxplot-grouped-transpose.ts
  __tests__/integration/charts/penguins-boxplot-grouped.ts
  __tests__/integration/charts/sepal-box-grouped-box.ts
  __tests__/integration/charts/sepal-box-polar-box.ts
  __tests__/integration/charts/sepal-box-simple-box.ts
  __tests__/integration/data/morley.csv
  __tests__/integration/snapshots/morleyBox.png
  __tests__/integration/snapshots/morleyBox1D.png
  __tests__/integration/snapshots/morleyBoxExtend.png
  __tests__/integration/snapshots/penguinsBoxPlotGrouped.png
  __tests__/integration/snapshots/penguinsBoxPlotGroupedExtent.png
  __tests__/integration/snapshots/penguinsBoxPlotGroupedTranspose.png
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/mark/box.spec.ts
  __tests__/unit/mark/point.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  package.json
  site/examples/single-view/interval/demo/acme-crop-income-statement.ts
  site/examples/single-view/interval/demo/revenue-flow-waterfall.ts
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/mark/box.ts
  src/mark/boxplot.ts
  src/mark/index.ts
  src/mark/pack.ts
  src/mark/point.ts
  src/mark/sankey.ts
  src/mark/treemap.ts
  src/mark/utils.ts
  src/runtime/plot.ts
  src/shape/box/box.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
  src/theme/light.ts
  src/transform/groupX.ts
  src/transform/groupY.ts
Labels: PR: unreviewed

#4266 docs: add dual-axis chart demo
  site/examples/single-view/dual/demo/line-bar.ts
  site/examples/single-view/dual/demo/meta.json
  site/examples/single-view/dual/demo/multi-line.ts
  site/examples/single-view/dual/index.zh.md
Labels: PR: reviewed-approved

#4268 feat(animation): add pathIn animation for line mark
  __tests__/unit/stdlib/index.spec.ts
  site/examples/others/animation/demo/meta.json
  site/examples/others/animation/demo/path-in.ts
  site/examples/others/animation/demo/scale-x.ts
  site/examples/others/animation/demo/scale-y.ts
  site/examples/others/animation/demo/wave-in.ts
  site/examples/others/animation/demo/zoom-in.ts
  site/examples/scenario/annotation/demo/meta.json
  site/examples/scenario/annotation/demo/quadrant-scatter.ts
  site/examples/single-view/area/demo/meta.json
  site/examples/single-view/area/demo/range-spline-area.ts
  site/examples/single-view/radial/demo/apple-activity.ts
  src/animation/index.ts
  src/animation/pathIn.ts
  src/spec/animate.ts
  src/stdlib/index.ts
  src/utils/size.ts
Labels: PR: reviewed-approved

#4267 docs: add text search demo
  site/.dumi/global.ts
  site/examples/others/plugins/demo/meta.json
  site/examples/others/plugins/demo/text-search.ts
  site/examples/others/plugins/index.en.md
  site/examples/others/plugins/index.zh.md
  site/package.json
Labels: PR: partially-approved

#4272 chore(plot): remove console.log
  src/runtime/plot.ts
Labels: PR: unreviewed

#4273 chore: init test env for animation
  __tests__/integration/animations/alphabet-interval-scale-in-y.ts
  __tests__/integration/animations/index.ts
  __tests__/integration/animations/people-interval-split-merge.ts
  __tests__/integration/data/people.json
  __tests__/integration/main.ts
  __tests__/integration/snapshot-animation.spec.ts
  __tests__/integration/snapshots/alphabet-interval-scale-in-y/interval0-0.png
  __tests__/integration/snapshots/alphabet-interval-scale-in-y/interval0-1.png
  __tests__/integration/snapshots/alphabet-interval-scale-in-y/interval0-2.png
  __tests__/integration/snapshots/people-interval-split-merge/interval1-0.png
  __tests__/integration/snapshots/people-interval-split-merge/interval1-1.png
  __tests__/integration/snapshots/people-interval-split-merge/interval2-0.png
  __tests__/integration/snapshots/people-interval-split-merge/interval2-1.png
  __tests__/integration/snapshots/people-interval-split-merge/interval2-2.png
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/types/options.ts
  src/utils/selection.ts
Labels: PR: partially-approved

#4265 docs(rough): add 2 sketchy-styled examples
  site/.dumi/global.ts
  site/examples/others/theme/demo/meta.json
  site/examples/others/theme/demo/rough-interval.ts
  site/examples/others/theme/demo/rough-point.ts
  site/package.json
Labels: PR: partially-approved

#4276 docs(chore): add sketchy radial & line chart
  site/examples/others/theme/demo/meta.json
  site/examples/others/theme/demo/rough-line.ts
  site/examples/others/theme/demo/rough-radial.ts
Labels: PR: reviewed-approved

#4262 docs(demo): add lottie #4221
  site/.dumi/global.ts
  site/examples/others/animation/demo/lottie.ts
  site/examples/others/animation/demo/meta.json
  site/package.json
Labels: PR: unreviewed

#4277 docs: demo of annotation
  site/examples/scenario/annotation/demo/line-badge.ts
  site/examples/scenario/annotation/demo/line-text.ts
  site/examples/scenario/annotation/demo/meta.json
  site/examples/single-view/area/demo/range-spline-area.ts
  site/examples/single-view/radial/demo/bar-radial.ts
  site/examples/single-view/radial/demo/donut.ts
  site/examples/single-view/radial/demo/pie.ts
Labels: PR: reviewed-approved

#4274 feat: add forceGraph mark
  __tests__/integration/charts/energy-sankey-defaults.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/miserable-force-custom.ts
  __tests__/integration/charts/miserable-force-default.ts
  __tests__/integration/data/miserable.json
  __tests__/integration/data/miserableDisjoint.json
  __tests__/integration/snapshots/miserableForceCustom.png
  __tests__/integration/snapshots/miserableForceDefault.png
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  package.json
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/mark/forceGraph.ts
  src/mark/index.ts
  src/mark/sankey.ts
  src/mark/utils.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4284 docs: add overview document
  site/docs/api/overview.zh.md
Labels: PR: partially-approved

#4286 docs: add vector api
  site/docs/api/common/style.en.md
  site/docs/api/common/style.zh.md
  site/docs/api/mark/interval.en.md
  site/docs/api/mark/interval.zh.md
  site/docs/api/mark/vector.en.md
  site/docs/api/mark/vector.zh.md
  site/docs/api/overview.zh.md
  site/examples/general/vector/demo/meta.json
  site/examples/general/vector/demo/wind.ts
Labels: PR: unreviewed

#4288 docs: add interval api
  site/docs/api/mark/image.zh.md
  site/docs/api/mark/interval.zh.md
  site/docs/api/mark/link.zh.md
  site/docs/api/mark/text.zh.md
  site/docs/api/mark/vector.zh.md
  site/docs/api/overview.zh.md
Labels: PR: unreviewed

#4281 feat(text): adjust text shape and label
  __tests__/integration/charts/population-interval-rose-label.ts
  __tests__/integration/charts/population-interval-rose-surround-label.ts
  __tests__/integration/charts/population2015-interval-pie-label.ts
  __tests__/integration/charts/population2015-interval-spider-label.ts
  __tests__/integration/snapshots/githubStarIntervalRadialLabel.png
  __tests__/integration/snapshots/population2015IntervalPieLabel.png
  __tests__/integration/snapshots/population2015IntervalSpiderLabel.png
  __tests__/integration/snapshots/populationIntervalRoseLabel.png
  __tests__/integration/snapshots/populationIntervalRoseSurroundLabel.png
  __tests__/unit/shape/text/text.spec.ts
  site/docs/api/label/overview.zh.md
  site/examples/general/interval/demo/revenue-flow-waterfall.ts
  site/examples/general/radial/demo/meta.json
  site/examples/general/radial/demo/rose-label.ts
  site/examples/general/radial/demo/spider-label.ts
  src/label-transform/spider.ts
  src/label-transform/surround.ts
  src/shape/label/label.ts
  src/shape/label/position.ts
  src/shape/text/advance.ts
  src/shape/text/text.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: partially-approved

#4289 docs(plugin): sketchy rendering & lottie
  site/docs/api/plugin/lottie.en.md
  site/docs/api/plugin/lottie.zh.md
  site/docs/api/plugin/rough.en.md
  site/docs/api/plugin/rough.zh.md
Labels: PR: reviewed-approved

#4290 docs: add 5 mark api
  __tests__/unit/mark/point.spec.ts
  __tests__/unit/runtime/point.spec.ts
  site/docs/api/mark/area.en.md
  site/docs/api/mark/area.zh.md
  site/docs/api/mark/cell.en.md
  site/docs/api/mark/cell.zh.md
  site/docs/api/mark/line.en.md
  site/docs/api/mark/line.zh.md
  site/docs/api/mark/point.en.md
  site/docs/api/mark/point.zh.md
  site/docs/api/mark/rect.en.md
  site/docs/api/mark/rect.zh.md
  site/docs/api/overview.zh.md
  site/examples/general/area/demo/area.ts
  src/mark/point.ts
Labels: PR: unreviewed

#4291 fix(runtime): independent option
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/weather-line-multi-axes.ts
  __tests__/integration/data/weather.js
  __tests__/integration/snapshots/weatherLineMultiAxes.png
  src/runtime/mark.ts
Labels: PR: reviewed-approved

#4293 feat: add wordCloud mark
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/philosophy-wordCloud-custom.ts
  __tests__/integration/charts/philosophy-wordCloud-default.ts
  __tests__/integration/charts/philosophy-wordCloud-image.ts
  __tests__/integration/data/philosophyWord.json
  __tests__/integration/data/wordCloud.png
  __tests__/integration/snapshot.spec.ts
  __tests__/integration/snapshots/flareTreeCustom.png
  __tests__/integration/snapshots/flareTreeDefault.png
  __tests__/integration/snapshots/philosophyWordCloudCustom.png
  __tests__/integration/snapshots/philosophyWordCloudDefault.png
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/label-transform/surround.ts
  src/mark/index.ts
  src/mark/wordCloud.ts
  src/runtime/plot.ts
  src/runtime/types/component.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4292 feat(theme): add light and dark theme token
  __tests__/integration/snapshots/blockChainLineAnnotation.png
  __tests__/integration/snapshots/blockChainLineBadgeAnnotation.png
  __tests__/integration/snapshots/energySankeyCustom.png
  __tests__/integration/snapshots/incomeStatementByRegionIntervalCustom.png
  __tests__/integration/snapshots/londonTubeLineGeo.png
  __tests__/integration/snapshots/paragraphTextVis.png
  __tests__/integration/snapshots/polio-point-stack-enter/interval0-3.png
  __tests__/integration/snapshots/population2015IntervalDonutTextAnnotation.png
  site/examples/theme/theme/demo/dark.ts
  site/examples/theme/theme/demo/default-color.ts
  site/examples/theme/theme/demo/meta.json
  site/examples/theme/theme/demo/palette.ts
  src/runtime/plot.ts
  src/runtime/types/theme.ts
  src/shape/utils.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: partially-approved

#4295 feat(interval): support stack corner
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/stateages-interval-stacked-cornered-all.ts
  __tests__/integration/charts/stateages-interval-stacked-cornered.ts
  __tests__/integration/snapshot.spec.ts
  __tests__/integration/snapshots/philosophyWordCloudCustom.png
  __tests__/integration/snapshots/philosophyWordCloudDefault.png
  __tests__/integration/snapshots/stateAgesIntervalStackedCornered.png
  __tests__/integration/snapshots/stateAgesIntervalStackedCorneredAll.png
  site/docs/api/mark/interval.zh.md
  src/runtime/plot.ts
  src/shape/interval/color.ts
  src/transform/stackY.ts
Labels: PR: unreviewed

#4297 feat(site): cover and scrollable
  site/.dumi/global.ts
  site/.dumi/style.css
Labels: PR: reviewed-approved

#4298 docs: add hierarchy&network&wordCloud demo
  __tests__/integration/charts/energy-sankey-custom.ts
  site/.dumi/global.ts
  site/examples/general/text/demo/meta.json
  site/examples/general/text/demo/wordCloud-mask.ts
  site/examples/general/text/demo/wordCloud.ts
  site/examples/graph/hierarchy/demo/circle-packing.ts
  site/examples/graph/hierarchy/demo/meta.json
  site/examples/graph/hierarchy/demo/sankey.ts
  site/examples/graph/hierarchy/demo/tree.ts
  site/examples/graph/hierarchy/demo/treemap.ts
  site/examples/graph/network/demo/forceGraph-disjoint.ts
  site/examples/graph/network/demo/forceGraph.ts
  site/examples/graph/network/demo/meta.json
  site/package.json
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/data/fetch.ts
  src/mark/tree.ts
  src/spec/geometry.ts
Labels: PR: reviewed-approved

#4303 docs: add pattern style demo
  site/examples/theme/pattern/demo/custom-pattern.ts
  site/examples/theme/pattern/demo/line-pattern.ts
  site/examples/theme/pattern/demo/meta.json
  site/examples/theme/pattern/index.en.md
  site/examples/theme/pattern/index.zh.md
Labels: PR: unreviewed

#4296 docs: add composition api
  site/docs/api/composition/facetCircle.en.md
  site/docs/api/composition/facetCircle.zh.md
  site/docs/api/composition/facetRect.en.md
  site/docs/api/composition/facetRect.zh.md
  site/docs/api/composition/repeatMatrix.en.md
  site/docs/api/composition/repeatMatrix.zh.md
  site/docs/api/composition/space-layer.en.md
  site/docs/api/composition/space-layer.zh.md
  site/docs/api/composition/spaceFlex.en.md
  site/docs/api/composition/spaceFlex.zh.md
  site/docs/api/composition/spaceLayer.en.md
  site/docs/api/composition/spaceLayer.zh.md
  site/docs/api/composition/timingKeyframe.en.md
  site/docs/api/composition/timingKeyframe.zh.md
  site/docs/api/overview.zh.md
  site/docs/api/scale/ordinal.zh.md
Labels: PR: unreviewed

#4302 docs(annotation): add several annotation demos
  site/examples/annotation/annotation/demo/histogram-mean-line.ts
  site/examples/annotation/annotation/demo/interval-connector.ts
  site/examples/annotation/annotation/demo/interval-mean-line.ts
  site/examples/annotation/annotation/demo/interval-point.ts
  site/examples/annotation/annotation/demo/interval-threshold.ts
  site/examples/annotation/annotation/demo/line-badge.ts
  site/examples/annotation/annotation/demo/line-range.ts
  site/examples/annotation/annotation/demo/line-text.ts
  site/examples/annotation/annotation/demo/meta.json
  site/examples/annotation/annotation/demo/point-line.ts
  site/examples/annotation/annotation/demo/point-point.ts
  site/examples/annotation/annotation/demo/point-range.ts
  site/examples/annotation/annotation/demo/quadrant-scatter.ts
  site/examples/annotation/annotation/index.en.md
  site/examples/annotation/annotation/index.zh.md
  site/examples/annotation/connector/demo/meta.json
  site/examples/annotation/connector/index.en.md
  site/examples/annotation/connector/index.zh.md
  site/examples/annotation/line/demo/meta.json
  site/examples/annotation/line/index.en.md
  site/examples/annotation/line/index.zh.md
  site/examples/annotation/range/demo/meta.json
  site/examples/annotation/range/index.en.md
  site/examples/annotation/range/index.zh.md
  site/examples/annotation/text/demo/meta.json
  site/examples/annotation/text/index.en.md
  site/examples/annotation/text/index.zh.md
Labels: PR: unreviewed

#4305 docs: add band, point, time scale api
  site/docs/api/overview.zh.md
  site/docs/api/scale/band.en.md
  site/docs/api/scale/band.zh.md
  site/docs/api/scale/point.en.md
  site/docs/api/scale/point.zh.md
  site/docs/api/scale/time.en.md
  site/docs/api/scale/time.zh.md
Labels: PR: reviewed-approved

#4307 docs: add chart api
  __tests__/integration/charts/flare-treemap-custom.ts
  __tests__/integration/snapshots/flareTreemapCustom.png
  __tests__/integration/snapshots/flareTreemapDefault.png
  __tests__/integration/snapshots/philosophyWordCloudCustom.png
  __tests__/integration/snapshots/philosophyWordCloudDefault.png
  site/docs/api/chart.zh.md
  site/examples/general/text/demo/wordCloud-mask.ts
  site/examples/general/text/demo/wordCloud.ts
  site/examples/graph/hierarchy/demo/treemap.ts
  src/mark/treemap.ts
  src/mark/wordCloud.ts
  src/runtime/render.ts
Labels: PR: reviewed-approved

#4306 docs: add theme api
  site/docs/api/component/overview.en.md
  site/docs/api/component/overview.zh.md
  site/docs/api/label/overview.zh.md
  site/docs/api/mark/text.zh.md
  site/docs/api/theme/theme.zh.md
  site/examples/theme/pattern/demo/custom-pattern.ts
  site/examples/theme/pattern/demo/line-pattern.ts
  site/examples/theme/theme/demo/default-color.ts
  site/examples/theme/theme/demo/layout-area.ts
  site/examples/theme/theme/demo/meta.json
Labels: PR: partially-approved

#4309 docs: add coordinate api
  site/docs/api/coordinate/fisheye.en.md
  site/docs/api/coordinate/fisheye.zh.md
  site/docs/api/coordinate/parallel.en.md
  site/docs/api/coordinate/parallel.zh.md
  site/docs/api/coordinate/polar.zh.md
  site/docs/api/coordinate/radial.en.md
  site/docs/api/coordinate/radial.zh.md
  site/docs/api/coordinate/theta.en.md
  site/docs/api/coordinate/theta.zh.md
  site/docs/api/coordinate/transpose.en.md
  site/docs/api/coordinate/transpose.zh.md
Labels: PR: unreviewed

#4308 docs: add data api
  site/docs/api/data/custom.en.md
  site/docs/api/data/custom.zh.md
  site/docs/api/data/filter.en.md
  site/docs/api/data/filter.zh.md
  site/docs/api/data/fold.en.md
  site/docs/api/data/fold.zh.md
  site/docs/api/data/join.en.md
  site/docs/api/data/join.zh.md
  site/docs/api/data/map.en.md
  site/docs/api/data/map.zh.md
  site/docs/api/data/overview.zh.md
  site/docs/api/data/pick.en.md
  site/docs/api/data/pick.zh.md
  site/docs/api/data/rename.en.md
  site/docs/api/data/rename.zh.md
  site/docs/api/data/sort-by.en.md
  site/docs/api/data/sort-by.zh.md
  site/docs/api/data/sort.en.md
  site/docs/api/data/sort.zh.md
  site/docs/api/data/subset.en.md
  site/docs/api/data/subset.zh.md
  site/docs/api/overview.zh.md
  src/spec/data.ts
Labels: PR: unreviewed

#4311 docs: add animation api
  site/docs/api/animation/fade-in.en.md
  site/docs/api/animation/fade-in.zh.md
  site/docs/api/animation/overview.en.md
  site/docs/api/animation/overview.zh.md
  site/docs/api/overview.zh.md
Labels: PR: reviewed-approved

#4310 docs(axis): add axis component docs
  site/docs/api/component/axis.en.md
  site/docs/api/component/axis.zh.md
Labels: PR: unreviewed

#4312 docs: add graph api
  site/docs/api/graph/circle-packing.en.md
  site/docs/api/graph/circle-packing.zh.md
  site/docs/api/graph/forceGraph.en.md
  site/docs/api/graph/forceGraph.zh.md
  site/docs/api/graph/sankey.zh.md
  site/docs/api/graph/tree.en.md
  site/docs/api/graph/tree.zh.md
  site/docs/api/graph/treemap.en.md
  site/docs/api/graph/treemap.zh.md
  site/docs/api/graph/wordCloud.en.md
  site/docs/api/graph/wordCloud.zh.md
  site/examples/graph/network/demo/meta.json
Labels: PR: reviewed-approved

#4313 docs: add geo api
  site/docs/api/geo/geo-path.en.md
  site/docs/api/geo/geo-path.zh.md
  site/docs/api/geo/geoPath.en.md
  site/docs/api/geo/geoPath.zh.md
  site/docs/api/geo/geoView.en.md
  site/docs/api/geo/geoView.zh.md
  site/docs/api/overview.zh.md
Labels: PR: reviewed-approved

#4314 docs: add tutorial
  site/.dumi/github-markdown-light.css
  site/.dumi/global.ts
  site/.dumi/prism-one-dark.css
  site/.dumirc.ts
  site/docs/manual/animation.en.md
  site/docs/manual/animation.zh.md
  site/docs/manual/customization.en.md
  site/docs/manual/customization.zh.md
  site/docs/manual/getting-started.en.md
  site/docs/manual/getting-started.zh.md
  site/docs/manual/interaction.en.md
  site/docs/manual/interaction.zh.md
  site/docs/manual/introduction.en.md
  site/docs/manual/introduction.zh.md
  site/docs/manual/multi-view/facet.en.md
  site/docs/manual/multi-view/facet.zh.md
  site/docs/manual/multi-view/repeat.en.md
  site/docs/manual/multi-view/repeat.zh.md
  site/docs/manual/multi-view/space.en.md
  site/docs/manual/multi-view/space.zh.md
  site/docs/manual/multi-view/timing.en.md
  site/docs/manual/multi-view/timing.zh.md
  site/docs/manual/single-view/annotation.en.md
  site/docs/manual/single-view/annotation.zh.md
  site/docs/manual/single-view/api.en.md
  site/docs/manual/single-view/api.zh.md
  site/docs/manual/single-view/chart.en.md
  site/docs/manual/single-view/chart.zh.md
  site/docs/manual/single-view/coordinate.en.md
  site/docs/manual/single-view/coordinate.zh.md
  site/docs/manual/single-view/data.en.md
  site/docs/manual/single-view/data.zh.md
  site/docs/manual/single-view/mark.en.md
  site/docs/manual/single-view/mark.zh.md
  site/docs/manual/single-view/scale.en.md
  site/docs/manual/single-view/scale.zh.md
  site/docs/manual/single-view/size.en.md
  site/docs/manual/single-view/size.zh.md
  site/docs/manual/single-view/transform.en.md
  site/docs/manual/single-view/transform.zh.md
  site/docs/manual/theme.en.md
  site/docs/manual/theme.zh.md
  site/docs/manual/view-composition.en.md
  site/docs/manual/view-composition.zh.md
Labels: PR: unreviewed

#4315 fix: 修复 wave-in 添加 inset 不生效问题
  site/examples/theme/theme/demo/dark.ts
  src/animation/waveIn.ts
Labels: PR: partially-approved

#4317 docs: add annotation mark api
  site/docs/api/mark/lineX.en.md
  site/docs/api/mark/lineX.zh.md
  site/docs/api/mark/lineY.en.md
  site/docs/api/mark/lineY.zh.md
  site/docs/api/mark/range.en.md
  site/docs/api/mark/range.zh.md
  site/docs/api/mark/rangeX.en.md
  site/docs/api/mark/rangeX.zh.md
  site/docs/api/mark/rangeY.en.md
  site/docs/api/mark/rangeY.zh.md
  site/docs/api/overview.zh.md
  site/examples/annotation/annotation/demo/interval-connector.ts
  site/examples/annotation/annotation/demo/line-range.ts
  site/examples/annotation/annotation/demo/point-range.ts
Labels: PR: reviewed-approved

#4319 fix website desc
  site/.dumirc.ts
Labels: PR: partially-approved

#4318 docs: add a custom demo
  site/docs/api/coordinate/theta.zh.md
  site/docs/api/mark/polygon.zh.md
  site/docs/api/transform/jitter.zh.md
  site/examples/annotation/annotation/demo/quadrant-scatter.ts
  site/examples/general/interval/demo/bar-diverging-stacked.ts
  site/examples/general/interval/demo/meta.json
  site/examples/general/point/demo/point-bubble.ts
  site/examples/general/polygon/demo/treemap.ts
  site/examples/general/polygon/demo/voronoi.ts
  site/examples/general/radial/demo/bar-stacked-radial.ts
  site/examples/general/radial/demo/point-jitter-radial.ts
Labels: PR: reviewed-approved

#4321 refactor: rename lookup to join
  __tests__/integration/charts/airports-point-choropleth.ts
  __tests__/integration/charts/hale-choropleth-world.ts
  __tests__/integration/charts/unemployment-choropleth.ts
  __tests__/unit/data/join.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/data/join.zh.md
  site/docs/api/geo/geoPath.zh.md
  site/examples/geo/geo/demo/choropleth-usa.ts
  site/examples/geo/geo/demo/choropleth-world.ts
  site/examples/geo/geo/demo/flights-airports.ts
  src/data/index.ts
  src/data/join.ts
  src/data/lookup.ts
  src/spec/data.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4320 refactor: rename data.filterBy to data.filter
  __tests__/integration/charts/airports-point-choropleth.ts
  __tests__/integration/charts/disasters-point-bubble.ts
  __tests__/integration/charts/indices-line-point-scale-key.ts
  __tests__/integration/charts/morley-box-1d.ts
  __tests__/integration/charts/population-interval-diverging.ts
  __tests__/integration/charts/population-interval-layered.ts
  __tests__/integration/charts/population-interval-normalized-stacked.ts
  __tests__/integration/charts/stocks-area-gradient.ts
  __tests__/integration/charts/weather-line-area-dual-axis.ts
  __tests__/unit/data/filter.spec.ts
  __tests__/unit/data/filterBy.spec.ts
  __tests__/unit/runtime/interaction.spec.ts
  __tests__/unit/runtime/line.spec.ts
  __tests__/unit/runtime/lineXY.spec.ts
  __tests__/unit/runtime/text.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/coordinate-parallel.md
  docs/coordinate.md
  docs/data-fetch.md
  docs/data-filter.md
  docs/data.md
  docs/mark-interval.md
  docs/mark-point.md
  docs/mark-polygon.md
  docs/mark-rect.md
  site/docs/api/coordinate/parallel.zh.md
  site/docs/api/data/filter.zh.md
  site/docs/api/mark/interval.zh.md
  site/docs/api/mark/lineX.zh.md
  site/docs/api/transform/normalizeY.zh.md
  site/docs/manual/single-view/data.zh.md
  site/examples/annotation/annotation/demo/histogram-mean-line.ts
  site/examples/general/area/demo/area-gradient.ts
  site/examples/general/dual/demo/dual-aggregated-line-area.ts
  site/examples/general/interval/demo/bar-aggregated-normalized-stacked.ts
  site/examples/general/interval/demo/bar-diverging.ts
  site/examples/general/interval/demo/bar-layered.ts
  site/examples/general/point/demo/point-bubble.ts
  site/examples/general/polygon/demo/treemap.ts
  site/examples/geo/geo/demo/flights-airports.ts
  src/data/filter.ts
  src/data/filterBy.ts
  src/data/index.ts
  src/interaction/action/service/elementSelection.ts
  src/interaction/action/transformer/filter.ts
  src/interaction/builtin/elementHighlightByColor.ts
  src/interaction/builtin/elementHighlightByX.ts
  src/spec/action.ts
  src/spec/data.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4323 docs: add group animation demo
  site/examples/animation/group/demo/area.ts
  site/examples/animation/group/demo/gantt.ts
  site/examples/animation/group/demo/interval-polar.ts
  site/examples/animation/group/demo/interval.ts
  site/examples/animation/group/demo/line.ts
  site/examples/animation/group/demo/meta.json
  site/examples/animation/group/demo/point.ts
Labels: PR: partially-approved

#4327 fix(corner): diverging stack bars
  __tests__/integration/charts/gain-lost-interval-cornered.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/gain-lost.json
  __tests__/integration/snapshots/gainLostIntervalCornered.png
  jest.config.js
  site/examples/general/interval/demo/bar-stacked-diverging-rounded.ts
  site/examples/general/interval/demo/meta.json
  src/shape/interval/color.ts
  src/transform/maybeVisualPosition.ts
  src/transform/stackY.ts
Labels: PR: reviewed-approved

#4329 refactor(interaction): rename elementActive to elementHighlight
  __tests__/integration/interactions/alphabet-interval-active-defaults.ts
  __tests__/integration/interactions/alphabet-interval-active-inactive.ts
  __tests__/integration/interactions/alphabet-interval-active.ts
  __tests__/integration/interactions/stateages-interval-active-by-color-linked.ts
  __tests__/integration/interactions/stateages-interval-active-by-color.ts
  __tests__/integration/interactions/stateages-interval-active-by-x.ts
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/index.ts
  src/interaction/native/elementHighlight.ts
  src/interaction/native/elementHighlightByColor.ts
  src/interaction/native/elementHighlightByX.ts
  src/interaction/native/elementSelect.ts
  src/interaction/native/elementSelectByColor.ts
  src/interaction/native/elementSelectByX.ts
  src/interaction/native/utils.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4330 refactor(api): group some methods to attr
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/mark.spec.ts
  site/docs/api/composition/facetRect.zh.md
  site/docs/api/composition/spaceFlex.zh.md
  site/docs/api/composition/spaceLayer.zh.md
  site/docs/manual/animation.zh.md
  site/docs/manual/introduction.zh.md
  site/docs/manual/single-view/api.zh.md
  site/docs/manual/single-view/mark.zh.md
  site/docs/manual/view-composition.zh.md
  site/examples/analysis/boxplot/demo/boxplot-1d.ts
  site/examples/analysis/boxplot/demo/boxplot-outlier.ts
  site/examples/animation/group/demo/point.ts
  site/examples/composition/facet/demo/rect-bar.ts
  site/examples/composition/facet/demo/rect-col.ts
  site/examples/composition/facet/demo/rect-pie.ts
  site/examples/composition/facet/demo/rect-row.ts
  site/examples/composition/facet/demo/rect.ts
  site/examples/composition/space/demo/space-flex.ts
  site/examples/composition/space/demo/space-layer.ts
  site/examples/unit/unit/demo/nested.ts
  site/examples/unit/unit/demo/share-data.ts
  site/examples/unit/unit/demo/share-size.ts
  src/api/composition/facetCircle.ts
  src/api/composition/facetRect.ts
  src/api/composition/geoPath.ts
  src/api/composition/geoView.ts
  src/api/composition/repeatMatrix.ts
  src/api/composition/spaceFlex.ts
  src/api/composition/spaceLayer.ts
  src/api/composition/timingKeyframe.ts
  src/api/composition/view.ts
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/spec/composition.ts
Labels: PR: reviewed-approved

#4331 feat(radar): add radar demo
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/score-by-item-area-radar.ts
  __tests__/integration/data/score-by-item.js
  __tests__/integration/snapshots/scoreByItemAreaRadar.png
  site/examples/general/radial/demo/meta.json
  site/examples/general/radial/demo/radar.ts
  src/runtime/render.ts
Labels: PR: reviewed-approved

#4332 feat(animation): opt morphing
  __tests__/integration/animations/index.ts
  __tests__/integration/animations/sex-interval-keyframe.ts
  __tests__/integration/animations/sold-interval-keyframe.ts
  __tests__/integration/animations/stocks-keyframe.ts
  __tests__/integration/data/sex.js
  __tests__/integration/data/sold.js
  __tests__/integration/data/stocks2.csv
  __tests__/integration/snapshots/sex-interval-keyframe/interval1-0.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval1-1.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval2-0.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval2-1.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval3-0.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval3-1.png
  __tests__/integration/snapshots/sex-interval-keyframe/interval3-2.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval1-0.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval1-1.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval2-0.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval2-1.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval3-0.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval3-1.png
  __tests__/integration/snapshots/sold-interval-keyframe/interval3-2.png
  __tests__/integration/snapshots/stocks-keyframe/interval1-0.png
  __tests__/integration/snapshots/stocks-keyframe/interval1-1.png
  __tests__/integration/snapshots/stocks-keyframe/interval2-0.png
  __tests__/integration/snapshots/stocks-keyframe/interval2-1.png
  __tests__/integration/snapshots/stocks-keyframe/interval3-0.png
  __tests__/integration/snapshots/stocks-keyframe/interval3-1.png
  src/animation/morphing.ts
  src/composition/timingKeyframe.ts
  src/interaction/native/chartIndex.ts
  src/interaction/native/fisheye.ts
  src/runtime/plot.ts
  src/shape/area/curve.ts
  src/shape/box/box.ts
  src/shape/connector/connector.ts
  src/shape/image/image.ts
  src/shape/interval/color.ts
  src/shape/interval/funnel.ts
  src/shape/interval/pyramid.ts
  src/shape/line/curve.ts
  src/shape/lineXY/line.ts
  src/shape/link/arc.ts
  src/shape/link/link.ts
  src/shape/link/smooth.ts
  src/shape/link/vhv.ts
  src/shape/path/color.ts
  src/shape/path/hollow.ts
  src/shape/path/path.ts
  src/shape/point/color.ts
  src/shape/polygon/polygon.ts
  src/shape/polygon/ribbon.ts
  src/shape/shape/shape.ts
  src/shape/text/badge.ts
  src/shape/text/text.ts
  src/shape/vector/vector.ts
Labels: PR: partially-approved

#4334 fix(axis): style
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/score-by-item-area-radar-custom.ts
  __tests__/integration/snapshots/scoreByItemAreaRadarCustom.png
  src/component/axis.ts
Labels: PR: partially-approved

#4333 feat(interaction): add tooltip
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/score-by-item-area-radar-custom.ts
  __tests__/integration/data/body.json
  __tests__/integration/data/temperatures.js
  __tests__/integration/interactions/aapl-line-tooltip.ts
  __tests__/integration/interactions/alphabet-interval-tooltip-1d.ts
  __tests__/integration/interactions/alphabet-interval-tooltip-multi.ts
  __tests__/integration/interactions/alphabet-interval-tooltip-title.ts
  __tests__/integration/interactions/body-point-tooltip-2d.ts
  __tests__/integration/interactions/cars3-line-tooltip-xd.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/indices-line-tooltip.ts
  __tests__/integration/interactions/morley-box-tooltip.ts
  __tests__/integration/interactions/stateages-interval-tooltip-shared.ts
  __tests__/integration/interactions/temperatures-line-tooltip-discrete.ts
  __tests__/integration/snapshot-interaction.spec.ts
  __tests__/integration/snapshots/scoreByItemAreaRadarCustom.png
  __tests__/unit/stdlib/index.spec.ts
  src/component/axis.ts
  src/interaction/index.ts
  src/interaction/native/tooltip.ts
  src/mark/area.ts
  src/mark/box.ts
  src/mark/cell.ts
  src/mark/image.ts
  src/mark/interval.ts
  src/mark/line.ts
  src/mark/link.ts
  src/mark/point.ts
  src/mark/polygon.ts
  src/mark/rect.ts
  src/mark/text.ts
  src/mark/utils.ts
  src/mark/vector.ts
  src/runtime/plot.ts
  src/runtime/types/mark.ts
  src/runtime/types/options.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/maybeTitle.ts
  src/transform/maybeTooltip.ts
  src/transform/maybeTooltipPosition.ts
  src/transform/maybeTooltipY.ts
Labels: PR: partially-approved

#4336 feat: add english wordCloud demo
  __tests__/integration/charts/english-wordCloud.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/txt-wordCloud.js
  __tests__/integration/snapshots/englishWordCloud.png
  __tests__/integration/snapshots/philosophyWordCloudCustom.png
  __tests__/integration/snapshots/philosophyWordCloudDefault.png
  src/mark/wordCloud.ts
Labels: PR: unreviewed

#4322 docs(legend): add legend api
  site/docs/api/common/componentTitle.en.md
  site/docs/api/common/componentTitle.zh.md
  site/docs/api/common/navigator.en.md
  site/docs/api/common/navigator.zh.md
  site/docs/api/component/axis.zh.md
  site/docs/api/component/legend.en.md
  site/docs/api/component/legend.zh.md
Labels: PR: unreviewed

#4337 chore: update version to 5.0.0-alpha.4
  package.json
Labels: PR: reviewed-approved

#4338 docs: refactor axis and legend api
  site/docs/api/component/axis.zh.md
  site/docs/api/component/legend.zh.md
Labels: PR: unreviewed

#4339 docs: update README
  README.md
  site/docs/api/component/legend.zh.md
  site/docs/manual/animation.zh.md
  site/docs/manual/introduction.zh.md
  site/docs/manual/single-view/annotation.zh.md
  site/docs/manual/single-view/coordinate.zh.md
  site/docs/manual/single-view/data.zh.md
  site/docs/manual/single-view/mark.zh.md
  site/docs/manual/single-view/scale.zh.md
  site/docs/manual/single-view/size.zh.md
  site/docs/manual/single-view/transform.zh.md
Labels: PR: unreviewed

#4341 fix(mark): hide axis for composite mark
  __tests__/integration/charts/english-wordCloud.ts
  __tests__/integration/charts/flare-point-circle-pack-custom.ts
  __tests__/integration/charts/flare-tree-custom.ts
  __tests__/integration/charts/flare-treemap-custom.ts
  __tests__/integration/charts/miserable-force-custom.ts
  site/examples/animation/general/demo/meta.json
  site/examples/general/text/demo/wordCloud-mask.ts
  site/examples/general/text/demo/wordCloud.ts
  site/examples/graph/hierarchy/demo/circle-packing.ts
  site/examples/graph/hierarchy/demo/meta.json
  site/examples/graph/hierarchy/demo/tree.ts
  site/examples/graph/hierarchy/demo/treemap.ts
  site/examples/graph/network/demo/meta.json
  site/examples/graph/network/demo/sankey.ts
  src/mark/pack.ts
  src/mark/sankey.ts
  src/mark/treemap.ts
  src/mark/wordCloud.ts
  src/spec/geometry.ts
Labels: PR: unreviewed

#4342 docs: update preview
  README.md
  site/docs/manual/introduction.zh.md
Labels: PR: unreviewed

#4343 fix: demo
  site/examples/annotation/annotation/demo/interval-threshold.ts
Labels: PR: unreviewed

#4345 docs: add keyframe
  site/examples/animation/group/demo/meta.json
  site/examples/animation/storytelling/demo/facet-keyframe.ts
  site/examples/animation/storytelling/demo/gantt.ts
  site/examples/animation/storytelling/demo/interval-keyframe.ts
  site/examples/animation/storytelling/demo/meta.json
  site/examples/animation/storytelling/demo/point-keyframe.ts
Labels: PR: unreviewed

#4346 chore: update version to 5.0.0-beta.1
  package.json
Labels: PR: reviewed-approved

#4348 fix(site): 404 url and news
  site/.dumirc.ts
Labels: PR: unreviewed

#4349 fix(site): update description and dependency
  site/.dumirc.ts
  site/package.json
Labels: PR: reviewed-approved

#4350 fix(rect): update cell, rect, add get default radius from theme
  site/docs/api/mark/cell.zh.md
  src/mark/cell.ts
  src/shape/interval/color.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4354 docs: remove choropleth-world demo
  site/examples/geo/geo/demo/meta.json
Labels: PR: reviewed-approved

#4353 docs: add demo poisson
  site/.dumi/global.ts
  site/examples/analysis/bin/demo/meta.json
  site/examples/analysis/bin/demo/poisson.ts
  site/package.json
Labels: PR: partially-approved

#4361 docs: add renderer demo, include canvas, svg, webgl
  site/.dumi/global.ts
  site/docs/api/overview.zh.md
  site/docs/api/plugin/renderer.en.md
  site/docs/api/plugin/renderer.zh.md
  site/examples/general/image/demo/contributor.ts
  site/examples/plugin/lottie/index.en.md
  site/examples/plugin/lottie/index.zh.md
  site/examples/plugin/renderer/demo/canvas.ts
  site/examples/plugin/renderer/demo/meta.json
  site/examples/plugin/renderer/demo/svg.ts
  site/examples/plugin/renderer/demo/webgl.ts
  site/examples/plugin/renderer/index.en.md
  site/examples/plugin/renderer/index.zh.md
  site/examples/plugin/rough/index.en.md
  site/examples/plugin/rough/index.zh.md
  site/examples/plugin/search/index.en.md
  site/examples/plugin/search/index.zh.md
  site/package.json
Labels: PR: partially-approved

#4365 chore: update 4.x version links
  deploy-4x.yml
  gatsby-config.js
Labels: PR: unreviewed, ignore-for-release

#4367 chore: simplify github actions
  .github/workflows/ci.yml
  .github/workflows/deploy-4x.yml
  .github/workflows/mirror.yml
  .github/workflows/npm-publish.yml
  .github/workflows/release.yml
Labels: PR: unreviewed, ignore-for-release

#4369 集成测试中展示不匹配的像素
  .gitignore
  __tests__/integration/canvas.ts
Labels: PR: reviewed-changes-requested

#4368 docs: add several demos of regression transform
  __tests__/integration/charts/forecast-range-area-line.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/data/forecast-range.js
  site/.dumi/global.ts
  site/docs/manual/single-view/data.zh.md
  site/examples/analysis/regression/demo/exponential-regression.ts
  site/examples/analysis/regression/demo/linear-regression.ts
  site/examples/analysis/regression/demo/logarithmic-regression.ts
  site/examples/analysis/regression/demo/meta.json
  site/examples/analysis/regression/demo/polynomial-regression.ts
  site/examples/analysis/regression/demo/quadratic-regression.ts
  site/examples/analysis/regression/index.en.md
  site/examples/analysis/regression/index.zh.md
  site/package.json
Labels: PR: reviewed-approved

#4352 docs(pattern): using g-pattern
  site/.dumi/global.ts
  site/.dumirc.ts
  site/docs/manual/theme.en.md
  site/docs/manual/theme/pattern.en.md
  site/docs/manual/theme/pattern.zh.md
  site/docs/manual/theme/theme.en.md
  site/docs/manual/theme/theme.zh.md
  site/examples/theme/pattern/demo/custom-pattern-with-canvas.ts
  site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
  site/examples/theme/pattern/demo/dots-pattern.ts
  site/examples/theme/pattern/demo/line-pattern.ts
  site/examples/theme/pattern/demo/lines-pattern.ts
  site/examples/theme/pattern/demo/meta.json
  site/examples/theme/pattern/demo/squares-pattern.ts
  site/package.json
Labels: PR: unreviewed

#4382 fix(animation): transition with morphing animation
  __tests__/integration/animations/aapl-area-keyframe.ts
  __tests__/integration/animations/index.ts
  __tests__/integration/snapshots/aapl-area-keyframe/interval2-0.png
  __tests__/integration/snapshots/aapl-area-keyframe/interval2-1.png
  __tests__/integration/snapshots/aapl-area-keyframe/interval2-2.png
  __tests__/integration/snapshots/aapl-area-keyframe/interval2-3.png
  __tests__/unit/api/chart.spec.ts
  src/animation/morphing.ts
  src/api/chart.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: reviewed-approved
