Repository antvis/G2, pull requests merged in 2022-08, with the labels that each got.

#4057 feat(interaction): implement ellipsisText interaction
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/interaction-more.md
  src/component/title.ts
  src/component/utils.ts
  src/interaction/action/index.ts
  src/interaction/action/service/recordTip.ts
  src/interaction/action/transformer/button.ts
  src/interaction/action/transformer/poptip.ts
  src/interaction/builtin/ellipsisText.ts
  src/interaction/create.ts
  src/interaction/index.ts
  src/interaction/stdlib.ts
  src/runtime/plot.ts
  src/spec/action.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4044 feat: add chart and interval api
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/interval.spec.ts
  __tests__/unit/api/node.spec.ts
  __tests__/unit/api/props.spec.ts
  src/api/chart.ts
  src/api/index.ts
  src/api/interval.ts
  src/api/node.ts
  src/api/props.ts
  src/api/types.ts
  src/index.ts
Labels: PR: reviewed-approved

#4060 chore(website): update genji to 0.1.0 and adjust the outline
  .genjirc
  package.json
Labels: PR: partially-approved

#4061 refactor(interaction): several changes of interactions
  .genjirc
  __tests__/unit/interaction/index.spec.ts
  docs/connector.md
  docs/image.md
  docs/node-edge.md
  docs/overview.md
  docs/polygon.md
  docs/schema.md
  package.json
  src/interaction/action/service/elementSelection.ts
  src/interaction/action/service/surfacePointSelection.ts
  src/interaction/action/transformer/activeRegion.ts
  src/interaction/action/transformer/tooltip.ts
  src/interaction/builtin/tooltip.ts
  src/interaction/utils.ts
  src/spec/action.ts
  src/spec/transform.ts
  src/transform/preprocessor/fetch.ts
Labels: PR: partially-approved

#4062 docs: add layout
  .genjirc
  __tests__/unit/api/chart.spec.ts
  docs/dimension.md
  docs/layout.md
  docs/overview.md
  src/api/chart.ts
Labels: PR: partially-approved

#4063 docs: adjust outline and remove node & edge
  .genjirc
  docs/pack.md
Labels: PR: unreviewed

#4064 fix(label): label 可以配置 是否支持捕获
  src/component/labels.ts
  src/geometry/label/interface.ts
Labels: PR: unreviewed, bugfix

#4067 docs: demos of component
  .genjirc
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/runtime/statistic.spec.ts
  docs/component.md
  docs/interaction-brush.md
  docs/interaction-more.md
  docs/overview.md
  docs/text.md
  src/component/title.ts
  src/interaction/builtin/brush.ts
  src/interaction/builtin/brushHighlight.ts
  src/interaction/builtin/brushVisible.ts
  src/interaction/builtin/legendActive.ts
  src/interaction/builtin/legendHighlight.ts
  src/runtime/component.ts
  src/spec/interaction.ts
Labels: PR: unreviewed

#4068 docs: add and update demos
  .genjirc
  docs/animation.md
  docs/area.md
  docs/connector.md
  docs/coordinate.md
  docs/grid.md
  docs/jitter.md
  docs/keyframe.md
  docs/line.md
  docs/link.md
  docs/matrix.md
  docs/pack.md
  docs/polygon.md
  docs/scale.md
  docs/schema.md
  docs/stack-enter.md
  docs/stack.md
  docs/symmetry.md
  docs/text.md
  docs/vector.md
Labels: PR: reviewed-approved

#4066 chore: v4.2.6 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#4070 docs: add preview for added examples
  .genjirc
  docs/coordinate.md
  docs/line.md
  docs/overview.md
  docs/point.md
  docs/scale.md
  docs/spatial.md
  docs/text.md
Labels: PR: unreviewed

#4071 docs: add demo thumbnail of interaction
  docs/interaction-more.md
  docs/overview.md
Labels: PR: reviewed-approved

#4072 docs: remove interaction suffix for interactions docs
  docs/interaction-brush.md
  docs/interaction-component.md
  docs/interaction-element.md
  docs/interaction-more.md
  docs/interaction-tooltip.md
  docs/overview.md
Labels: PR: reviewed-approved

#4073 fix(test): call done in test
  __tests__/unit/runtime/interval.spec.ts
Labels: PR: unreviewed

#4075 docs(overview): remove and adjust demos
  docs/overview.md
Labels: PR: unreviewed

#4076 fix(tooltip): tooltip hide when mouseleave tooltip
  src/chart/controller/tooltip.ts
  tests/bugs/tooltip-spec.ts
Labels: PR: reviewed-approved, bugfix

#4079 docs(example): delete excess data
  examples/interaction/component/demo/axis-label-highlight.ts
  examples/interaction/component/demo/element-list-highlight.ts
  examples/interaction/component/demo/legend-active.ts
  examples/interaction/component/demo/legend-highlight.ts
Labels: Documentation, PR: unreviewed, PR: reviewed-approved

#4078 fix(legend-highlight): reset highlighting after legend filter
  src/index.ts
Labels: PR: unreviewed, interaction, bugfix

#4081 feat: add rest node and composition api
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/composition.spec.ts
  __tests__/unit/api/interval.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/api/node.spec.ts
  __tests__/unit/api/props.spec.ts
  __tests__/unit/composition/flex.spec.ts
  __tests__/unit/runtime/unit.spec.ts
  src/api/chart.ts
  src/api/composition/circle.ts
  src/api/composition/flex.ts
  src/api/composition/index.ts
  src/api/composition/keyframe.ts
  src/api/composition/layer.ts
  src/api/composition/matrix.ts
  src/api/composition/rect.ts
  src/api/composition/view.ts
  src/api/interval.ts
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/api/node.ts
  src/api/props.ts
  src/composition/flex.ts
  src/composition/mark.ts
  src/composition/rect.ts
  src/composition/view.ts
  src/runtime/component.ts
  src/runtime/plot.ts
  src/spec/composition.ts
  src/spec/geometry.ts
Labels: PR: unreviewed

#4087 fix: transform and guide
  src/component/axis.ts
  src/interaction/action/transformer/tooltip.ts
  src/transform/statistic/select.ts
Labels: PR: partially-approved

#4088 fix(annotation): do not pass className to children
  src/shape/annotation/badge.ts
  src/shape/annotation/text.ts
Labels: PR: reviewed-approved

#4089 chore: ready to release 5.0.0-alpha.0
  package.json
Labels: PR: unreviewed

#4094 fix(label): 修复 webworker 执行多条任务时 label 渲染混乱问题
  src/geometry/label/layout/hide-overlap.ts
  src/geometry/label/util/createWorker.ts
Labels: PR: partially-approved, bugfix

#4091 docs: add introduction
  .genjirc
  docs/introduction.md
  docs/overview.md
  package.json
Labels: PR: partially-approved

#4096 docs: update README and outline of docs
  .genjirc
  README.en-US.md
  README.md
  docs/basic.md
  docs/examples.md
  docs/introduction.md
  docs/tutorials.md
Labels: PR: partially-approved

#4092 fix(docs): tooltip文档缺少花阔号
  docs/manual/tutorial/tooltip.en.md
  docs/manual/tutorial/tooltip.zh.md
Labels: PR: reviewed-approved, bugfix

#4097 fix: use attributes from style instead of parsed style
  __tests__/unit/animation/scaleInX.spec.ts
  __tests__/unit/animation/scaleInY.spec.ts
  __tests__/unit/animation/scaleOutX.spec.ts
  __tests__/unit/animation/scaleOutY.spec.ts
  package.json
  src/animation/fadeIn.ts
  src/animation/fadeOut.ts
  src/animation/morphing.ts
  src/animation/scaleInX.ts
  src/animation/scaleInY.ts
  src/animation/scaleOutX.ts
  src/animation/scaleOutY.ts
Labels: PR: reviewed-approved

#4098 Revert "fix(tooltip): tooltip hide when mouseleave tooltip"
  src/chart/controller/tooltip.ts
  tests/bugs/tooltip-spec.ts
Labels: PR: unreviewed

#4099 chore: v4.2.7
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#4100 feat(coordinate): add fisheye, reflect and theta
  __tests__/unit/coordinate/index.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/interaction-more.md
  docs/mark-interval.md
  src/coordinate/fisheye.ts
  src/coordinate/fisheyeX.ts
  src/coordinate/fisheyeY.ts
  src/coordinate/helix.ts
  src/coordinate/index.ts
  src/coordinate/reflect.ts
  src/coordinate/reflectX.ts
  src/coordinate/reflectY.ts
  src/coordinate/theta.ts
  src/interaction/action/service/fisheyeFocus.ts
  src/runtime/component.ts
  src/runtime/coordinate.ts
  src/runtime/scale.ts
  src/shape/interval/colorRect.ts
  src/spec/coordinate.ts
  src/stdlib/index.ts
  src/utils/coordinate.ts
Labels: PR: reviewed-approved

#4109 fix(runtime): fail to identify annotation as mark (close: #4106)
  __tests__/unit/runtime/annotationText.spec.ts
  src/runtime/plot.ts
Labels: bug, PR: unreviewed, PR: partially-approved

#4110 docs: add a customize donut demo
  .genjirc
  docs/show-case.md
Labels: PR: reviewed-approved
