Repository antvis/G2, pull requests merged in 2022-04, with the labels that each got.

#3842 feat(transform): add transform for sankey layout
  .eslintrc
  __tests__/unit/transform/d3-sankey/constant.spec.ts
  __tests__/unit/transform/d3-sankey/energy-links.json
  __tests__/unit/transform/d3-sankey/energy-nodes.json
  __tests__/unit/transform/d3-sankey/energy.json
  __tests__/unit/transform/d3-sankey/sankey.spec.ts
  __tests__/unit/transform/sankey.spec.ts
  __tests__/unit/transform/utils.spec.ts
  __tests__/utils/delay.ts
  jest.config.js
  src/spec/transform.ts
  src/transform/fetch.ts
  src/transform/filterBy.ts
  src/transform/index.ts
  src/transform/pick.ts
  src/transform/rename.ts
  src/transform/sankey.ts
  src/transform/sortBy.ts
  src/transform/subset.ts
  src/transform/utils/d3-sankey/align.ts
  src/transform/utils/d3-sankey/constant.ts
  src/transform/utils/d3-sankey/index.ts
  src/transform/utils/d3-sankey/sankey.ts
  src/transform/utils/memo.ts
  tsconfig.json
Labels: PR: unreviewed, G2 5.x

#3848 feat(selection): implement simple selection to bind data into DOM of @antvis/g for animation and interaction
  __tests__/unit/geometry/helper.ts
  __tests__/unit/geometry/interval.spec.ts
  __tests__/unit/geometry/line.spec.ts
  __tests__/unit/infer/index.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/runtime/line.spec.ts
  __tests__/unit/shape/helper.ts
  __tests__/unit/shape/interval/hollowRect.spec.ts
  __tests__/unit/shape/interval/rect.spec.ts
  __tests__/unit/shape/line/line.spec.ts
  __tests__/unit/shape/line/smooth.spec.ts
  __tests__/unit/statistic/key.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/utils/selection.spec.ts
  src/component/axis.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/geometry/interval.ts
  src/geometry/line.ts
  src/infer/index.ts
  src/infer/maybeKey.ts
  src/runtime/component.ts
  src/runtime/layout.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/scale.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/shape/interval/colorRect.ts
  src/shape/interval/hollowRect.ts
  src/shape/interval/rect.ts
  src/shape/line/curveLine.ts
  src/shape/line/line.ts
  src/shape/line/smooth.ts
  src/shape/utils.ts
  src/spec/statistic.ts
  src/statistic/index.ts
  src/statistic/key.ts
  src/stdlib/index.ts
  src/utils/selection.ts
Labels: PR: reviewed-approved

#3850 feat(point): add components for chart related to point geometry
  __tests__/unit/geometry/point.spec.ts
  __tests__/unit/infer/index.spec.ts
  __tests__/unit/runtime/point.spec.ts
  __tests__/unit/scale/index.spec.ts
  __tests__/unit/shape/line/line.spec.ts
  __tests__/unit/shape/line/smooth.spec.ts
  __tests__/unit/shape/point/hollowPoint.spec.ts
  __tests__/unit/shape/point/point.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/geometry/index.ts
  src/geometry/point.ts
  src/infer/index.ts
  src/infer/maybeKey.ts
  src/infer/maybeSize.ts
  src/infer/maybeSplitPosition.ts
  src/infer/maybeZeroY1.ts
  src/runtime/scale.ts
  src/scale/index.ts
  src/scale/log.ts
  src/scale/pow.ts
  src/shape/index.ts
  src/shape/point/colorPoint.ts
  src/shape/point/hollowPoint.ts
  src/shape/point/point.ts
  src/spec/geometry.ts
  src/spec/scale.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3854 feat(selection): add on, state and reset for selection
  __tests__/unit/utils/selection.spec.ts
  src/utils/selection.ts
Labels: PR: partially-approved

#3858 feat(scale): 优化 scale 文档，增加 showLast 配置说明
  docs/api/general/scale.zh.md
  src/interface.ts
Labels: feature, PR: unreviewed

#3852 feat(text): support text geometry and wordCloud transform
  __tests__/unit/geometry/text.spec.ts
  __tests__/unit/runtime/text.spec.ts
  __tests__/unit/shape/text/text.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/transform/wordCloud.spec.ts
  __tests__/unit/utils/helper.spec.ts
  jest.config.js
  src/geometry/index.ts
  src/geometry/text.ts
  src/shape/index.ts
  src/shape/text/text.ts
  src/spec/geometry.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/utils/d3-cloud/index.ts
  src/transform/wordCloud.ts
  src/utils/helper.ts
Labels: PR: reviewed-approved

#3863 feat(axis): 添加坐标轴标题详细说明 icon 交互事件
  docs/api/general/axis.zh.md
  package.json
  src/chart/chart.ts
  src/index.ts
  src/interaction/action/component/axis/axis-description.ts
  src/interface.ts
  src/theme/style-sheet/dark.ts
  src/theme/style-sheet/light.ts
  src/theme/util/create-by-style-sheet.ts
Labels: feature, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested

#3865 chore: v4.1.50 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#3870 docs: preview docs and update README
  .genjirc
  README.md
  docs/animation.md
  docs/assets/logo.png
  docs/coordinate.md
  docs/dimension.md
  docs/encode.md
  docs/interaction.md
  docs/interval.md
  docs/line.md
  docs/point.md
  docs/scale.md
  docs/statistic.md
  docs/text.md
  docs/theme.md
  docs/transform.md
  package.json
Labels: PR: partially-approved

#3880 fix(transform): cache transform component rather than transform function
  __tests__/unit/transform/utils.spec.ts
  src/runtime/types/component.ts
  src/transform/fetch.ts
  src/transform/filterBy.ts
  src/transform/rename.ts
  src/transform/sankey.ts
  src/transform/sortBy.ts
  src/transform/subset.ts
  src/transform/utils/memo.ts
  src/transform/wordCloud.ts
Labels: PR: partially-approved

#3878 feat(composition): add layer and space
  .genjirc
  __tests__/unit/composition/flex.spec.ts
  __tests__/unit/composition/layer.spec.ts
  __tests__/unit/runtime/spatial.spec.ts
  __tests__/unit/runtime/view.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/spatial.md
  src/component/legendCategory.ts
  src/composition/flex.ts
  src/composition/index.ts
  src/composition/layer.ts
  src/runtime/layout.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/spec/index.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3879 feat(axis): update @antv/gui to make axis easier to custom style
  package.json
  src/component/axis.ts
Labels: PR: reviewed-approved

#3876 feat(runtime): support render view with multiple marks
  .genjirc
  __tests__/unit/composition/flex.spec.ts
  __tests__/unit/composition/layer.spec.ts
  __tests__/unit/geometry/text.spec.ts
  __tests__/unit/runtime/spatial.spec.ts
  __tests__/unit/runtime/view.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/utils/selection.spec.ts
  docs/animation.md
  docs/interaction.md
  docs/spatial.md
  docs/view.md
  package.json
  src/action/service/fisheyeFocus.ts
  src/action/service/surfacePointSelection.ts
  src/action/transformer/tooltip.ts
  src/component/axis.ts
  src/component/legendCategory.ts
  src/composition/flex.ts
  src/composition/index.ts
  src/composition/layer.ts
  src/geometry/text.ts
  src/runtime/component.ts
  src/runtime/coordinate.ts
  src/runtime/interaction.ts
  src/runtime/layout.ts
  src/runtime/mark.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/scale.ts
  src/runtime/types/common.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/spec/geometry.ts
  src/spec/index.ts
  src/stdlib/index.ts
  src/utils/selection.ts
Labels: PR: partially-approved

#3882 feat(runtime): add grid geometry and related scales(threshold, quantize, quantile)
  .genjirc
  __tests__/unit/geometry/grid.spec.ts
  __tests__/unit/runtime/grid.spec.ts
  __tests__/unit/scale/index.spec.ts
  __tests__/unit/shape/interval/rect.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/grid.md
  docs/scale.md
  src/geometry/grid.ts
  src/geometry/index.ts
  src/geometry/point.ts
  src/infer/maybeTooltip.ts
  src/runtime/render.ts
  src/runtime/scale.ts
  src/scale/index.ts
  src/scale/quantile.ts
  src/scale/quantize.ts
  src/scale/threshold.ts
  src/shape/interval/colorRect.ts
  src/spec/geometry.ts
  src/spec/scale.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3885 fix(fetch): add useMemoConnector to memorize fetch
  __tests__/unit/transform/fetch.spec.ts
  __tests__/unit/transform/utils.spec.ts
  src/transform/fetch.ts
  src/transform/utils/memo.ts
Labels: PR: reviewed-approved

#3886 refactor/labels update
  docs/common/geom-base-cfg.md
  examples/other/big-data/API.en.md
  examples/other/big-data/API.zh.md
  examples/other/big-data/demo/big-data-interval.ts
  examples/other/big-data/demo/big-data-line.ts
  examples/other/big-data/demo/meta.json
  examples/other/big-data/index.en.md
  examples/other/big-data/index.zh.md
  src/component/labels.ts
  src/constant.ts
  src/geometry/base.ts
  src/geometry/label/layout/hide-overlap.ts
  src/geometry/label/util/index.ts
  tests/unit/geometry/base-spec.ts
Labels: PR: unreviewed

#3887 refactor(runtime): separate compute and render logic for plotting a view
  __tests__/unit/composition/mark.spec.ts
  __tests__/unit/composition/view.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/animation/utils.ts
  src/composition/flex.ts
  src/composition/index.ts
  src/composition/layer.ts
  src/composition/mark.ts
  src/composition/view.ts
  src/runtime/interaction.ts
  src/runtime/mark.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/types/common.ts
  src/runtime/types/component.ts
  src/spec/composition.ts
  src/stdlib/index.ts
  src/utils/container.ts
Labels: PR: partially-approved

#3888 feat: use worker to do label layout 🚀
  examples/other/big-data/demo/big-data-interval.ts
  examples/other/big-data/index.en.md
  examples/other/big-data/index.zh.md
  src/component/labels.ts
  src/geometry/base.ts
  src/geometry/element/index.ts
  src/geometry/label/base.ts
  src/geometry/label/layout/hide-overlap.ts
  src/geometry/label/layout/path/adjust-position.ts
  src/geometry/label/layout/worker/hide-overlap.ts
  src/geometry/label/util/createWorker.ts
  src/geometry/label/util/index.ts
  src/util/collision-detect.ts
  tests/bugs/2295-spec.ts
  tests/bugs/2778-spec.ts
  tests/bugs/3056-spec.ts
  tests/bugs/3065-spec.ts
  tests/bugs/3073-spec.ts
  tests/bugs/3146-spec.ts
  tests/bugs/3160-spec.ts
  tests/bugs/pie-update-spec.ts
  tests/unit/chart/controller/scrollbar-spec.ts
  tests/unit/geometry/label/base-spec.ts
  tests/unit/geometry/label/interval-spec.ts
  tests/unit/geometry/label/label-offset-spec.ts
  tests/unit/geometry/label/label-update-spec.ts
  tests/unit/geometry/label/labels-spec.ts
  tests/unit/geometry/label/layout/adjust-color-spec.ts
  tests/unit/geometry/label/layout/hide-overlap-spec.ts
  tests/unit/geometry/label/layout/interval/adjust-position-spec.ts
  tests/unit/geometry/label/layout/pie-outer-spec.ts
  tests/unit/geometry/label/layout/pie-spider-spec.ts
  tests/unit/geometry/label/pie-spec.ts
  tests/unit/interaction/action/active-spec.ts
  tests/unit/util/collision-detect-spec.ts
Labels: feature, PR: unreviewed

#3891 chore: v4.2.0, use deferred label & web worker to do layout
  CHANGELOG.md
  package.json
  src/core.ts
  tests/unit/geometry/label/layout/hide-overlap-spec.ts
Labels: PR: unreviewed

#3893 feat(runtime): support flex options for interval and grid
  __tests__/unit/runtime/grid.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  docs/grid.md
  docs/interval.md
  docs/scale.md
  src/component/axis.ts
  src/geometry/grid.ts
  src/geometry/interval.ts
  src/runtime/types/component.ts
Labels: PR: partially-approved

#3897 fix(animate): optimize scale-in by break the animation into two phases
  __tests__/unit/animation/scaleInY.spec.ts
  __tests__/unit/shape/interval/hollowRect.spec.ts
  __tests__/unit/shape/point/point.spec.ts
  src/animation/scaleInY.ts
Labels: PR: unreviewed
