Repository antvis/G2, pull requests merged in 2022-06, with the labels that each got.

#3955 refactor(annotation): lineX and lineY swap rename
  __tests__/unit/mark/annotation/lineX.ts
  __tests__/unit/mark/annotation/lineY.spec.ts
  __tests__/unit/runtime/annotationLine.spec.ts
  __tests__/unit/runtime/statistic.spec.ts
  docs/stack.md
  src/mark/annotation/index.ts
  src/mark/annotation/lineX.ts
  src/mark/annotation/lineY.ts
Labels: PR: partially-approved

#3954 feat(legend): support config category legend
  __tests__/unit/runtime/statistic.spec.ts
  src/component/legendCategory.ts
Labels: PR: partially-approved

#3957 feat(transform): add select
  .genjirc
  __tests__/unit/runtime/statistic.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/overview.md
  docs/select.md
  src/spec/statistic.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/statistic/select.ts
  src/transform/statistic/selectX.ts
  src/transform/statistic/selectY.ts
Labels: PR: partially-approved

#3960 typo: fix annotaion to annotation
  docs/manual/concepts/interaction.zh.md
Labels: PR: unreviewed

#3962 chore: change JitterY to jitterY and Jitter to jitter
  .gitignore
  docs/dodge.md
  src/transform/index.ts
  src/transform/statistic/jitter.ts
  src/transform/statistic/jitterY.ts
Labels: PR: reviewed-approved

#3956 feat(title): support title component
  __tests__/unit/runtime/facet.spec.ts
  __tests__/unit/runtime/interaction.spec.ts
  __tests__/unit/runtime/interval.spec.ts
  __tests__/unit/runtime/view.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/theme/light.spec.ts
  src/component/index.ts
  src/component/legendCategory.ts
  src/component/title.ts
  src/composition/mark.ts
  src/runtime/component.ts
  src/runtime/types/common.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/spec/title.ts
  src/stdlib/index.ts
  src/theme/light.ts
Labels: PR: partially-approved

#3964 fix(transform): change connector to preprocessor
  __tests__/unit/runtime/line.spec.ts
  __tests__/unit/runtime/text.spec.ts
  __tests__/unit/transform/fold.spec.ts
  docs/annotation.md
  docs/connector.md
  docs/interval.md
  docs/line.md
  docs/scale.md
  docs/spatial.md
  docs/text.md
  src/runtime/mark.ts
  src/runtime/plot.ts
  src/runtime/types/transform.ts
  src/transform/index.ts
  src/transform/preprocessor/fetch.ts
  src/transform/preprocessor/filterBy.ts
  src/transform/preprocessor/fold.ts
  src/transform/preprocessor/pick.ts
  src/transform/preprocessor/rename.ts
  src/transform/preprocessor/sortBy.ts
  src/transform/preprocessor/subset.ts
Labels: PR: unreviewed

#3966 fix(shape): change the startAngle of angle function to -Math.PI / 2
  __tests__/unit/coordinate/index.spec.ts
  __tests__/unit/shape/interval/rect.spec.ts
  __tests__/unit/shape/line/line.spec.ts
  src/coordinate/polar.ts
  src/shape/interval/colorRect.ts
  src/utils/vector.ts
Labels: PR: partially-approved

#3965 feat(shape): add index and point2d params
  src/runtime/plot.ts
  src/runtime/types/component.ts
Labels: PR: partially-approved

#3963 feat: add `ribbon` shape for polygon
  __tests__/data/sankey.ts
  __tests__/unit/mark/geometry/polygon.spec.ts
  __tests__/unit/runtime/polygon.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/transform/connector.ts
  __tests__/unit/transform/subset.spec.ts
  src/mark/geometry/polygon.ts
  src/runtime/mark.ts
  src/shape/index.ts
  src/shape/polygon/ribbon.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/preprocessor/connector.ts
  src/transform/preprocessor/subset.ts
Labels: PR: partially-approved

#3970 fix(transform): merge ignore undefined new encode
  src/transform/preprocessor/wordCloud.ts
  src/transform/utils/helper.ts
Labels: PR: partially-approved

#3973 feat: add vector geometry and shape
  .genjirc
  __tests__/unit/mark/geometry/vector.spec.ts
  __tests__/unit/runtime/vector.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/vector.md
  src/mark/geometry/index.ts
  src/mark/geometry/vector.ts
  src/shape/index.ts
  src/shape/vector/vector.ts
  src/spec/geometry.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#3979 fix(title): title support config a string
  src/runtime/component.ts
Labels: PR: unreviewed

#3980 feat(composition): add matrix
  .genjirc
  .github/workflows/build.yml
  __tests__/unit/runtime/facet.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/utils/selection.spec.ts
  docs/matrix.md
  docs/rect.md
  src/composition/index.ts
  src/composition/matrix.ts
  src/composition/rect.ts
  src/composition/view.ts
  src/runtime/mark.ts
  src/spec/composition.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3969 fix(interval): 修复同时存在坐标系转制和 y 镜像的时候 的bakcground radius 的错误
  src/geometry/shape/interval/util.ts
  tests/bugs/interval-background-radius-spec.ts
Labels: PR: reviewed-approved, bugfix

#3981 fix(sector-path): 修复扇形非常小的时候, 角度 diff 会被重置为 Math.PI * 2
  CHANGELOG.md
  package.json
  src/animate/animation/sector-path-update.ts
  src/animate/animation/wave-in.ts
  src/core.ts
  tests/unit/animate/sector-path-update-spec.ts
Labels: PR: unreviewed, bugfix

#3982 refactor(rect): support sync scales among facets
  .genjirc
  __tests__/unit/runtime/facet.spec.ts
  docs/rect.md
  src/composition/matrix.ts
  src/composition/rect.ts
  src/runtime/layout.ts
  src/runtime/mark.ts
  src/runtime/plot.ts
  src/runtime/scale.ts
Labels: PR: partially-approved

#3984 feat: add src shape for edge
  __tests__/unit/mark/geometry/edge.spec.ts
  __tests__/unit/runtime/edge.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  __tests__/unit/transform/arc/index.spec.ts
  src/mark/geometry/edge.ts
  src/shape/edge/arc.ts
  src/shape/edge/smoothEdge.ts
  src/shape/index.ts
  src/spec/transform.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/preprocessor/arc.ts
  src/transform/preprocessor/fetch.ts
  src/transform/utils/arc/arc.ts
  src/transform/utils/arc/index.ts
  src/transform/utils/arc/sort.ts
  src/transform/utils/arc/types.ts
  src/utils/vector.ts
Labels: PR: partially-approved

#3985 feat(composition): add circle
  .genjirc
  __tests__/unit/runtime/facet.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/more-composition.md
  src/component/axis.ts
  src/composition/circle.ts
  src/composition/index.ts
  src/composition/matrix.ts
  src/composition/rect.ts
  src/composition/utils.ts
  src/runtime/component.ts
  src/shape/interval/colorRect.ts
  src/spec/composition.ts
  src/stdlib/index.ts
  src/utils/vector.ts
Labels: PR: partially-approved

#3990 fix: build error
  src/transform/utils/arc/arc.ts
  src/transform/utils/arc/index.ts
Labels: PR: reviewed-approved

#3993 refactor(interaction): remove interaction grammar from runtime
  __tests__/unit/interaction/index.spec.ts
  __tests__/unit/interaction/interactor.spec.ts
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/action/index.ts
  src/interaction/action/service/fisheyeFocus.ts
  src/interaction/action/service/surfacePointSelection.ts
  src/interaction/action/transformer/highlightSelection.ts
  src/interaction/action/transformer/plot.ts
  src/interaction/action/transformer/tooltip.ts
  src/interaction/builtin/elementActive.ts
  src/interaction/builtin/fisheye.ts
  src/interaction/builtin/tooltip.ts
  src/interaction/create.ts
  src/interaction/index.ts
  src/interaction/interactor/index.ts
  src/interaction/interactor/mousePosition.ts
  src/interaction/interactor/touchPosition.ts
  src/interaction/stdlib.ts
  src/interaction/types.ts
  src/runtime/interaction.ts
  src/runtime/plot.ts
  src/runtime/types/common.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
  src/shape/annotation/connector.ts
  src/shape/utils.ts
  src/spec/action.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#3992 feat(interaction): support element-highlight interactions
  __tests__/unit/interaction/elementHightlight.spec.ts
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/action/index.ts
  src/interaction/action/service/elementSelection.ts
  src/interaction/action/transformer/highlight.ts
  src/interaction/builtin/elementHighlight.ts
  src/interaction/builtin/elementHighlightByColor.ts
  src/interaction/builtin/elementHighlightByX.ts
  src/interaction/index.ts
  src/interaction/stdlib.ts
  src/spec/action.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4000 fix(animate waveIn): 修复 waveIn 动画 最后没有给 element 附上更新后样式的问题
  src/animate/animation/wave-in.ts
  tests/bugs/3694-spec.ts
Labels: PR: reviewed-approved, bugfix

#4002 fix(axis-label): 修复 axis-label tooltip 移开没有 hide 的问题
  src/index.ts
Labels: PR: reviewed-approved, bugfix

#4003 chore: v4.2.4 & changelog
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: unreviewed, ignore-for-release

#4006 chore: remove extra action tp deploy site
  .github/workflows/site-deploy.yml
Labels: PR: unreviewed

#3999 fix(backgroundName): 修复 柱形存在背景时添加 interval:click 触发两次的问题
  src/geometry/shape/interval/index.ts
  tests/bugs/3748-spec.ts
Labels: PR: reviewed-approved, bugfix

#4010 feat: add groupX
  .genjirc
  __tests__/unit/runtime/statistic.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  docs/group.md
  docs/overview.md
  src/spec/statistic.ts
  src/stdlib/index.ts
  src/transform/index.ts
  src/transform/inference/maybeStackY.ts
  src/transform/statistic/groupX.ts
  src/transform/utils/helper.ts
Labels: PR: partially-approved

#3994 feat(interaction): support legend interaction
  __tests__/unit/interaction/elementHightlight.spec.ts
  __tests__/unit/interaction/index.spec.ts
  __tests__/unit/interaction/legend.spec.ts
  __tests__/unit/interaction/stdlib.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/component/legendCategory.ts
  src/interaction/action/index.ts
  src/interaction/action/service/legendItemSelection.ts
  src/interaction/action/service/triggerInfoSelection.ts
  src/interaction/action/transformer/activeElement.ts
  src/interaction/action/transformer/highlightElement.ts
  src/interaction/action/transformer/setItemState.ts
  src/interaction/builtin/elementActive.ts
  src/interaction/builtin/elementHighlightByColor.ts
  src/interaction/builtin/elementHighlightByX.ts
  src/interaction/builtin/elementListHighlight.ts
  src/interaction/builtin/legendActive.ts
  src/interaction/builtin/legendHighlight.ts
  src/interaction/index.ts
  src/interaction/stdlib.ts
  src/spec/action.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4015 fix(slider): 修改 slider 的最大值最小值 位置 计算数据方式 floor 为 round
  src/chart/controller/slider.ts
  tests/bugs/g2plot-1899-spec.ts
  tests/bugs/slider-spec.ts
  tests/unit/chart/controller/slider-spec.ts
Labels: PR: reviewed-approved, bugfix

#4011 feat: support merge and split animation
  __tests__/unit/animation/helper.ts
  __tests__/unit/animation/scaleInX.spec.ts
  __tests__/unit/animation/scaleInY.spec.ts
  __tests__/unit/animation/scaleOutX.spec.ts
  __tests__/unit/animation/scaleOutY.spec.ts
  __tests__/unit/mark/annotation/connector.spec.ts
  __tests__/unit/mark/annotation/lineX.spec.ts
  __tests__/unit/mark/annotation/lineY.spec.ts
  __tests__/unit/mark/annotation/range.spec.ts
  __tests__/unit/mark/annotation/rangeX.spec.ts
  __tests__/unit/mark/annotation/rangeY.spec.ts
  __tests__/unit/mark/annotation/text.spec.ts
  __tests__/unit/mark/geometry/area.spec.ts
  __tests__/unit/mark/geometry/edge.spec.ts
  __tests__/unit/mark/geometry/grid.spec.ts
  __tests__/unit/mark/geometry/image.spec.ts
  __tests__/unit/mark/geometry/interval.spec.ts
  __tests__/unit/mark/geometry/line.spec.ts
  __tests__/unit/mark/geometry/link.spec.ts
  __tests__/unit/mark/geometry/node.spec.ts
  __tests__/unit/mark/geometry/point.spec.ts
  __tests__/unit/mark/geometry/polygon.spec.ts
  __tests__/unit/mark/geometry/schema.spec.ts
  __tests__/unit/mark/geometry/text.spec.ts
  __tests__/unit/mark/geometry/vector.spec.ts
  __tests__/unit/runtime/keyframe.spec.ts
  __tests__/unit/utils/selection.spec.ts
  docs/keyframe.md
  src/animation/fadeIn.ts
  src/animation/fadeOut.ts
  src/animation/morphing.ts
  src/animation/scaleInX.ts
  src/animation/scaleInY.ts
  src/animation/scaleOutX.ts
  src/animation/scaleOutY.ts
  src/mark/utils.ts
  src/runtime/plot.ts
  src/runtime/types/component.ts
  src/spec/geometry.ts
  src/utils/selection.ts
Labels: PR: reviewed-approved
