Repository antvis/G2, pull requests merged in 2023-02, with the labels that each got.

#4610 fix: continuous legend use correct color
  __tests__/integration/snapshots/cars3LineParallelHorizontal.png
  __tests__/integration/snapshots/cars3LineParallelVertical.png
  __tests__/integration/snapshots/cars3LineRadar.png
  __tests__/integration/snapshots/commitsPointGrouped.png
  __tests__/integration/snapshots/haleChoroplethWorld.png
  __tests__/integration/snapshots/moviesRectBin.png
  __tests__/integration/snapshots/polio-point-stack-enter/interval0-0.png
  __tests__/integration/snapshots/polio-point-stack-enter/interval0-1.png
  __tests__/integration/snapshots/polio-point-stack-enter/interval0-2.png
  __tests__/integration/snapshots/polio-point-stack-enter/interval0-3.png
  __tests__/integration/snapshots/question8IntervalRadialGradientColor.png
  __tests__/integration/snapshots/settle-weather-cell-brush-filter/step0.png
  __tests__/integration/snapshots/settle-weather-cell-brush-filter/step1.png
  __tests__/integration/snapshots/settleWeatherCellGrouped.png
  __tests__/integration/snapshots/unemploymentChoropleth.png
  __tests__/integration/snapshots/vaccinesCellScaleRelation.png
  src/component/legendContinuous.ts
  src/runtime/types/component.ts
Labels: PR: reviewed-approved

#4609 chore: update to 4.2.9
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: partially-approved, ignore-for-release

#4611 refactor(tests): add toMatchSnapshot
  __tests__/integration/canvas.ts
  __tests__/integration/jsdom.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshot-animation.spec.ts
  __tests__/integration/snapshot-interaction.spec.ts
  __tests__/integration/snapshot-tooltip.spec.ts
  __tests__/integration/snapshot.spec.ts
  __tests__/integration/snapshots/tooltip-aapl-line/step0.html
  __tests__/integration/snapshots/tooltip-alphabet-interval-multi/step0.html
  __tests__/integration/snapshots/tooltip-alphabet-interval-object/step0.html
  __tests__/integration/snapshots/tooltip-alphabet-interval-title/step0.html
  __tests__/integration/snapshots/tooltip-alphabet-interval1d-mounted/step0.html
  __tests__/integration/snapshots/tooltip-alphabet-interval1d/step0.html
  __tests__/integration/snapshots/tooltip-body-point2d/step0.html
  __tests__/integration/snapshots/tooltip-cars3-line-xd/step0.html
  __tests__/integration/snapshots/tooltip-flare-treemap-poptip-custom/step0.html
  __tests__/integration/snapshots/tooltip-flare-treemap-poptip/step1.html
  __tests__/integration/snapshots/tooltip-flare-treemap-poptip/step3.html
  __tests__/integration/snapshots/tooltip-indices-line-chart-facet/step0.html
  __tests__/integration/snapshots/tooltip-indices-line-chart-facet/step1.html
  __tests__/integration/snapshots/tooltip-indices-line-items/step0.html
  __tests__/integration/snapshots/tooltip-indices-line-point-reverse/step0.html
  __tests__/integration/snapshots/tooltip-indices-line-point-reverse/step1.html
  __tests__/integration/snapshots/tooltip-indices-line-reverse/step0.html
  __tests__/integration/snapshots/tooltip-indices-line-reverse/step1.html
  __tests__/integration/snapshots/tooltip-indices-line/step0.html
  __tests__/integration/snapshots/tooltip-morley-box/step0.html
  __tests__/integration/snapshots/tooltip-state-ages-interval-shared/step0.html
  __tests__/integration/snapshots/tooltip-temperatures-line-discrete/step0.html
  __tests__/integration/snapshots/tooltip-temperatures-line-point-discrete/step0.html
  __tests__/integration/snapshots/tooltip-weather-line-interval/step0.html
  __tests__/integration/svg.ts
  __tests__/integration/tooltips/indices-line.ts
  __tests__/integration/utils/createDOMGCanvas.ts
  __tests__/integration/utils/createNodeGCanvas.ts
  __tests__/integration/utils/fetch.ts
  __tests__/integration/utils/filterTests.ts
  __tests__/integration/utils/kebabCase.ts
  __tests__/integration/utils/renderSpec.ts
  __tests__/integration/utils/renderToMountedElement.ts
  __tests__/integration/utils/sleep.ts
  __tests__/integration/utils/toMatchCanvasSnapshot.ts
  __tests__/integration/utils/toMatchDOMSnapshot.ts
  __tests__/integration/utils/useCustomFetch.ts
  __tests__/integration/utils/useSnapshotMatchers.ts
Labels: PR: unreviewed

#4617 fix: 修复 sibling-x-filter，sibling-y-filter 过滤全部数据的问题
  src/index.ts
  tests/unit/interaction/action/sibling-filter-xy-action-spec.ts
Labels: PR: reviewed-approved, bugfix

#4623 fix(animation): skip path morphing animation with sub path
  __tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-0.png
  __tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-1.png
  __tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-2.png
  __tests__/integration/snapshots/animation/iris-point-shapes-keyframe/interval2-3.png
  __tests__/plots/animation/index.ts
  __tests__/plots/animation/iris-point-shapes-keyframe.ts
  src/animation/morphing.ts
  src/interaction/native/brushFilter.ts
Labels: PR: partially-approved

#4624 chore: update version to beta.9
  package.json
Labels: PR: reviewed-approved

#4625 chore: update version to beta.9
  package.json
  site/package.json
Labels: PR: unreviewed

#4626 fix(site): update selection.remove
  src/utils/selection.ts
Labels: PR: partially-approved

#4629 feat(interaction): bubble mark interaction to view
  __tests__/integration/snapshots/interaction/alphabet-interval-bubble-interaction/step0.png
  __tests__/plots/interaction/alphabet-interval-bubble-interaction.ts
  __tests__/plots/interaction/index.ts
  src/runtime/plot.ts
  src/runtime/types/component.ts
  src/runtime/types/options.ts
Labels: PR: partially-approved

#4638 feat(coordinate): mark coordinate bubble to view
  __tests__/integration/snapshots/static/population2015IntervalBubbleCoordinate.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/population2015-interval-bubble-coordinate.ts
  __tests__/unit/api/mark.spec.ts
  src/api/mark/mark.ts
  src/api/mark/types.ts
  src/composition/view.ts
Labels: PR: unreviewed

#4640 feat(view): propagate encode and transform
  __tests__/data/forecast-range.json
  __tests__/data/fuel.json
  __tests__/integration/snapshots/static/forecastRangeAreaLine.png
  __tests__/integration/snapshots/static/fuelLineEncodePropagate.png
  __tests__/integration/snapshots/static/fuelLineTransformPropagate.png
  __tests__/plots/static/forecast-range-area-line.ts
  __tests__/plots/static/fuel-line-encode-propagate.ts
  __tests__/plots/static/fuel-line-transform-propagate.ts
  __tests__/plots/static/index.ts
  src/composition/view.ts
  src/mark/boxplot.ts
  src/runtime/plot.ts
  src/transform/sample.ts
Labels: PR: unreviewed

#4645 fix(pie): add radius and inset to shape.style
  __tests__/integration/snapshots/animation/population2015-interval-wave-in-radius/interval0-0.png
  __tests__/integration/snapshots/animation/population2015-interval-wave-in-radius/interval0-1.png
  __tests__/plots/animation/index.ts
  __tests__/plots/animation/population2015-interval-wave-in-radius.ts
  src/animation/waveIn.ts
  src/shape/interval/color.ts
Labels: PR: partially-approved

#4644 fix(label): support view level labelTransform
  __tests__/integration/snapshots/static/weatherLineViewLabelTransform.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/weather-line-view-label-transform.ts
  src/runtime/plot.ts
  src/runtime/types/common.ts
Labels: PR: partially-approved

#4647 docs: error links in tooltip docs
  site/docs/api/interaction/tooltip.zh.md
Labels: PR: reviewed-approved

#4653 fix(tooltip): selected expected elements (close: #4650)
  __tests__/integration/api-mark-change-data-tooltip.spec.ts
  __tests__/integration/snapshots/api/markChangeDataTooltip.html
  __tests__/main.ts
  __tests__/plots/api/index.ts
  __tests__/plots/api/mark-change-data-tooltip.ts
  __tests__/plots/api/mark-change-data.ts
  src/interaction/native/utils.ts
Labels: PR: partially-approved

#4655 chore(version): bump to 5.0.0-beta.10
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4664 feat(scale): add constant
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/native/tooltip.ts
  src/runtime/mark.ts
  src/runtime/scale.ts
  src/runtime/transform.ts
  src/scale/constant.ts
  src/scale/index.ts
  src/spec/scale.ts
  src/stdlib/index.ts
Labels: PR: reviewed-approved

#4677 fix(ci): set --max-old-space-size
  __tests__/integration/utils/toMatchCanvasSnapshot.ts
  __tests__/plots/interaction/alphabet-interval-highlight-offset-polar.ts
  package.json
Labels: PR: reviewed-approved

#4680 chore(version): bump to 5.0.0-beta.11
  package.json
  site/package.json
Labels: PR: partially-approved

#4690 refactor(chart): rename context & node api to getContext and getNode (f…
  __tests__/plots/api/mark-change-data-tooltip.ts
  __tests__/plots/api/mark-change-data.ts
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/interaction.spec.ts
  site/docs/api/chart.zh.md
  site/docs/api/component/scrollbar.zh.md
  site/docs/api/component/slider.zh.md
  site/docs/api/mark/shape.zh.md
  site/docs/api/plugin/lottie.zh.md
  site/docs/manual/interaction.zh.md
  site/docs/manual/single-view/chart.zh.md
  site/docs/manual/theme/pattern.zh.md
  site/examples/annotation/annotation/demo/watermark.ts
  site/examples/plugin/lottie/demo/lottie.ts
  site/examples/theme/pattern/demo/custom-pattern-with-g-api.ts
  src/api/chart.ts
  src/api/composition/base.ts
  src/api/mark/base.ts
  src/api/node.ts
Labels: PR: reviewed-approved

#4689 feat(MarkBase): change the name from MarkBase to MarkNode (fix #4672)
  __tests__/unit/api/mark.spec.ts
  src/api/composition/base.ts
  src/api/composition/facetCircle.ts
  src/api/composition/facetRect.ts
  src/api/composition/geoPath.ts
  src/api/composition/geoView.ts
  src/api/composition/index.ts
  src/api/composition/repeatMatrix.ts
  src/api/composition/spaceFlex.ts
  src/api/composition/spaceLayer.ts
  src/api/composition/timingKeyframe.ts
  src/api/composition/view.ts
  src/api/index.ts
  src/api/mark/base.ts
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/index.ts
Labels: PR: reviewed-approved

#4697 fix(column): group produce non-constant columns
  __tests__/integration/snapshots/static/commitsPointGroupedConstant.png
  __tests__/plots/static/commits-point-grouped-constant.ts
  __tests__/plots/static/index.ts
  src/transform/groupN.ts
  src/transform/utils/helper.ts
Labels: PR: reviewed-approved

#4695 feat(mark): group animation options
  __tests__/plots/animation/alphabet-interval-non-animate-enter.ts
  __tests__/plots/animation/alphabet-interval-scale-in-y.ts
  __tests__/plots/animation/deaths-rose-stack-enter.ts
  __tests__/plots/animation/doughnut-purchases-line-path-in.ts
  __tests__/plots/animation/fruits-interval-stack-enter-color-x.ts
  __tests__/plots/animation/fruits-interval-stack-enter-color.ts
  __tests__/plots/animation/fruits-interval-stack-enter-defaults.ts
  __tests__/plots/animation/fruits-interval-stack-enter-x-color.ts
  __tests__/plots/animation/os-area-stack-enter.ts
  __tests__/plots/animation/polio-point-stack-enter.ts
  __tests__/plots/animation/population-interval-rose-keyframe.ts
  __tests__/plots/animation/population2015-interval-wave-in-radius.ts
  __tests__/plots/animation/profit-interval-range.ts
  __tests__/plots/animation/sold-interval-pie-keyframe.ts
  __tests__/plots/animation/stocks-keyframe.ts
  __tests__/plots/static/population2015-interval-pie.ts
  __tests__/unit/api/mark.spec.ts
  site/docs/api/animation/fadeIn.zh.md
  site/docs/api/animation/fadeOut.zh.md
  site/docs/api/animation/growInX.zh.md
  site/docs/api/animation/growInY.zh.md
  site/docs/api/animation/morphing.zh.md
  site/docs/api/animation/pathIn.zh.md
  site/docs/api/animation/scaleInX.zh.md
  site/docs/api/animation/scaleInY.zh.md
  site/docs/api/animation/scaleOutX.zh.md
  site/docs/api/animation/scaleOutY.zh.md
  site/docs/api/animation/waveIn.zh.md
  site/docs/api/animation/zoomIn.zh.md
  site/docs/api/animation/zoomOut.zh.md
  site/docs/manual/animation.zh.md
  site/docs/manual/more/use-in-framework.zh.md
  site/examples/animation/general/demo/fade.ts
  site/examples/animation/general/demo/path-in.ts
  site/examples/animation/general/demo/scale-x.ts
  site/examples/animation/general/demo/scale-y.ts
  site/examples/animation/general/demo/wave-in.ts
  site/examples/animation/general/demo/zoom-in.ts
  site/examples/animation/group/demo/area.ts
  site/examples/animation/group/demo/interval-polar.ts
  site/examples/animation/group/demo/interval.ts
  site/examples/animation/group/demo/line.ts
  site/examples/animation/group/demo/point.ts
  site/examples/animation/storytelling/demo/facet-keyframe.ts
  site/examples/general/radial/demo/apple-activity.ts
  site/examples/general/radial/demo/bar-cornered-radial.ts
  site/examples/general/radial/demo/bar-radial.ts
  site/examples/general/radial/demo/bar-stacked-radial.ts
  site/examples/general/radial/demo/donut.ts
  site/examples/general/radial/demo/pie.ts
  site/examples/general/radial/demo/rose-label.ts
  site/examples/general/radial/demo/rose.ts
  site/examples/general/radial/demo/spider-label.ts
  site/examples/plugin/lottie/demo/lottie.ts
  site/examples/theme/theme/demo/dark.ts
  src/composition/timingKeyframe.ts
  src/runtime/plot.ts
  src/runtime/transform.ts
  src/runtime/types/options.ts
  src/spec/geometry.ts
Labels: PR: partially-approved

#4700 fix(hocMark): the render problem in hoc mark.
  __tests__/integration/snapshots/static/homMultipleMark.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/sold-hom-multiple.ts
  src/runtime/plot.ts
Labels: PR: reviewed-approved

#4699 refactor: refactor performance test env
  scripts/bench/README.md
  scripts/bench/chart.html
  scripts/bench/chart.ts
  scripts/bench/data/alphabet.csv
  scripts/bench/main.ts
  scripts/bench/package.json
  scripts/bench/renderer.html
  scripts/bench/reports/intervalAlphabet-2023-2-27_11:30:9.json
  scripts/bench/reports/pointTemperatures-2023-2-27_10:19:34.json
  scripts/bench/reports/pointTemperatures-2023-2-27_10:19:47.json
  scripts/bench/reports/pointTemperatures-2023-2-27_11:30:1.json
  scripts/bench/reports/renderer-2023-2-27_13:2:53.json
  scripts/bench/server.ts
  scripts/bench/tests/chart/index.ts
  scripts/bench/tests/chart/interval-alphabet/d3-g-canvas.ts
  scripts/bench/tests/chart/interval-alphabet/d3-g-svg.ts
  scripts/bench/tests/chart/interval-alphabet/d3-svg.ts
  scripts/bench/tests/chart/interval-alphabet/echarts-canvas.ts
  scripts/bench/tests/chart/interval-alphabet/g2-v4-canvas.ts
  scripts/bench/tests/chart/interval-alphabet/g2-v5-canvas-spec.ts
  scripts/bench/tests/chart/interval-alphabet/index.ts
  scripts/bench/tests/chart/interval-alphabet/plot.ts
  scripts/bench/tests/chart/interval-alphabet/vega-lite-svg.ts
  scripts/bench/tests/chart/point-temperatures/d3-g-canvas.ts
  scripts/bench/tests/chart/point-temperatures/d3-g-svg.ts
  scripts/bench/tests/chart/point-temperatures/d3-svg.ts
  scripts/bench/tests/chart/point-temperatures/echarts-canvas.ts
  scripts/bench/tests/chart/point-temperatures/g2-v4-canvas.ts
  scripts/bench/tests/chart/point-temperatures/g2-v5-canvas-api.ts
  scripts/bench/tests/chart/point-temperatures/g2-v5-canvas-spec.ts
  scripts/bench/tests/chart/point-temperatures/index.ts
  scripts/bench/tests/chart/point-temperatures/plot.ts
  scripts/bench/tests/chart/point-temperatures/vega-lite-svg.ts
  scripts/bench/tests/chart/types.ts
  scripts/bench/tests/index.ts
  scripts/bench/tests/module/renderer/canvas.ts
  scripts/bench/tests/module/renderer/g-4.0.ts
  scripts/bench/tests/module/renderer/g.ts
  scripts/bench/tests/module/renderer/main.ts
  scripts/bench/tests/module/renderer/svg.ts
  scripts/bench/tsconfig.json
  scripts/bench/types.ts
  scripts/bench/utils.ts
  scripts/bench/vite.config.js
Labels: PR: reviewed-approved

#4703 feat(tooltip): support render (close: #4495)
  __tests__/integration/snapshots/tooltip/alphabet-interval-custom-dom/step0.html
  __tests__/integration/snapshots/tooltip/alphabet-interval-custom-dom/step1.html
  __tests__/integration/snapshots/tooltip/alphabet-interval-custom-string/step0.html
  __tests__/integration/snapshots/tooltip/alphabet-interval-custom-string/step1.html
  __tests__/integration/snapshots/tooltip/indices-line-custom/step0.html
  __tests__/integration/snapshots/tooltip/indices-line-custom/step1.html
  __tests__/plots/tooltip/alphabet-interval-custom-dom.ts
  __tests__/plots/tooltip/alphabet-interval-custom-string.ts
  __tests__/plots/tooltip/index.ts
  __tests__/plots/tooltip/indices-line-custom.ts
  src/interaction/native/tooltip.ts
  src/spec/geometry.ts
  src/spec/interaction.ts
Labels: PR: reviewed-approved

#4705 fix: snapshots
  __tests__/integration/snapshots/static/soldHOMMultiple.png
Labels: PR: reviewed-approved

#4709 feat(element): handle click event (close: #4665)
  __tests__/integration/chart-on-item-element.spec.ts
  __tests__/integration/chart-on-series-element.spec.ts
  __tests__/plots/api/chart-on-item-element.ts
  __tests__/plots/api/chart-on-series-element.ts
  __tests__/plots/api/index.ts
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/index.ts
  src/interaction/native/event.ts
  src/runtime/plot.ts
  src/runtime/types/component.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4712 chore: bumps to 5.0.0-beta.12
  package.json
  site/package.json
Labels: PR: partially-approved
