Repository antvis/G2, pull requests merged in 2023-05, with the labels that each got.

#4932 fix(transform): sort x only sort data in specified domain
  __tests__/integration/snapshots/static/alphabetIntervalSortXDomain.png
  __tests__/plots/static/alphabet-interval-sort-x-domain.ts
  __tests__/plots/static/index.ts
  src/transform/sort.ts
Labels: PR: reviewed-approved

#4933 feat(interaction): brushFilter emit filter event
  __tests__/integration/chart-on-brush-filter.spec.ts
  __tests__/integration/chart-on-series-element.spec.ts
  __tests__/integration/utils/event.ts
  __tests__/plots/api/chart-on-brush-filter.ts
  __tests__/plots/api/index.ts
  site/docs/spec/interaction/brushFilter.zh.md
  src/interaction/brushFilter.ts
  src/interaction/brushHighlight.ts
Labels: PR: reviewed-approved, v5

#4934 chore: bump to 5.0.5
  CHANGELOG.md
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4936 fix: chart.options changeData problem
  __tests__/integration/api-chart-options-change-data.spec.ts
  __tests__/integration/snapshots/api/chartOptionsChangeData.png
  __tests__/plots/api/chart-options-change-data.ts
  __tests__/plots/api/index.ts
  src/api/chart.ts
Labels: PR: reviewed-approved

#4940 fix: chart.theme as unrequired params
  __tests__/plots/api/chart-options.ts
  src/api/chart.ts
Labels: PR: reviewed-approved

#4943 fix(test): unhandled promise rejection
  __tests__/integration/chart-on-brush-filter.spec.ts
  __tests__/plots/api/chart-on-brush-filter.ts
  package.json
Labels: PR: unreviewed

#4941 feat: chart bind autoFit in render
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
Labels: PR: reviewed-approved

#4948 docs: 如何在 UMD 下使用非内置渲染器
  site/docs/spec/plugin/renderer.zh.md
Labels: PR: reviewed-approved

#4946 feat(interaction): support focus context
  __tests__/integration/api-chart-on-brush-filter.spec.ts
  __tests__/integration/api-chart-on-focus-context.spec.ts
  __tests__/integration/api-chart-on-item-element.spec.ts
  __tests__/integration/api-chart-on-series-element.spec.ts
  __tests__/integration/snapshots/api/chart-on-focus-context/step0-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step0-focus.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step1-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step1-focus.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step2-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step2-focus.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step3-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step3-focus.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step4-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step4-focus.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step5-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step5-focus.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step6-context.png
  __tests__/integration/snapshots/api/chart-on-focus-context/step6-focus.png
  __tests__/plots/api/chart-on-focus-context.ts
  __tests__/plots/api/index.ts
  package.json
  site/examples/interaction/interaction/demo/focus-context.ts
  site/examples/interaction/interaction/demo/meta.json
  src/interaction/brushFilter.ts
  src/interaction/brushHighlight.ts
  src/utils/scale.ts
Labels: PR: partially-approved

#4958 chore: bump to 5.0.6
  CHANGELOG.md
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4960 fix(legend-filter): funnel
  __tests__/integration/snapshots/interaction/alphabet-interval-funnel-legend-filter/step0.png
  __tests__/integration/snapshots/interaction/alphabet-interval-funnel-legend-filter/step1.png
  __tests__/plots/interaction/alphabet-interval-funnel-legend-filter.ts
  __tests__/plots/interaction/index.ts
  src/runtime/plot.ts
Labels: PR: reviewed-approved

#4962 fix(tooltip): rerender correctly
  __tests__/integration/snapshots/tooltip/alphabet-interval-tooltip-render-update/step0.html
  __tests__/integration/snapshots/tooltip/alphabet-interval-tooltip-render-update/step1.html
  __tests__/plots/tooltip/alphabet-interval-tooltip-render-update.ts
  __tests__/plots/tooltip/index.ts
  src/runtime/plot.ts
  src/transform/filter.ts
Labels: PR: partially-approved

#4949 feat: update gui and adapt to crossSize config
  __tests__/integration/snapshots/animation/population-interval-rose-keyframe/interval2-0.png
  __tests__/integration/snapshots/animation/population-interval-rose-keyframe/interval2-1.png
  __tests__/plots/animation/population-interval-rose-keyframe.ts
  __tests__/plots/interaction/appl-line-slider-filter-transpose.ts
  package.json
  site/docs/spec/component/axis.zh.md
  src/component/axis.ts
  src/component/axisX.ts
  src/component/axisY.ts
  src/theme/classic.ts
Labels: PR: partially-approved

#4968 fix: fix issue that legend category cannot update shape
  __tests__/integration/snapshots/api/chartChangeSize.png
  __tests__/plots/api/chart-change-size.ts
  src/component/legendCategory.ts
  src/component/utils.ts
Labels: PR: unreviewed
