Repository antvis/G2, pull requests merged in 2023-04, with the labels that each got.

#4856 Update size.zh.md
  site/docs/manual/single-view/size.zh.md
Labels: PR: reviewed-approved

#4857 fix(ci): lock version of canvas to 2.11.0
  __tests__/plots/interaction/penguins-point-highlight.ts
  package.json
Labels: PR: reviewed-approved

#4858 fix(fisheye): reset when pointerleave
  __tests__/integration/snapshots/interaction/gdp2-point-fisheye/step1.png
  __tests__/plots/interaction/gdp2-point-chart-fisheye.ts
  src/interaction/fisheye.ts
Labels: PR: reviewed-approved

#4855 fix(runtime): wait for the next tick to finish rendering (close: #4771)
  __tests__/integration/snapshots/interaction/penguins-point-highlight/step0.png
  __tests__/integration/utils/renderSpec.ts
  src/runtime/render.ts
Labels: PR: unreviewed

#4860 fix(tooltip): hide tooltip when move mask
  __tests__/integration/snapshots/tooltip/alphabet-interval-brush-tooltip/step1.html
  __tests__/plots/tooltip/alphabet-interval-brush-tooltip.ts
  __tests__/plots/tooltip/index.ts
  src/interaction/tooltip.ts
Labels: PR: partially-approved

#4861 fix: chart render type (#4853)
  src/api/chart.ts
Labels: PR: reviewed-approved

#4864 Update coordinate.zh.md
  site/docs/manual/single-view/coordinate.zh.md
Labels: PR: reviewed-approved

#4865 Update annotation.zh.md
  site/docs/manual/single-view/annotation.zh.md
Labels: PR: reviewed-approved

#4866 Update component.zh.md
  site/docs/manual/single-view/component.zh.md
Labels: PR: reviewed-approved

#4869 fix: update legend marker
  __tests__/integration/snapshots/animation/os-area-stack-enter/interval0-0.png
  __tests__/integration/snapshots/animation/os-area-stack-enter/interval0-1.png
  __tests__/integration/snapshots/animation/os-area-stack-enter/interval0-2.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-axis/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-axis/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-filter/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-filter/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-filter/step2.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-reverse/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-reverse/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-x-filter/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-x/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-y-filter/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-y/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step2.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step3.png
  __tests__/integration/snapshots/interaction/penguins-point-highlight/step0.png
  __tests__/integration/snapshots/interaction/points-point-regression-quad/step0.png
  __tests__/integration/snapshots/interaction/score-by-item-area-radar/step0.png
  __tests__/integration/snapshots/static/agesIntervalRadialStacked.png
  __tests__/integration/snapshots/static/agesIntervalRadialStackedSorted.png
  __tests__/integration/snapshots/static/alphabetIntervalDataDrivenStyled.png
  __tests__/integration/snapshots/static/cars2PointJitterY.png
  __tests__/integration/snapshots/static/housePricePointShapes.png
  __tests__/integration/snapshots/static/indicesLineChartScaleRelations.png
  __tests__/integration/snapshots/static/irisPointShapes.png
  __tests__/integration/snapshots/static/irisPointShapesDefaults.png
  __tests__/integration/snapshots/static/morleyBox.png
  __tests__/integration/snapshots/static/morleyBoxExtend.png
  __tests__/integration/snapshots/static/ordersLineMissingField.png
  __tests__/integration/snapshots/static/penguinsBoxPlotGroupedExtent.png
  __tests__/integration/snapshots/static/scoreByItemAreaSmoothRadar.png
  __tests__/integration/snapshots/static/stocksLineAggregateLabel.png
  __tests__/integration/snapshots/static/temperature1LineVarColor.png
  __tests__/integration/snapshots/static/titanic2PointPack.png
  __tests__/integration/snapshots/static/titanicPointPack.png
  __tests__/integration/snapshots/static/titanicPointPackNested.png
  __tests__/integration/snapshots/static/titanicPointPackSharedData.png
  __tests__/integration/snapshots/static/titanicPointPackSharedSize.png
  __tests__/integration/snapshots/static/weatherLineRepeatMatrixCol.png
  package.json
Labels: PR: reviewed-approved

#4871 chore: update version to 5.0.2
  CHANGELOG.md
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4874 Update overview.zh.md
  site/docs/spec/overview.zh.md
Labels: PR: reviewed-approved

#4872 docs(site): fix spec timingKeyframe url
  site/docs/api/overview.zh.md
  site/docs/api/timingKeyframe.en.md
  site/docs/api/timingKeyframe.zh.md
  site/docs/spec/overview.zh.md
Labels: PR: reviewed-approved

#4876 fix: 文档中的sort->sortBy
  site/docs/spec/data/sortBy.zh.md
Labels: PR: reviewed-approved

#4880 docs: correct typo docs
  site/docs/spec/component/axis.zh.md
Labels: PR: reviewed-approved

#4875 fix(interval): fix interval render funnel (#4868)
  __tests__/integration/snapshots/static/alphabetIntervalFunnel.png
  __tests__/integration/snapshots/static/alphabetIntervalPyramid.png
  __tests__/plots/static/alphabet-interval-funnel.ts
  __tests__/plots/static/alphabet-interval-pyramid.ts
  __tests__/plots/static/index.ts
  src/shape/interval/funnel.ts
  src/shape/interval/pyramid.ts
Labels: PR: reviewed-approved

#4887 chore: update to 5.0.3
  CHANGELOG.md
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4884 docs: add legend layout docs
  site/docs/spec/component/legend.zh.md
Labels: PR: reviewed-approved

#4890 docs: fix simple typo, transfrom -> transform
  site/docs/spec/transform/sample.zh.md
Labels: PR: reviewed-approved

#4899 fix(OOM): clear interaction and cancel animation when rerendering
  __tests__/integration/api-chart-render-clear-animation.spec.ts
  __tests__/plots/api/chart-render-clear-animation.ts
  __tests__/plots/api/index.ts
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/interaction.spec.ts
  src/interaction/legendFilter.ts
  src/runtime/plot.ts
Labels: PR: reviewed-approved

#4901 feat(scale): tickCount of log scale support -1
  __tests__/integration/snapshots/static/mockPointLogTicks.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/mock-point-log-ticks.ts
  site/docs/spec/mark/shape.zh.md
Labels: PR: unreviewed

#4906 fix: update legend component inferring strategies
  __tests__/integration/snapshots/static/bodyPointScatterPlot.png
  __tests__/integration/snapshots/static/moviesPointBin.png
  __tests__/plots/static/body-point-scatter-plot.ts
  __tests__/plots/static/index.ts
  src/component/constant.ts
  src/component/legendContinuousBlockSize.ts
  src/component/legendContinuousSize.ts
  src/runtime/component.ts
Labels: PR: reviewed-approved, bugfix

#4828 chore: add gpt for code review
  .github/workflows/cr.yml
Labels: PR: unreviewed

#4911 fix: labelFilter 参数与 labelFormatter 保持一致
  __tests__/integration/snapshots/static/aaplLineBasicSampleLabelFilter.png
  __tests__/plots/static/aapl-line-basic-sample-label-filter.ts
  __tests__/plots/static/index.ts
  src/component/axis.ts
Labels: PR: reviewed-approved

#4914 fix(label): support specified transform (close: #4881)
  __tests__/integration/snapshots/static/alphabetIntervalLabelRotate.png
  __tests__/plots/static/alphabet-interval-label-rotate.ts
  __tests__/plots/static/index.ts
  src/shape/label/label.ts
  src/shape/text/advance.ts
Labels: PR: unreviewed

#4912 fix(demo): disable series tooltip for regression
  __tests__/integration/snapshots/tooltip/points-point-regression-quad/step0.html
  __tests__/plots/tooltip/index.ts
  __tests__/plots/tooltip/points-point-regression-quad.ts
  site/examples/analysis/regression/demo/exponential-regression.ts
  site/examples/analysis/regression/demo/linear-regression.ts
  site/examples/analysis/regression/demo/logarithmic-regression.ts
  site/examples/analysis/regression/demo/polynomial-regression.ts
  site/examples/analysis/regression/demo/quadratic-regression.ts
  src/interaction/tooltip.ts
Labels: PR: partially-approved

#4916 chore(version): update to 5.0.4
  CHANGELOG.md
  package.json
  site/package.json
Labels: PR: partially-approved

#4918 fix(axis): order of ticks for transposed x axis
  __tests__/integration/snapshots/interaction/points-point-regression-quad-transpose/step0.png
  __tests__/integration/snapshots/static/aaplAreaMissingDataTranspose.png
  __tests__/integration/snapshots/static/aaplLineBasicTranspose.png
  __tests__/integration/snapshots/static/aaplLineSliderTransponsed.png
  __tests__/plots/static/aapl-line-basic-transpose.ts
  __tests__/plots/static/index.ts
  src/component/axis.ts
Labels: PR: reviewed-approved

#4925 fix(chart): new Chart() do not set default view key
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
  src/api/composition/base.ts
Labels: PR: reviewed-approved

#4929 docs(site): add spec tab for examples
  site/.dumi/global.ts
  site/.dumirc.ts
  site/examples/analysis/bin/demo/bin-color.ts
  site/examples/component/legend/demo/continuous.ts
  site/examples/composition/facet/demo/rect.ts
  site/examples/composition/space/demo/space-flex.ts
  site/examples/composition/space/demo/space-layer.ts
  site/examples/general/area/demo/area-band.ts
  site/examples/general/cell/demo/cell-aggregated.ts
  site/examples/general/cell/demo/cell-heatmap.ts
  site/examples/general/line/demo/line-gradient-encoding.ts
  site/examples/general/parallel/demo/line-parallel-horizontal.ts
  site/examples/general/parallel/demo/line-parallel-vertical.ts
  site/examples/general/point/demo/point-sequential.ts
  site/examples/general/radar/demo/parallel-radar.ts
  site/examples/general/vector/demo/wind.ts
  site/examples/geo/geo/demo/choropleth-usa.ts
  site/examples/geo/geo/demo/projection-comparison.ts
  site/examples/geo/geo/demo/world-map.ts
  site/examples/style/pattern/demo/custom-pattern-with-canvas.ts
  site/examples/style/pattern/demo/custom-pattern-with-g-api.ts
  site/examples/style/theme/demo/layout-area.ts
  src/runtime/render.ts
Labels: PR: partially-approved
