Repository antvis/G2, pull requests merged in 2023-03, with the labels that each got.

#4707 feat(mark): chart support HOM mark
  __tests__/integration/api-chart-hom-mark.spec.ts
  __tests__/integration/snapshots/api/chartHOMMark.png
  __tests__/plots/api/chart-hom-mark.ts
  __tests__/plots/api/index.ts
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/api/props.ts
  src/spec/geometry.ts
Labels: PR: reviewed-approved

#4678 fix(animate): 部分动画覆盖 callback 配置导致外部的 callback 配置失效
  src/animate/animation/sector-path-update.ts
  src/animate/animation/wave-in.ts
  src/animate/animation/zoom.ts
  tests/unit/animate/animate-callback-spec.ts
Labels: PR: reviewed-approved, bugfix

#4716 feat(event): add more bubbles event
  __tests__/integration/chart-on-item-element.spec.ts
  __tests__/integration/chart-on-series-element.spec.ts
  __tests__/integration/utils/event.ts
  __tests__/plots/api/chart-on-item-element.ts
  src/interaction/native/event.ts
Labels: PR: partially-approved

#4704 feat(component): add component.style
  __tests__/integration/snapshots/static/alphabetIntervalTitle.png
  __tests__/plots/animation/population-interval-rose-keyframe.ts
  __tests__/plots/interaction/cars3-line-brush-axis.ts
  __tests__/plots/interaction/cars3-line-vertical-brush-axis.ts
  __tests__/plots/static/alphabet-interval-title.ts
  __tests__/plots/static/cars3-line-parallel-horizontal.ts
  __tests__/plots/static/cars3-line-parallel-vertical.ts
  __tests__/plots/static/cars3-line-radar.ts
  __tests__/plots/static/income-statement-by-region-interval-custom.ts
  __tests__/plots/static/indices-line-point-scale-key.ts
  __tests__/plots/static/metros-link-trending.ts
  __tests__/plots/static/movies-interval-multiple-measure.ts
  __tests__/plots/static/score-by-item-area-radar-custom.ts
  __tests__/plots/static/weather-line-area-dual-axis.ts
  __tests__/plots/static/weather-line-multi-axes.ts
  __tests__/plots/static/weather-line-multi-scrollbar.ts
  __tests__/plots/static/weather-line-multi-slider.ts
  __tests__/plots/static/world-history-interval-multi-tick-count.ts
  __tests__/plots/tooltip/cars3-line-xd.ts
  __tests__/plots/tooltip/weather-line-interval.ts
  site/docs/api/component/category.zh.md
  site/docs/manual/single-view/coordinate.zh.md
  site/examples/annotation/annotation/demo/interval-connector.ts
  site/examples/general/dual/demo/dual-aggregated-line-area.ts
  site/examples/general/dual/demo/line-bar.ts
  site/examples/general/dual/demo/multi-line.ts
  site/examples/general/interval/demo/bar-flex.ts
  site/examples/general/interval/demo/bar-stacked.ts
  site/examples/general/line/demo/line-parallel-horizontal.ts
  site/examples/general/line/demo/line-parallel-vertical.ts
  site/examples/general/link/demo/link.ts
  site/examples/general/radial/demo/area-radial.ts
  site/examples/general/radial/demo/parallel-radar.ts
  site/examples/plugin/rough/demo/interval.ts
  site/examples/plugin/rough/demo/line.ts
  site/examples/plugin/rough/demo/point.ts
  src/component/axis.ts
  src/component/scrollbar.ts
  src/component/slider.ts
  src/component/title.ts
  src/interaction/native/brushFilter.ts
  src/interaction/native/sliderFilter.ts
  src/runtime/types/common.ts
  src/runtime/types/theme.ts
Labels: PR: partially-approved

#4720 feat: style.shape support function
  __tests__/integration/snapshots/static/soldIntervalCustomShape.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/sold-interval-custom-shape.ts
  src/runtime/plot.ts
Labels: PR: reviewed-approved

#4721 feat: 新增 chart options 并移除 chart getOptions
  .editorconfig
  .eslintignore
  __tests__/integration/api-chart-options.spec.ts
  __tests__/integration/snapshots/api/chart-options/step0.png
  __tests__/integration/snapshots/api/chart-options/step1.png
  __tests__/plots/api/chart-options.ts
  __tests__/plots/api/index.ts
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
Labels: PR: reviewed-approved

#4728 test(chart): chart.options(options) should return this
  __tests__/plots/api/chart-options.ts
  __tests__/unit/api/chart.spec.ts
Labels: PR: partially-approved

#4736 chore: update version to 5.0.0-beta.13
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4738 ci: when ci failed, it will upload to oss server
  .github/workflows/build.yml
  package.json
  scripts/uploadSnapshot.js
Labels: PR: reviewed-approved

#4740 fix(tests): update failing snapshots
  __tests__/integration/snapshots/interaction/indices-line-chart-facet/step0.png
Labels: PR: unreviewed

#4743 fix(regression): add missing euler number
  site/examples/analysis/regression/demo/exponential-regression.ts
Labels: PR: reviewed-approved

#4748 fix(tooltip): multi-view and hollow shape
  __tests__/integration/snapshots/static/alphabetIntervalSpaceLayer.png
  __tests__/plots/static/alphabet-interval-space-layer.ts
  site/examples/composition/space/demo/space-layer.ts
  src/composition/spaceLayer.ts
  src/interaction/tooltip.ts
  src/shape/interval/color.ts
  src/shape/point/color.ts
  src/spec/composition.ts
  src/spec/mark.ts
Labels: PR: partially-approved

#4749 feat(tooltip): for transpose and polar
  __tests__/integration/snapshots/interaction/points-point-regression-quad-transpose/step0.png
  __tests__/integration/snapshots/interaction/score-by-item-area-radar/step0.png
  __tests__/integration/snapshots/tooltip/forecast-range-area-line-transpose/step0.html
  __tests__/integration/snapshots/tooltip/score-by-item-area-radar/step0.html
  __tests__/plots/interaction/index.ts
  __tests__/plots/interaction/points-point-regression-quad-transpose.ts
  __tests__/plots/interaction/score-by-item-area-radar.ts
  __tests__/plots/tooltip/forecast-range-area-line-transpose.ts
  __tests__/plots/tooltip/index.ts
  __tests__/plots/tooltip/score-by-item-area-radar.ts
  site/examples/general/radial/demo/area-radial.ts
  src/interaction/tooltip.ts
Labels: PR: partially-approved

#4739 feat: gauge mark
  __tests__/integration/snapshots/static/gaugeCustomColor.png
  __tests__/integration/snapshots/static/gaugeCustomShape.png
  __tests__/integration/snapshots/static/gaugeDefault.png
  __tests__/plots/static/gauge-custom-color.ts
  __tests__/plots/static/gauge-custom-shape.ts
  __tests__/plots/static/gauge-default.ts
  __tests__/plots/static/index.ts
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/mark.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/api/mark/index.ts
  src/api/mark/mark.ts
  src/mark/gauge.ts
  src/mark/index.ts
  src/shape/point/color.ts
  src/shape/utils.ts
  src/spec/mark.ts
  src/stdlib/index.ts
  src/utils/coordinate.ts
  src/utils/helper.ts
Labels: PR: unreviewed

#4754 fix: fix the default length of components
  __tests__/integration/snapshots/interaction/settle-weather-cell-brush-filter/step0.png
  __tests__/integration/snapshots/interaction/settle-weather-cell-brush-filter/step1.png
  __tests__/integration/snapshots/static/commitsPointGrouped.png
  __tests__/integration/snapshots/static/commitsPointGroupedConstant.png
  __tests__/integration/snapshots/static/haleChoroplethWorld.png
  __tests__/integration/snapshots/static/moviesPointBin.png
  __tests__/integration/snapshots/static/moviesRectBin.png
  __tests__/integration/snapshots/static/moviesRectBinOpacity.png
  __tests__/integration/snapshots/static/salaryHeatmapScaleLinear.png
  __tests__/integration/snapshots/static/salaryHeatmapScaleQuantize.png
  __tests__/integration/snapshots/static/salaryHeatmapScaleThreshold.png
  __tests__/integration/snapshots/static/settleWeatherCellGrouped.png
  __tests__/integration/snapshots/static/unemploymentChoropleth.png
  __tests__/integration/snapshots/static/vaccinesCellScaleRelation.png
  __tests__/plots/static/hale-choropleth-world.ts
  __tests__/plots/static/unemployment-choropleth.ts
  site/examples/geo/geo/demo/choropleth-usa.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/component/utils.ts
Labels: PR: reviewed-approved

#4750 docs(tooltip): optimize tooltip in docs
  __tests__/integration/snapshots/interaction/points-point-regression-quad-inset/step0.png
  __tests__/plots/interaction/index.ts
  __tests__/plots/interaction/points-point-regression-quad-inset.ts
  site/examples/analysis/group/demo/bar-aggregated.ts
  site/examples/annotation/annotation/demo/interval-connector.ts
  site/examples/annotation/annotation/demo/interval-mean-line.ts
  site/examples/annotation/annotation/demo/quadrant-scatter.ts
  site/examples/annotation/annotation/demo/revenue-flow-waterfall.ts
  site/examples/annotation/annotation/demo/watermark.ts
  site/examples/general/area/demo/cascade-area.ts
  site/examples/general/area/demo/percentage-area.ts
  site/examples/general/cell/demo/cell-heatmap.ts
  site/examples/general/interval/demo/bar-marimekko.ts
  site/examples/general/interval/demo/bar-normalized-stacked.ts
  site/examples/general/line/demo/line-aggregated-label.ts
  site/examples/general/line/demo/line-candle-stick.ts
  site/examples/general/line/demo/line-normalized.ts
  site/examples/general/line/demo/line-parallel-horizontal.ts
  site/examples/general/line/demo/line-parallel-vertical.ts
  site/examples/general/link/demo/link.ts
  site/examples/general/radial/demo/parallel-radar.ts
  site/examples/general/radial/demo/polar-box.ts
  site/examples/general/radial/demo/radar.ts
  site/examples/general/radial/demo/rose-label.ts
  site/examples/general/radial/demo/rose.ts
  site/examples/general/vector/demo/poisson.ts
  site/examples/general/vector/demo/wind.ts
  src/interaction/tooltip.ts
Labels: PR: partially-approved

#4753 refactor(composite): add maybeAnimation
  __tests__/unit/api/mark.spec.ts
  src/geo/geoView.ts
  src/mark/boxplot.ts
  src/mark/forceGraph.ts
  src/mark/pack.ts
  src/mark/sankey.ts
  src/mark/tree.ts
  src/mark/treemap.ts
  src/runtime/transform.ts
  src/spec/mark.ts
  src/utils/mark.ts
Labels: PR: reviewed-approved

#4755 chore: v5.0.0-rc.1
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4756 feat: undefined scales fusion
  __tests__/integration/snapshots/api/registerShape.png
  src/component/legendCategory.ts
  src/runtime/component.ts
Labels: PR: reviewed-approved

#4759 docs: update site demos of sketching
  site/examples/plugin/rough/demo/interval.ts
  site/examples/plugin/rough/demo/line.ts
  site/examples/plugin/rough/demo/point.ts
Labels: PR: reviewed-approved

#4714 fix(interval): 避免 background 在交互时被捕捉导致错误(如 element-selected)
  src/geometry/shape/interval/hollow-rect.ts
  src/geometry/shape/interval/index.ts
Labels: PR: partially-approved, bugfix

#4764 fix: Horizontal cylindrical bar display error
  .gitignore
  __tests__/integration/snapshots/static/penguinsIntervalTransposeGroupColor.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/penguins-interval-transpose-group-color.ts
  src/shape/interval/color.ts
Labels: bug, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved

#4766 docs: update contribution.md
  CONTRIBUTING.md
Labels: PR: partially-approved

#4773 docs: adjust site demo
  site/examples/annotation/annotation/demo/meta.json
  site/examples/annotation/annotation/index.en.md
  site/examples/annotation/annotation/index.zh.md
  site/examples/annotation/connector/demo/interval-connector.ts
  site/examples/annotation/connector/demo/meta.json
  site/examples/annotation/connector/demo/revenue-flow-waterfall.ts
  site/examples/annotation/connector/index.en.md
  site/examples/annotation/connector/index.zh.md
  site/examples/annotation/line/demo/histogram-mean-line.ts
  site/examples/annotation/line/demo/interval-mean-line.ts
  site/examples/annotation/line/demo/interval-threshold.ts
  site/examples/annotation/line/demo/meta.json
  site/examples/annotation/line/demo/point-line.ts
  site/examples/annotation/line/demo/point-point.ts
  site/examples/annotation/line/demo/quadrant-scatter.ts
  site/examples/annotation/line/index.en.md
  site/examples/annotation/line/index.zh.md
  site/examples/annotation/range/demo/line-range.ts
  site/examples/annotation/range/demo/meta.json
  site/examples/annotation/range/demo/point-range.ts
  site/examples/annotation/range/index.en.md
  site/examples/annotation/range/index.zh.md
  site/examples/annotation/shape/demo/interval-point.ts
  site/examples/annotation/shape/demo/line-badge.ts
  site/examples/annotation/shape/demo/meta.json
  site/examples/annotation/shape/demo/watermark.ts
  site/examples/annotation/shape/index.en.md
  site/examples/annotation/shape/index.zh.md
  site/examples/annotation/text/demo/line-text.ts
  site/examples/annotation/text/demo/meta.json
  site/examples/annotation/text/index.en.md
  site/examples/annotation/text/index.zh.md
  site/examples/general/gauge/demo/gauge-custom-shape.ts
  site/examples/general/gauge/demo/gauge-default.ts
  site/examples/general/gauge/demo/meta.json
  site/examples/general/gauge/index.en.md
  site/examples/general/interval/demo/meta.json
  site/examples/general/rose/demo/meta.json
  site/examples/general/rose/demo/stacked-rose.ts
  site/examples/renderer/renderer/demo/meta.json
  site/examples/style/theme/demo/meta.json
  src/mark/gauge.ts
Labels: PR: partially-approved

#4772 fix: demo bug
  __tests__/integration/api-chart-options.spec.ts
  __tests__/integration/api-view-facetCircle.spec.ts
  __tests__/integration/snapshots/api/viewFacetCircle.png
  __tests__/plots/api/chart-options.ts
  __tests__/plots/api/index.ts
  __tests__/plots/api/view-facetCircle.ts
  site/examples/annotation/line/demo/point-line.ts
  site/examples/annotation/line/demo/quadrant-scatter.ts
  site/examples/annotation/range/demo/point-range.ts
  src/api/chart.ts
Labels: PR: reviewed-approved

#4776 chore: v4.2.10
  CHANGELOG.md
  package.json
  src/core.ts
Labels: PR: reviewed-approved, ignore-for-release

#4775 docs: update manual
  README.en-US.md
  README.md
  site/docs/manual/animation.zh.md
  site/docs/manual/customization.zh.md
  site/docs/manual/getting-started.zh.md
  site/docs/manual/interaction.zh.md
  site/docs/manual/more/experimental-spec-api.en.md
  site/docs/manual/more/experimental-spec-api.zh.md
  site/docs/manual/more/use-in-framework.en.md
  site/docs/manual/more/use-in-framework.zh.md
  site/docs/manual/single-view/annotation.en.md
  site/docs/manual/single-view/annotation.zh.md
  site/docs/manual/single-view/chart.zh.md
  site/docs/manual/single-view/component.en.md
  site/docs/manual/single-view/component.zh.md
  site/docs/manual/single-view/coordinate.zh.md
  site/docs/manual/single-view/data.zh.md
  site/docs/manual/single-view/label.en.md
  site/docs/manual/single-view/label.zh.md
  site/docs/manual/single-view/mark.zh.md
  site/docs/manual/single-view/scale.zh.md
  site/docs/manual/single-view/size.zh.md
  site/docs/manual/single-view/transform.zh.md
  site/docs/manual/theme/theme.zh.md
  site/docs/manual/view-composition.zh.md
  src/spec/scale.ts
Labels: PR: reviewed-approved

#4774 docs: add interaction and components demos
  __tests__/data/gold.png
  __tests__/plots/api/chart-axis-label-formatter.ts
  __tests__/plots/api/index.ts
  site/.dumirc.ts
  site/examples/component/component/demo/axis.ts
  site/examples/component/component/demo/category.ts
  site/examples/component/component/demo/continuous.ts
  site/examples/component/component/demo/meta.json
  site/examples/interaction/interaction/demo/brush.ts
  site/examples/interaction/interaction/demo/highlight.ts
  site/examples/interaction/interaction/demo/legend.ts
  site/examples/interaction/interaction/demo/meta.json
  site/examples/interaction/interaction/demo/select.ts
  site/examples/interaction/interaction/demo/slider.ts
  src/component/axis.ts
Labels: PR: reviewed-approved

#4777 fix: catch render exceptions and throw them
  __tests__/unit/api/chart.spec.ts
  site/docs/manual/single-view/chart.zh.md
  src/api/chart.ts
  src/runtime/render.ts
Labels: PR: partially-approved

#4784 docs: add migration
  .gitignore
  site/docs/manual/more/migration-from-g2v4.en.md
  site/docs/manual/more/migration-from-g2v4.zh.md
  site/examples/component/component/demo/category.ts
  site/examples/component/component/demo/continuous.ts
  site/examples/component/component/demo/meta.json
  site/examples/style/theme/demo/layout-area.ts
Labels: PR: reviewed-approved

#4786 fix(animation): facet keyframe
  __tests__/integration/snapshots/animation/stocks-keyframe/interval3-0.png
  __tests__/integration/snapshots/animation/stocks-keyframe/interval3-1.png
  src/runtime/plot.ts
  src/utils/helper.ts
Labels: PR: partially-approved

#4787 feat(interaction): add sliderFilter to defaults
  __tests__/plots/interaction/appl-line-slider-filter.ts
  site/examples/interaction/interaction/demo/slider.ts
  src/interaction/sliderFilter.ts
  src/runtime/plot.ts
Labels: PR: reviewed-approved

#4788 feat(interaction): add legendFilter to defaults
  __tests__/integration/snapshots/interaction/population-interval-diverging/step0.png
  __tests__/integration/snapshots/interaction/state-ages-interval-normalized/step0.png
  __tests__/plots/interaction/index.ts
  __tests__/plots/interaction/population-interval-diverging.ts
  __tests__/plots/interaction/profit-interval-custom-legend-filter.ts
  __tests__/plots/interaction/profit-interval-legend-filter-ordinal.ts
  __tests__/plots/interaction/stateages-interval-normalized.ts
  __tests__/plots/interaction/temperatures-line-legend-filter-ordinal.ts
  site/examples/annotation/range/demo/line-range.ts
  site/examples/general/area/demo/cascade-area.ts
  site/examples/general/area/demo/label.ts
  site/examples/general/candlestick/demo/line-candle-stick.ts
  site/examples/general/interval/demo/bar-stacked-diverging-rounded.ts
  site/examples/style/theme/demo/dark.ts
  src/interaction/legendFilter.ts
  src/mark/utils.ts
  src/runtime/plot.ts
  src/transform/filter.ts
Labels: PR: reviewed-approved

#4790 docs: add tooltip, color, interaction docs
  __tests__/integration/chart-on-item-element.spec.ts
  package.json
  site/.dumi/global.ts
  site/.dumirc.ts
  site/docs/api/component/tooltip.en.md
  site/docs/api/component/tooltip.zh.md
  site/docs/api/palette.en.md
  site/docs/api/palette.zh.md
  site/docs/manual/animation.en.md
  site/docs/manual/animation.zh.md
  site/docs/manual/color.en.md
  site/docs/manual/color.zh.md
  site/docs/manual/event.en.md
  site/docs/manual/event.zh.md
  site/docs/manual/interaction.en.md
  site/docs/manual/interaction.zh.md
  site/docs/manual/single-view/tooltip.en.md
  site/docs/manual/single-view/tooltip.zh.md
  site/examples/analysis/bin/demo/bin-color.ts
  site/examples/component/component/demo/category.ts
  site/examples/interaction/interaction/demo/meta.json
  site/examples/interaction/interaction/demo/tooltip-render.ts
  site/scripts/palette.ts
  src/api/chart.ts
  src/index.ts
  src/interaction/event.ts
  src/interaction/tooltip.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/spec/interaction.ts
  src/utils/event.ts
Labels: PR: reviewed-approved

#4791 chore: update version to 5.0.0-rc.2
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4779 refactor(chart): update chart clear & destroy api
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
  src/runtime/render.ts
Labels: PR: partially-approved

#4795 docs: adjust the architecture of examples in website
  site/.dumirc.ts
Labels: PR: reviewed-approved

#4798 fix(theme): chart theme as requried key
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
  src/runtime/render.ts
  src/spec/theme.ts
Labels: PR: reviewed-approved

#4800 docs: adjust annotation line demo
  site/examples/annotation/line/demo/histogram-mean-line.ts
  site/examples/annotation/line/demo/interval-mean-line.ts
  site/examples/annotation/line/demo/interval-threshold.ts
  site/examples/annotation/line/demo/point-line.ts
Labels: PR: reviewed-approved

#4803 docs: update annotation demo
  site/examples/annotation/line/demo/anomaly-area-line.ts
  site/examples/annotation/line/demo/meta.json
Labels: PR: reviewed-approved

#4799 feat(legend): emit legend filter
  __tests__/integration/api-chart-emit-legend-filter.spec.ts
  __tests__/integration/snapshots/api/chart-emit-legend-filter/step0.png
  __tests__/integration/snapshots/interaction/profit-interval-brush-filter/step0.png
  __tests__/integration/snapshots/interaction/profit-interval-brush-filter/step2.png
  __tests__/plots/animation/aapl-area-keyframe.ts
  __tests__/plots/animation/iris-point-shapes-keyframe.ts
  __tests__/plots/animation/people-interval-split-merge.ts
  __tests__/plots/animation/polio-point-stack-enter.ts
  __tests__/plots/animation/sold-interval-keyframe.ts
  __tests__/plots/api/chart-emit-legend-filter.ts
  __tests__/plots/api/index.ts
  __tests__/plots/interaction/profit-interval-brush-filter.ts
  __tests__/unit/api/chart.spec.ts
  jest.config.js
  site/examples/component/axis/demo/axis.ts
  site/examples/component/axis/demo/meta.json
  site/examples/component/axis/index.en.md
  site/examples/component/axis/index.zh.md
  site/examples/component/component/index.en.md
  site/examples/component/component/index.zh.md
  site/examples/component/legend/demo/category.ts
  site/examples/component/legend/demo/continuous.ts
  site/examples/component/legend/demo/custom.ts
  site/examples/component/legend/demo/meta.json
  site/examples/component/legend/index.en.md
  site/examples/component/legend/index.zh.md
  src/api/composition/base.ts
  src/interaction/legendFilter.ts
  src/runtime/types/component.ts
Labels: PR: unreviewed

#4805 fix: fix some issues about components
  __tests__/integration/snapshots/animation/deaths-rose-stack-enter/interval0-0.png
  __tests__/integration/snapshots/animation/deaths-rose-stack-enter/interval0-1.png
  __tests__/integration/snapshots/animation/deaths-rose-stack-enter/interval0-2.png
  __tests__/integration/snapshots/animation/population-interval-rose-keyframe/interval2-0.png
  __tests__/integration/snapshots/animation/population-interval-rose-keyframe/interval2-1.png
  __tests__/integration/snapshots/animation/population-interval-rose-keyframe/interval2-2.png
  __tests__/integration/snapshots/animation/population-interval-rose-keyframe/interval2-3.png
  __tests__/integration/snapshots/interaction/cars3-line-brush-axis/step0.png
  __tests__/integration/snapshots/interaction/cars3-line-brush-axis/step1.png
  __tests__/integration/snapshots/interaction/cars3-line-vertical-brush-axis/step0.png
  __tests__/integration/snapshots/interaction/cars3-line-vertical-brush-axis/step1.png
  __tests__/integration/snapshots/interaction/score-by-item-area-radar/step0.png
  __tests__/integration/snapshots/static/agesIntervalRadialStacked.png
  __tests__/integration/snapshots/static/agesIntervalRadialStackedSorted.png
  __tests__/integration/snapshots/static/cars3LineParallelHorizontal.png
  __tests__/integration/snapshots/static/githubStarIntervalRadialLabel.png
  __tests__/integration/snapshots/static/populationIntervalRose.png
  __tests__/integration/snapshots/static/question8IntervalRadialGradientColor.png
  __tests__/integration/snapshots/static/scoreByItemAreaRadar.png
  __tests__/integration/snapshots/static/scoreByItemAreaRadarCustom.png
  __tests__/integration/snapshots/static/scoreByItemAreaSmoothRadar.png
  __tests__/integration/snapshots/static/seasonalWeatherAreaRadial.png
  __tests__/integration/snapshots/static/sepalBoxPolarBox.png
  __tests__/integration/snapshots/static/sepalBoxSimpleBox.png
  __tests__/plots/interaction/cars3-line-brush-axis.ts
  __tests__/plots/interaction/cars3-line-vertical-brush-axis.ts
  __tests__/plots/interaction/score-by-item-area-radar.ts
  __tests__/plots/static/cars3-line-parallel-horizontal.ts
  __tests__/plots/static/cars3-line-parallel-vertical.ts
  __tests__/plots/static/question8-interval-radial-gradient-color.ts
  __tests__/plots/static/score-by-item-area-radar-custom.ts
  __tests__/plots/static/score-by-item-area-radar.ts
  __tests__/plots/static/score-by-item-area-smooth-radar.ts
  __tests__/plots/static/sepal-box-polar-box.ts
  __tests__/plots/static/world-history-interval-multi-tick-count.ts
  __tests__/plots/tooltip/score-by-item-area-radar.ts
  site/docs/spec/component/axis.zh.md
  site/docs/spec/component/continuous.zh.md
  site/docs/spec/component/slider.zh.md
  site/docs/spec/interaction/tooltip.zh.md
  site/examples/component/legend/demo/continuous.ts
  src/component/axis.ts
  src/component/axisRadar.ts
  src/component/axisX.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/component/legendContinuousBlockSize.ts
  src/component/legendContinuousSize.ts
  src/component/utils.ts
  src/theme/academy.ts
  src/theme/dark.ts
  src/theme/light.ts
Labels: PR: reviewed-approved

#4806 docs(manual): optimize docs
  site/docs/manual/color.zh.md
  site/docs/manual/event.zh.md
  site/docs/manual/introduction.zh.md
  site/docs/manual/more/experimental-spec-api.zh.md
  site/docs/manual/more/migration-from-g2v4.zh.md
  site/docs/manual/single-view/annotation.zh.md
  site/docs/manual/single-view/api.zh.md
  site/docs/manual/single-view/chart.zh.md
  site/docs/manual/single-view/component.en.md
  site/docs/manual/single-view/component.zh.md
  site/docs/manual/single-view/coordinate.zh.md
  site/docs/manual/single-view/data.zh.md
  site/docs/manual/single-view/label.zh.md
  site/docs/manual/single-view/mark.zh.md
  site/docs/manual/single-view/scale.zh.md
  site/docs/manual/single-view/tooltip.zh.md
  site/docs/manual/single-view/transform.zh.md
  site/docs/manual/theme/pattern.zh.md
  site/docs/spec/palette.zh.md
  site/scripts/palette.ts
Labels: PR: unreviewed

#4804 docs: refactor site api
  site/docs/api/chart.zh.md
  site/docs/api/facetCircle.en.md
  site/docs/api/facetCircle.zh.md
  site/docs/api/facetRect.en.md
  site/docs/api/facetRect.zh.md
  site/docs/api/geoView.en.md
  site/docs/api/geoView.zh.md
  site/docs/api/mark.en.md
  site/docs/api/mark.zh.md
  site/docs/api/overview.zh.md
  site/docs/api/repeatMatrix.en.md
  site/docs/api/repeatMatrix.zh.md
  site/docs/api/spaceFlex.en.md
  site/docs/api/spaceFlex.zh.md
  site/docs/api/spaceLayer.en.md
  site/docs/api/spaceLayer.zh.md
  site/docs/api/timingKeyFrame.en.md
  site/docs/api/timingKeyFrame.zh.md
  site/docs/api/view.en.md
  site/docs/api/view.zh.md
Labels: PR: reviewed-approved

#4810 docs: adjust site link
  site/docs/api/chart.zh.md
  site/docs/api/facetCircle.zh.md
  site/docs/api/facetRect.zh.md
  site/docs/api/geoView.zh.md
  site/docs/api/mark.zh.md
  site/docs/api/overview.zh.md
  site/docs/api/repeatMatrix.zh.md
  site/docs/api/spaceFlex.zh.md
  site/docs/api/spaceLayer.zh.md
  site/docs/api/timingKeyFrame.zh.md
  site/docs/api/view.zh.md
Labels: PR: reviewed-approved

#4807 refactor(api): rename some api
  __tests__/plots/animation/aapl-area-keyframe.ts
  __tests__/plots/static/aapl-area-missing-data-transpose.ts
  __tests__/plots/static/aapl-area-missing-data.ts
  __tests__/plots/static/aapl-line-missing-connect.ts
  __tests__/plots/static/aapl-line-missing-styled.ts
  __tests__/plots/static/morley-box-extend.ts
  __tests__/plots/static/penguins-boxplot-grouped-extent.ts
  __tests__/plots/tooltip/morley-box-default-extend.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/spec/coordinate/fisheye.zh.md
  site/docs/spec/mark/area.zh.md
  site/docs/spec/mark/line.zh.md
  site/docs/spec/mark/point.zh.md
  site/examples/general/area/demo/missing-data-area.ts
  site/examples/general/box/demo/boxplot.ts
  site/examples/general/line/demo/line-connect-nulls.ts
  src/coordinate/fisheye.ts
  src/interaction/fisheye.ts
  src/mark/boxplot.ts
  src/runtime/render.ts
  src/shape/area/curve.ts
  src/shape/line/curve.ts
  src/spec/coordinateTransform.ts
  src/stdlib/index.ts
  src/theme/classic.ts
  src/theme/classicDark.ts
  src/theme/index.ts
Labels: PR: reviewed-approved

#4811 refactor: refactor component api
  __tests__/plots/interaction/movies-interval-highlight-multiple-state.ts
  __tests__/plots/interaction/score-by-item-area-radar.ts
  __tests__/plots/static/acme-crop-income-interval-connector.ts
  __tests__/plots/static/alphabet-interval-title.ts
  __tests__/plots/static/blockchain-line-annotation.ts
  __tests__/plots/static/blockchain-line-badge-annotation.ts
  __tests__/plots/static/cars3-line-parallel-vertical.ts
  __tests__/plots/static/gdp-interval-flex.ts
  __tests__/plots/static/indices-line-point-scale-key.ts
  __tests__/plots/static/question8-interval-radial-gradient-color.ts
  __tests__/plots/static/seasonal-weather-area-radial.ts
  __tests__/plots/static/stateages-interval-stacked.ts
  __tests__/plots/static/train-line-multi-axes.ts
  __tests__/plots/static/weather-line-area-dual-axis.ts
  __tests__/plots/static/weather-line-multi-axes.ts
  __tests__/plots/static/weather-line-multi-scrollbar.ts
  __tests__/plots/static/weather-line-multi-slider.ts
  __tests__/plots/static/weather-line-view-label-transform.ts
  __tests__/plots/static/world-history-interval-multi-tick-count.ts
  __tests__/plots/tooltip/weather-line-interval.ts
  src/component/axis.ts
  src/component/legendCategory.ts
  src/component/legendContinuous.ts
  src/component/title.ts
  src/interaction/brushFilter.ts
  src/interaction/sliderFilter.ts
  src/runtime/types/common.ts
  src/spec/component.ts
Labels: PR: reviewed-approved

#4812 feat(chart): add changeData
  __tests__/unit/api/chart.spec.ts
  src/api/composition/base.ts
Labels: PR: reviewed-approved

#4813 docs: add labelTransform
  __tests__/unit/api/chart.spec.ts
  site/docs/api/chart.zh.md
  site/docs/api/overview.zh.md
  src/api/chart.ts
Labels: PR: reviewed-approved

#4814 docs(theme): update theme
  site/docs/spec/mark/.polygon.en.md
  site/docs/spec/mark/.polygon.zh.md
  site/docs/spec/theme/academy.en.md
  site/docs/spec/theme/academy.zh.md
  site/docs/spec/theme/classic.en.md
  site/docs/spec/theme/classic.zh.md
  site/docs/spec/theme/classicDark.en.md
  site/docs/spec/theme/classicDark.zh.md
  site/docs/spec/theme/theme.en.md
  site/docs/spec/theme/theme.zh.md
Labels: PR: unreviewed

#4817 docs: update website docs
  site/.dumirc.ts
  site/docs/spec/common/componentTitle.zh.md
  site/docs/spec/common/navigator.zh.md
  site/docs/spec/component/axis.zh.md
  site/docs/spec/component/category.en.md
  site/docs/spec/component/category.zh.md
  site/docs/spec/component/continuous.en.md
  site/docs/spec/component/continuous.zh.md
  site/docs/spec/component/legend.en.md
  site/docs/spec/component/legend.zh.md
  site/docs/spec/component/scrollbar.zh.md
  site/docs/spec/component/slider.zh.md
  site/docs/spec/component/title.zh.md
  site/docs/spec/component/tooltip.zh.md
  site/docs/spec/overview.zh.md
  site/docs/spec/palette.zh.md
  site/scripts/palette.ts
  src/component/utils.ts
Labels: PR: reviewed-approved

#4820 chore: update to 5.0.0
  package.json
  site/package.json
Labels: PR: unreviewed

#4822 feat: update README.en-US.md
  README.en-US.md
  README.md
Labels: PR: reviewed-approved

#4823 docs: remove empty api fold
  api/chart
Labels: PR: reviewed-approved

#4825 docs: fix docs typo
  CONTRIBUTING.md
  site/docs/manual/single-view/annotation.zh.md
  site/docs/manual/single-view/api.zh.md
  site/docs/manual/single-view/data.zh.md
  site/docs/spec/animation/scaleOutX.zh.md
  site/docs/spec/composition/facetCircle.zh.md
  site/docs/spec/composition/facetRect.zh.md
  site/docs/spec/composition/repeatMatrix.zh.md
  site/docs/spec/data/overview.zh.md
  site/docs/spec/label/overview.zh.md
  site/docs/spec/mark/box.zh.md
  site/docs/spec/mark/boxplot.zh.md
  site/docs/spec/mark/image.zh.md
  site/docs/spec/scale/band.zh.md
  site/docs/spec/scale/point.zh.md
  site/docs/spec/scale/quantile.zh.md
  site/docs/spec/scale/quantize.zh.md
  site/docs/spec/scale/sqrt.zh.md
  site/docs/spec/scale/time.zh.md
  site/docs/spec/transform/groupX.zh.md
  site/docs/spec/transform/groupY.zh.md
  site/docs/spec/transform/selectX.zh.md
  site/docs/spec/transform/selectY.zh.md
  site/docs/spec/transform/sortColor.zh.md
  site/examples/general/interval/demo/bar-dodged.ts
Labels: PR: reviewed-approved

#4826 docs: update the book name of gg
  README.en-US.md
  README.md
Labels: PR: reviewed-approved

#4832 fix(tooltip): sample
  __tests__/integration/snapshots/tooltip/aapl-line-area-basic-sample/step0.html
  __tests__/plots/tooltip/aapl-line-area-basic-sample.ts
  __tests__/plots/tooltip/index.ts
  src/transform/maybeTitle.ts
Labels: PR: reviewed-approved

#4833 fix(tooltip): support NaN data in transpose
  __tests__/integration/snapshots/tooltip/aapl-area-missing-data-transpose/step0.html
  __tests__/plots/tooltip/aapl-area-missing-data-transpose.ts
  __tests__/plots/tooltip/index.ts
  src/interaction/tooltip.ts
Labels: PR: unreviewed

#4835 fix(tests): remove .only
  __tests__/integration/snapshots/interaction/penguins-point-brush-axis/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-axis/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-filter/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-filter/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-filter/step2.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-reverse/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-reverse/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-x-filter/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-x/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-y-filter/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush-y/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step0.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step1.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step2.png
  __tests__/integration/snapshots/interaction/penguins-point-brush/step3.png
  __tests__/integration/snapshots/interaction/penguins-point-highlight/step0.png
  __tests__/integration/snapshots/interaction/score-by-item-area-radar/step0.png
  __tests__/integration/snapshots/interaction/temperatures-line-legend-filter-ordinal/step0.png
  __tests__/integration/snapshots/interaction/temperatures-line-legend-filter-ordinal/step1.png
  __tests__/integration/snapshots/interaction/temperatures-line-legend-filter-ordinal/step2.png
  __tests__/integration/snapshots/interaction/temperatures-line-legend-filter-ordinal/step3.png
  __tests__/plots/interaction/profit-interval-brush-filter.ts
  __tests__/plots/tooltip/aapl-area-missing-data-transpose.ts
Labels: PR: reviewed-approved

#4836 feat(ci): throw error for .only and missing snapshot
  __tests__/integration/utils/filterTests.ts
  __tests__/integration/utils/toMatchCanvasSnapshot.ts
  __tests__/integration/utils/toMatchDOMSnapshot.ts
Labels: PR: unreviewed

#4844 chore(version): update to 5.0.1 and add changelog
  CHANGELOG.md
  package.json
  site/package.json
Labels: PR: unreviewed

#4850 fix(axis): unexpected radius in polar
  __tests__/integration/snapshots/static/scoreByItemAreaRadarSize.png
  __tests__/plots/static/index.ts
  __tests__/plots/static/score-by-item-area-radar-size.ts
  src/component/axis.ts
Labels: PR: reviewed-approved
