Repository antvis/G2, pull requests merged in 2023-01, with the labels that each got.

#4546 fix(update): skip empty selection (close: #4490)
  __tests__/integration/animations/index.ts
  __tests__/integration/animations/profit-interval-range.ts
  __tests__/integration/snapshots/profit-interval-range/interval2-0.png
  __tests__/integration/snapshots/profit-interval-range/interval2-1.png
  __tests__/integration/snapshots/profit-interval-range/interval2-2.png
  src/runtime/plot.ts
Labels: PR: partially-approved

#4545 fix(brush): replace getBounds with getRenderBounds of brush area
  __tests__/integration/interactions/penguins-point-brush-matrix.ts
  __tests__/integration/snapshots/cars3-line-brush-axis/step0.png
  __tests__/integration/snapshots/cars3-line-brush-axis/step1.png
  __tests__/integration/snapshots/cars3-line-vertical-brush-axis/step0.png
  __tests__/integration/snapshots/cars3-line-vertical-brush-axis/step1.png
  __tests__/integration/snapshots/indices-line-brush-series/step0.png
  __tests__/integration/snapshots/indices-line-chart-facet-brush-shared/step0.png
  __tests__/integration/snapshots/penguins-point-brush-axis/step0.png
  __tests__/integration/snapshots/penguins-point-brush-axis/step1.png
  __tests__/integration/snapshots/penguins-point-brush-filter/step0.png
  __tests__/integration/snapshots/penguins-point-brush-filter/step1.png
  __tests__/integration/snapshots/penguins-point-brush-reverse/step0.png
  __tests__/integration/snapshots/penguins-point-brush-reverse/step1.png
  __tests__/integration/snapshots/penguins-point-brush-x-filter/step0.png
  __tests__/integration/snapshots/penguins-point-brush-x/step0.png
  __tests__/integration/snapshots/penguins-point-brush-y-filter/step0.png
  __tests__/integration/snapshots/penguins-point-brush-y/step0.png
  __tests__/integration/snapshots/penguins-point-brush/step0.png
  __tests__/integration/snapshots/penguins-point-brush/step1.png
  __tests__/integration/snapshots/penguins-point-brush/step3.png
  __tests__/integration/snapshots/profit-interval-brush-filter/step0.png
  __tests__/integration/snapshots/profit-interval-brush-filter/step2.png
  src/interaction/native/utils.ts
Labels: PR: partially-approved

#4543 docs: add details of axis gridLength option
  site/docs/api/component/axis.zh.md
  site/docs/api/component/category.zh.md
  site/docs/api/component/continuous.zh.md
Labels: PR: partially-approved

#4536 fix: area support transpose
  __tests__/integration/charts/aapl-area-missing-data-transpose.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/snapshots/aaplAreaMissingDataTranspose.png
  __tests__/unit/mark/area.spec.ts
  src/mark/area.ts
  src/shape/area/curve.ts
Labels: PR: reviewed-approved

#4549 fix: listen window-resize in chart instead of render. (fix #4492)
  __tests__/unit/api/chart.spec.ts
  src/api/chart.ts
  src/runtime/render.ts
Labels: PR: reviewed-approved

#4558 fix(tooltip): custom group-items
  __tests__/integration/snapshots/tooltip-indicesLineItems/step0.html
  __tests__/integration/tooltips/index.ts
  __tests__/integration/tooltips/indices-line-items.ts
  src/interaction/native/tooltip.ts
Labels: PR: partially-approved

#4565 fix(docs): remove mark.coordinate
  site/examples/composition/space/demo/space-flex.ts
  site/examples/composition/space/demo/space-layer.ts
Labels: PR: partially-approved

#4566 chore: update version to 5.0.0-beta.6
  package.json
Labels: PR: reviewed-approved

#4567 refactor: select options
  site/docs/api/transform/select.zh.md
  site/docs/manual/single-view/annotation.zh.md
  src/spec/transform.ts
  src/transform/select.ts
  src/transform/selectX.ts
  src/transform/selectY.ts
Labels: PR: reviewed-approved

#4569 fix(test): unify test result for date object between local and online ci env
  __tests__/integration/main.ts
  __tests__/integration/snapshot-tooltip.spec.ts
  __tests__/integration/snapshots/tooltip-indicesLine/step0.html
  __tests__/integration/tooltips/indices-line.ts
  src/geo/d3Projection.ts
  src/geo/geoView.ts
Labels: PR: partially-approved

#4573 fix: fix issue that component scale lack of relations operation
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/indices-line-chart-scale-relations.ts
  __tests__/integration/snapshots/indicesLineChartScaleRelations.png
  src/runtime/component.ts
  src/runtime/plot.ts
  src/runtime/scale.ts
Labels: PR: reviewed-approved

#4575 fix: support zIndex to control mark depth
  __tests__/integration/charts/aapl-line-z-index.ts
  __tests__/integration/charts/barley-point-facet-rect-col-z-index.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/main.ts
  __tests__/integration/snapshots/aaplLineZIndex.png
  __tests__/integration/snapshots/barleyPointFacetRectColZIndex.png
  src/runtime/plot.ts
  src/spec/geometry.ts
Labels: PR: reviewed-approved

#4586 fix(test): transform esm to cmjs in node_modules
  .husky/pre-commit
  jest.config.js
  package.json
Labels: PR: reviewed-approved, bugfix

#4583 feat(slider): add slider-filter
  __tests__/integration/interactions/appl-line-slider-filter.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/profit-interval-slider-filter.ts
  __tests__/integration/snapshots/aapl-line-slider-filter/step0.png
  __tests__/integration/snapshots/aapl-line-slider-filter/step1.png
  __tests__/integration/snapshots/profit-interval-slider-filter/step0.png
  __tests__/integration/snapshots/profit-interval-slider-filter/step1.png
  __tests__/integration/snapshots/settle-weather-cell-brush-filter/step1.png
  __tests__/unit/stdlib/index.spec.ts
  src/component/slider.ts
  src/interaction/index.ts
  src/interaction/native/brushFilter.ts
  src/interaction/native/brushXFilter.ts
  src/interaction/native/brushYFilter.ts
  src/interaction/native/sliderFilter.ts
  src/runtime/plot.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
  src/utils/scale.ts
Labels: PR: partially-approved, v5

#4582 fix: interaction should be destroy before rerendering
  __tests__/integration/charts/barley-point-facet-rect-col-z-index.ts
  __tests__/integration/interactions/appl-line-slider-filter.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/profit-interval-slider-filter.ts
  __tests__/integration/snapshots/aapl-line-slider-filter/step0.png
  __tests__/integration/snapshots/aapl-line-slider-filter/step1.png
  __tests__/integration/snapshots/profit-interval-slider-filter/step0.png
  __tests__/integration/snapshots/profit-interval-slider-filter/step1.png
  __tests__/integration/snapshots/settle-weather-cell-brush-filter/step1.png
  __tests__/unit/api/interaction.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  src/component/slider.ts
  src/interaction/index.ts
  src/interaction/native/brushFilter.ts
  src/interaction/native/brushXFilter.ts
  src/interaction/native/brushYFilter.ts
  src/interaction/native/elementHighlight.ts
  src/interaction/native/elementSelect.ts
  src/interaction/native/sliderFilter.ts
  src/interaction/native/tooltip.ts
  src/runtime/plot.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
  src/utils/scale.ts
Labels: PR: unreviewed, v5

#4588 feat: modify chartchart&mark class dependencies
  src/api/chart.ts
  src/api/composition/base.ts
  src/api/composition/facetCircle.ts
  src/api/composition/facetRect.ts
  src/api/composition/geoPath.ts
  src/api/composition/geoView.ts
  src/api/composition/index.ts
  src/api/composition/repeatMatrix.ts
  src/api/composition/spaceFlex.ts
  src/api/composition/spaceLayer.ts
  src/api/composition/timingKeyframe.ts
  src/api/composition/view.ts
  src/api/mark/mark.ts
  src/api/node.ts
Labels: PR: reviewed-approved

#4591 chore: update version to 5.0.0-beta.7
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4589 feat: multiple mask actions
  docs/api/general/interaction.zh.md
  examples/interaction/brush/demo/brush-x-multi.ts
  examples/interaction/brush/demo/meta.json
  src/index.ts
  src/interaction/action/mask/circle.ts
  src/interaction/action/mask/dim-rect.ts
  src/interaction/action/mask/multiple/base.ts
  src/interaction/action/mask/multiple/circle.ts
  src/interaction/action/mask/multiple/dim-rect.ts
  src/interaction/action/mask/multiple/path.ts
  src/interaction/action/mask/multiple/rect.ts
  src/interaction/action/mask/multiple/smooth-path.ts
  src/interaction/action/mask/path.ts
  src/interaction/action/mask/rect.ts
  src/interaction/action/mask/smooth-path.ts
  src/interaction/action/util.ts
  tests/unit/interaction/action/multi-mask-spec.ts
Labels: feature, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested

#4594 fix: g can't clone undefined attribute
  src/label-transform/overlapDodgeY.ts
Labels: PR: partially-approved

#4590 feat: add api for chart & mark to get view instance
  __tests__/unit/api/chart.spec.ts
  __tests__/unit/api/mark.spec.ts
  src/api/composition/base.ts
  src/api/mark/base.ts
  src/api/mark/mark.ts
  src/runtime/plot.ts
  src/runtime/types/options.ts
Labels: PR: reviewed-approved

#4568 feat: add area shapes include hvh, hv, vh
  __tests__/integration/charts/browser-line-area-trending.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/temperature-compare-area-difference.ts
  __tests__/integration/charts/temperatures3-area-band-gradient.ts
  __tests__/integration/snapshots/browserLineAreaTrending.png
  __tests__/unit/mark/area.spec.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/mark/area.zh.md
  site/docs/api/mark/line.zh.md
  site/docs/api/transform/diffY.zh.md
  site/examples/general/area/demo/area-difference.ts
  site/examples/general/area/demo/step-area.ts
  src/mark/area.ts
  src/shape/area/hv.ts
  src/shape/area/hvh.ts
  src/shape/area/vh.ts
  src/shape/index.ts
  src/stdlib/index.ts
Labels: PR: partially-approved

#4596 feat(interaction): optimize element select
  __tests__/integration/interactions/alphabet-interval-select-background.ts
  __tests__/integration/interactions/alphabet-interval-select-offset-polar.ts
  __tests__/integration/interactions/alphabet-interval-select-single-background.ts
  __tests__/integration/interactions/appl-line-slider-filter.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/snapshots/alphabet-interval-select-background/step0.png
  __tests__/integration/snapshots/alphabet-interval-select-background/step1.png
  __tests__/integration/snapshots/alphabet-interval-select-background/step2.png
  __tests__/integration/snapshots/alphabet-interval-select-background/step3.png
  __tests__/integration/snapshots/alphabet-interval-select-background/step4.png
  __tests__/integration/snapshots/alphabet-interval-select-offset-polar/step0.png
  __tests__/integration/snapshots/alphabet-interval-select-offset-polar/step1.png
  __tests__/integration/snapshots/alphabet-interval-select-offset-polar/step2.png
  __tests__/integration/snapshots/alphabet-interval-select-single-background/step0.png
  __tests__/integration/snapshots/alphabet-interval-select-single-background/step1.png
  __tests__/integration/snapshots/alphabet-interval-select-single-background/step2.png
  __tests__/integration/snapshots/alphabet-interval-select-single-background/step3.png
  src/interaction/native/elementSelect.ts
  src/interaction/native/elementSelectByColor.ts
  src/interaction/native/elementSelectByX.ts
  src/spec/interaction.ts
Labels: PR: unreviewed

#4547 feat: add transform.sample and document
  __tests__/integration/charts/aapl-line-area-basic-sample.ts
  __tests__/integration/charts/aapl-line-basic-sample.ts
  __tests__/integration/charts/aapl-line-point-basic-sample.ts
  __tests__/integration/charts/house-price-point-sample.ts
  __tests__/integration/charts/house-price-point-shapes.ts
  __tests__/integration/charts/index.ts
  __tests__/integration/charts/unemployment-area-stacked-sample.ts
  __tests__/integration/snapshots/aaplLineAreaBasicSample.png
  __tests__/integration/snapshots/aaplLineBasicSample.png
  __tests__/integration/snapshots/aaplLinePointBasicSample.png
  __tests__/integration/snapshots/housePricePointSample.png
  __tests__/integration/snapshots/housePricePointShapes.png
  __tests__/integration/snapshots/unemploymentAreaStackedSample.png
  package.json
  site/docs/api/transform/sample.zh.md
  src/spec/transform.ts
  src/transform/sample.ts
  src/transform/utils/lttb.ts
Labels: PR: reviewed-approved

#4602 refactor: update gui to version 65
  __tests__/integration/snapshots/question8IntervalRadialGradientColor.png
  package.json
  src/component/axis.ts
  src/component/legendContinuous.ts
Labels: PR: reviewed-approved

#4598 feat(interaction): add legendHighlight
  __tests__/integration/charts/aapl-line-clip.ts
  __tests__/integration/interactions/index.ts
  __tests__/integration/interactions/profit-interval-legend-highlight.ts
  __tests__/integration/snapshots/profit-interval-legend-highlight/step0.png
  __tests__/integration/snapshots/profit-interval-legend-highlight/step1.png
  __tests__/integration/snapshots/profit-interval-legend-highlight/step2.png
  __tests__/unit/stdlib/index.spec.ts
  src/interaction/index.ts
  src/interaction/native/legendFilter.ts
  src/interaction/native/legendHighlight.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: unreviewed

#4601 refactor(api): add emitter
  __tests__/integration/snapshot-animation.spec.ts
  __tests__/unit/api/chart.spec.ts
  package.json
  src/api/chart.ts
  src/api/props.ts
  src/runtime/plot.ts
  src/runtime/render.ts
  src/runtime/types/options.ts
  src/spec/composition.ts
  src/utils/event.ts
Labels: PR: unreviewed

#4604 chore(version): update to 5.0.0-beta.8
  package.json
  site/package.json
Labels: PR: reviewed-approved

#4597 feat(interaction): add poptip
  __tests__/integration/snapshot-tooltip.spec.ts
  __tests__/integration/snapshots/tooltip-flareTreemapPoptip/step1.html
  __tests__/integration/snapshots/tooltip-flareTreemapPoptip/step3.html
  __tests__/integration/snapshots/tooltip-flareTreemapPoptipCustom/step0.html
  __tests__/integration/tooltips/flare-treemap-poptip-custom.ts
  __tests__/integration/tooltips/flare-treemap-poptip.ts
  __tests__/integration/tooltips/index.ts
  __tests__/unit/stdlib/index.spec.ts
  site/docs/api/component/category.zh.md
  src/component/legendCategory.ts
  src/interaction/index.ts
  src/interaction/native/poptip.ts
  src/mark/pack.ts
  src/mark/treemap.ts
  src/spec/interaction.ts
  src/stdlib/index.ts
Labels: PR: unreviewed
